### ISSUE TITLE
Doc: typo "boostrap"

### ISSUE THREAD

**Issue by mlavi** [siderolabs/talos#10000]
https://www.talos.dev/v1.9/reference/cli/#synopsis second and third sentence of the first paragraph have typos for the word _bootstrap_:
"One node should be picked as the **boostrap** node. When **boostrap** command is issued,"

**Comment by mlavi** [comment]
@smira thanks for the rapid response, I see that it was reviewed and merged! However, the second occurrence was not corrected. Can you reopen this issue or would you like a new issue?

**Comment by smira** [comment]
The CLI documentation is auto-generated, so we can't really update 1.9 docs, but 1.10 docs are correct.
