### ISSUE TITLE
Incorrect docker command for RPi Imager with overlay

### ISSUE THREAD

**Issue by umbertix** [siderolabs/talos#10007]
The command for [rpi imager](https://www.talos.dev/v1.9/talos-guides/install/boot-assets/#example-raspberry-pi-overlay-with-imager) is missing the `--privileged` flag. Failing to do so spits an error:
`failed to attach loopback device: could not open /dev/loop-control: open /dev/loop-control: no such file or directory`

Current code:
`docker run --rm -t -v $PWD/_out:/out ghcr.io/siderolabs/imager:v1.9.0 rpi_generic --arch arm64 --system-extension-image ghcr.io/siderolabs/iscsi-tools:v0.1.4@sha256:548b2b121611424f6b1b6cfb72a1669421ffaf2f1560911c324a546c7cee655e --overlay-image ghcr.io/siderolabs/sbc-raspberrypi:v0.1.0@sha256:849ace01b9af514d817b05a9c5963a35202e09a4807d12f8a3ea83657c76c863 --overlay-name=rpi_generic`
 --------------> 
 Suggested code
 `docker run --rm -t -v $PWD/_out:/out ghcr.io/siderolabs/imager:v1.9.0 --privileged rpi_generic --arch arm64 --system-extension-image ghcr.io/siderolabs/iscsi-tools:v0.1.4@sha256:548b2b121611424f6b1b6cfb72a1669421ffaf2f1560911c324a546c7cee655e --overlay-image ghcr.io/siderolabs/sbc-raspberrypi:v0.1.0@sha256:849ace01b9af514d817b05a9c5963a35202e09a4807d12f8a3ea83657c76c863 --overlay-name=rpi_generic`

**Comment by smira** [comment]
Please send a PR, there's a direct link to edit the page, it's easier than creating an issue.
