### ISSUE TITLE
Talos `1.9.0`: disk issues during installation on baremetal

### ISSUE THREAD

**Issue by eugene-marchanka** [siderolabs/talos#10055]
### Description

Talos is not getting provisioned on Dell R350/R340 I assume because of disk issues:

```
[  764.314972] Error: failed to create partitions: failed to write GPT: failed to add partition 1: invalid argument
[  764.314974] Usage:
[  764.314976]   installer install [flags]
[  764.314977]
[  764.314978] Flags:
[  764.314980]   -h, --help   help for install
[  764.314981]
[  764.314983] Global Flags:
[  764.314986]       --arch string                    The target architecture (default "amd64")
[  764.314988]       --board string                   Deprecated: no op (default "none")
[  764.315016]       --bootloader                     Deprecated: no op (default true)
[  764.315085]       --config string                  The value of talos.config
[  764.315102]       --disk string                    The path to the disk to install to
[  764.315118]       --extra-kernel-arg stringArray   Extra argument to pass to the kernel
[  764.315132]       --force                          Indicates that the install should forcefully format the partition
[  764.315133]       --meta metaValueSlice            A key/value pair for META (default [])
[  764.315135]       --platform string                The value of talos.platform
[  764.315136]       --upgrade                        Indicates that the install is being performed by an upgrade
[  764.315138]       --zero                           Indicates that the install should write zeros to the disk before installing
[  764.315139]
```

```
machine:
    install:
        disk: /dev/sda
        diskSelector:
            size: < 900GB
        extraKernelArgs:
            - -console
            - console=tty0
            - console=ttyS0
            - cpufreq.default_governor=performance
            - talos.logging.kernel=tcp://127.0.0.1:5044/
            - talos.device.settle_time=1m
        image: ghcr.io/siderolabs/installer:v1.9.0
        bootloader: true
        wipe: true
```

### Logs

[1-9-0-r350-install.txt](https://github.com/user-attachments/files/18253935/1-9-0-r350-install.txt)

### Environment

- Talos version: [`1.9.0`]
- Kubernetes version: [`v1.31.2`]
- Platform: `baremetal`

**Comment by smira** [comment]
I think the issue is:

```
[  601.114763] [talos] task install (1/1): using disk match expression: disk.size < 900000000000u && !disk.readonly && !disk.cdrom
[  602.452526] [talos] task install (1/1): installing Talos to disk /dev/dm-0
```

It's certainly wrong, but most probably you have some LVM leftover?

```
[  128.681144] [talos] activating LVM volume {"component": "controller-runtime", "controller": "block.LVMActivationController", "name": "csi-lvm"}
```

I guess this should go away if you actually specify disk type correctly.

**Comment by smira** [comment]
(this is probably still a bug on Talos side, but providing a workaround here)

**Comment by eugene-marchanka** [comment]
I ran `Reset Talos installation` before installing Talos. I thought it supposed to wipe all disks at this stage.
[reset-installation-r350.txt](https://github.com/user-attachments/files/18254130/reset-installation-r350.txt)

**Comment by smira** [comment]
No, it's not supposed to wipe non-Talos disks. Specify disk type and the problem will go away.

**Comment by eugene-marchanka** [comment]
Setting this helped:
```
machine:
    install:
        disk: /dev/sda
        diskSelector:
            size: < 900GB
            type: ssd
```
Thanks!

**Comment by frezbo** [comment]
> Re-opening, as it's still a bug, `dm-0` shouldn't be picked up

:thinking: but if there was a raid setup outside talos, isn't `dm-0` an installation candidate disk?

**Comment by smira** [comment]
In that case it can be picked up via `disk: /dev/<something>` explicitly, but I don't think diskSelector should pick it up

**Comment by dhess** [comment]
We're seeing something similar when attempting to upgrade `v1.8.4` bare metal nodes to `v1.9.1`. The upgrade is failing here:

https://github.com/siderolabs/talos/blame/650eb3a4f2d89d173cdd6581a6d1232511a8e219/cmd/installer/pkg/install/install.go#L312

complaining that the filesystem is ZFS. We have a few ZFS drives attached to each node, but obviously not on the install disk.
