### ISSUE TITLE
Unable to load ceph kernel module

### ISSUE THREAD

**Issue by huangkevin404** [siderolabs/talos#10067]
### Description

I am unable to load the ceph kernel module.

I added the following to my machineconfig and applied it:
```
machine:
  kernel:
    modules:
      - name: ceph
      - name: nbd
      - name: rbd
```
Running `talosctl read /proc/modules` shows that it has managed to load the nbd module, but not rbd and ceph:
```
nbd 57344 - - Live 0xffffffffc064b000
virtio_balloon 32768 - - Live 0xffffffffc0444000
virtio_pci 28672 - - Live 0xffffffffc0434000
virtio_pci_legacy_dev 12288 - - Live 0xffffffffc042b000
virtio_pci_modern_dev 16384 - - Live 0xffffffffc0421000
```

From what I've [seen](https://github.com/hackworthltd/pkgs/blob/b1764e1d9b11ae6fbe4ad169001b6c173870536f/kernel/build/config-amd64#L1750), the kernel module should be included. Am I supposed to use an extension ? I stumbled upon this [closed PR](https://github.com/siderolabs/extensions/pull/215).

I am trying to mount a cephfs volume using ceph-csi-cephfs, and when trying to mount, cephfs-nodeplugin gives me `modprobe: FATAL: Module ceph not found in directory /lib/modules/6.6.58-talos`

Thanks in advance for the help !

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
```
Client:
        Tag:         v1.9.0
        SHA:         undefined
        Built:
        Go version:  go1.23.3
        OS/Arch:     linux/amd64
Server:
        NODE:        NODE_IP
        Tag:         v1.8.2
        SHA:         88f861a0
        Built:
        Go version:  go1.22.8
        OS/Arch:     linux/amd64
        Enabled:     RBAC
```
- Kubernetes version: [`kubectl version --short`]
```
Client Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.31.2
```
- Platform: Linux/Proxmox

**Comment by frezbo** [comment]
ceph and rbd have `CONFIG_` values `=y` which means they are already part of kernel and not build as loadable modules, so no need to load them explicitly. `/proc/modules` only contains loadable modules, not modules built-in
