### ISSUE TITLE
[rfc] logd: talos network logging accumulator

### ISSUE THREAD

**Issue by Ulexus** [siderolabs/talos#1217]
Debugging boot issues is hard.  Sometimes (#1211) we have systems which make it hard to see the console.

Something to consider would be to add a logd service which could provide a logging ringbuffer for each node, expecting the kernels for each of the nodes to include a `netconsole=` cmdline to shove console output to the service.

Obviously, this would need to a be low priority, ideally RAM-only, service.  It is very easy to become overwhelmed by network logging.  It should also probably be opt-in.  Supporting a streaming API for this would be really helpful for debugging, particularly if integrated into osctl.

Other options, of course, are just noting that the kernel accepts the `netconsole=` parameter, and to have the user set up a netcat or remote syslog service.

**Comment by Ulexus** [comment]
For reference, netconsole is actually really powerful and modifiable in userspace:  https://www.kernel.org/doc/Documentation/networking/netconsole.txt

**Comment by andrewrynhard** [comment]
This sounds really neat. @bradbeam something like a `logd` has been something we have thought about for a while. Probably worth dropping some of your thoughts down here and we can turn into a proposal later.

**Comment by Ulexus** [comment]
Implementation idea:
  - _any_ of the masters could receive any particular log message
  - the API could consolidate and stitch these together
  - reduces realtime load by only doing consolidation on request
