### ISSUE TITLE
Azure E2E test

### ISSUE THREAD

**Issue by rsmitty** [siderolabs/talos#1824]

**Comment by rsmitty** [comment]
Kicking this back out of this sprint, since we'll need to wait a few weeks for azure to get the metadata service back in order.

Notes:

- customData is currently disabled in the metadata service due to a "product issue". hopefully back shortly.
- the use of "standard" SKU public IPs results in them not being present in the "publicIP" field in metadata. this is a known issue that is also being worked on.

I don't have an ETA for these, so we'll just have to check back in a few weeks.

**Comment by herenyi** [comment]
Hi, does talos work on Azure now?
I have tried to follow the instructions: https://www.talos.dev/docs/v0.5/en/guides/cloud/azure
but I cannot get the kubeconfig and I think the VMs are in constant reboot:
[    3.517332] Run /init as init process
[    3.522053] [talos] [initramfs] booting Talos v0.5.0
[    3.525361] [talos] [initramfs] mounting the rootfs
[    3.533532] [talos] [initramfs] entering the rootfs
[    3.537288] [talos] [initramfs] moving mounts to the new rootfs
[    3.542261] [talos] [initramfs] changing working directory into /root
[    3.546784] [talos] [initramfs] moving /root to /
[    3.550264] [talos] [initramfs] changing root directory
[    3.554340] [talos] [initramfs] cleaning up initramfs
[    3.557786] [talos] [initramfs] executing /sbin/init
[    3.668274] psmouse serio1: trackpoint: failed to get extended button data, assuming 3 buttons
2020/07/13 15:14:58 waiting 1 second(s) for USB storage
2020/07/13 15:14:59 initialize sequence: 10 phase(s)
2020/07/13 15:14:59 phase 1/10: 1 tasks(s)
2020/07/13 15:14:59 task 1/1: starting
[    5.552244] [talos] task 1/1: done, 2.0314ms
[    5.555470] [talos] phase 1/10: done, 8.4566ms
[    5.558452] [talos] phase 2/10: 7 tasks(s)
[    5.561200] [talos] task 7/7: starting
[    5.563881] [talos] task 7/7: done, 2.6433ms
[    5.567435] [talos] task 1/7: starting
[    5.570815] [talos] task 1/7: done, 6.7908ms
[    5.574087] [talos] task 2/7: starting
[    5.584712] [talos] task 3/7: starting
[    5.587259] [talos] task 4/7: starting
[    5.591245] [talos] task 4/7: done, 27.3166ms
[    5.594303] [talos] task 5/7: starting
[    5.597413] [talos] task 6/7: starting
[    5.601477] [talos] task 3/7: done, 23.4164ms
[    5.605931] [talos] task 2/7: done, 20.9035ms
[    5.608844] [talos] task 6/7: done, 37.5894ms
[    5.611776] [talos] task 5/7: done, 33.3123ms
[    5.614596] [talos] phase 2/10: done, 56.1444ms
[    5.617549] [talos] phase 3/10: 1 tasks(s)
[    5.621067] [talos] task 1/1: starting
[    5.623552] audit: type=1807 audit(1594653299.347:2): action=dont_measure fsmagic=0x9fa0 res=1
[    5.629955] ima: policy update completed
[    5.632505] [talos] task 1/1: done, 2.4162ms
[    5.635421] audit: type=1807 audit(1594653299.354:3): action=dont_measure fsmagic=0x62656572 res=1
[    5.642227] audit: type=1807 audit(1594653299.354:4): action=dont_measure fsmagic=0x64626720 res=1
[    5.649061] audit: type=1807 audit(1594653299.354:5): action=dont_measure fsmagic=0x1021994 res=1
[    5.655101] audit: type=1807 audit(1594653299.354:6): action=dont_measure fsmagic=0x1cd1 res=1
[    5.660998] audit: type=1807 audit(1594653299.354:7): action=dont_measure fsmagic=0x42494e4d res=1
[    5.668004] audit: type=1807 audit(1594653299.354:8): action=dont_measure fsmagic=0x73636673 res=1
[    5.674557] audit: type=1807 audit(1594653299.354:9): action=dont_measure fsmagic=0xf97cff8c res=1
[    5.681624] audit: type=1807 audit(1594653299.354:10): action=dont_measure fsmagic=0x43415d53 res=1
[    5.688640] [talos] phase 3/10: done, 71.087ms
[    5.691708] [talos] phase 4/10: 2 tasks(s)
[    5.694433] [talos] task 2/2: starting
[    5.703470] [talos] task 2/2: done, 2.6568ms
[    5.706428] [talos] task 1/2: starting
[    5.709548] [talos] task 1/2: done, 11.9381ms
[    5.713865] [talos] phase 4/10: done, 22.1597ms
[    5.717064] [talos] phase 5/10: 1 tasks(s)
[    5.719835] [talos] task 1/1: starting
[    5.722384] [talos] discovering local interfaces
[    5.726067] [talos] link "lo" has carrier signal
[    5.730172] [talos] link "bond0" has carrier signal
[    5.733537] [talos] link "eth0" has carrier signal
[    5.737802] [talos] configuring non-bonded interfaces
[    5.742385] [talos] setting up eth0
[    5.747015] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[    5.752240] [talos] setting up lo
[    5.768718] [talos] setting up bond0
[    5.868857] [talos] configuring bonded interfaces
[    5.924914] [talos] writing resolvconf
[    5.928603] [talos] task 1/1: done, 2.519ms
[    5.931599] [talos] phase 5/10: done, 214.5363ms
[    5.934790] [talos] phase 6/10: 1 tasks(s)
[    5.938482] [talos] task 1/1: starting
[    6.045983] FAT-fs (sdb1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
[    6.054543] [talos] task 1/1: done, 2.657ms
[    6.057566] [talos] phase 6/10: done, 122.7802ms
[    6.061201] [talos] phase 7/10: 1 tasks(s)
[    6.064251] [talos] task 1/1: starting
[    6.067875] [talos] task 1: downloading config
[    6.079729] [talos] task 1: storing config in memory
[    6.084762] [talos] task 1/1: done, 3.5424ms
[    6.087571] [talos] initialize sequence: done: 6.1586ms
[    6.092003] **### [talos] error running phase 7 in initialize sequence: task 1/1: failed, failed to set config: unknown version: ""**
[    6.101221] [talos] rebooting in 10 seconds
[    7.105200] [talos] rebooting in 9 seconds
[    7.419737] psmouse serio1: trackpoint: IBM TrackPoint firmware: 0x01, buttons: 3/3
[    7.426668] input: TPPS/2 IBM TrackPoint as /devices/platform/i8042/serio1/input/input4
[    8.108136] [talos] rebooting in 8 seconds
[    9.111120] [talos] rebooting in 7 seconds
[   10.114527] [talos] rebooting in 6 seconds
[   11.117506] [talos] rebooting in 5 seconds
[   12.122261] [talos] rebooting in 4 seconds
[   13.125283] [talos] rebooting in 3 seconds
[   14.128369] [talos] rebooting in 2 seconds
[   15.131305] [talos] rebooting in 1 seconds
[   16.136296] [talos] rebooting in 0 seconds
[   17.139431] [talos] waiting for sync...
[   17.142220] [talos] sync done
[   17.145257] sd 0:0:0:0: [sdb] Synchronizing SCSI cache
[   17.149108] reboot: Restarting system
[   17.151546] reboot: machine restart

**Comment by andrewrynhard** [comment]
@rsmitty Did we merge the Azure fix?

**Comment by rsmitty** [comment]
Hey, @herenyi, we did merge a fix for this, but it didn't land until our v0.6.0-alpha.2 release. If you want to give this a shot with our latest alpha release, it should totally work for you. Here's the PR where we fixed the machine config handling: https://github.com/talos-systems/talos/pull/2231

**Comment by herenyi** [comment]
Hi, thanks for the information. Now the nodes came up and managed to get kubeconfig. However when I tried this: ./kubectl --kubeconfig ./kubeconfig apply -f https://k8s.io/examples/pods/inject/dapi-envars-pod.yaml
The pod is stuck at container creating and the describe shows the following:
./kubectl --kubeconfig ./kubeconfig describe po dapi-envars-fieldref
Name:         dapi-envars-fieldref
Namespace:    default
Priority:     0
Node:         talos-worker-0/172.18.12.101
Start Time:   Wed, 15 Jul 2020 09:42:48 +0100
Labels:       <none>
Annotations:  kubernetes.io/psp: privileged
Status:       Pending
IP:
IPs:          <none>
Containers:
  test-container:
    Container ID:
    Image:         k8s.gcr.io/busybox
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
    Args:
      while true; do echo -en '\n'; printenv MY_NODE_NAME MY_POD_NAME MY_POD_NAMESPACE; printenv MY_POD_IP MY_POD_SERVICE_ACCOUNT; sleep 10; done;
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      MY_NODE_NAME:             (v1:spec.nodeName)
      MY_POD_NAME:             dapi-envars-fieldref (v1:metadata.name)
      MY_POD_NAMESPACE:        default (v1:metadata.namespace)
      MY_POD_IP:                (v1:status.podIP)
      MY_POD_SERVICE_ACCOUNT:   (v1:spec.serviceAccountName)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-j9r22 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  default-token-j9r22:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-j9r22
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age        From                     Message
  ----     ------                  ----       ----                     -------
  Normal   Scheduled               <unknown>  default-scheduler        Successfully assigned default/dapi-envars-fieldref to talos-worker-0
  Warning  FailedCreatePodSandBox  59s        kubelet, talos-worker-0  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "dd06461ce6032214843b6b8474935f74ee2ac46c6e3a804c29961d6b9a366f23": open /run/flannel/subnet.env: no such file or directory
  Warning  FailedCreatePodSandBox  46s        kubelet, talos-worker-0  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "b3b9e28b5a4403ee159dbc0114e2fad619ebdeac09197e93804ef92dfc04b442": open /run/flannel/subnet.env: no such file or directory
  Warning  FailedCreatePodSandBox  34s        kubelet, talos-worker-0  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "02fd56cbee38f5bfc0ee9be57484d75d3be63bb2d339c8694352b26c473c5a6f": open /run/flannel/subnet.env: no such file or directory
  Warning  FailedCreatePodSandBox  19s        kubelet, talos-worker-0  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "9cf44ef255aed6c976e349cde4f69db06c4fa1e7f4bdba709a678d7a017c1e9f": open /run/flannel/subnet.env: no such file or directory
  Warning  FailedCreatePodSandBox  6s         kubelet, talos-worker-0  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "985ddcfa67416a9feccf28fc22b75e81903332c4f6ffef195f54823cf40921c3": open /run/flannel/subnet.env: no such file or directory

Any ideas what is wrong with flannel?
Thank you in advance!
Cheers,
Gergo

**Comment by andrewrynhard** [comment]
@herenyi Are you able to join our slack? We could give you better support there.

**Comment by herenyi** [comment]
I have joined!

**Comment by rsmitty** [comment]
Probably going to punt here for a little while, but my "azure" branch of talos fork has my latest work. Because of the way the azure capi provider works, there's multiple NICs attached to a given VM when using the "allocate public IP" option. One is used for internal traffic, while another is there specifically for that public IP. We'll need to spend some time figuring out how to configure both nics if this winds up being a route we want to go, since it doesn't seem to be accessible on that public interface.

**Comment by sanmai-NL** [comment]
What are the acceptance criteria for this issue, @rsmitty? https://github.com/siderolabs/talos/blob/12827b861c13bb9b83a2f0ea2960582e8be319f0/hack/test/e2e-azure.sh exists, is it incomplete?
