### ISSUE TITLE
Compatibility with aws eks 

### ISSUE THREAD

**Issue by rverma-jm** [siderolabs/talos#1834]
Is it advisable to use this os with the aws managed controlpane (eks)? 
What are some features which one should try that with that combo :)

Please excuse me for asking such a broad question, I am still reading about this. 
Got too much fed-up with aws's default eks ami randomly giving NodeNotReady, just started investigating for a long term solution.

**Comment by Talos-Hope** [comment]
Thank you, Rohit. One of our engineers will respond to your question in a few hours.

**Comment by rsmitty** [comment]
Hi @rverma-jm, this is a great question. Unfortunately, I don't have a better answer for you than **_soon_**.

We've talked about this a few times now and we really want to make this a possibility. As it currently stands, however, there are several OS-level components that traditionally run on the Talos control plane that wouldn't be present in one created by EKS. We've been having conversations internally about the ability to break those out and run them on Kubernetes, but the planning for that is ongoing.

In the meantime, I'll keep this issue open so we can use it during our planning and be sure to keep you in the loop.

**Comment by matglas** [comment]
Is this something that is available or still on the roadmap?

**Comment by smira** [comment]
I would say no, this is not available and not planned, so I will close it to avoid confusion. The solution will be similar to other non-Talos control planes if we ever decide to pursue that path.
