### ISSUE TITLE
Talosctl: Add info option to parameters

### ISSUE THREAD

**Issue by patatman** [siderolabs/talos#2141]
## Feature Request
To get information on what node I'm currently connected to, I'd like to have an info option.
Syntax: 
 `talosctl info` 
Expected output:
```
Client: v0.4.1
Node:
        IP:        192.168.2.80
        MAC: 00:AA:BB:CC:DD:EE
        Version:         v0.4.1
        SHA:         f1120eb4

Resources:
        RAM: 40GB
        Cores: 4
        Load: 0.22
        Disks: 
            |-> /dev/sda
            |-> /dev/sdb
        OS/Arch:     linux/amd64
```
### Description
This helps troubleshooting, and displaying which node your connected to.
For now a simple symlink to `talosctl version` should be enough, since this displays the basics. 
From there we can extend to more node specific information

**Comment by smira** [comment]
`talosctl dashboard` and various resources which can be pulled back is a way to see which node you're connected to
