### ISSUE TITLE
talosctl: Cordon node on reboot

### ISSUE THREAD

**Issue by patatman** [siderolabs/talos#2162]
## Feature Request
`talosctl reboot` 
would Cordon the node being rebooted.
### Description
If talos received a reboot trough the talosctl, it would be nice if that specific node is Cordonned in K8s.
This would mean that K8s is aware the node is having maintenance. The question however, wether the node should be uncordonned when it's back online. Or is this something you should do manually?

**Comment by freswa** [comment]
I agree with cordoning a node on shutdown. But when it's back up again, it should only be uncordoned if explicitly set to do so (e.g. `talosctl reboot --auto-uncordon`). Sometimes there are hickups after an upgrade and it's pretty nice that you have some time to check the node before it's on duty again.
