### ISSUE TITLE
Better config validation

### ISSUE THREAD

**Issue by andrewrynhard** [siderolabs/talos#2670]
### Description

https://github.com/RussellLuo/validating

**Comment by andrewrynhard** [comment]
Registry mirrors could be validated too.

**Comment by DWSR** [comment]
Just spent an hour trying to figure out why my RPi was in a boot loop when trying to mount user disks. Turns out I left `device` blank.

Would love better config validation. :)

**Comment by andrewrynhard** [comment]
@DWSR Mind posting context around `device`? I believe we have more than one `device` field. Maybe 🤔.

**Comment by DWSR** [comment]
Sorry, I guess that would help, wouldn't it?
This `device`: https://www.talos.dev/docs/v0.8/reference/configuration/#machinedisk
