### ISSUE TITLE
Server side shared IP for Talos API (and maybe k8s APIServer)

### ISSUE THREAD

**Issue by Ulexus** [siderolabs/talos#2711]
## Feature Request

It would be a large boon to prospective users to be able to leverage:
  - a known-in-advance IP
  - which works without any external services

Right now, `talosctl` implements client-side load-balancing, which is great, but it still relies of knowing the individual IP addresses of each control node.  This can be coordinated, but it is easier for everything if an IP address could be defined in advance and then proffered by the control nodes outside of their DHCP-acquired host IPs.

There are three usual ways of doing this:
  - layer 2 ARP/NDP shenanigans
  - layer 3 BGP
  - layer 4 IPVS

Layer 2 is the simplest; it just works with the existing layer 3 network on a layer 2 segment, using a different, reserved IP address for the controlplane.  The down side is that this is not really a "load balancer" so much as an automatic failover.  That's probably fine for many installs, especially play clusters.

Layer 3 BGP requires some outside coordination, such as a router which speaks BGP.  This is pretty common and standardized, though.  It's the most reliable system but has a number of configuration options.  It is still not a "load balancer" per se, but it handles the failover more gracefully and naturally, with less chance of conflict.

Layer 4 IPVS would also be a good option, especially since this usual involves a true load balancer.  However, it makes use of multicast addresses, which may not be allowed on networks, and worse, there doesn't seem to be a pure Go implementation, based on my limited search (one relies on `libnl`; another just wraps `ipvsadm`).

### Description

While Load Balancers are standard an API-available services in most Cloud providers, they are less commonly available in baremetal systems, and where they _are_ available, they have no standard means of communicating.  Thus for Sidero and other baremetal-focused systems which wish to implement an API-based network, this presents a significant challenge.  Allowing Talos to handle this internally would go a long way toward making a Talos cluster more ubiquitous and user-friendly.

**Comment by Ulexus** [comment]
It should also be noted that the Layer2 method would be equally applicable to Cloud systems which have VPC-like semantics (a common layer 2 real-or-tunneled network).

**Comment by Ulexus** [comment]
The main concern here is, as usual, bootstrapping.  While it doesn't really matter which of the control nodes gets the bootstrap API call, it _does_ matter that _only_ one act upon it.  gRPC, being TCP-based, _should_ provide sufficient protection for this, so long as the conversation is sufficiently short.

**Comment by Ulexus** [comment]
Split brain scenarios are always a possibility, but they are no more so with this setup than they are now.

**Comment by Ulexus** [comment]
metallb's implementation looks pretty good, for [layer 2](https://github.com/metallb/metallb/tree/66698c23b352c2fac03eac0e87e10214b0527564/internal/layer2) and [layer 3](https://github.com/metallb/metallb/tree/66698c23b352c2fac03eac0e87e10214b0527564/internal/bgp) (BGP)

**Comment by Ulexus** [comment]
kube-vip should basically just work as a dropped-in extraManifest.  Need to test.

**Comment by DWSR** [comment]
I would vote for MetalLB over `kube-vip` as there's a bigger community and it's better documented.
