### ISSUE TITLE
prototool linter: require comments in protobuf files

### ISSUE THREAD

**Issue by andrewrynhard** [siderolabs/talos#2722]
### Description

We have protobufs that are barely documented. The `prototool` linter could help us and require comments.

**Comment by AlekSi** [comment]
I think we also should run `prototool format`

**Comment by AlekSi** [comment]
I think that one is done, but someone should create follow-up issues

**Comment by smira** [comment]
* we need to add documentation to the `.proto` files
* we need to add a linter which will require all future APIs to be properly documented
