### ISSUE TITLE
Ability to view and set efi boot order

### ISSUE THREAD

**Issue by scheuk** [siderolabs/talos#2906]
## Feature Request
As an operator I would like the ability view and set the efi boot order via the talos api and exposed via the talosctl cli so that in an environment without ipmi, I can set the boot order to force the server to PXE boot.  

### Description
When you install an OS on a clean disk, the efi boot order is automatically switched to boot from the disk first even if the bios was configured for network boot first. In a traditionally linux OS you can change the boot order from the command line using efibootmgr post installation. By exposing this in the API we can have sidero force the node to pxe boot and wipe/and re-install talos into the disk.

**Comment by smira** [comment]
This seems like something we could implement in Talos.

One way around right now might be to disable `machine.install.bootloader` in Talos config and enable `server.pxeBootAlways` in Sidero Server resource. This way Talos won't touch EFI boot manager and it will always PXE boot from Sidero. (not perfect, but workaround for now)
