### ISSUE TITLE
add wipe/reset API support to maintenance mode

### ISSUE THREAD

**Issue by Ulexus** [siderolabs/talos#2985]
## Feature Request

One of the biggest frustrations in installing, testing, and reinstalling Talos is handling the case where Talos has already been installed on a disk, but the credentials are missing or the installation is broken.  In this case, Talos will not boot, but neither can you install Talos on top of it.

Therefore, it would be very useful to allow node reset/wipe when in maintenance mode, so that (after #2980 is implemented) we could force a node into maintenance mode and then wipe it.

**Comment by smira** [comment]
Supported via GRUB option now (both ISO and on-disk).
