### ISSUE TITLE
API to create user talosconfig

### ISSUE THREAD

**Issue by Ulexus** [siderolabs/talos#3019]
## Feature Request

We should create an API to generate user/named talosconfigs.  This can be used (especially) for construction of in-kubernetes Secrets of the same, for use with in-cluster automation and monitoring.

This also sets up the general pattern for privilege separation using certificate CommonNames and CRLs for user access repudiation.

An example:

`talosctl user create joe`  -- would output to stdout a talosconfig with keys, cert, endpoints for the cluster

`talosctl user create mary --secret` -- would output to stdout a talosconfig encapsulated within a kubernetes Secret.  This could then be applied to whatever namespace the user chose.

We could later applies roles and/or permissions for the Talos API based on the CommonName of the cert (like kubernetes itself does).

**Comment by smira** [comment]
`talosctl config new`
