### ISSUE TITLE
Talos not working with Longhorn

### ISSUE THREAD

**Issue by bbarclay** [siderolabs/talos#3057]
Somebody said this might be because Talos does not support ISCI. But it would have great to be able to install and use Longhorn. Ceph is a nice alternative, but I do feel like Longhorn has a better UI for managing drives. 
### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: [`kubectl version --short`]
- Platform:

**Comment by Ulexus** [comment]
FWIW, it looks like Longhorn supports both TCMU and iSCSI.

While TCMU is still an iSCSI project, it is possible it is not as bad as iSCSI itself (that is, requiring ancient user-space utilities on the host).  Therefore, it _may_ be possible to support Longhorn/TCMU.

I would still recommend Mayastor as a supported alternative.

**Comment by frezbo** [comment]
@runningman84 mayastor supports pointing to a local raw disk file which needs to pre-provisioned. Ref: https://mayastor.gitbook.io/introduction/quickstart/tips-and-tricks#using-file-backed-disks

**Comment by reitermarkus** [comment]
> which needs to pre-provisioned

@frezbo, how would I go about doing that?

**Comment by mr-sab** [comment]
I am also looking into mayastore, but first before buying extra disks would like to test it.
I think the link of @frezbo is it good place to start, but looking at the Talos documentation, I don't know how to create the local raw disk file. Is this even possible because talos don't have something like SSH access.
Can someone please help us with this?

Thanks in advance

**Comment by frezbo** [comment]
sorry I missed the earlier messages, creating a sparse file would require to schedule a pod with host volume and create the file from the pod. It's not recommended since talos by default wipes the disks on upgrade. Using extra disks is possibly a better approach.

**Comment by Ulexus** [comment]
**Clarification**:  Talos wipes the _system_ disk on upgrade (by default), not all disks of the system.

**Comment by mr-sab** [comment]
Thank you for the reply, I tried it and couldn't get it working.
So I bought some second hands SSD's and it all work out.

**Comment by maaft** [comment]
Any updates on this topic? Would really love to use longhorn in my talos cluster.

**Comment by bdsoha** [comment]
It seems like the inverse issue is also being tracked:
https://github.com/longhorn/longhorn/issues/3161

**Comment by bdsoha** [comment]
> @runningman84 mayastor supports pointing to a local raw disk file which needs to pre-provisioned. Ref: https://mayastor.gitbook.io/introduction/quickstart/tips-and-tricks#using-file-backed-disks

Mayastor does not currently support as reported on the [most recent release](https://github.com/openebs/mayastor/releases/tag/v1.0.5):
> "Unsupported" Architectures and Operating Systems (inc. ARM, Raspberry Pi, MacOS)

**Comment by jakoberpf** [comment]
Hello everyone, I don't get a clear picture from the conversation. So talos has iscsi support now with the `ghcr.io/siderolabs/iscsi-tools`, but I still have some errors when deploying **Longhorn**.

```logs
time="2023-03-02T16:13:31Z" level=error msg="Failed environment check, please make sure you have iscsiadm/open-iscsi installed on the host"
time="2023-03-02T16:13:31Z" level=fatal msg="Error starting manager: environment check failed: invalid mount namespace /host/proc/1/ns/mnt: failed to execute: nsenter [--mount=/host/proc/1/ns/mnt mount], output , stderr nsenter: failed to execute mount: No such file or directory\n: exit status 127"
```

Is the general consens, that we cannot use Longhorn on Talos ? Would be kind of a dealbreaker for me :-/

**Comment by frezbo** [comment]
yes, that's correct, from the LongHorn docs it requires binaries like `curl`, `bash`, `awk`, `bash` etc to be present on host. Bash is a no-go on talos, so longhorn cannot be supported until that requirement changes.

**Comment by jakoberpf** [comment]
@frezbo Alright thanks for clarifying this for me :-)

**Comment by zimmertr** [comment]
Looks like they're working on changing that: https://github.com/longhorn/longhorn/issues/3161

**Comment by bdsoha** [comment]
> Looks like they're working on changing that: [longhorn/longhorn#3161](https://github.com/longhorn/longhorn/issues/3161)

This is a very old issue, it has been open for over 1.5 years.

**Comment by zimmertr** [comment]
Did you see the latest comment on it?

**Comment by frezbo** [comment]
Longhorn v1.6.0 supports Talos, ref: https://longhorn.io/docs/1.6.0/advanced-resources/os-distro-specific/talos-linux-support/
