### ISSUE TITLE
Validation of extra disks

### ISSUE THREAD

**Issue by salkin** [siderolabs/talos#3140]
## Feature Request
Verify that extra disks specified are valid disk devices

### Description
When applying configuration specifying extra disks the actual disk is not verified to exist on apply-config. 

This results in a never ending crashloop if one makes a typo for non-existing disk, when adding extra disks and the box has to be scratch installed.

**Comment by smira** [comment]
Now Talos will pause on discovering a problem with `extraDisks`, allowing the `apply-config` API so the configuration can be fixed, not perfect but it's not a crash loop anymore.
