### ISSUE TITLE
Add the ability to customize static pod manifests

### ISSUE THREAD

**Issue by DWSR** [siderolabs/talos#3562]
## Feature Request

Add the ability to customize static pod manifests

### Description

As a user, I'd like the ability to customize the static pod manifests in order to better tailor Talos to my use case. For example, I'd like to be able to set pod requests and limits on control plane components in order to help support development clusters where workloads are running on the same nodes as the control plane components.

**Comment by smira** [comment]
Requests/limits are configurable now, as many other aspects of the static pods.
