### ISSUE TITLE
Support stdin for `talosctl apply-config`

### ISSUE THREAD

**Issue by DWSR** [siderolabs/talos#3563]
## Feature Request

Support stdin for `apply-config`

### Description

As a cluster operator, I'd like to be able to supply configuration to `talosctl apply-config` via STDIN in order to support better composability with tools like `sops` e.g. `sops 172.16.0.10.yaml | talosctl apply-config -f -`

**Comment by smira** [comment]
this should work today with `-f /dev/stdin`, I agree that having `-` is better UX of course
