### ISSUE TITLE
Extend ISO config-by-disklabel support

### ISSUE THREAD

**Issue by Ulexus** [siderolabs/talos#3564]
## Feature Request

In some environments, DHCP must not be used.  This makes it difficult to install Talos, since we have no way to bootstrap the network configuration before having a machine configuration available.

Presently, the installer supports pulling the config from a disk label (currently `metal-iso`, though I suggest perhaps renaming this to comething a bit clearer, like `talos-install-config`), which is exptected to contain a `config.yaml` file to use for the initial machine configuration.

However, that facility is hidden behind a kernel flag, which makes it less useful for the ISO, since you cannot easily modify the kernel parameters.

We should:
 - [ ] make the ISO (metal platform) default to looking for a local volume (and fall through to network config, of course)
 - [ ] extend this feature to support loading from `<mac>.yaml` in addition to and in preference of `config.yaml`

The latter would support deployment teams loading several configurations for a bank of new machines on a single USB stick which they could just move sequentially through to install and configure Talos.

**Comment by andrewrynhard** [comment]
We have a version of this 🙂 : https://github.com/talos-systems/talos/blob/22f375300c1cc1d95db540afd510a21b66d7c8a3/internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go#L107

**Comment by Ulexus** [comment]
Would be nice to extend it with `<mac>.yaml` support, so you could load it up with a bunch of machines... but yeah, it looks like that should work for now.  I'll modify this issue to reflect that.
