### ISSUE TITLE
IPv6 cluster and service CIDRs

### ISSUE THREAD

**Issue by Ulexus** [siderolabs/talos#3691]
## Feature Request

Since dual-stack is getting close to GA in Kubernetes, we should ship default Cluster and Service CIDRs for IPv6 alongside the IPv4 ones.  At a minimum, if we detect IPv6 in use, we should supply them.

We'll need to choose prefixes which are not generally routable, of course, but there are... plenty. :)

**Comment by uhthomas** [comment]
https://unique-local-ipv6.com/ should probably be used for generating IPv6 CIDRs (inline with the Kubernetes documentation).

**Comment by smira** [comment]
Talos already has some: https://github.com/siderolabs/talos/blob/dad517a71d8d07e78d0688cc19b80687c607b2d7/pkg/machinery/constants/constants.go#L720-L725

They are used if `gen config` is supplied with IPv6 address for the controlplane (not perfect, but hard to say what else can we do).
