### ISSUE TITLE
Makes ipv6 more securely

### ISSUE THREAD

**Issue by sergelogvinov** [siderolabs/talos#3818]
## Feature Request

Set stablehand secure  link-local/autoconfigured IPv6-address  using net.ipv6.conf.eth0.stable_secret kernel parameter.
On startup stage generate/set stable_secret  to the interface by default (as dm-crypt do now). 
This capabilities hide your mac address, and keep you IPv6 stable. 

https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt
* stable_secret=$random_seed
* addr_gen_mode=2

**Comment by flokli** [comment]
What's the advantage of obfuscating the mac addresses here?

**Comment by sergelogvinov** [comment]
there are two goals here.

1) hide the mac address. For example GCP creates unsafe mac addresses (ip -> mac with few changes)
2) have a stable IPv6 address. After reboot you will get the same IP.

**Comment by sergelogvinov** [comment]
EUI64 based on your mac. By mac you can get the local (cloud) IP. (GCP case)

Share your mac - is not secure. That's why ```stable_secret``` param was introduced.

**Comment by flokli** [comment]
I don't understand. Why is this a security issue? Can you link to something describing this attack vector?

**Comment by sergelogvinov** [comment]
> 

May be it helps to you https://www.internetsociety.org/blog/2015/02/ipv6-security-myth-5-privacy-addresses-fix-everything/

**Comment by flokli** [comment]
> Thus, this method enables keeping the “stability” properties of the Interface Identifiers specified in [RFC4291], while still mitigating address-scanning attacks and preventing correlation of the activities of a host as it moves from one network to another.

I fully understand why this is desirable for laptops and consumer devices in general, one way to remove one tracking possibility.

I still don't understand why it makes sense to have this for kubernetes worker nodes though :thinking:
