### ISSUE TITLE
network: support RDNSS

### ISSUE THREAD

**Issue by Ulexus** [siderolabs/talos#3840]
## Feature Request
Pure IPv6 systems frequently do not use DHCP services, instead relying on SLAAC, router advertisements, and RDNSS.

We should add support for discovering DNS servers via RDNSS.

### Description

mdlayher has a convenient Go package to facilitate:  https://github.com/mdlayher/ndp

This may be best accomplished by adding a `slaac` mode in the interface configuration (whether it is default or not is a different question).  This `slaac` mode would, similarly to how DHCP works now, take control of SLAAC-related services, such as:  neighbor discovery, route solicitation, DNS acquisition, etc after initial boot.

With the mode explicitly enabled (or enabled by default), we can then make explicit acceptance of router advertisements (#3841 ) and recursive DNS services (this issue).

**Comment by telmich** [comment]
How this works in general:

* Read the details in the router advertisement (RA)
* fill in the name servers from the RDNSS entries
* fill in the search path from the DNSSL entries

Both entries are usually having a lifetime that can be different from the router advertisement. Whenever a periodic router advertisement comes along, the entries should be updated.

If they expire and no RA is seen, the DNS entries should be dropped.

**Comment by asteven** [comment]
Possibly of interest:
https://mdlayher.com/blog/network-protocol-breakdown-ndp-and-go/
https://github.com/mdlayher/ndp

**Comment by smira** [comment]
I feel we should try to put that tentatively for 0.13
