### ISSUE TITLE
Dual-stack IPv6 default services

### ISSUE THREAD

**Issue by Ulexus** [siderolabs/talos#3918]
## Feature Request

Kubernetes v1.21 now supports dual-stack services, so we should convert our current method of two separate single-stack DNS and Kubernetes Services to be single dual-stack Services (each) when Kubernetes v1.21 is detected.

**Comment by smira** [comment]
see #3807

**Comment by Ulexus** [comment]
Good reference for CoreDNS, but we also need the Kubernetes service.
