### ISSUE TITLE
Support for Non runc runtimes

### ISSUE THREAD

**Issue by grepler** [siderolabs/talos#3922]
## Feature Request

support for other runtimes (like sysbox). This would allow us to run container virtualization workloads on Talos. 

### Description
We've successfully deployed Talos inside of our Proxmox hosts and are happily deploying applications, but one of them has the ability to utilize CVM (container virtualization) using sysbox. it looks like the resources it requires are more than Talos exposes - is this even possible with Talos, or will I need to create some bespoke workers for this application?

From the application [docs](https://coder.com/docs/coder/v1.20/admin/workspace-management/cvms):

- CVMs leverage the [Sysbox container runtime](https://github.com/nestybox/sysbox), so the Kubernetes Node must run a supported Linux distro with the minimum kernel version (see [Sysbox distro compatibility](https://github.com/nestybox/sysbox/blob/master/docs/distro-compat.md) for more information)

- The cluster must allow privileged containers and hostPath mounts. Read more about why this is still secure [here](https://coder.com/docs/coder/v1.20/admin/workspace-management#security).

**Comment by MichaelTrip** [comment]
This would be a great feature. I use sysbox for both professional and personal use and I would love to see this in Talos!

**Comment by hegerdes** [comment]
Would this also include support for runtime like `crun` and `rkt`?

I already run crun with wasm enabled on some onprem clusters. I'm really interested in talos. Can I just add the needed binaries and configure containerd oder is this not supposed yet?

**Comment by frezbo** [comment]
> Would this also include support for runtime like `crun` and `rkt`?
> 
> I already run crun with wasm enabled on some onprem clusters. I'm really interested in talos. Can I just add the needed binaries and configure containerd oder is this not supposed yet?

Containerd is the only runtime supported, but wasm,gvisor etc are supported via extensions: https://github.com/siderolabs/extensions

**Comment by Suertzz** [comment]
We also have some deployment using sysbox as a runtime ( gitlab runner, coder.com, and other « untrusted » code ) 

We didn’t find any workaround, so we cannot use talos right now

It will be great to have these implemented
