### ISSUE TITLE
add context delete option

### ISSUE THREAD

**Issue by Ulexus** [siderolabs/talos#3989]
## Feature Request

Especially since adding contexts can be automated, we should add a context remove CLI option, as well.

`talosctl context remove XXXX`

Ideally, this should allow glob patterns, too:  `talosctl context remove talos-default-*`.

**Comment by hobyte** [comment]
Love this Idea

It would be nice, if this can delete the kubernetes context too

**Comment by murtaza-u** [comment]
There's already the `talosctl config add <myctx>` command to add new contexts. It would make much more sense to plan the new sub-command as `talosctl config remove <myctx>`.

**Comment by DmitriyMV** [comment]
@murtaza-u are you going to open pull request?

**Comment by murtaza-u** [comment]
@DmitriyMV Yeah...shortly.

**Comment by DmitriyMV** [comment]
Just wanted to say, that we probably want confirmation dialogue for each match individually.

**Comment by murtaza-u** [comment]
Yeah that actually makes sense. The way I have it setup is that there's only one confirmation dialogue for all the matches. Any suggestion on how we should go about designing this? May be a flag like `--step` which steps over each match one by one.

**Comment by DmitriyMV** [comment]
`noconfirm` should be enough when you want to delete every match without confirmations. For completeness there could probably be a `dry` mode which will basically show what will be deleted.

**Comment by DmitriyMV** [comment]
Closed in #6671
