### ISSUE TITLE
Update VIP documentation to make using the VIP as the endpoint explicit

### ISSUE THREAD

**Issue by steverfrancis** [siderolabs/talos#4011]
## Feature Request
Following https://www.talos.dev/docs/v0.11/guides/vip/ will give you a VIP, but not one that is in use by the endpoints.
### Description
Should update the documentation to explictly show how to enable the created VIP for  both the Kubernetes API server and the Talos endpoint set.

**Comment by smira** [comment]
do you mean Talos API endpoints? that doesn't have to use the VIP, in fact it shouldn't, as Talos API access shouldn't depend on VIP, otherwise if the VIP goes down, Talos API access is screwed
