### ISSUE TITLE
Health check to Talos-api

### ISSUE THREAD

**Issue by sergelogvinov** [siderolabs/talos#4088]
Can you make health check endpoint for Talos-api

like https://$host:50000/healthz to makes external unauthorized checks 

tcp S/SA check does not check the daemon (kernel can response SA packet)

**Comment by SixFive7** [comment]
We'd love a health check endpoint as well so we can integrate it into our monitoring stack. Even better would be to split `/healthz` into `/livez` and `/readyz` where possible and provide a `?verbose` option that details out the components. Just as the kubernetes API server does. See: [Kubernetes API health endpoints](https://kubernetes.io/docs/reference/using-api/health-checks/)
