### ISSUE TITLE
docs: update mayastor docs to cover deficiencies in upstream docs

### ISSUE THREAD

**Issue by Ulexus** [siderolabs/talos#4129]
## Bug Report

There are a few common sticking points for people installing Mayastor where the upstream docs are wrong or lacking.  We should cover these errors and omissions in our own docs.

The biggest one to wit is the no topology one.

**Comment by MrMarble** [comment]
Hugepages are also wrong, following the Talos documentation I set the hugepages to `1024` but mayastor refused to start
 ```
0/1 nodes are available: 1 Insufficient hugepages-2Mi. preemption: 0/1 nodes are available: 1 Insufficient hugepages-2Mi
```

With `talosctl -n node-ip read /proc/meminfo` I saw that the hugepage size is not right, only **1Gib** of **2MiB-sized** pages
```
HugePages_Total:    1024
HugePages_Free:     1024
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
```

Setting the value to `2048` made it work as stated in mayastor [documentation](https://mayastor.gitbook.io/introduction/quickstart/prerequisites#general)

> - **HugePage support**
>	- A minimum of **2GiB** of **2MiB-sized** pages

```yaml
- op: add
  path: /machine/sysctls
  value:
    vm.nr_hugepages: "2048"
```
