### ISSUE TITLE
allow interface configuration by selectors

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#4203]
## Feature Request

This allows to attach configuration not to the current `eth` naming scheme (`eth0`, `eth1`, etc.), but rather use flexible selectors which pick one (or many?) interfaces.

### Description

Example:

```yaml
interfaces:
 - name: public
   deviceSelector:
    - busPrefix: "00:10"
```

See also: https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/

See also: https://github.com/systemd/systemd/blob/main/src/udev/udev-builtin-net_id.c

**Comment by smira** [comment]
Implementation hints:

* add labels to `LinkStatus` resource in `LinkStatusController`
* match links by selectors in `LinkConfigController`, build final network configuration as `LinkSpec`

**Comment by smira** [comment]
* this should work for all network controllers which consume machine config `.machine.network.interfaces` section (addresses, routes, links, operators, ...)
* idea: build intermediate controller which consumes network machine config, performs matching on selectors, and produces `.machine.network.interfaces` without selectors and with names resolved to the physical interface names (`eth0`, `eth1`, ...). make existing network controllers consume this "resolved" config instead of raw machine config

**Comment by mjohnson9** [comment]
I noticed that this comment says that selecting interfaces is supported in bond slave lists:

> where we support it:
> 
>     * top-level interfaces
> 
>     * bond slave list

How does one select interfaces in a bond slave list? I haven't had any luck.

**Comment by smira** [comment]
I think this never got implemented for bond slaves.

**Comment by mjohnson9** [comment]
Understood. Thank you.

**Comment by runiq** [comment]
Does this also change the interface name if I use both `name` and `deviceSelector` in the same config? For example, given this config:

```yaml
network:
  interfaces:
    - interface: "infra"
      deviceSelector: "52:54:00:00:00:00"
```

Will the interface get the name `infra`? (Probably not, because the selector can match multiple interfaces, right…?)

**Comment by smira** [comment]
> Does this also change the interface name if I use both `name` and `deviceSelector` in the same config? For example, given this:

Using both name and selector is not valid. Talos doesn't rename interface selectors.

Please also keep in mind that Talos 1.5+ will by default use predictable interface naming.

**Comment by runiq** [comment]
> > Does this also change the interface name if I use both `name` and `deviceSelector` in the same config? For example, given this:
> 
> Using both name and selector is not valid. Talos doesn't rename interface selectors.

Thanks, that's good to know.

> Please also keep in mind that Talos 1.5+ will by default use predictable interface naming.

Yeah, I'm currently testing with 1.5.0. (Great choice to incorporate the MAC address into the interface name, by the way!)
