### ISSUE TITLE
add Node.PodCIDRs to the k8s nodeadress filter

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#4212]
## Feature Request

Right now we're only using value from Talos machine configuration, but for some CNIs (e.g. Cilium) machine configuration might be out of sync with CNI configuration, so better to add actual config from the Node resource (append to the filter).

**Comment by SixFive7** [comment]
Next to the `v1.Node` resource fields:
- spec.podCIDR
- spec.podCIDRs

the cilium Kubernetes Host Scope IPAM mode also uses the `v1.Node` annotations:
- io.cilium.network.ipv4-pod-cidr
- io.cilium.network.ipv6-pod-cidr
- io.cilium.network.ipv4-cilium-host
- io.cilium.network.ipv6-cilium-host
- io.cilium.network.ipv4-health-ip
- io.cilium.network.ipv6-health-ip

But more importantly, the default IPAM mode (Cluster Scope) uses an entirely different resource `v2.CiliumNode` with the field: `Spec.IPAM.PodCIDRs`.
