### ISSUE TITLE
Document dd command on MacOS

### ISSUE THREAD

**Issue by andrewrynhard** [siderolabs/talos#4235]
We tell users to use `dd` to write images to SD cards. A few changes are needed on MacOS:

```bash
dd if=metal-rpi_4-arm64.img of=/dev/X conv=sync bs=4m
```

**Comment by AlekSi** [comment]
Maybe we could recommend Raspberry Pi Imager only on macOS? It is not like macOS users don't have GUI…

**Comment by peterkuiper** [comment]
@andrewrynhard I was following [this](https://www.talos.dev/v0.14/single-board-computers/rpi_4/) and noticed the same. How do you want to address that? Specific instructions per OS? I'd be happy to add it to the docs. This could be as simple as:

```
Linux:
    sudo dd if=metal-rpi_4-arm64.img of=/dev/mmcblk0 conv=fsync bs=4M

MacOS:
    sudo dd if=metal-rpi_4-arm64.img of=/dev/X conv=sync bs=4m
```

There is another issues as well. The guide assumes `amd64` when downloading `talosctl`. Running this on a different Pi obviously does not work.
