### ISSUE TITLE
Second look at NTP server defaults

### ISSUE THREAD

**Issue by rsmitty** [siderolabs/talos#4252]
We're not supposed to use pool.ntp.org directly it seems. We should look at changing the default to be a list.

The [pool docs](https://www.ntppool.org/en/use.html) say that we could use something like:

```
server 0.pool.ntp.org
server 1.pool.ntp.org
server 2.pool.ntp.org
server 3.pool.ntp.org
```

**Comment by smira** [comment]
This (0,1,2,3) should not be required for our implementation as we anyways resolve to the list of IP addresses and lock to the IP address until the sync fails.

**Comment by smira** [comment]
And our implementation is SNTP, not full NTP protocol for what it's worth.

**Comment by rsmitty** [comment]
Right on, just wanted to track the convo from Slack. We should at the very least apply for a vendor zone again once our name change stuff is all done. They do at least ask that you don't include pool.ntp.org *as a default*.

**Comment by rsmitty** [comment]
I tried to submit a vendor zone request but quickly ran into cert issues and 500s on their side. Will keep this ticket open just to track and will try again later.

**Comment by smira** [comment]
I did same multiple times, Andrew did that I believe, it just never works.

**Comment by ion1** [comment]
{0,1,2,3}.pool.ntp.org are equivalent to pool.ntp.org and {0,1,2,3}.<vendor>.pool.ntp.org are equivalent to <vendor>.pool.ntp.org. The reason they suggest using the numbered ones with ntpd is that you need four "server" keywords to talk to four servers at the same time. If an NTP client is able to talk to all four servers that pool.ntp.org or <vendor>.pool.ntp.org resolves to then you don't need the numbered ones.

The reason you want the NTP client to talk to four servers is that you can't trust just one or two, even more so given a volunteer-based NTP pool anyone can join. Hardware/firmware issues and even malicious servers could result in falsetickers; querying multiple servers and validating the results against a majority mitigates that.
