### ISSUE TITLE
drain daemonsets on upgrade/shutdown

### ISSUE THREAD

**Issue by sergelogvinov** [siderolabs/talos#4275]
## Feature Request

Kubernetes drain method skip DaemonSet by default.
But taint **NoExecute** can move out (delete) gracefully DaemonSets (witch does not have tolerations)

### Description

So, better to set taint NoExecute to the node after drain stage.
Usually network daemonsets/system pods have NoExecute tolerations.

**Comment by smira** [comment]
# Planning Meeting Notes

We should have credentials on worker nodes, as they add taint `NoSchedule`.

:+1:

**Comment by smira** [comment]
Probably it should be covered anyways #3095

**Comment by smira** [comment]
#3095 covers daemonsets (and any pods running on the node)
