### ISSUE TITLE
Support VIP over BGP like ARP.

### ISSUE THREAD

**Issue by anthr76** [siderolabs/talos#4334]
## Feature Request

For users on bare-metal that utilize BGP for Load-Balancer services it would be great to provide vip functionality over BGP instead of ARP. For example looking for functionality kube-vip provides for the control-plane over BGP. 

Alternatives to this feature would be:

* kube-vip as a static pod with the file directive
* Anycast with bird as a static-pod

Both solutions wouldn't be as seamless as having this intergration directley in Talos. What is the community's thoughts on having this implemented?

**Comment by ryanjafari** [comment]
I was hoping metallb would be able to handle this (planning on it actually). Am I mistaken?
