### ISSUE TITLE
accessing Talos API from Kubernetes workloads

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#4422]
- [ ] Talos auth controller/mutating webhook which based on pod annotations injects a configmap volume mount which contains generated (and refreshed) `talosconfig` with RBAC tied to Kubernetes RBAC for the Service Account
- [x] service for the Talos API in Kubernetes: endpoints, service which talks to endpoints
- [ ] map Talos API RBAC to Kubernetes RBAC (use CRDs?)
- [ ] have a way to limit Talos RBAC roles user can get, default to empty (disabled by default, requires Kubernetes RBAC to be set up properly)
- [ ] final user experience should be that `talosctl` should work out of the box if the RBAC is configured

**Comment by dimatha** [comment]
Hi Guys, I just wanted to know how far we are from reaching this goal? Thanks!

**Comment by smira** [comment]
@dimatha no commitment yet, but we plan on delivering that in the next release 1.1

**Comment by smira** [comment]
See also: https://github.com/siderolabs/rfcs/pull/9
