### ISSUE TITLE
feat: Extend ISO config for USB-sourced config (sneakerconf)

### ISSUE THREAD

**Issue by Ulexus** [siderolabs/talos#4423]
## Feature Request

A common problem, particularly in non-automated baremetal systems, is providing a configuration to a machine without knowing that machine's IP or before networking can be established with that machine.  

Presently, the installer supports pulling the config from a disk label (currently `metal-iso`, though I suggest perhaps renaming this to something a bit clearer, like `talos-config`), which is exptected to contain a `config.yaml` file to use for the initial machine configuration.

When a Talos machine is running in maintenance mode, it waits for configuration to be applied.  One possible vector for the application of configuration is plugging in a USB stick.

The scheme could be as follows:
 - Talos maintenance mode probes (periodically or on disk addition) for partition label TALOS_CONFIG (or whatever)
 - Talos mounts `TALOS_CONFIG` and looks for its configuration there, in the following order:
   - `MAC.yaml` where `MAC` is the MAC address of each discovered network interface
   - `DMI-SERIAL.yaml` where `DMI-SERIAL` is the chassis serial number as discovered from DMI.
   - `config.yaml` - default non-machine-specific configuration file
 - Talos applies the discovered configuration as if through `apply-config`

**Comment by flokli** [comment]
> I think the `metal` platform and `nocloud` do the same. We can merge they in one solution. And add network presets MAC.yaml DMI-SERIAL.yaml.

Yes, `nocloud` and `metal` can both read config from an additional filesystem.

In the case of `nocloud`, this filesystem is named `CIDATA`/`cidata`, and can contain `user-data`, `meta-data` and `network-config` files.
In the case of `metal`, the filesystem seems to have to be named `metal-iso`, and config is read from `config.yaml`.

I couldn't get both to work though :thinking: .

**Comment by sergelogvinov** [comment]
> 
> I couldn't get both to work though 🤔 .

Can you add more details, why you can use metal/nocloud platform?

**Comment by flokli** [comment]
This has been discussed on Slack a bit - I think in my case, it's might be mostly due to it only detecting CIDATA if it's a separate block devices, and not just a partition.

**Comment by flokli** [comment]
Ah, on Slack you replied:

> CIDATA partition usually stores as separate block device. Openstack uses additional partition to store cloud-config. Try to use openstack platform…

I'll try the openstack variant.

It'd be really nice if we could unify all these code paths, so they will pick up from `CIDATA`/`cidata`/`metal-iso`/`talos-config`, independent on whether it's a separate block device or partition. This is all pretty confusing right now.

**Comment by flokli** [comment]
`openstack/metadata.go` also just seems to be using `probe.GetDevWithFileSystemLabel`, like `nocloud` and `metal` - which doesn't seem to work with partitions.

**Comment by flokli** [comment]
The partition detection was fixed in https://github.com/siderolabs/talos/commit/efa3f289853a47ae0d4bca5dbf656e527cf312dd.  :tada: 

It'd still be nice if the different configs could be merged together a bit, so the config partition name can be any of `CIDATA`/`cidata`/`metal-iso`/`talos-config`, and the talos config be either `./user-data` or `./config.yaml` in there.

There should probably still be an ISO variant, and a "small disk with partition" variant.

**Comment by smira** [comment]
Right now I believe it should work ISOs as well if they're properly labeled. But yeah, this needs to be properly documented

**Comment by silenium-dev** [comment]
> The partition detection was fixed in [efa3f28](https://github.com/siderolabs/talos/commit/efa3f289853a47ae0d4bca5dbf656e527cf312dd). 🎉

It doesn't work any more, as the config mount tries to use `dev.Device().Path()`, which points to the entire disk, instead of `dev.Path`, which contains the path to the actual partition: https://github.com/siderolabs/talos/blob/d7c3a0735eab85dd24e86fe3e0872253067e8f10/internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go#L131
