### ISSUE TITLE
Make /system a tmpfs volume in Talos containers

### ISSUE THREAD

**Issue by TimJones** [siderolabs/talos#4478]
### Description
As a follow-up to issue #4462 & its fix #4465 it might well be worth considering making the`/system` volume of a docker container running Talos a tmpfs volume, so it more closely mirrors the ephemeral nature of a host disk install.

**Comment by haslersn** [comment]
In this case, why does it need to be a volume at all? Is it in order that it works with `ReadonlyRootfs`?

**Comment by smira** [comment]
`/system` on Talos also contains `/system/state` which is persistent, so probably we should have both

**Comment by smira** [comment]
I tried experimenting with that a bit, and I think Docker config is not flexible enough to replicate exactly what we need.

Even `ReadonlyRootfs` doesn't quite work, but that is more a deficiency of Talos in container mode.
