### ISSUE TITLE
Provide a way to set CPU scaling governor

### ISSUE THREAD

**Issue by rsmitty** [siderolabs/talos#4508]
We'll be defaulting to `schedutil` soon instead of `userspace`, but some users want to set to `performance`. We should figure out how to make this value tweak-able. Sysctl sounds like the first place to look but I haven't found a good example of it, so we may have to find some other way to accomplish it.

**Comment by abckey** [comment]
any update on this ?

**Comment by rsmitty** [comment]
Hey @abckey, just to be clear about this issue, this will only solve being able to set the value explicitly in the machine config. Talos v0.14 already includes the `schedutil` default, which should see massive gains for you. But no movement on the configurability part yet. Stay tuned!

**Comment by Ulexus** [comment]
CPU governor cannot be set by sysctl; rather, it is sysfs.  We can/should add support for sysfs in a similar manner as we support sysctl.

**Comment by Ulexus** [comment]
Depends on #4703

**Comment by nberlee** [comment]
As a FYI for documenting purposes, setting the scaling governor in sysctl is nice for testing. (instant) 
But quite awkward as it is needed to be set for all cores/threads (`/cpu0/`, '/cpu1/' etc)

A more elegant solution is to add a kernel parameter using:
```
machine:
  install:
    extraKernelArgs:
      - cpufreq.default_governor=performance
```

(in a existing cluster you need to run a talos upgrade in order for this to become effective)
