### ISSUE TITLE
network: send node hostname to DHCP server

### ISSUE THREAD

**Issue by dimatha** [siderolabs/talos#4536]
## Feature Request

Ability to send node hostname to the DHCP server (option 12?) 

### Description

We are relying on our DHCP server to update DNS records for our DHCP clients and need the ability to provide Talos hostname to the DHCP server

**Comment by smira** [comment]
Thanks, that makes perfect sense to me. Talos might not have hostname on the initial DHCP request, but it should be able to send it while renewing the lease.

**Comment by smira** [comment]
There are many ways to set the hostname (including getting it from the DHCP server), so Talos might learn the hostname after the initial DHCP or before that, but still when it knows the hostname, it could update the DHCP server.

**Comment by dimatha** [comment]
That's actually related to https://github.com/talos-systems/cluster-api-bootstrap-provider-talos/issues/96
We use CAPI/CAPV + CABPT/CACPPT.
The idea is to use the Machine name provided by CAPI and DHCP client ship the right hostname to the DHCP server for DNS update. 
Currently the hostname defaults to 'talos-1.2.3.4'
