### ISSUE TITLE
Summary console

### ISSUE THREAD

**Issue by Ulexus** [siderolabs/talos#4584]
## Feature Request

While logging to the console is useful, as people have to perform less debugging, it becomes potentially _more_ useful to display summary information to the console instead (at least by default).  For one thing, it is difficult to sift through much of the data, and for another, when the console scrolls, it is often difficult to retrieve the data in any case.

Consider the use case of a fleet of machines in a rack.  Plug up a monitor, and you can get vital IDs and status before physically servicing the machine.  Presently, this is difficult to do, since the console does not necessarily show any identifying information:  it's just whatever the last log messages were.

Next, consider the use case of the novice:  debug/log information may be of little use at best; at worst, various transient errors may be interpreted as severe and problematic.  If simple summary data is displayed instead, this presents a much more pleasant experience.

Proposed, therefore, is a "summary" mode (as opposed to the current "debug" or "logging" mode) for the local console (not logging destination) with (as an example) the following data:
 - Node ID
 - Cluster ID
 - Node Name
 - Node Addresses
 - Service status summary (e.g. `talosctl services`)
 - perhaps a section to the screen which displays the last few console log lines

Also, when in summary mode, it could be pleasant to display a simple splash screen and Sidero/Talos logo, if a graphical console is detected.  That may not be easily achievable without external programs in the initrd, though... needs research.

At this point, we don't need to look at a fully-interactive console; just a display mode switch.  As a later feature, an interactive console could be nice.

Sub-tasks:

- [ ] #4790
- [ ] #4791

**Comment by andrewrynhard** [comment]
Another idea is to have different output types on different virtual consoles (tty0, tty1, ..., ttyn). (e.g. logs on tty0, summary on tty1)

**Comment by smira** [comment]
Superseded #6752
