### ISSUE TITLE
Force reboot

### ISSUE THREAD

**Issue by sergelogvinov** [siderolabs/talos#4655]
## Feature Request

By default Talos send kill signal to the kubelet and wait...
Then trying to stop other containers.

In bad case, Talos spends a lot of time to wait/stop process.
So can you add ```reboot --force``` method, which makes fast unsafe reboot?

**Comment by smira** [comment]
## Planning Meeting Notes

Better idea might be to add a flag `--grace-period=90s` which controls the time spent shutting down pods. Force reboot can be triggered by setting a short `--grace-period`.

Stopping Talos services should take no more than a few seconds, but we can add internal timeout there (if it's not there?) to make sure Talos reboots even if the system services can't be stopped.

**Comment by smira** [comment]
Idea: `--force` reboot that skips stopping anything and reboots immediately.
