### ISSUE TITLE
Documentation: Guide for IP v6

### ISSUE THREAD

**Issue by steverfrancis** [siderolabs/talos#4696]
## Feature Request
Talos.dev documentation shows no search results for "ipv6", "ip v6" or "v6". Possibly a search bug, but I couldn't find a Guide or Reference detailing how to set up IP v6.

There are two references to IP v6 in https://www.talos.dev/docs/v0.13/reference/configuration/#config but that is all, as far as I can see.

We need a Guide that clearly documents how to enable IP v6, caveats, what is supported and not, etc.

**Comment by Ulexus** [comment]
Kubernetes has gotten much better on its side (especially with respect to dual-stack deployments), so yeah; it could use some documentation.

For the most part, though, using single-stack IPv4 or IPv6 is a non-issue.  Just set the Pod and Service subnets to what you want, make sure your Nodes get IPv6 addresses from the network (or machine config), make sure your CNI is configured for IPv6, and that's it.  It should Just Work.

Dual stack might have some more hurdles.  Testing needed.

**Comment by Ulexus** [comment]
Also, looks like a search bug.  There are definitely references to IPv6 in the docs:

```
$ grep -ri ipv6 .
./Cloud Platforms/hetzner.md:# IPv6: 2a01:4f8:X:X::1
./Guides/kubespan.md:Talos automatically configures unique IPv6 address for each node in the cluster-specific IPv6 ULA prefix.
./Learn More/kubespan.md:- send all IPv6 traffic to the WireGuard interface
./Reference/cli.md:      --cidr string                             CIDR of the cluster network (IPv4, ULA network for IPv6 is derived in automated way) (default "10.5.0.0/24")
./Reference/cli.md:      --ipv6                                    enable IPv6 network in the cluster (QEMU provisioner only)
./Reference/configuration.md:For dual stack configuration, there should be two subnets: one for IPv4, another for IPv6.
./Reference/configuration.md:If not specified, node IP is picked based on cluster podCIDRs: IPv4/IPv6 address or both.
./Reference/configuration.md:<code>ipv6</code>  <i>bool</i>
```

**Comment by kurious-diru** [comment]
I think the search only works for headings/sub-headings, there are references to ipv6 in the content at multiple places
