### ISSUE TITLE
Sponsored: multipath support

### ISSUE THREAD

**Issue by andrewrynhard** [siderolabs/talos#4720]
### Description

We had initial work to include multipath functionality inside Talos.
It could be useful to complete the work for including this service in a optional way.

**Comment by andrewrynhard** [comment]
Questions on our side:

  - What all is required for this? Is it just a kernel module? Do we need userspace binaries/services?

**Comment by andrewrynhard** [comment]
Looking at https://github.com/sbskas/pkgs/commit/1d527ad71577e21b7ebcac8c843835cdbaeee3a3, we wonder if we can skip any host binaries and just do kernel modules. If we _have_ to have host binaries, can we skip the ncurses, readline, etc. libraries since we don't have interactive shells?

**Comment by sbskas** [comment]
multipath is a cooperation between different part of the system on a normal system :
1. multipath
2. device-mapper
3. udevd
Don't know if it's doable without any helpers like lacp.
