### ISSUE TITLE
Sponsored: ability to remove a directory

### ISSUE THREAD

**Issue by andrewrynhard** [siderolabs/talos#4726]
### Description

Ability to wipe a certain directory in the /var/lib (/var/lib/rook for example) to recover from a failed install of rook for example.

**Comment by Ulexus** [comment]
This is a pretty big break from our current stance.  We support wholesale wipe, and we do now have RBAC... but this feels is getting pretty specific.
Also, this isn't a good solution to a failed (or recycled) Rook installation.  Instead, you want the ability to wipe a _partition_ or a _disk_, not a filesystem or directory.

**Comment by steverfrancis** [comment]
Seems like a bad idea from an immutability/declarative config stance

**Comment by sbskas** [comment]
This feature is to reset a bad state from the ephemeral FS.
It's partially covered by the new feature [feat: introduce talos.exp.wipe kernel param to wipe system disk](https://github.com/talos-systems/talos/commit/da0b36e61).
It could be enough for now to recover the node.
