### ISSUE TITLE
UEFI install does not setup talos as the first entry to boot.

### ISSUE THREAD

**Issue by sbskas** [siderolabs/talos#4767]
### Description
When we install talos on a UEFI machine which was running a previous OS, the installer does not setup an entry for talos in uefi boot order.
At cold/warm boot, the system tries to boot with the old OS entry which is obviously not there anymore.
installer should create an entry for talos and set it up to boot first.
### Environment

- Talos version: 0.14.0
- Kubernetes version: 
Client Version: v1.23.1
Server Version: v1.23.1

- Platform:
Uefi hardware.

**Comment by rio** [comment]
Can confirm, running talos v1.0.5. It keeps trying to boot the old ubuntu install.
