### ISSUE TITLE
put `talosctl dashboard` on a virtual tty

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#4791]
## Feature Request

After boot Talos should keep console logs on one tty9, and switch tty1 (0?) to display `talosctl dashboard` with summary view as a default.

### Description

* are we missing any kernel config?
* how to implement switching between virtual ttys?
* how to redirect console logs to another tty?

**Comment by smira** [comment]
setting up virtual consoles: https://github.com/systemd/systemd/blob/main/src/vconsole/vconsole-setup.c

**Comment by flokli** [comment]
This should probably only apply to servers with multiple (functional) ttys.

Headless VMs, or SBCs without a GPU should probably only show their console logs on the serial port (which has a too small "screen size" anyways to make the dashboard useful)

**Comment by utkuozdemir** [comment]
https://github.com/siderolabs/talos/pull/6879
