### ISSUE TITLE
Truly ephemeral local node install

### ISSUE THREAD

**Issue by nwmcsween** [siderolabs/talos#4824]
## Feature Request
Don't store any state that isn't administered by k8s on a local node.

### Description
By default almost all k8s distros or k8s installations depend on non k8s administered state (partitoning, etcd state, etc), this makes treating hardware nodes as disposable hard.

I see two paths for this, use externally visible filesystem (NFS, etc and rely on that being managed by some infra) or use CAPI and create bootstrap cluster and migrate the storage of k8s to within k8s itself (etcd, etc).

**Comment by romanchyla** [comment]
I'd like to second this. **Treating hardware nodes as disposable** is a wonderful use case for bare metal. And Talos seems to be almost there. Booting over PXE, living in RAM, and giving all the hardware (all the disks) to k8s workloads.

**Comment by x041** [comment]
till intrested in this
