### ISSUE TITLE
Ambiguous resource alias

### ISSUE THREAD

**Issue by andrewrynhard** [siderolabs/talos#5009]
```
~> talosctl get ksps
rpc error: code = InvalidArgument desc = resource type "ksps" is ambiguous: [kubespanpeerspecs.kubespan.talos.dev kubespanpeerstatuses.kubespan.talos.dev]
```

**Comment by smira** [comment]
that is expected... what are you looking for as a solution?

**Comment by andrewrynhard** [comment]
> that is expected... what are you looking for as a solution?

I don't know. But it seems wrong to print out that a user can use the alias/shorthand and then it doesn't work.

**Comment by smira** [comment]
ah, you mean we shouldn't even show them? I'm not sure, as by nature resource definition list is dynamic. we should basically update resource definitions on the fly removing ambiguous aliases

**Comment by andrewrynhard** [comment]
> ah, you mean we shouldn't even show them? I'm not sure, as by nature resource definition list is dynamic. we should basically update resource definitions on the fly removing ambiguous aliases

Yeah that sounds like all we can do.

**Comment by smira** [comment]
I don't quite like that from the architectural point of view, as it means we have to special case resource definitions and do some additional processing on them.
