### ISSUE TITLE
Ship kernel logs to Loki using the Push API

### ISSUE THREAD

**Issue by rafaribe** [siderolabs/talos#5017]
## Feature Request
Talos should support sending kernel logs to Loki.

For this we could use the [push API](https://grafana.com/docs/loki/latest/api/#post-lokiapiv1push)

### Description

Since Talos already supports the log shipping in `json_lines` it should not be too hard to add some configuration options to ship logs to Loki. 

Some considerations for configuration parameters:

- Basic Auth
- Labels

**Comment by smira** [comment]
Please see #4880
