### ISSUE TITLE
Raspberry pi 3 support

### ISSUE THREAD

**Issue by maxromanovsky** [siderolabs/talos#5019]
Just wondering if RPI3 support is something possible / planned. There are still plenty of RPI3s around, and they run k3s just fine, so I think it's worth asking.

**Comment by mladedav** [comment]
I tried using the image for 4 in my 3b+ but it looked like nothing is happening. I do not have a raspberry pi 4 on hand to verify that the image is actually working.

Can a maintainer please acknowledge this even if you tell us that you do not plan to support this or that it is so deep in the backlog that we shouldn't expect it see the light of day.

Additionally if anyone knows what the issues are, I would be somewhat interested. I don't think I would be able to help, but I would still like to know.

**Comment by frezbo** [comment]
| I tried using the image for 4 in my 3b+ but it looked like nothing is happening. I do not have a raspberry pi 4 on hand to verify that the image is actually working.

So quite a few things to get it working

* needs u-boot compiled for rpi3b (you can start by taking a look [here](https://github.com/siderolabs/pkgs/blob/master/u-boot/pkg.yaml#L77=)
* can only be used for Talos worker nodes (control plane will need at least 2gig of RAM)
* Talos is 64 bit only and I have seen conflicted results on Rpi 3B+ 64 bit support, this also needs to be tested
