### ISSUE TITLE
Log sender color chars

### ISSUE THREAD

**Issue by sergelogvinov** [siderolabs/talos#5034]
### Description

It will be better to remove/clean the special characters from tcp/udp logs.

```
2022-02-21T19:00:14.667Z \u001b[34mINFO\u001b[0m created
```

### Logs

```json
{"date":1645470015.54143,"component":"controller-runtime","controller":"network.RouteSpecController","destination":"default","gateway":"192.168.10.253","link":"eth0","msg":"2022-02-21T19:00:14.667Z \u001b[34mINFO\u001b[0m created route","table":"main","talos-level":"info","talos-service":"controller-runtime","talos-time":"2022-02-21T19:00:15.541177292Z"}
```

### Environment

- Talos version: master branch

**Comment by smira** [comment]
Better fix would be to have a separate log for `controller-runtime` which is JSON formatted without colors, the log we have today is more for humans rather than machines.
