### ISSUE TITLE
virtual box setup is not working:controlplane is not up due to controller manager Authorization error

### ISSUE THREAD

**Issue by gururajsrk** [siderolabs/talos#5040]
## Bug Report
Controlplane is not up due to controller manager Authorization error

$kubectl get nodes
No resources found

### Description
After installation flowing the procedure : https://www.talos.dev/docs/v0.14/local-platforms/virtualbox/
>export CONTROL_PLANE_IP=192.168.29.202
>talosctl gen config talos-vbox-cluster https://$CONTROL_PLANE_IP:6443 --output-dir _out
>talosctl apply-config --insecure --nodes $CONTROL_PLANE_IP --file _out/controlplane.yaml
>talosctl config endpoint $CONTROL_PLANE_IP
 >talosctl config node $CONTROL_PLANE_IP
>talosctl --talosconfig talosconfig config endpoint 192.168.29.202
>talosctl --talosconfig _out/talosconfig config endpoint 192.168.29.202
>talosctl --talosconfig _out/talosconfig config node 192.168.29.202
>talosctl --talosconfig _out/talosconfig bootstrap
>talosctl --talosconfig _out/talosconfig kubeconfig .
$kubectl get nodes
No resources found
### Logs
**controller-runtime is failing:**
192.168.29.202: user: warning: [2022-02-23T08:05:02.817145832Z]: [talos] controller failed {"component": "controller-runtime", "controller": "k8s.KubeletStaticPodController", "error": "error refreshing pod status: error fetching pod status: an error on the server (\x5c"Authorization error (user=apiserver-kubelet-client, verb=get, resource=nodes, subresource=proxy)\x5c") has prevented the request from succeeding"}
192.168.29.202: user: warning: [2022-02-23T08:06:05.117451832Z]: [talos] controller failed {"component": "controller-runtime", "controller": "k8s.KubeletStaticPodController", "error": "error refreshing pod status: error fetching pod status: an error on the server (\x5c"Authorization error (user=apiserver-kubelet-client, verb=get, resource=nodes, subresource=proxy)\x5c") has prevented the request from succeeding"}
192.168.29.202: user: warning: [2022-02-23T08:07:29.364493832Z]: [talos] controller failed {"component": "controller-runtime", "controller": "k8s.KubeletStaticPodController", "error": "error refreshing pod status: error fetching pod status: an error on the server (\x5c"Authorization error (user=apiserver-kubelet-client, verb=get, resource=nodes, subresource=proxy)\x5c") has prevented the request from succeeding"}
192.168.29.202: user: warning: [2022-02-23T08:08:28.368433832Z]: [talos] controller failed {"component": "controller-runtime", "controller": "k8s.KubeletStaticPodController", "error": "error refreshing pod status: error fetching pod status: an error on the server (\x5c"Authorization error (user=apiserver-kubelet-client, verb=get, resource=nodes, subresource=proxy)\x5c") has prevented the request from succeeding"}
[dmesg.log](https://github.com/talos-systems/talos/files/8122753/dmesg.log)

**kube-api server** 
192.168.29.202: 2022-02-23T08:10:55.94408012Z stdout F {"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"0f26c398-1864-46a0-8e5c-37aae1e8ccd8","stage":"RequestReceived","requestURI":"/apis/storage.k8s.io/v1/csinodes/talos-192-168-29-202","verb":"get","user":{"username":"system:anonymous","groups":["system:unauthenticated"]},"sourceIPs":["192.168.29.202"],"userAgent":"Go-http-client/2.0","objectRef":{"resource":"csinodes","name":"talos-192-168-29-202","apiGroup":"storage.k8s.io","apiVersion":"v1"},"requestReceivedTimestamp":"2022-02-23T08:10:55.943261Z","stageTimestamp":"2022-02-23T08:10:55.943261Z"}
192.168.29.202: 2022-02-23T08:10:55.957021337Z stdout F {"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"0f26c398-1864-46a0-8e5c-37aae1e8ccd8","stage":"ResponseComplete","requestURI":"/apis/storage.k8s.io/v1/csinodes/talos-192-168-29-202","verb":"get","user":{"username":"system:anonymous","groups":["system:unauthenticated"]},"sourceIPs":["192.168.29.202"],"userAgent":"Go-http-client/2.0","objectRef":{"resource":"csinodes","name":"talos-192-168-29-202","apiGroup":"storage.k8s.io","apiVersion":"v1"},"responseStatus":{"metadata":{},"status":"Failure","reason":"Forbidden","code":403},"requestReceivedTimestamp":"2022-02-23T08:10:55.943261Z","stageTimestamp":"2022-02-23T08:10:55.956420Z","annotations":{"authorization.k8s.io/decision":"forbid","authorization.k8s.io/reason":""}}
### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
-Client:
	Tag:         v0.14.2
	SHA:         06ea409b
	Built:       
	Go version:  go1.17.7
	OS/Arch:     linux/amd64
Server:
	NODE:        192.168.29.202
	Tag:         v0.14.2
	SHA:         06ea409b
	Built:       
	Go version:  go1.17.7
	OS/Arch:     linux/amd64
	Enabled:     RBAC

- Kubernetes version: [`kubectl version --short`]
-Client Version: v1.23.1
Server Version: v1.23.1

- Platform:
 UBUNTU -20.04 - VirtualBox 6.1

**Comment by frezbo** [comment]
Seems the node got a different IP address after you applied the config:

```bash
retrying error: Get "https://192.168.29.202:6443/api/v1/nodes/talos-192-168-29-202?timeout=30s": dial tcp 192.168.29.202:6443: connect: connection refused
```
whereas the config was generated for `192.168.29.251`

Do you see the same errors after a while, Talos will keep on retrying until the components are up and healthy

**Comment by gururajsrk** [comment]
Hi,
Regret the inconvience.

my bad. I pasted the wrong  IP from the previous retry. but the correct IP is 192.168.29.202, as there in log.

Configuration was generated only for 192.168.29.202

WIth Regards,
Gururaj 
[talosconfig.zip](https://github.com/talos-systems/talos/files/8122854/talosconfig.zip)
[machinconfig.zip](https://github.com/talos-systems/talos/files/8122868/machinconfig.zip)
S

**Comment by frezbo** [comment]
I still don't see anything in the logs that is worth worrying (these are mostly transient errors). Could you provide the logs of `talosctl logs kubelet` and `talosctl logs etcd`

**Comment by gururajsrk** [comment]
Hi,

Please find the logs.

WIth Regards,
Gururaj S
[etcd.log.gz](https://github.com/talos-systems/talos/files/8122944/etcd.log.gz)
[kubelet.log.gz](https://github.com/talos-systems/talos/files/8122946/kubelet.log.gz)

**Comment by gururajsrk** [comment]
As I see from log:
192.168.29.202: {"ts":1645606599246.2493,"caller":"kubelet/kubelet_node_status.go:92","msg":"Unable to register node with API server","node":{"name":"talos-192-168-29-202"},"err":"nodes is forbidden: User \"system:anonymous\" cannot create resource \"nodes\" in API group \"\" at the cluster scope"}

With Regards,
Gururaj S

**Comment by oliverwiegers** [comment]
I got the same issue. It seems everything is running fine but the kubernetes components

**Comment by smira** [comment]
https://www.talos.dev/v1.4/advanced/troubleshooting-control-plane/ might be helpful here. I don't think this issue is still relevant, so closing it avoid confusion. Please open a specific issue with output of `talosctl support` in case of a problem. Thanks you!

**Comment by vibescirca81** [comment]
Running into the same issue. The metal-amd64 image simply will not start the cp correctly. :(

**Comment by smira** [comment]
@vibescirca81 please open a separate issue attaching the logs, preferrably `talosctl support` produced `support.zip` file.
