### ISSUE TITLE
document certificate/secret generation

### ISSUE THREAD

**Issue by flokli** [siderolabs/talos#5056]
Hey! When bootstrapping a new cluster, I'd like to render `controlplane.yaml`, `worker.yaml` and `talosconfig` through another tool, so running `talosctl gen config` and then editing the files isn't really an option.

(I essentially want to render the config with terraform, and then configure instances with their rendered config in userdata directly).

I ran `talosctl gen config $clusterName $clusterEndpoint --with-docs=false --with-examples=false` to get a more condensed example config, but I'm struggling a bit with the shape of the certificates/keys/tokens that are created.

Some of these seem to be (base64-encoded) certificates:

 - machine.ca.{crt,key}
 - cluster.ca.{crt,key}
 - cluster.aggregatorCA.{crt,key}
 - clusterserviceAccount.{key}
 - cluster.etcd.ca.{crt,key}

What keys/ciphers and subjects need to be used here?

Is there any relationship between them (such as `machine.ca.crt` needs to be signed by `cluster.ca.key`)?

Is there any expiration dates on these certs? Which of these are OK to be shared across multiple nodes, for which it's not OK?

Some seem to be random(-ish) tokens, or weird base? encoding:
 - cluster.id
 - cluster.secret
 - cluster.token
 - aescbcEncryptionSecret

What's the encoding? Any length/character set requirements?

## Feature Request
Document all these secrets, how they can be created manually, and their relationships between each other.

**Comment by frezbo** [comment]
@flokli I've worked on an example that uses Pulumi here: https://github.com/frezbo/pulumi-provider-talos/tree/main/examples

**Comment by flokli** [comment]
Thanks for the link! However, this is a pulumi provider, which I can't really use from terraform.

Also, the whole pulumi ecosystem still feels a bit too unstable for my taste.

It'd be nice if what's generated during `talosctl gen-config` could get documented somewhere, so people could create these secrets on their own.

**Comment by frezbo** [comment]
We have a story to improve this, in the meantime if you want to take a peek at how it's generated: https://github.com/talos-systems/talos/blob/master/pkg/machinery/config/types/v1alpha1/generate/generate.go#L195

**Comment by smira** [comment]
@flokli I would recommend against trying to generate Talos machine configuration without Talos code, as there are many small details which change from version to version of Talos, and that is all included into the Talos `machinery` package. So I would rather try to use the `machinery` package, or output of `talosctl gen config` and customize the output as necessary with the config patches or other means. But the base config should come from the `machinery` package.

Also `machinery` from Talos version X can generate machine configs compatible with older Talos releases, so it makes sense to keep `machinery` up to the latest release, and have an option to generate configs for older versions of Talos as needed.

**Comment by flokli** [comment]
> @flokli I would recommend against trying to generate Talos machine configuration without Talos code, as there are many small details which change from version to version of Talos, and that is all included into the Talos machinery package

Fair enough - I was hoping the versioning and validation of the schema would be sufficent though ;-) 

---

How would the story look like to dynamically create custom talos config and attach it to userdata with *terraform*? I assume I'm not the only one not yet comfortable with Pulumi.

I could imagine using something like https://registry.terraform.io/providers/poseidon/ct/latest/docs/data-sources/ct_config, but for rendering talos configs. Did you do some tinkering in that direction?

On first sight, it might get a bit tricky, both keeping that in sync with the Talos machinery, as well as generating different configs all sharing the same cluster credentials - so there might need to be some dependency tree to ensure they all base from the same root config…

**Comment by smira** [comment]
I haven't tried that, but there's https://github.com/borancar/terraform-provider-talos

**Comment by flokli** [comment]
Hmmh, that one looks a bit outdated (using `v0.10.0-alpha.2.0.20210524192334-209527eccc6c`), with a draft PR to bump to v0.11.5 sitting around since August last year (https://github.com/borancar/terraform-provider-talos/pull/1).

It also defines a single `talos_cluster_config` resource, exposing `bootstrap_user_data`, `controlplane_user_data`, `join_user_data` and `talos_config` attributes, rather than having a "base talos config" resource wrapping all the secrets generation and allowing further customization of the controlplane/worker configs in "child resources".

The story of updating generated json files inside terraform isn't great either. I wonder if this could be adopted/supported somehow by Talos directly.

**Comment by smira** [comment]
We are looking to improve the machinery API to make it easier to generate the config files, but it is right now possible to generate the secrets once and stamp out machine configs with patches, etc. 

it's not optimal from the Go API point of view, but works perfectly:

https://github.com/talos-systems/cluster-api-bootstrap-provider-talos/blob/3bc5406fcbbfac8024771b7e7b11228dd798fed1/controllers/talosconfig_controller.go#L485-L501
