### ISSUE TITLE
talosctl doesn't use KUBECONFIG environment variable

### ISSUE THREAD

**Issue by TimJones** [siderolabs/talos#5091]
### Description

It seems that if the [kubeconfig environment variable](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#the-kubeconfig-environment-variable) is set, `talosctl` will always use `~/.kube/config`. I would expect that, when set, `KUBECONFIG` is used as the source/destination of the Kubernetes configuration.

Looks like it would just need to be added to [internal/pkg/kubeconfig/kubeconfig.go](https://github.com/talos-systems/talos/blob/master/internal/pkg/kubeconfig/kubeconfig.go#L14), but I'm not sure that catches all uses of the kube config file.

### Reproduction

```shell
# No default kube config
$ ls -lAh ~/.kube
ls: cannot access '/home/tim/.kube': No such file or directory

# Create & use temp directory
$ cd "$(mktemp -d)"
$ export KUBECONFIG="${PWD}/kubeconfig"
$ talosctl cluster create --name kubeconfig-test                           
validating CIDR and reserving IPs
generating PKI and tokens
creating network kubeconfig-test
creating master nodes
creating worker nodes
waiting for API
bootstrapping cluster
waiting for etcd to be healthy: OK
waiting for apid to be ready: OK
waiting for kubelet to be healthy: OK
waiting for all nodes to finish boot sequence: OK
waiting for all k8s nodes to report: OK
waiting for all k8s nodes to report ready: OK
waiting for all control plane components to be ready: OK
waiting for kube-proxy to report ready: OK
waiting for coredns to report ready: OK
waiting for all k8s nodes to report schedulable: OK

merging kubeconfig into "/home/tim/.kube/config"
PROVISIONER       docker
NAME              kubeconfig-test
NETWORK NAME      kubeconfig-test
NETWORK CIDR      10.5.0.0/24
NETWORK GATEWAY   10.5.0.1
NETWORK MTU       1500

NODES:

NAME                        TYPE           IP         CPU    RAM      DISK
/kubeconfig-test-master-1   controlplane   10.5.0.2   2.00   2.1 GB   -
/kubeconfig-test-worker-1   worker         10.5.0.3   2.00   2.1 GB   -

# No kubeconfig as per KUBECONFIG
$  ls -lAh
total 0

# It's in the default location
$ ls -lAh ~/.kube       
total 4.0K
-rw------- 1 tim tim 2.3K Mar  8 18:36 config
```

### Environment

- Talos version: `v0.14.0`
- Kubernetes version: `v1.20.1`
- Platform: N/A

**Comment by smira** [comment]
I think it makes perfect sense to use `KUBECONFIG` variable, not using it was an oversight.

**Comment by TimJones** [comment]
I think the only issue would be when `KUBECONFIG` contains multiple entries when merging a talos cluster config out into the kube config. Would we want to select the first file in the list, last file, all of them, fail with an error condition?

**Comment by smira** [comment]
good question, I would rather fail in that case, as it's not clear which file to use.
