### ISSUE TITLE
ntp query error prevents talos from boot

### ISSUE THREAD

**Issue by ahmadidev** [siderolabs/talos#5274]
### Description
I've attached the v1.0.0-amd64 iso image to a VM on ESXi with an internal network without Internet connectivity. Despite @smira [noting](https://github.com/siderolabs/talos/issues/3005#issuecomment-766361983) that `Just to make it clear, it doesn't block the boot nor it doesn't fail on time sync failure`, it doesn't boot.

### Logs
![image](https://user-images.githubusercontent.com/5775036/161240388-cc5146c1-e088-4ee6-8636-6eec704e5f6c.png)

### Environment
ESXi hypervisor

- Talos version: v1.0.0
- Kubernetes version: N/A
- Platform:

**Comment by smira** [comment]
Talos should be up with the mode you selected. If that is ISO, it should be in the maintenance mode now, ready to accept config where you can override settings for your environment

**Comment by smira** [comment]
So to make it clear: Talos boots with machine config, so it uses default NTP configuration (`pool.ntp.org`). There's nothing wrong with that, and Talos complains that it can't do the time sync. At the same time Talos should be ready to accept machine config in the `--insecure` mode: https://www.talos.dev/v1.0/introduction/getting-started/#apply-configuration

**Comment by ahmadidev** [comment]
I reboot the VM and found its IP on the next boot, as the getting-started link pointed out. Thanks.
After generating a new config and applying it on the control plane node, it's complaining on `/dev/sda` doesn't exist. I may create another issue if I couldn't find a solution in docs.

**Comment by smira** [comment]
You can use `talosctl disks --insecure -n <IP>` to see the disks available on your VM, it might be not `sda`
