### ISSUE TITLE
talosctl disks --insecure -n <IP> returns nothing

### ISSUE THREAD

**Issue by ahmadidev** [siderolabs/talos#5277]
### Description
The VM has a disk attached to it but `talosctl disks --insecure -n <IP>` returns nothing.
(By the way, I'm not sure it's a bug report but a question, but I can't access the community Slack.)

### Environment

- Talos version: 
Client:
        Tag:         v1.0.0
        SHA:         80167fd2
        Built:
        Go version:  go1.17.8
        OS/Arch:     linux/amd64
Server:
error constructing client: failed to determine endpoints

- Kubernetes version:  N/A
- Platform: VMware ESXi

**Comment by smira** [comment]
this feels like a bug, but please try `talosctl disks --insecure -e <IP> -n <IP>`

**Comment by smira** [comment]
but hold on, have you changed `<IP>` to the actual VM IP I hope?

**Comment by ahmadidev** [comment]
Yes of course. I've got the `specified install disk does not exist: "/dev/sda"` error. So I think the connection is fine.

**Comment by ahmadidev** [comment]
> 

Ran this command with the same order, but it returns nothing.

**Comment by smira** [comment]
ah, sorry, I saw `error constructing client:`, but that is from the `talosctl version`.

if you get nothing back, my only guess is that disks are not detected by Linux kernel. 

What is the platform you're using?

**Comment by smira** [comment]
I know many users run Talos successfully on VMWare, but I don't have any specific details. @rsmitty any thoughts?

**Comment by JaeGerW2016** [comment]
change vm virtual disk type from SCSI(S) to SATA(A) on Vmware Workstation . I successfully run `talosctl -n <IP> disks --insecure
` it returns normal

**Comment by ugurmendi** [comment]
Same problem here

**Comment by JaeGerW2016** [comment]
邮件已收到，我会尽快查看并回复

**Comment by andreiperepiolkin** [comment]
Have same issue.
That is probably related to that way how esxis presents storage to OS.
In my case it was by SCSI controller.

Changing disk from scsi to ide helped me:
Open VM settings -> Hard disk -> Virtual Device Node -> IDE 0 + IDE (0:1) Hard disk 1

**Comment by JaeGerW2016** [comment]
邮件已收到，我会尽快查看并回复

**Comment by Filip7656** [comment]
I had the same problem, if you install talos from OVA file talosctl will show you disk even if it's with SCSI controller.
