### ISSUE TITLE
enable seccomp profile by default

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#5293]
## Feature Request

See e.g. https://betterprogramming.pub/secure-your-kubernetes-cluster-with-seccomp-9403ecf831b2

We can enable seccomp default profile to be applied by default to all Kubernetes workloads, this should improve overall security.

We should also ship the audit profile and provide instructions on building custom seccomp profiles.

We should provide a way to inject additional seccomp profiles to the system (via machine config?).

**Comment by JAORMX** [comment]
I'd really dig this enhancement!

@smira @frezbo also, if y'all are interested in the SPO, I'm one of the maintainers. We'd be happy to answer questions on the #security-profiles-operator channel in the kubernetes slack instance.
