### ISSUE TITLE
talosctl images support for --kubernetes-version

### ISSUE THREAD

**Issue by bnason** [siderolabs/talos#5308]
## Feature Request
Have the command `talosctl images` support the `--kubernetes-version` option that `talosctl cluster create` has.

### Description
My automated process relies on `talosctl images` to download all images needed to bootstrap the cluster and currently if I don't use the default `--kubernetes-version` the images will not match.

**Comment by smira** [comment]
`talosctl images` is meant to provide an initial list of images Talos might pull in the default configuration. This list doesn't include CNIs, any workload images. So I think in general it makes sense to customize the list to match your particular setup, e.g. the Kubernetes version. Some people run `kube-proxy`, some might skip it.

**Comment by bnason** [comment]
> `talosctl images` is meant to provide an initial list of images Talos might pull in the default configuration. 

Yea, that is all I want it for. My process takes all the manifests that I'll later deploy for CNI, workloads etc and extracts the images from their manifest files. I'm looking for the images that talos requires to stand itself up.

> This list doesn't include CNIs [...] Some people run kube-proxy, some might skip it.

It does return both flannel and kube-proxy images

```
> talosctl images
quay.io/coreos/flannel:v0.15.1
ghcr.io/siderolabs/install-cni:v1.0.0
docker.io/coredns/coredns:1.9.1
gcr.io/etcd-development/etcd:v3.5.2
k8s.gcr.io/kube-apiserver:v1.23.5
k8s.gcr.io/kube-controller-manager:v1.23.5
k8s.gcr.io/kube-scheduler:v1.23.5
k8s.gcr.io/kube-proxy:v1.23.5
ghcr.io/siderolabs/kubelet:v1.23.5
ghcr.io/siderolabs/installer:v1.0.0
k8s.gcr.io/pause:3.2

> talosctl version
Client:
	Tag:         v1.0.0
	SHA:         80167fd2
	Built:
	Go version:  go1.17.8
	OS/Arch:     linux/amd64
```

**Comment by bnason** [comment]
Alternatively, `talosctl cluster create` could potentially have a dry-run option that can save the machine configs. When inspecting the docker container, I can see it has a .Config.Env USERDATA entry that has the file.

**Comment by rgl** [comment]
If `talos images --kubernetes-version` is not provided, isn't the [air-gapped installation mode](https://www.talos.dev/v1.2/advanced/air-gapped/) misleading/broken?

How are we expected to have a complete image manifest of what is required by `talosctl cluster create` (and all its combinations that change the image list)?

Are we expected to manually parse the `talosctl cluster create` generated yaml and hunt for images? Isn't that a bit of a whack-a-mole against future talos releases?

**Comment by smira** [comment]
it's always whack-a-mole, as you might use different CNI, install Prometheus, or Rook/Ceph, your own workloads. `talosctl images` provides the initial list, especially the images which are not obvious (like `k8s.gcr.io/pause`).

**Comment by rgl** [comment]
I was referring to the images put by `talosctl cluster create` itself. I mean, the ones that are automatically pulled in by talos, which are the ones that are harder for me to keep up with.

My workload (as applied/modified with `--config-patch*`) is something that I was not expecting that talos would known about (but would be happily delighted if it detected them ;-). My workload are my own doing, so I'm expecting to known about them by some other way.

**Comment by frezbo** [comment]
> I was referring to the images put by talosctl cluster create itself. I mean, the ones that are automatically pulled in by talos, which are the ones that are harder for me to keep up with.

The talos release is tied in to a specific k8s release version, so if you use `talosctl cluster create` the image used by that version of talosctl is already in the `talosctl images` output.

**Comment by rgl** [comment]
I'm not sure what you mean by being tied. What I'm seeing is a way to generate a configuration where we can set the kubernetes version, but there is no way to output a list of images from it. So something is missing or something should be removed. As it is, this does not seems to have a consistent/similar/simetric ux.

**Comment by frezbo** [comment]
> I'm not sure what you mean by being tied. What I'm seeing is a way to generate a configuration where we can set the kubernetes version, but there is no way to output a list of images from it. So something is missing or something should be removed. As it is, this does not seems to have a consistent/similar/simetric ux.

My point was a particular release of talosctl doesn't have any info about what previous versions of k8s could use. For example even if there was an option to specify k8s version, it could be that it could be an unsupported k8s version for talos or the other images for eg: etcd/pause that's shipped with talos might be incompatible with the version of k8s you're specifying. Talos always guarantees whatever is provided with a particular release works with talosctl cluster create or the generated config. Having an option to specify k8s versions is going to just cause more issues than it solves.

**Comment by rgl** [comment]
But [there is a way to specify the k8s version](https://www.talos.dev/v1.1/reference/cli/#talosctl-gen-config): `talosctl gen config --kubernetes-version K8S_VERSION`. Is that a bogus argument that does not really do anything anymore?

**Comment by smira** [comment]
We will not add support for `--kubernetes-version` to this command. This command provides a bootstrap list of default images. There are numerous ways to configure Talos, and this tool will never support them all, so we won't start the battle we can't win.

**Comment by rgl** [comment]
Why have the images sub-command at all? Isn't it kinda half-useless? In other words, when is this useful?

**Comment by frezbo** [comment]
> Why have the images sub-command at all? Isn't it kinda half-useless? In other words, when is this useful?

This is for generating a list of images that talos uses by default for generating an offline archive.

**Comment by rgl** [comment]
Indeed, that is understood. What I'm trying to argue, is that, that command is misleading, and will get me in trouble sooner or later. Because its not doing what I was expecting for the use-case of doing an air-gapped installation. I was expecting it to behave in tandem with `talosctl gen config --kubernetes-version K8S_VERSION`. Not doing that, from my viewpoint, that command is half-baked, and should either be removed or it should support `--kubernetes-version K8S_VERSION`. But either way, its all good if this is not implemented.
