### ISSUE TITLE
join etcd based on cluster discovery

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#5343]
## Feature Request

At the moment control plane nodes only join etcd based on the Kubernetes API server endpoints, while we could have used cluster discovery feature in addition to that to build etcd cluster before the Kubernetes endpoint is up.

**Comment by andrewrynhard** [comment]
One thing to keep in mind is air gapped. So this feature would have to be opportunistic.

**Comment by smira** [comment]
yes, it is in _addition_ to the Kubernetes API endpoints, not replacing it, as cluster discovery can be disabled
