### ISSUE TITLE
Allow Kubernetes emptyDir to survive node reboot

### ISSUE THREAD

**Issue by Timoses** [siderolabs/talos#5357]
## Feature Request
Kubernetes `emptyDir` should survive node reboots just as Kubernetes documents it: "While tmpfs is very fast, be aware that **unlike disks, tmpfs is cleared on node reboot**".

### Description
I stumbled across this in the Rook usage documentation: https://www.talos.dev/v1.0/kubernetes-guides/configuration/ceph-with-rook/#talos-linux-considerations

Currently, it sounds as though if a cluster is shutdown (e.g. complete cluster reboot) with rook installed, the rook cluster will loose its complete integrity due to removal of `emptyDir` `/var/lib/rook` directory contents.

According to Kubernetes documentation, a node reboot should leave the `emptyDir` of a pod in tact (https://kubernetes.io/docs/concepts/storage/volumes/#emptydir).

One idea could be: Partition installation media to contain a partition which is left untouched by Talos when it reboots. 

I am not quite sure where Kubernetes (I suppose kubelet) sets up `emptyDir`s. The untouched partition should probably be mounted there.

In general: Wouldn't it be a good idea to stay consistent with Kubernetes' concept of emptyDir (enabling emptyDir to survive node reboots) as Kubernetes intends and documents?

**Comment by frezbo** [comment]
the kubernetes documentation clearly mentions that the emptyDir data is deleted on the pod being deleted.

```text
When a Pod is removed from a node for any reason, the data in the emptyDir is **deleted permanently**.
```

also the docs mention that emptyDir data is removed on node reboot

```text
While tmpfs is very fast, be aware that unlike disks, tmpfs is **cleared** on node reboot and any files you write count against your container's memory limit.
```

The took installation on talos does not use an emptyDir and uses a hostpath at `/var/lib/rook` which will survive a reboot always

**Comment by Timoses** [comment]
Yes, sorry, I mistook rook operator configuration which uses `emptyDir` with rook cluster config which uses `dataDirHostPath` defined in a CRD which probably tells the operator to create a `hostPath` on the node for the rook pods under given path.

I have to disagree on this, though: 
> also the docs mention that emptyDir data is removed on node reboot
```
While tmpfs is very fast, be aware that unlike disks, tmpfs is **cleared** on node reboot and any files you write count against your container's memory limit.
```

I read it as: 
* (unlike disks) tmpfs does not persist on node reboot
* so (like disks...) (without the memory option) `emptyDir` on node disks **does** persist on node reboot.


> The [r]ook installation on talos [...] uses a hostpath at /var/lib/rook which will survive a reboot always
In that case I am really glad for my use case.

Regarding `emptyDir` persistence: I leave it up to you whether you wish to keep this issue open or not.

**Comment by Timoses** [comment]
One more thing: I think the documentation is misleading.

> It is important to note that a Rook Ceph cluster saves cluster information directly onto the node (be default dataDirHostPath is set to /var/lib/rook) which under Talos Linux is ephemeral

(from https://www.talos.dev/v1.0/kubernetes-guides/configuration/ceph-with-rook/#talos-linux-considerations)

If indeed `hostPath` is persistent, then it shouldn't be ephemeral, correct?

**Comment by frezbo** [comment]
> so (like disks...) (without the memory option) emptyDir on node disks does persist on node reboot.

good point, this will need testing with a standard k8s installation to confirm the behavior, it's confusing

> If indeed hostPath is persistent, then it shouldn't be ephemeral, correct?

`/var` persists reboots on Talos, but on upgrades Talos wipes the `/var` partition, this wouldn't be a problem with rook when there are multiple OSD/nodes and rook can easily recover, if using a single node, you can tell talos to persist contents `/var` by passing in the `--preserve` flag while upgrading.

@TimJones let's make sure the docs are little more clear here about what means ephermeral in talos sense

**Comment by TimJones** [comment]
@Timoses I've made some changes to the Rook Ceph guide in #5369 and would appreciate your input if the changes improve the clarity of the `/var` ephemeral nature.
