### ISSUE TITLE
integrate with Tow-Boot

### ISSUE THREAD

**Issue by flokli** [siderolabs/talos#5374]
## Feature Request
[Tow-Boot](https://tow-boot.org/) provides a nice standard interface, so "distros" (like Talos) can easily boot on a variety of hardware, as it splits firmware-related bits from the OS, and provides hooks to just boot a UEFI payload.

Instead of having various targets for varios ARM SBCs, we could just provide one generic image per arch, and assumes a machine is set up with Tow-Boot.

**Comment by frezbo** [comment]
I've looked into tow-boot and it doesn't support all the SBC's that Talos currently supports and some of their released images doesn't seem to work
