### ISSUE TITLE
config reference doc uses Go structs

### ISSUE THREAD

**Issue by TimJones** [siderolabs/talos#5376]
The Talos [config reference](https://www.talos.dev/v1.0/reference/configuration/) uses Go struct names, but since the reference for the config file, it makes more sense to reference using the yaml tags.

Also, indent the right-hand menu to resemble the file tree to improve readability.

**Comment by smira** [comment]
I think we should stop trying to de-duplicate the nodes in the tree, and present the tree as it is.
