### ISSUE TITLE
docs: the registry setup for Talos air-gapped installation is wrong

### ISSUE THREAD

**Issue by masoudbahar** [siderolabs/talos#5410]
### Description
The [image registry example](https://www.talos.dev/v1.0/advanced/air-gapped/#preparing-the-internal-registry) used in https://www.talos.dev/v1.0/advanced/air-gapped/ has the following issues:

1. It's setup as a regular private registry, not as a mirror, or caching, registry (i.e. proxy: remoteurl: _public-registry-endpoint_ is not used in its configuration). Docker's [Registry as a pull through cache](https://docs.docker.com/registry/recipes/mirror/) guide could provide further information.
2. When setup as a caching registry, you cannot push images to it.
3. One can use a single regular private registry to host all sorts of images; however, a caching registry only proxies a single public registry, not multiple ones, as it implied.

@TimJones, FYI.

**Comment by smira** [comment]
I'm not sure what the question is here, pull through caches and airgrapped use different registry mirrors. And I believe Talos docs list them correctly.

**Comment by masoudbahar** [comment]
> I'm not sure what the question is here, pull through caches and airgrapped use different registry mirrors. And I believe Talos docs list them correctly.

**Comment by masoudbahar** [comment]
Please see Talos documentation on [air-gapped installation](https://www.talos.dev/v1.0/advanced/air-gapped/), and let me know if Talos is using a pull-through cache (as indicated in our Slack chats) or a simple regular private registry (as the document implies).

**Comment by frezbo** [comment]
the air-gapped installation is not a pull through cache

**Comment by frezbo** [comment]
the pull through is mostly used for faster local environments, air-gapped needs a private registry, sorry if that was not clear earlier

**Comment by masoudbahar** [comment]
Thanks for the clarification.
So, if I configure my private registry as a regular one, load images there and configure Talos registry mirrors to use that endpoint, then are you saying the installation will be air-gapped?

**Comment by frezbo** [comment]
Yes, I just tested this following our documentation and it works like a charm, the only thing you'd probably need to worry about is have a local NTP server available

**Comment by masoudbahar** [comment]
I’ll close the issue, given that the documentation doesn’t need to be changed. I’ll report back on my local test on the discussion topic.
Thank you for your support.
