### ISSUE TITLE
Talos doesn't complete all sequences of boot process if any extension service fails to start

### ISSUE THREAD

**Issue by frezbo** [siderolabs/talos#5441]
## Bug Report

Talos fails to complete the boot sequence if some extension service fails to start due to mounting issues or something else. The possible solution is to allow the user to specify if an extension service should block the boot sequence or not

**Comment by smira** [comment]
Issues identified:

* when Talos is waiting for all services to start, it doesn't say which services it's waiting for
* when boot sequence isn't done, we can't upgrade the node (we should be able to upgrade the node always)
* we need to have a way for extension services to do `required-by` for other services (including system services), e.g. `kubelet` might depend on `iscsid`
