### ISSUE TITLE
Add Scoop package manifest for talosctl

### ISSUE THREAD

**Issue by pcgeek86** [siderolabs/talos#5458]
## Feature Request

- My developer workstation is running Windows 11
- On Windows 11, I use the Scoop package manager to install developer / Kubernetes tools
- The `talosctl` utility is not available on Scoop

### Description

Please add `talosctl` to the Scoop package manager, according to [their directions](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifests).
I would like to be able to easily install `talosctl` using my standard package manager on Windows 11.

![image](https://user-images.githubusercontent.com/466713/165766888-08ef6888-baa2-428b-9a5c-2bafaa5f2353.png)

**Comment by andrewrynhard** [comment]
Hello @pcgeek86 . These types of things are typical handled by the members in our community. I wouldn't say it isn't a priority of ours, we just believe that there are so many ways to distribute our assets that it is best left if champions within our community handled them.

**Comment by dedene** [comment]
@pcgeek86 As I was missing a quick way to add talosctl on my Windows macgines, I took the liberty to add both [Scoop](https://github.com/ScoopInstaller/Main/pull/4633) and [Chocolatey](https://community.chocolatey.org/packages/talosctl) packages.

@andrewrynhard The autoupdate functionality of Scoop makes it easy to stay updated with the official releases. But I also think it can be integrated in the release pipeline without a lot of work. What's your opinion on this? (I asked a similar question in https://github.com/siderolabs/talos/issues/6066#issuecomment-1501838520).
