### ISSUE TITLE
API to report supported Kubernetes versions

### ISSUE THREAD

**Issue by Ulexus** [siderolabs/talos#5465]
## Feature Request

We've talked before about having a web service API for release information, such as supported Kubernetes versions of a release, but it actually makes a lot of sense to have the OS API itself respond to this.

First, the authors of a release are the ones who know what the support matrix is, canonically, so it is simple enough for them to define these in each release.  Since it is known at build time, it would be easy enough to store this inside `machined` at that time.  Then, a simple read API could be implemented which returns the range or set of supported Kubernetes releases... _locally_.

This has the added advantage of it working with simple automation anywhere, even in air-gapped environments.

### Description

```proto
service MachineService {
   rpc SupportedKubernetesVersions(google.protobuf.Empty) returns (SupportedKubernetesVersionsResponse)
}

message SupportedKubernetesVersionResponse {
   string TalosVersion = 1;
   string MinimumVersion = 2;
   string MaximumVersion = 3;
   repeated string ExcludedVersions = 4;
}
```

**Comment by smira** [comment]
I feel it might be easier to provide that as part of the release assets, as in any case we need it before Talos is deployed for the first time. In air-gapped this metadata file might be mirrored like other release assets.

**Comment by Ulexus** [comment]
I agree that it can be provided as part of the release assets, but they address two different needs.  This is specifically about the user and automation systems trying to determine what Kubernetes version they can run on _this_ cluster.

**Comment by smira** [comment]
Once the cluster is up, version is predetermined. We can put supported versions to Talos machinery package, they are fixed and easy to keep track of

**Comment by Ulexus** [comment]
The _current_ version is predetermined, yes.  The entire point of this API is to determine _supported_ versions as potential targets.
Whether the support matrix is stored in `machinery` or elsewhere, the need is the same:  determination of the supported versions of Kubernetes for the running version of Talos.  The plan hithertofore has been to build a web service to supply this information, and that is good, but the proposal _here_ has the benefit of providing the information at the _canonically_ correct source:  the server itself.
