### ISSUE TITLE
[BUG] Qemu provisioner cannot find OVMF image on Fedora 35/36

### ISSUE THREAD

**Issue by usrbinkat** [siderolabs/talos#5466]
### Description
Command `talosctl cluster create` fails with error:
```sh
the required flash image was not found in any of the expected paths for (["/usr/share/ovmf/OVMF.fd" "/usr/share/OVMF/OVMF.fd"]), please install it with the package manager or specify --extra-uefi-search-paths
```

### Workaround
```sh
sudo ln -s /usr/share/edk2/ovmf/OVMF_CODE.fd /usr/share/OVMF/OVMF.fd
```

### Environment
```sh
$ talosctl version
Client:
	Tag:         v1.0.3
	SHA:         689c6e54
	Built:       
	Go version:  go1.17.7
	OS/Arch:     linux/amd64
```

**Comment by frezbo** [comment]
https://github.com/siderolabs/talos/pull/4865 this was fixed by adding the option to specify `extra-uefi-search-paths`

**Comment by usrbinkat** [comment]
I would be inclined to wonder if the default well-known locations for major distributions should be searched by default to reduce friction for new users.

If not, then maybe this is a docs bug/enhancement opportunity? At the very least it should be easy to self-discover the solution based on notes in the [qemu guide](https://www.talos.dev/v1.0/talos-guides/install/local-platforms/qemu/#create-the-cluster).

**Comment by frezbo** [comment]
yup, definitely the docs can be updated to mention this

**Comment by smira** [comment]
No Fedora users here :) should be an easy PR to add a path to  https://github.com/siderolabs/talos/blob/a269f740ce323b21e532b24aa327b1f4b4b1e951/pkg/provision/providers/qemu/arch.go#L74
