### ISSUE TITLE
State directory is wrongly created at /root/.talos when using sudo as non-root user

### ISSUE THREAD

**Issue by usrbinkat** [siderolabs/talos#5467]
### Description
State directory is wrongly created at `/root/.talos` when executing with `sudo -E` as non-root user.

### Logs
```sh
creating state directory in "/root/.talos/clusters/talos-qemu"
```

### Environment
```sh
talosctl version
Client:
	Tag:         v1.0.3
	SHA:         689c6e54
	Built:       
	Go version:  go1.17.7
	OS/Arch:     linux/amd64
```

**Comment by frezbo** [comment]
what does this return `sudo -E bash -c "echo \$HOME"`, i wonder if it's not properly passing down env vars

**Comment by usrbinkat** [comment]
tested from both zsh and bash shells
```
sudo -E bash -c "echo \$HOME"            
/root
```

Also ran a printenv and found most of my env vars are correctly inherited but the `$HOME` env var seems to be off limits to over-writing with the -E flag.

When printing env, the only other var I found that we could leverage was `SUDO_USER`. From that I can get my home correctly with:
```sh
sudo -E bash -c "eval echo ~\${SUDO_USER}"
```

**Comment by frezbo** [comment]
I wonder if it's a os thing, on my debian derivate i see this:

```bash
❯ sudo -E bash -c "echo \$HOME"  
/home/frezbo
❯ 
```

**Comment by usrbinkat** [comment]
I checked on Fedora 35 and Fedora 36, the behavior is the same on both:
```sh
$ cat /etc/os-release 
NAME="Fedora Linux"
VERSION="36 (Thirty Six)"
ID=fedora
VERSION_ID=36
VERSION_CODENAME=""
PLATFORM_ID="platform:f36"
PRETTY_NAME="Fedora Linux 36 (Thirty Six)"
```

**Comment by ohauer** [comment]
There is a sudo direktive that is not set on every OS

see:
[Defaults env_keep](https://www.sudo.ws/docs/man/1.8.30/sudoers.man/#EXAMPLES)
```man
# Run X applications through sudo; HOME is used to find the
# .Xauthority file.  Note that other programs use HOME to find
# configuration files and this may lead to privilege escalation!
Defaults env_keep += "DISPLAY HOME"
```
and obsolate [always_set_home](https://www.sudo.ws/docs/man/1.8.30/sudoers.man/#SUDOERS_OPTIONS)

**Comment by hobyte** [comment]
I have the same problem on openSUSE Tumbleweed . 
```
$ sudo -E talosctl cluster create --provisioner=qemu --with-uefi=false                     
validating CIDR and reserving IPs
generating PKI and tokens
creating state directory in "/root/.talos/clusters/talos-default"
```
@ohauer, do you have a workaround for this problem?

Talos Version:
```
$ talosctl version
Client:
        Tag:         v1.0.5
        SHA:         9f2bfac2
        Built:       
        Go version:  go1.17.10
        OS/Arch:     linux/amd64
```

**Comment by hobyte** [comment]
`sudo --preserve-env=HOME talosctl cluster create --provisioner=qemu` worked for me to keep `$HOME`
