### ISSUE TITLE
[RFE] Add qemu cluster create flag --no-config-nodes

### ISSUE THREAD

**Issue by usrbinkat** [siderolabs/talos#5468]
### Description
Iterating on and testing MachineConfigs locally with the qemu provisioner would improve UX & administration confidence.

Can we consider adding a flag which exits the qemu provisioner once networking is configured and instances are booted but before nodes get machine configs? Usage would look something like the following.
```sh
$ talosctl cluster create --provisioner qemu --no-config-nodes
```

This would allow for manually writing and distributing the configs as an easier config development workflow.

**Comment by frezbo** [comment]
if there's a directory with pre-generated config containing `controlplane.yaml` and `worker.yaml` you could pass that as `--input-dir`, does this help with the use case?

**Comment by usrbinkat** [comment]
Yep! That's definitely a step in the right direction. It doesn't feel like quite as native of an experience for emulating the bare metal provisioning experience locally but that does at least help with debugging/iterating on configs quickly.

**Comment by smira** [comment]
There's already a flag for it --skip-injecting-config, machines will stay in maintenance mode. You can apply your config to the nodes via other means

**Comment by smira** [comment]
And also configs will be written to disk if you want something to start with

**Comment by usrbinkat** [comment]
That's all I needed to know! Thanks!
