### ISSUE TITLE
Add Support for NFS v4.2

### ISSUE THREAD

**Issue by Y0ngg4n** [siderolabs/talos#5471]
## Feature Request
Please add support for NFS v4.2 because it has many good improvements.

### Description
https://ngelinux.com/difference-between-nfs-v2-v3-v4-v4-1-and-v4-2/

**Comment by smira** [comment]
This should be mostly within the `kubelet` image

**Comment by Y0ngg4n** [comment]
@smira it is currently not implemented. v4.1 works fine but not v4.2

**Comment by smira** [comment]
Yep, that was just a note from my side, as it depends on NFS version installed to the kubelet image: https://github.com/siderolabs/kubelet/blob/master/Dockerfile#L47

**Comment by Y0ngg4n** [comment]
ah ok :)

**Comment by smira** [comment]
@frezbo should we close this now?

**Comment by frezbo** [comment]
> @frezbo should we close this now?

yes, closing

**Comment by frezbo** [comment]
This should be supported in Talos >= 1.2.0
