### ISSUE TITLE
use URL-based manifests to present static pods to the kubelet

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#5494]
See https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/#pods-created-via-http for details.

Controllers can simply start serving on localhost a tiny web server which lists the virtual list of static pods to present.

For the compatibility with previous versions of Talos, we should probably still support static pod path, but anything Talos-managed should be automatically cleaned up from that path on boot and replaced with web-based manifest.

**Comment by frezbo** [comment]
the link mentions the kubelet cmdline argument, but this should go in the kubelet config file
