### ISSUE TITLE
NoSchedule taint on node even when "Allow Scheduling on masters" selected in GUI

### ISSUE THREAD

**Issue by boardmaster357** [siderolabs/talos#5507]
## Bug Report
allowSchedulingOnMasters is not set in the machine config file, and master node is tainted when using the interactive GUI to avoid taint.
### Environment
- Talos version: [`talosctl version --nodes <problematic nodes>`]
Client:
        Tag:         v1.0.0
        SHA:         80167fd2
        Built:       
        Go version:  go1.17.8
        OS/Arch:     linux/amd64
Server:
        NODE:        192.168.1.5
        Tag:         v1.0.4
        SHA:         f6696063
        Built:       
        Go version:  go1.17.7
        OS/Arch:     linux/amd64
        Enabled:     RBAC
- Kubernetes version: [`kubectl version --short`]
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.23.5
- Platform:
Linux Mint

**Comment by smira** [comment]
@Unix4ever can you please take a look? 

I think this is about interactive installer.
