### ISSUE TITLE
talosctl linking wrong image for installation using gen config

### ISSUE THREAD

**Issue by acul009** [siderolabs/talos#5508]
Current Version: 1.0.4-2

![talos bug](https://user-images.githubusercontent.com/54124197/167228675-496af9fe-1909-4053-a669-3e81d6933007.png)

right link would be ghcr.io/siderolabs/installer:v1.0.4

**Comment by acul009** [comment]
I got it from the AUR.
I'll take it up with the maintainer, sorry for bothering you.

I wish you the best of luck, I've been having a great time using Talos.

**Comment by smira** [comment]
AUR maintainers might need to update `USERNAME` variable passed to the build
