### ISSUE TITLE
Document disk layout

### ISSUE THREAD

**Issue by haslersn** [siderolabs/talos#5520]
The documentation mentions partition labels such as `EPHEMERAL` and `STATE`. By reading through the documentation, I could infer some of the purposes of the different partitions. However, it would be nice to have a dedicated section or page that explains:

- the layout of the Talos disk (or disks, if Talos can be installed on multiple disks)
- the purpose of the individual partitions
- the concrete contents of the individual partitions. Contents might be, among others, kernel, bootloader, binaries that aren't containerized (such as machined and containerd, I guess), configuration, container images, etcd data and kubelet's (ephemeral?) data.

Or is there already such a page that I missed?

**Comment by frezbo** [comment]
https://www.talos.dev/v1.0/learn-more/architecture/#file-system-partitions this should help you get started
