### ISSUE TITLE
talosctl gen config does not set cluster.apiServer.certSANs if port is omitted

### ISSUE THREAD

**Issue by haslersn** [siderolabs/talos#5536]
When running

```bash
talosctl gen config talos https://example.com
```

with talosctl v1.0.4, then the generated `controlplane.yaml` doesn't have `cluster.apiServer.certSANs`. When adding a port (e.g. `talosctl gen config talos https://example.com:6443`) then it works.

**Comment by smira** [comment]
In fact, this shouldn't be needed, as Talos should inject the control plane endpoint hostname automatically as `certSAN` (there's no need to have it explicitly in the config).
