### ISSUE TITLE
cluster health check: Ceph/Rook health

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#5557]
Look for Cluster Rook CRDs (we can use Kubernetes dynamic client), check the `.status` field for readiness, display the failure reason if any.

**Comment by smira** [comment]
See also https://github.com/siderolabs/capi-utils/blob/master/pkg/capi/check.go#L32

**Comment by flokli** [comment]
Yeah, but where do you draw the line? #5556 and #5555 are for things that are managed by Talos itself (`lifecycle.talos.dev/healthCheck`), but this is an entirely separate piece of software. Do you want to include custom healthchecks for all sorts of other software? Let's say, interpreting if the Ingress controller of choice, cert-manager and external-dns are properly configured, too?

I personally think the healthcheck should only cover things managed by Talos itself, and "determining the state of the rest of the applications deployed in the cluster" is a task that should be left to things like Monitoring/Alerting.

See also [this set](https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/alerts) of alerting rules. There's some alerts for `rook-ceph` too: https://monitoring.mixins.dev/ceph/

In the field of "ad hoc healthchecks", there's also https://github.com/emirozer/kubectl-doctor worth mentioning.

**Comment by smira** [comment]
Rook/Ceph is the recommended storage solution for Talos, and it's a thing which is hard to manage during cluster upgrades, so this makes sense. Other storage solutions might use lifecycle labels or other custom health checks.
