### ISSUE TITLE
Make extra-uefi-search-paths configurable through environment variable

### ISSUE THREAD

**Issue by haslersn** [siderolabs/talos#5566]
## Feature Request

As mentioned in https://github.com/NixOS/nixpkgs/pull/167836#issuecomment-1092607816, it would be nice for `talosctl` to have `--extra-uefi-search-paths` configurable via an environment variable, too. This way, OS package maintainers can create a wrapper that sets this environment variable as required for the specific OS.

@flokli Do you disagree?
@zowoq

**Comment by flokli** [comment]
There doesn't seem to be a generic pattern in talosctl to configure cli arguments with env vars.

@haslersn probably best you provide a PR to start the discussion.
