### ISSUE TITLE
kernel module unloading

### ISSUE THREAD

**Issue by frezbo** [siderolabs/talos#5569]
## Feature Request

Currently removing the module section has no effect on the loaded kernel modules. Standard OS support unloading kernel modules. Currently the only way in talos is to comment/remove the kernel modules section and reboot

**Comment by frezbo** [comment]
yeh, not a blocker, but i ended by constantly applying/de-applying patches and rebooting to test with nvidia

**Comment by steverfrancis** [comment]
Philosophically, it seems an immutable OS should *not* support unloading modules without a reboot, no?
