### ISSUE TITLE
disk wipe takes forever

### ISSUE THREAD

**Issue by Daxcor69** [siderolabs/talos#5612]
During the apply-config phase  we get to the point of "wiping /dev/sda"  Here are the specifics of the drives on the system

```
brad@gateway1:~/infrastructure/talos$ talosctl --nodes 173.201.26.221  --endpoints 173.201.26.221 disks --insecure
DEV        MODEL              SERIAL   TYPE   UUID   WWID   MODALIAS      NAME   SIZE     BUS_PATH
/dev/sda   Micron_5300_MTFD   -        SSD    -      -      scsi:t-0x00   -      1.9 TB   /pci0000:00/0000:00:17.0/ata1/host0/target0:0:0/0:0:0:0/
/dev/sdb   Micron_5300_MTFD   -        SSD    -      -      scsi:t-0x00   -      1.9 TB   /pci0000:00/0000:00:17.0/ata3/host2/target2:0:0/2:0:0:0/```

I was working with Frezbo in slack on this issue.  

I am using    iso, 1.0.5 amd64.
installer 1.0.5

After a few hours the wipe was finished and the configuration completed.  Is the wipe supposed to take this long?

**Comment by smira** [comment]
probably it's not documented clearly, but Talos always "wipes" the install disk in the sense it creates new partition table on it (but it will never wipe existing Talos install). 

the option to wipe in the `.machine.install` section performs complete zeroing out of the device, which depending on hardware capabilities might take a lot of time for huge disks.

**Comment by Daxcor69** [comment]
Thank you for the clarification on this.
