### ISSUE TITLE
Adding metadata to inital configs

### ISSUE THREAD

**Issue by Daxcor69** [siderolabs/talos#5614]
I would like to be able to control the name of the node.  Currently it creates a name  talos-<ip of node>.  I would like to be able to set the node name myself.

Also, I would like the ability to add labels to the node definition during the boot strapping for both the controllers and workers.

Thanks
Brad

**Comment by Daxcor69** [comment]
I should have put my reason,  In the event of having to rebuild the environment I would like as much information in the declaration as possible.  Trying to get as close to "infrastructure as code" as possible.

**Comment by smira** [comment]
Talos static hostname: https://www.talos.dev/v1.0/reference/configuration/#networkconfig (`hostname:`)

Adding node labels can be done via kubelet `extraArgs`: https://www.talos.dev/v1.0/reference/configuration/#kubeletconfig

See https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/, `--node-labels`
