### ISSUE TITLE
Empty talosconfig confuses `talosctl`

### ISSUE THREAD

**Issue by TimJones** [siderolabs/talos#5625]
### Description

"Cleaning up" talosconfig file by emptying it (something like `echo > ~/.talos/config`) will cause subsequent commands to throw unhelpful errors as the talosconfig file exists but without the expected yaml structure.

We should be able to catch this and at least throw a better error.

### Logs

```shell
$ sudo -E _out/talosctl-linux-amd64 cluster create  --name dev --provisioner=qemu --registry-mirror docker.io=http://10.5.0.1:5000 --registry-mirror k8s.gcr.io=http://10.5.0.1:5001 --registry-mirror quay.io=http://10.5.0.1:5002 --registry-mirror gcr.io=http://10.5.0.1:5003 --registry-mirror ghcr.io=http://10.5.0.1:5004 --registry-mirror 10.5.0.1:5005=http://10.5.0.1:5005 --install-image=127.0.0.1:5005/siderolabs/installer:v1.1.0-alpha.2-24-g1156daac2 --with-bootloader=false --extra-uefi-search-paths=/usr/share/ovmf/x64
validating CIDR and reserving IPs
generating PKI and tokens
created controlplane.yaml
created worker.yaml
creating state directory in "/home/tim/.talos/clusters/dev"
creating network dev
creating load balancer
creating dhcpd
creating master nodes
creating worker nodes
EOF
```

**Comment by smira** [comment]
I think this error about specifically not empty, but only a single new line probably?

nevertheless the error is unhelpful and should be fixed

**Comment by TimJones** [comment]
Exactly, even a standard "error unmarshalling yaml in talosconfig" would
have made the issue way more apparent and pointed to the culprit.
