### ISSUE TITLE
talosctl upgrade k8s to 1.23.7 alters cilium configuration

### ISSUE THREAD

**Issue by szinn** [siderolabs/talos#5640]
## Bug Report

I did a dry run to upgrade my staging cluster from 1.23.6 to 1.23.7 and it appears to be changing the cilium version to 1.11.4 (was 1.11.5) plus making other changes to the configuration (removing the cluster-id and changing the cluster-name to "default" when it was "staging")

It looks like it might be reverting the cilium configuration to what was used to bootstrap the cluster. (After bootstrapping, I update the cilium with a helm chart install). Is there a way (besides manually doing the patches) to do them without touching the manifest stage?

Attached is the output of the dry-run.

### Environment

- Talos version: [1.0.5]
- Kubernetes version: [1.23.6]
- Platform: talosctl running on OSX

[output.txt](https://github.com/siderolabs/talos/files/8775651/output.txt)

**Comment by frezbo** [comment]
this is the expected behavior, machine config is the declared state, the better solution would be to use a url for the cilium manifests and update the manifests at the url with changes, then do upgrades via `talosctl upgrade-k8s`

**Comment by szinn** [comment]
Thanks for the info. My original controlplane.yaml has

cluster:
    network:
        cni:
            name: custom
            urls:
                - http://router/staging-cilium-quick-install.yaml

to define the cilium CNI.

If I understand what you are saying, the upgrade-k8s should refetch the contents of this URL and will then figure out the diff to get the current configuration back to that. Am I correct there?

I updated a couple of lines in the contents with my current configuration, but the upgrade-k8s still uses the original values for those lines. Does upgrade-k8s actually refetch the URLs or is it using a copy of the data somewhere on the node?

**Comment by szinn** [comment]
Also looks like the upgrade is expecting a siderolabs 1.23.7 kubelet which doesn't appear to be available yet.

**Comment by frezbo** [comment]
> If I understand what you are saying, the upgrade-k8s should refetch the contents of this URL and will then figure out the diff to get the current configuration back to that. Am I correct there?

@smira do we cache the content somewhere?

**Comment by frezbo** [comment]
> Also looks like the upgrade is expecting a siderolabs 1.23.7 kubelet which doesn't appear to be available yet.

yes, we'll do that soon, i think the 1.23 series were delayed a bit

**Comment by szinn** [comment]
Let me know if it is indeed caching the original manifests from the initial node configuration - it kind of looks like it did.

I continued with the upgrade and the manifests for cilium got moved back to 1.11.4. Once the upgrade was complete, I applied the helmrelease for cilium and it upgraded everything back to 1.11.5

**Comment by smira** [comment]
Talos might re-fetch bootstrap manifests at any time, so the URLs used should be pinned to a specific version.
