### ISSUE TITLE
Azure shutdown process

### ISSUE THREAD

**Issue by sergelogvinov** [siderolabs/talos#5641]
### Description

Talos does not shutdown properly. 

hv_utils module receive shutdown  event from hyper-v. 
It call the function [orderly_poweroff](https://github.com/torvalds/linux/blob/master/drivers/hv/hv_util.c#L165-L168) 
which runs [/sbin/poweroff](https://github.com/torvalds/linux/blob/master/kernel/reboot.c#L420) in user space.

Talos does not have this command. Thats why shutdown process failed. ```reboot: Failed to start orderly shutdown: forcing the issue```

### Logs

```
172.16.136.6: kern:    info: [2022-05-25T13:07:50.681476988Z]: hv_utils: Shutdown request received - graceful shutdown initiated
172.16.136.6: kern: warning: [2022-05-25T13:07:50.689541988Z]: reboot: Failed to start orderly shutdown: forcing the issue
172.16.136.6: kern:    info: [2022-05-25T13:07:50.698726988Z]: ACPI: PM: Preparing to enter system sleep state S5
172.16.136.6: kern:   emerg: [2022-05-25T13:07:50.709230988Z]: reboot: Power down
```

### Environment

- Talos version: master branch
- Platform: azure

**Comment by smira** [comment]
I'm not sure what is exactly the issue here? It doesn't poweroff correctly? 

Talos does syscall which `/sbin/poweroff` should do, if Azure needs something else we need more details

**Comment by sergelogvinov** [comment]
Sorry. 

Hyper-V is trying to gracefully shutdown the node. 
1. it send event to the kernel driver (it does not use ACPI-shutdown event)
2. the drivers calls function ```orderly_poweroff``` (kernel function)
3. orderly_poweroff is trying to launch ```/sbin/poweroff``` which does not exist on the Talos root disk.
4. If function ```orderly_poweroff``` got an error, it forces the switch-off the node.

So the node cannot switch off gracefully... Only through talos api.
You can see on logs - the node switches off less that one second.

**Comment by smira** [comment]
1. Creating a client which connects to the API on the same node without auth: https://github.com/siderolabs/talos/blob/dc9a0cfe94b59c688d65ef74ebc04f273b8a72fb/pkg/cluster/local.go#L35-L36
2. We can hardlink `/sbin/poweroff` to `/sbin/init` (`machined`)  and in `main.go` figure out how we got called.
3. What is the way to trigger `orderly_poweroff` from QEMU? 
4. Shutdown API should have an option to do poweroff vs. halt.
