### ISSUE TITLE
Machine configuration intermittently recognizes custom CA certificate

### ISSUE THREAD

**Issue by rsadowsk** [siderolabs/talos#5652]
### Description
When I create a new cluster, the cluster config has a custom cni with a url to a private gitlab repo which uses a custom CA. In the machine config I append my custom CA to /etc/ssl/certs/ca-certificates. But, when my new CP node boots up for the first time I continuously get x509 errors when it's trying to pull the cni manifest. After I reboot the server after the initial config loads then it's able to grab the manifests.
### Logs
TBD, logs are in an air-gapped environment which I'll work on pulling over. 
### Environment

- Talos version: v1.0.5
- Kubernetes version: 1.23.6
- Platform: Sidero Metal

**Comment by smira** [comment]
That is a bug, and most probably the root cause is that controller doesn't ever re-create HTTP client, so HTTP client doesn't pick up new CA certificates. We need to think about a proper way to fix it. I believe it's using `go-getter` library, so it might even be buried somewhere there.

**Comment by smira** [comment]
I did some investigation, and looks like issue is even more complicated - the problem is that Go caches system CA roots, so we need to override that to load CAs each time we create a client.

**Comment by rsadowsk** [comment]
If I'm looking at this right, getter.Client is recreated everytime extra_manifests.processURL is called. Would it be appropriate to have a special case when Machine.files gets written, if it's overwriting or being appended to /etc/ssl/certs/ca-certificates (per https://www.talos.dev/v1.0/talos-guides/configuration/certificate-authorities/) then that content should be parsed into *x509.Certificate(s) and appended to the certpool via x509.SystemCertPool().AddCert()? 

Two things I haven't been able to find are where Machine.files get written and where machined is run from. If I recall right, there might be some special grpc arguments that need to be invoked to make sure the server uses a loaded SystemCertPool that can be manipulated throughout runtime.

**Comment by smira** [comment]
`x509.SystemCertPool()` returns a copy, so this is not that simple, and system roots are cached internally.
