### ISSUE TITLE
talosctl --all --yes instead of talosctl -n X,Y,Z

### ISSUE THREAD

**Issue by Timoses** [siderolabs/talos#5653]
## Feature Request

Improve usability of talosctl command.

### Description

Currently, it is quite a lot of work to fire commands on all nodes which appears to always require listing all nodes as a comma-separated string, e.g.:
```
talosctl -n 192.168.2.36,192.168.2.37,192.168.2.38
```

Suggestion: Introduce a `--all | -a` flag which will put all node endpoints into the targetted nodes for that command.

I understand the security implications.
As an addition to this, using the `--all` flag could trigger `talosctl` to ask for confirmation by the user with a promt (`y/n`).
This would be very well accompanied by a `--yes | -y` flag to automatically answer 'y' to the prompt.

For me, I am using Talos in a hobby project and have:
`alias t=talosctl`
and would love to have something like
`alias ta="talosctl --all --yes"`.

**Comment by smira** [comment]
Please see also #5637 which is a similar idea

**Comment by anthr76** [comment]
FWIW I lost my cluster due to forgetting to pass the node flag to apply-config and having a worker config be applied to all my nodes. We should definitely not assume all nodes at least for apply-config

**Comment by Timoses** [comment]
I believe that only happens if you configure talosconfig to use all nodes as default (and doing that is warned about in the documentation if I remember correctly).
That is why I do not desire using all nodes as default. 

A `--all` or `-a` however would be explicit. 

Jun 4, 2022, 17:07 by ***@***.***:
