### ISSUE TITLE
Talos can't boot on Raspberry Pi 8GB

### ISSUE THREAD

**Issue by rszamszur** [siderolabs/talos#5686]
### Description

I've carefully followed the [documentation](https://www.talos.dev/v1.0/talos-guides/install/single-board-computers/rpi_4/) but was unable to boot Talos on Raspberry. It seems U-boot fails to boot initramfs for some unknown reason. However, it logs only "gibberish" to the console (each time a bit different). I'm not sure how to understand this error, I haven't seen something similar yet.

Things I've tried so far:
* Talos releases:
    * v1.0.4
    * v1.0.5
    * v1.1.0-beta.0
* Booting from SD card (tried two cards), and USB
* Updated bootloader to version `v2020.09.03-138a1`(version from documentation) then to `v2022.04.26-138a1`(latest)
* Updated Raspberry Pi firmware
* Successfully boot a different OS to exclude issues with the board itself.
* Successfully boot Talos on Rock64 board to exclude issues with flashing SD.

All tries and combinations render the same problem.

### Logs

![out1](https://user-images.githubusercontent.com/10353018/171908855-e2a085d4-3958-4b18-8a8f-5b6c890f970f.jpeg)

![out2](https://user-images.githubusercontent.com/10353018/171908719-f969ac4a-ba3e-4ace-9227-10e3314bf60f.jpeg)

### Environment

- Talos version: v1.0.5
- Platform: Raspberry Pi 4B - 8GB (bootloader version: [v2022.04.26-138a1](https://github.com/raspberrypi/rpi-eeprom/releases/tag/v2022.04.26-138a1))

**Comment by frezbo** [comment]
it's seems something is sending characters to u-boot while booting? Also which image have you flashed? I've talos running successfully on Rpi 4b 8gig

**Comment by rszamszur** [comment]
[metal-rpi_4-arm64.img.xz](https://github.com/siderolabs/talos/releases/download/v1.0.5/metal-rpi_4-arm64.img.xz)

> it's seems something is sending characters to u-boot while booting?

It was my first guess, but besides a USB/SD nothing is plugged in. Unless the cooling fan connected via GPIO could cause this. I'll try without.

**Comment by rszamszur** [comment]
The GPIO-connected cooling fan was the root cause (I didn't see that coming :laughing:).

<img src="https://user-images.githubusercontent.com/10353018/171923295-8487d75f-5d51-4c80-9c89-2f2e43926973.jpeg" alt="fan" width="300"/>

I did some digging and it uses [GPIO pins 14 and 15](https://pinout.xyz/pinout/fan_shim) for controlling LEDs. Unfortunately, those are UART pins.

@frezbo Great guess, and lightning speed support! Thanks for the help!

Have a good one!

**Comment by frezbo** [comment]
glad it resolved, if you need the fan control, the official PoE hats works great (compatible hats also should work fine, I haven't tested any), and the kernel driver will control the fan.
