### ISSUE TITLE
Unable to set "secure-port" on API server

### ISSUE THREAD

**Issue by techmunk** [siderolabs/talos#5706]
## Bug Report

Adding this patch to the controlplane:
```json
{
  "op": "add",
  "path": "/cluster/apiServer/extraArgs",
  "value": {
    "secure-port": 443
  }
}
```

and this patch to all nodes:
```yaml
{
  "op": "add",
  "path": "/cluster/controlPlane/localAPIServerPort",
  "value": 443
},
```

The endpoint also has no port spec on it and is just `https://<vip-domain>`.

I would've expected everything to "just work". However, it looks like the kubeconfig secret generated for the controller manager has a hard coded port of 6443 in the below places:

- https://github.com/siderolabs/talos/blob/63519286110e75adc03edb89b4dc9cb432b15d46/internal/app/machined/pkg/controllers/secrets/kubernetes.go#L249
- https://github.com/siderolabs/talos/blob/63519286110e75adc03edb89b4dc9cb432b15d46/internal/app/machined/pkg/controllers/secrets/kubernetes.go#L269
- https://github.com/siderolabs/talos/blob/63519286110e75adc03edb89b4dc9cb432b15d46/internal/app/machined/pkg/controllers/secrets/kubernetes.go#L291

It seems to me that port should be the `localAPIServerPort` value, rather than a hard coded value.

### Description

Most things seem fine, however inline manifest never get created as it tries to talk on the hardcoded 6443, instead of the port set in the API server config.

Removing the above patches makes everything "work" again.

I think either the documentation should be updated to say this configuration option is not supported (maybe it is somewhere and I missed it?), or the port in the kubectl secret for the controller manager should not be hardcoded.

### Environment

- Talos version: v1.1.0-beta.0
- Kubernetes version: v1.24.1
- Platform:

**Comment by smira** [comment]
That's clearly a bug, and we'll get it fixed
