### ISSUE TITLE
Api server returns unauthorized responses (seemingly due to errors with writing kubelet PKI)

### ISSUE THREAD

**Issue by BeeHiveJava** [siderolabs/talos#5736]
### Description
Api Server keeps returning unauthorized responses, which in turn leads to all kinds of issues:
```
[   49.709097] [talos] controller failed {"component": "controller-runtime", "controller": "k8s.KubeletStaticPodController", "error": "error refreshing pod status: error fetching pod status: an error on the server (\"Authorization error (user=apiserver-kubelet-client, verb=get, resource=nodes, subresource=proxy)\") has prevented the request from succeeding"}
[   49.713294] [talos] restarting controller in 442.604113ms {"component": "controller-runtime", "controller": "k8s.KubeletStaticPodController"}
```

I'm not too familiar with how the internals of talos (or even kubernetes) work, but I think the fact that talos cannot list the nodes is problematic. Very early in the process I can see the following error popping up:
```
[    6.700744] [talos] controller failed {"component": "controller-runtime", "controller": "k8s.KubeletServiceController", "error": "error writing kubelet PKI: open /etc/kubernetes/bootstrap-kubeconfig: read-only file system"}
```

I can imagine that if writing certificates / keys fails, everything that follows might fail as well. For context, I'm using the nocloud amd64 image (v1.0.6) with a full machineconfig (including every certificate & key) provided using cloud-init. It seems that the cloud-init part is working fully (all other options get set correctly, such as the hostname and vip).

### Logs
Full logs: https://pastebin.com/LJv5nWAE

### Environment

- Talos version: [v1.0.6]
- Kubernetes version: [v1.23.6]
- Platform: nocloud amd64 v1.0.6

**Comment by frezbo** [comment]
Talos is similar in operation to k8s, it'll keep re-trying until successful. It seems either the api server is not up or something to do with kubelet. Could you provide information on these:

`talosctl get services`

`talosctl containers -k`

`talosctl logs kubelet`

`talosctl logs -k <api server name from containers -k output from previous command> `

**Comment by BeeHiveJava** [comment]
Kubelet seems to be filled with logs of not being able to find nodes, which makes sense since api calls fail.

`talosctl get services`
```
NODE            NAMESPACE   TYPE      ID           VERSION   RUNNING   HEALTHY   HEALTH UNKNOWN
10.10.100.100   runtime     Service   apid         2         true      true      false
10.10.100.100   runtime     Service   containerd   2         true      true      false
10.10.100.100   runtime     Service   cri          2         true      true      false
10.10.100.100   runtime     Service   etcd         2         true      true      false
10.10.100.100   runtime     Service   kubelet      3         true      true      false
10.10.100.100   runtime     Service   machined     1         true      false     true
10.10.100.100   runtime     Service   trustd       2         true      true      false
10.10.100.100   runtime     Service   udevd        2         true      true      false
```

`talosctl containers -k`
```
NODE            NAMESPACE   ID                                                     IMAGE                               PID    STATUS
10.10.100.100   k8s.io      kube-system/kube-apiserver-talos-1                     k8s.gcr.io/pause:3.6                1913   SANDBOX_READY
10.10.100.100   k8s.io      └─ kube-system/kube-apiserver-talos-1:kube-apiserver   k8s.gcr.io/kube-apiserver:v1.23.6   2011   CONTAINER_RUNNING
10.10.100.100   k8s.io      kube-system/kube-scheduler-talos-1                     k8s.gcr.io/pause:3.6                1899   SANDBOX_READY
10.10.100.100   k8s.io      └─ kube-system/kube-scheduler-talos-1:kube-scheduler   k8s.gcr.io/kube-scheduler:v1.23.6   2120   CONTAINER_RUNNING
10.10.100.100   k8s.io      └─ kube-system/kube-scheduler-talos-1:kube-scheduler   k8s.gcr.io/kube-scheduler:v1.23.6   0      CONTAINER_EXITED
```

`talosctl logs kubelet`
[kubelet-logs.txt](https://github.com/siderolabs/talos/files/8886364/kubelet-logs.txt)

`talosctl logs -k kube-system/kube-apiserver-talos-1:kube-apiserver`
[logs-apiserver.txt](https://github.com/siderolabs/talos/files/8886373/logs-apiserver.txt)

**Comment by BeeHiveJava** [comment]
Had a revelation with the following process (suggested by someone):

1. Provision node as normal.
2. Wait 3 minutes.
3. Bootstrap node as normal.
4. Wait 10 minutes.
5. Reboot node.

Following this process I was able to get everything working. For me this is enough to continue, but if you still consider this a bug I'm happy to conduct more tests and provide more feedback.
