### ISSUE TITLE
Detect qemu-kvm binary

### ISSUE THREAD

**Issue by Davincible** [siderolabs/talos#5761]
With qemu install it looks for the `qemu-system-x86` binary. After not being able to install it, I found that according to [this](https://unix.stackexchange.com/questions/585610/qemu-and-centos-8-where-is-usr-bin-qemu-system-x86-64-and-the-qemu-system-x86) it changed to `/usr/libexec/qemu-kvm`. Would be good if the qemu install could also detect that

**Comment by smira** [comment]
Symlink in `$PATH` with a proper name should be sufficient here I guess.

**Comment by Davincible** [comment]
Yes that is what I've done locally. Would be nice to have talosctl auto detect it

**Comment by smira** [comment]
PR is very much welcome, we don't have anyone using CentOS in the development team :(
