### ISSUE TITLE
Sysbox Support

### ISSUE THREAD

**Issue by dezren39** [siderolabs/talos#5803]
## Feature Request
Hi! I'm currently testing talos in my xenserver lab. I wondered your thoughts on:

https://github.com/nestybox/sysbox

And whether there could be an option to enable it?

I'm guessing it's not something I could typically do as a regular talos end-user, but I'd love to learn more.

Thank you.

**Comment by smira** [comment]
This might be added as a system extension, like gvisor container runtime: https://github.com/siderolabs/extensions
