### ISSUE TITLE
Talos v1.1.0 crashes during boot on Proxmox

### ISSUE THREAD

**Issue by sauterp** [siderolabs/talos#5823]
### Description

I have an old installation of Talos v0.14 on Proxmox that works. Today I tried to create a new VM with Talos v1.1.0 and it cannot boot. It crashes and reboots forever.

To ensure this is an issue with the new VM configuration, I swapped the ISO on the crashing VM with the v0.14 ISO and it worked.

The problem persists after I shut down all other VMs on the proxmox node.

Hint for those who would like to connect to a serial console on Proxmox: Add a Serial Port 0 in the `Hardware` section of the VM. Log in as root on the host and run `qm terminal <VMID>`.

### Logs
[talos-proxmox-crash.log](https://github.com/siderolabs/talos/files/8995596/talos-proxmox-crash.log)

### Environment

- Talos version: v1.1.0
- Platform: Proxmox

**Comment by lidstah** [comment]
Hi, that might be due to the kvm64 default CPU (which does not have the x86_64v2 instructions). Does using a "host" CPU configuration on your VM solves the problem?

**Comment by sauterp** [comment]
> Hi, that might be due to the kvm64 default CPU (which does not have the x86_64v2 instructions). Does using a "host" CPU configuration on your VM solves the problem?

Yes, this works, I had to change the Processor Type from the default `kvm64` to `host`. Thanks!

**Comment by wibed** [comment]
for me it does not work.

the boot loop is resolved, but gets stuck at boot up.
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/69305089/176323465-ac9bc123-406b-428b-af87-c85293a42970.png">

**Comment by frezbo** [comment]
@wibed 

> for me it does not work.

as the kernel console says you'd need to apply the machine config to the node
