### ISSUE TITLE
DHCP renew fails with ICMP port unreachable (3/3)

### ISSUE THREAD

**Issue by lrosenman** [siderolabs/talos#5838]
### Description
talos VM's (all 5 of mine) whine about renew packets not making it.  I captured pcaps of all the DHCP (67/68) and ICMP traffic for a
period of time to demonstrate,
in the tarball are:
1) console log (talosctl logs -f controller-runtime | grep dhcp >file
2) macaddrs.txt showing mac's and IP's of the machines in this test
3) talos.vm.pcap (the pcap from the vm's switch port)
4) talos.switch.pcap (the pcap from the bridge that has also has the other 4 talos nodes)

in the talos.vm.pcap file look at packets 30-34 for what I believe is the renew->ack->ICMP.

### logs
[talos-dhcp.tar.gz](https://github.com/siderolabs/talos/files/9014853/talos-dhcp.tar.gz)

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`] v1.1.0
- Kubernetes version: [`kubectl version --short`] 1.24.2
- Platform: FreeBSD/bhyve VM's/using sysutils/vm-bhyve to control the VM's.

**Comment by lrosenman** [comment]
still occurring with 1.1.1 and 1.1.2

**Comment by smira** [comment]
Talos 1.4+ has a completely rewritten DHCP stack, so please specify which version you're seeing it with.

**Comment by RussianFox** [comment]
v1.4.1

**Comment by smira** [comment]
It makes sense to supply the full packet dump from the network, otherwise it's hard to say anything. And it's better to open a new issue, as it's not clear whether this is the same one.
