### ISSUE TITLE
Default hostname should not use an IP that wasn't assigned as a kubelet node IP

### ISSUE THREAD

**Issue by evandeaubl** [siderolabs/talos#5886]
### Description

I added a node to an existing cluster that had both public IP addresses and a wireguard IP address. I intended the cluster communication to go over wireguard, so I specified only the wireguard network under .machine.kubelet.nodeIP.validSubnets. Unforunately, when it assigned the <cluster name>-<IP addr> default name to the node, it used one of the public IP addresses, even though the kubelet node IP was properly assigned to the internal wireguard IP.

Workaround is easy enough: specify the hostname under .machine.network.hostname, but it would be better if it defaulted correctly.

Maybe this is related to #5834?

### Logs

<Didn't capture logs at the time, but can maybe set up a test area and try to reproduce it again to get logs>

### Environment

- Talos version: 1.1
- Kubernetes version: 1.24.2
- Platform: metal

**Comment by smira** [comment]
Talos default hostname is based on the IP address, but it's not recommended to use, as it's not stable. Hostname is chosen without any connection to the kubelet node IP, so they might use different IPs.

**Comment by evandeaubl** [comment]
Just read over the release notes for the first 1.2 alpha, and the new method for picking a default hostname makes this issue moot, so I'll close this out. Thanks for making the default for node names stable!
