### ISSUE TITLE
democratic-csi?

### ISSUE THREAD

**Issue by depeo** [siderolabs/talos#5939]
Hello, I'd like to use Talos but I need democratic-csi ( https://github.com/democratic-csi/democratic-csi )
I need it for NFS and ISCSI to TrueNAS.

Any idea how democratic-csi can be modified to work with Talos? I saw another issue where someone modified some other csi, but  I couldn't figure out how to apply that to democratic-csi.

**Comment by frezbo** [comment]
you could try installing the `iscsi` system extension as mentioned here: https://www.talos.dev/v1.1/kubernetes-guides/configuration/replicated-local-storage-with-openebs-jiva/#preparing-the-nodes (only the extensions part) and see if it works. I couldn't find any easy way to customize the democratic csi just (did a quick glance at the project)

**Comment by depeo** [comment]
Someone fixed this, and its working fine now!
