### ISSUE TITLE
Implement encoding/decoding for common proto types

### ISSUE THREAD

**Issue by DmitriyMV** [siderolabs/talos#5940]
We should implement `BinaryMarshaler` and `BinaryUnmarshaler` for types like:
- [ ] `github.com/talos-systems/crypto/x509.PEMEncodedCertificateAndKey`
- [ ] `github.com/talos-systems/crypto/x509.PEMEncodedKey`
- [ ] `netaddr.IP`
- [ ] `netaddr.IPPort`
- [ ] `netaddr.IPPrefix`
- [ ] `time.Time`

Also there is unstructured type (basically `map[string]interface{}`) which should be serialized to JSON and this string form is encoded in BinaryMarshaler (same goes for decoder).

Linked issue: https://github.com/siderolabs/talos/issues/5893

**Comment by smira** [comment]
Should we simply do proper `.proto` files and let them be compiled? we could then implement methods to convert back and forth to go generated proto structs? but we can do also custom marshaler
