### ISSUE TITLE
Talos installation on Hetzner bare metal servers not possible

### ISSUE THREAD

**Issue by Janik440** [siderolabs/talos#5989]
### Description
When starting the Talos ISO image or other Talos images on Hetzner **dedicated servers** the server get's stuck in a reboot loop.

This is probably caused by Talos detecting the server is hosted by Hetzner and therefore trying to access the Hetzner Cloud API which is not available on Hetzner **dedicated servers**.

Setting the `talos.platform=metal` in the grub bootloader doesn't resolve the issue and is already set by default.

### Logs
<img width="798" alt="Screenshot" src="https://user-images.githubusercontent.com/110305049/181943681-427f3620-ddbe-45e7-a0ea-031d0657896d.png">

### Environment

- Talos version: 1.1.2
- Kubernetes version: N/A
- Platform: metal amd64
- [https://github.com/siderolabs/talos/releases/download/v1.1.2/talos-amd64.iso](https://github.com/siderolabs/talos/releases/download/v1.1.2/talos-amd64.iso)

**Comment by 0xbrigles** [comment]
Hi :)

we run this on Hetzner's AX41-NVME's without any issues.

login to rescue-mode and run
```shell
> cd /tmp \
  && wget -O /tmp/talos.tar.gz \
  https://github.com/siderolabs/talos/releases/download/v1.1.2/metal-amd64.tar.gz \
  && tar xzOf talos.tar.gz | dd of=/dev/nvme0n1 && sync
```

after the `sync` is done reboot the server and apply your config
```shell
> talosctl apply-config --insecure \
    --nodes <target-ip> \
    --file path/to/controlplane.yaml
```

maybe you need to change your target disk before apply config
```yaml
....
    install:
        disk: /dev/nvme0n1
....
```

**Comment by Janik440** [comment]
> Hi :)
> 
> we run this on Hetzner's AX41-NVME's without any issues.
> 
> login to rescue-mode and run
> 
> ```shell
> > cd /tmp \
>   && wget -O /tmp/talos.tar.gz \
>   https://github.com/siderolabs/talos/releases/download/v1.1.2/metal-amd64.tar.gz \
>   && tar xzOf talos.tar.gz | dd of=/dev/nvme0n1 && sync
> ```
> 
> after the `sync` is done reboot the server and apply your config
> 
> ```shell
> > talosctl apply-config --insecure \
>     --nodes <target-ip> \
>     --file path/to/controlplane.yaml
> ```
> 
> maybe you need to change your target disk before apply config
> 
> ```yaml
> ....
>     install:
>         disk: /dev/nvme0n1
> ....
> ```

Thank you for your insights. I just tested it myself. Unfortunately it isn't working for me. I still get the same error message as before.

Maybe it is because I don't have a server from one of its main lines? I got mine from the auction site.

**Comment by smira** [comment]
There should be some issue with the way you boot the server, as generic Talos ISO image will never reach out to the Hetzner metadata server. Most probably you're booting off the Hetzner image. I don't have any specific details about Hetzner, but certainly Talos won't try to use Hetzner metadata server for `metal` platform.

**Comment by Janik440** [comment]
Thank you for your reply. Before I try again to install Talos via the ISO file. Is there another way to install Talos over the Hetzner Rescue system without having the described problem above?

**Comment by 0xbrigles** [comment]
I would ensure that the boot disk is wiped before try it again

1. enable `rescue-mode` in Hetzner-Robot
2. reboot and login over ssh into `rescue-mode`
3. list all disk by using `lsblk`
4. wipe boot disk, should be `/dev/sda`

```shell
> dd if=/dev/zero bs=1M count=100 oflag=direct of=/dev/sda \
  && wipefs --all /dev/sda
```

5. get and write talos `metal-amd64` image to disk
```shell
# change into /tmp directory
> cd /tmp

# get "metal-amd64" image
> wget -O /tmp/talos.tar.gz \
  https://github.com/siderolabs/talos/releases/download/v1.1.2/metal-amd64.tar.gz

# extract archive and dump it directly to first boot device disk "/dev/sda"
> tar xzOf talos.tar.gz | dd of=/dev/sda && sync

# reboot server
> reboot
```

> from now the server should boot the talos `metal-amd64` image

6. apply your previously created talos config
```shell
> talosctl apply-config --insecure \
    --nodes <target-ip> \
    --file controlplane.yaml
```

7. bootstrap your node
```shell
> talosctl --talosconfig talosconfig \
  bootstrap
```

---
Sadly i can't test the auction server at the moment.
But from what i know the auction servers are the same like the regular ones.

I saw that you have a console output posted, seams that you ordered a kvm-console plugged into your server. Is it possible that a boot stick was also ordered. Did you changed your boot device or something in this direction? Maybe the old one is booted.

**Comment by Janik440** [comment]
> I would ensure that the boot disk is wiped before try it again
> 
> 1. enable `rescue-mode` in Hetzner-Robot
> 2. reboot and login over ssh into `rescue-mode`
> 3. list all disk by using `lsblk`
> 4. wipe boot disk, should be `/dev/sda`
> 
> ```shell
> > dd if=/dev/zero bs=1M count=100 oflag=direct of=/dev/sda \
>   && wipefs --all /dev/sda
> ```
> 
>  5. get and write talos `metal-amd64` image to disk
> 
> ```shell
> # change into /tmp directory
> > cd /tmp
> 
> # get "metal-amd64" image
> > wget -O /tmp/talos.tar.gz \
>   https://github.com/siderolabs/talos/releases/download/v1.1.2/metal-amd64.tar.gz
> 
> # extract archive and dump it directly to first boot device disk "/dev/sda"
> > tar xzOf talos.tar.gz | dd of=/dev/sda && sync
> 
> # reboot server
> > reboot
> ```
> 
>  > from now the server should boot the talos `metal-amd64` image
> 
> 6. apply your previously created talos config
> 
> ```shell
> > talosctl apply-config --insecure \
>     --nodes <target-ip> \
>     --file controlplane.yaml
> ```
> 
>  7. bootstrap your node
> 
> ```shell
> > talosctl --talosconfig talosconfig \
>   bootstrap
> ```
> 
> Sadly i can't test the auction server at the moment. But from what i know the auction servers are the same like the regular ones.
> 
> I saw that you have a console output posted, seams that you ordered a kvm-console plugged into your server. Is it possible that a boot stick was also ordered. Did you changed your boot device or something in this direction? Maybe the old one is booted.

Awesome! Thank you very much for the very detailed explanation how to install the metal image with the Hetzer Rescue system. Everything is working now. ☺️

For other people that might come across the issue, keep in mind to change the default [NTP servers to those from Hetzer ](https://community.hetzner.com/tutorials/install-and-configure-ntp) in the generated configs. Hetzers firewall seems to block other NTP servers partially on auction servers.
