### ISSUE TITLE
make image-metal fails on shallow clone.

### ISSUE THREAD

**Issue by Flightkick** [siderolabs/talos#6030]
### Description
Hoping to optimize the build speed in a CD environment I created a shallow clone of the repository.
`make image-metal` tries to pull `siderolabs/imager` with the version determined by `git describe --tag --always --dirty --match v[0-9]\*`

For a shallow clone, this results in: `e97b9f6`
For a normal clone, this results in: `v1.2.0-alpha.1-21-ge97b9f6d3`

Since the former version doesn't exist, this results in:
```
Error response from daemon: manifest unknown
make: *** [Makefile:235: image-metal] Error 1
```

Maybe this should be emphasized in the docs and/or make help command.

-----

_I encountered this issue while trying to automate Talos Linux builds, discussion here: https://github.com/siderolabs/talos/discussions/6018_

**Comment by frezbo** [comment]
This is fixed by always setting a custom TAG using

```bash
make imager TAG=<custom-tag> PUSH=true
make image-metal TAG=<custom-tag>
```
