### ISSUE TITLE
Makefile $(USERNAME) hides system username.

### ISSUE THREAD

**Issue by Flightkick** [siderolabs/talos#6031]
### Description
The Docker registry `USERNAME` variable in `Makefile` hides the system username. (this is also the case for [extensions](https://github.com/siderolabs/extensions))

This results in Docker registry calls failing unless `USERNAME` is explicitly specified.

### To reproduce
1. Create a `Makefile` with the following contents:
```Makefile
hello:
	@echo "hello $(USERNAME)"
```
2. Run as root: `sudo make`

Output:
```
$ sudo make
hello root
```

### Environment

`Linux ubuntu-18 4.15.0-58-generic #64-Ubuntu`, or easier: Vagrant box `hashicorp/bionic64` under HyperV.

-----

_I encountered this issue while trying to automate Talos Linux builds, discussion here: https://github.com/siderolabs/talos/discussions/6018_

**Comment by frezbo** [comment]
if you want to use a custom registry please use `make REGISTRY=docker.io USERNAME=<username>`. The username is shadown since `sudo` without `-E` drops the user env vars, if you would like to preserve user env vars use `sudo -E`

**Comment by Flightkick** [comment]
Of course you can pass them as variables but why not pick a name that has no collision with external variables?
Like `REGISTRY_USERNAME` for example.
