### ISSUE TITLE
Build dependencies missing crane.

### ISSUE THREAD

**Issue by Flightkick** [siderolabs/talos#6032]
The `Makefile` only mentions the following build dependencies:

https://github.com/siderolabs/talos/blob/4fd676c0468c67799b5d5a1b449551d6243999a5/Makefile#L114-L119

Building the image also seems to depend on [`crane`](https://github.com/google/go-containerregistry/blob/main/cmd/crane/README.md)~, for which `golang` is also required~.

-----

_I encountered this issue while trying to automate Talos Linux builds, discussion here: https://github.com/siderolabs/talos/discussions/6018_

**Comment by frezbo** [comment]
`crane` doesn't depend on golang, you can use pre-built binaries available in the go-containerregistry repo [releases](https://github.com/google/go-containerregistry/releases). Would you mind doing a PR to update the `Makefile`
