### ISSUE TITLE
Makefile TAG variable includes --dirty which breaks image pulls.

### ISSUE THREAD

**Issue by Flightkick** [siderolabs/talos#6033]
https://github.com/siderolabs/talos/blob/856beb21cc3505c10d17e030d2ce0487e019c7ab/Makefile#L4

Including `--dirty` appends `-dirty` to the tag being pulled from the docker registry when the source is modified.
Because there are no `*-dirty` image tags on the ghcr.io registry, builds will fail.

Removing this flag resulted in the expected behavior.

-----

_I encountered this issue while trying to automate Talos Linux builds, discussion here: https://github.com/siderolabs/talos/discussions/6018_

**Comment by frezbo** [comment]
you could always override the variables in Makefile defined as `VAR ?=`, and this is exactly what happens in our CI, please use `make imager TAG=<custom tag>` so that it uses whatever is set by the user.

**Comment by Flightkick** [comment]
I don't think this should be closed yet.
If your CI doesn't use the defaults provided in the Makefile and the `--dirty` flag doesn't contribute anything but breaks the build in some cases. Why not remove said flag from the Makefile?

Passing the TAG would be a valid workaround but making the defaults more resilient would be a more permanent fix.

**Comment by frezbo** [comment]
Our CI use the defaults, it's expected to add `-dirty` when there are un-tracked files in the source. The CI doesn't modify any files during build. It's possible your build process is modifying source files.

**Comment by Flightkick** [comment]
Maybe the `-dirty` appendix has a purpose that I'm not aware of but in my case, the appendix had a side effect of polluting `IMAGE_TAG` which resulted in failures at e.g.:

https://github.com/siderolabs/talos/blob/4fd676c0468c67799b5d5a1b449551d6243999a5/Makefile#L235

**Comment by frezbo** [comment]
> Maybe the `-dirty` appendix has a purpose that I'm not aware of but in my case, the appendix had a side effect of polluting `IMAGE_TAG` which resulted in failures at e.g.:
> 
> https://github.com/siderolabs/talos/blob/4fd676c0468c67799b5d5a1b449551d6243999a5/Makefile#L235

oh you'd have to do a `make imager PUSH=true` first, then it would be able to pull down the image
