### ISSUE TITLE
talosctl --output jsonpath

### ISSUE THREAD

**Issue by sergelogvinov** [siderolabs/talos#6109]
## Feature Request

Support jsonpath output.

### Description

As kubectl, I'd like to have -o jsonpath output filter.
It helps me to get resource values from api.

Example:
```shell
talosctl get etcdsecrets.secrets.talos.dev -ojsonpath="{.spec.etcdPeer.crt}" | base64 --decode
```

**Comment by smira** [comment]
this is a good feature request!

as a temporary workaround, `jq` or `yq` can be used
