### ISSUE TITLE
Support for SCSI block devices

### ISSUE THREAD

**Issue by andrewrynhard** [siderolabs/talos#6117]
The Talos kernel seems to be missing the drivers needed for SCSI block devices. Reporting here so it is easy for users to find.

**Comment by frezbo** [comment]
I don't think that's entirely true (maybe we're missing some specific scsi controller drivers), but if it's a virtualised host scsi mode needs to be set correctly so that kernel can detect them

**Comment by andrewrynhard** [comment]
VMware workstation uses SCSI driver by default. Block devices don't show up there. Possible it is a flavor of SCSI.
