### ISSUE TITLE
Setting IPv6 on the NIC failes the installation

### ISSUE THREAD

**Issue by tomkleinnoordholland** [siderolabs/talos#6126]
When creating a template for a deployment and setting IPv4 and IPv6 address in the controller.yaml failes the installation failes.
The controller.yaml does allow for the ipv6 to be added for the pods and services though.

**Comment by frezbo** [comment]
Could you explain a bit more, are you mentioning about the talos machineconfig?

**Comment by smira** [comment]
There is no `controller.yaml` path in Talos, probably `controlplane.yaml`? 

Do you mean static IPv6 addresses?

**Comment by jlgeering** [comment]
see also #6281 for some ipv6 issues and fixes
