### ISSUE TITLE
Split reset subcommand into reset and delete

### ISSUE THREAD

**Issue by andrewrynhard** [siderolabs/talos#6148]
### Description

I have found that the expectation of users  with the `reset` subcommand is that they want the reset the ephemeral and state partitions. The default behavior of `reset` is more probably more accurately described as `delete`. I propose we split `reset` up into these two commands.

**Comment by andrewrynhard** [comment]
@steverfrancis

**Comment by smira** [comment]
We should also provide a way to `delete` other node (which is not functional anymore)
