### ISSUE TITLE
Provide detail about known disks when install.diskSelector has no matches

### ISSUE THREAD

**Issue by nickbp** [siderolabs/talos#6175]
## Feature Request

I'm currently trying to install to a system which has a Samsung EVO 870 512GB drive and a Samsung QVO 870 8TB drive. In theory I could use `size: '< 1024GB'` or similar, but this risks Talos selecting the USB stick containing the installer. It's a tricky thing to filter without knowing the UUIDs in advance. I've tried `model: '*EVO*'` and somehow Talos isn't matching that.

The [installer error message](https://github.com/siderolabs/talos/blob/e97b9f6d3e14757288d7b2f415b69aef222e8e99/pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go#L1050) just says that my diskSelector doesn't match, but stubbornly hides any detail on what disk options are available. I also cannot run `talosctl disks` to see what Talos is filtering against since nothing's running yet.

Ideally the [error message](https://github.com/siderolabs/talos/blob/e97b9f6d3e14757288d7b2f415b69aef222e8e99/pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go#L1050) would be updated to enumerate the available disks and their sizes/models/makes/uuids/etc so that the end user can revise the diskSelector. Better too much information than nothing at all.

**Comment by frezbo** [comment]
if you 're in maintenance mode you could run `talosctl disks --insecure`

**Comment by nickbp** [comment]
Oh that did the trick after all!

Looks like it works iff `--insecure` and `--nodes` are both manually specified. This is with `nodes: [172.30.3.1]` in `~/.talos/config`:
```
$ talosctl apply-config --insecure --nodes 172.30.3.1 --file controlplane.yaml 
error applying new configuration: rpc error: code = Unknown desc = configuration validation failed: 1 error occurred:
	* no disk found matching provided parameters

$ talosctl disks 
error getting disks: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for talos-172-30-3-1, not kube.example.com"

$ talosctl disks --nodes 172.30.3.1
error getting disks: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for talos-172-30-3-1, not kube.example.com"

$ talosctl disks --insecure
failed to determine endpoints

$ talosctl disks --insecure --nodes 172.30.3.1
DEV        MODEL             SERIAL   TYPE   UUID   WWID   MODALIAS      NAME   SIZE     BUS_PATH
/dev/sda   Samsung SSD 870   -        SSD    -      -      scsi:t-0x00   -      500 GB   /pci0000:00/0000:00:17.0/ata2/host1/target1:0:0/1:0:0:0/
```

Now there's the mystery of why the above `500 GB` drive doesn't match this `500 GB` filter but that's a separate issue - I assume the matching isn't fuzzy enough. Going to just use the `busPath` instead:
```
        diskSelector:
          size: '500 GB'
```
