### ISSUE TITLE
talosctl returns invalid json for some resources

### ISSUE THREAD

**Issue by stereobutter** [siderolabs/talos#6177]
### Description
For some resources *talosctl* returns multiple json objects (i.e. a stream of concatenated json objects) which is **not** valid json. An example of this is `talosctl get address -o json`. This is really unexpected and standard compliant json parsers will not parse this. The correct thing might be to return a list of json objects. This is in contrast to `-o yaml` which returns multiple documents (which is a supported, albeit not as often used feature of yaml parsers).

**Comment by smira** [comment]
This is supported by compliant JSON parsers - read the JSON object one by one from the stream until the EOF. I agree it might be not the best possible solution, but changing that will be a breaking change.
