### ISSUE TITLE
Ability to configure kube-scheduler under ClusterConfig.scheduler

### ISSUE THREAD

**Issue by cvandesande** [siderolabs/talos#6241]
## Feature Request

`kube-scheduler` can be configured with a `PodTopologySpread` yaml configuration file (example attached). The Kubernetes reference mentions the config yaml should be passed to the kube-scheduler command with the `--config path/to/yaml` option. See [here.](https://kubernetes.io/docs/reference/scheduling/config/)

I believe this can be achieved in Talos with a combination of `extraArgs` and `extraMounts` but it's not the most intuitive approach.
It would be nice if Talos supported inline configuration directly in `cluster.scheduler`
[kube-scheduler-topology.yaml.txt](https://github.com/siderolabs/talos/files/9538507/kube-scheduler-topology.yaml.txt)

Thanks again for this amazing project.

**Comment by smira** [comment]
`kube-scheduler` config will be available in Talos 1.6
