### ISSUE TITLE
Hyper-V Setup according to manual fails.

### ISSUE THREAD

**Issue by Martin-Forster** [siderolabs/talos#6295]
Dear Sirs,

im trying , the 1st time in my life, to setup a kubernetes cluster, utilizing talos.

Im following [the guide](https://www.talos.dev/v1.2/talos-guides/install/virtualized-platforms/hyper-v/) 

This seems to work until:
` talosctl apply-config --insecure --nodes $CONTROL_PLANE_IP --file .\controlplane.yaml`
This command seems to be not successful.

When the machined restarts i end up , it looks like, a non working api on port 6443.
I have multiple error messages which ends up like `connect: connection refused`.

# Environment:
HYPER V 2016
talos-amd64.iso from release 1.22
utilizing a existing network with a active dhcp server.

# Screenshot with some output
![image](https://user-images.githubusercontent.com/74290986/191021843-4867bd4e-d88b-46bd-96a9-e2be7561f379.png)

My ultimate goal is to to setup kubernetes cluster for ci/cd usage, and tests. I do not have any pervious expierence with kubernetes. My Idea was that stuff like k3os, or talos would give me a easy and trimmed down approach.

**Comment by smira** [comment]
It looks like you missed the 'Bootstrap' step probably: https://www.talos.dev/v1.2/talos-guides/install/virtualized-platforms/hyper-v/#bootstrap-cluster****

**Comment by Martin-Forster** [comment]
that is accorrding to the document the last step. 
After 

- Pushing Config to the Nodes

i start to get errors,

the following commands then fail.

**Comment by Martin-Forster** [comment]
yo you mean the order in the documentation https://www.talos.dev/v1.2/talos-guides/install/virtualized-platforms/hyper-v/#bootstrap-cluster

is wrong ?

**Comment by smira** [comment]
Probably you should also read generic intro https://www.talos.dev/v1.2/introduction/getting-started/ to understand the common concepts.

The Hyper-V guide is missing some steps, probably you need to run `talosctl config merge ./talosconfig` to merge `talosconfig` generated for your cluster into default `talosconfig` search path.

**Comment by Martin-Forster** [comment]
Thanks i will try
