### ISSUE TITLE
Feature request: better disk management

### ISSUE THREAD

**Issue by myndzi** [siderolabs/talos#6325]
### Description
Talos has config for specifying attached disks and their partitions, and will automatically partition and format them when it boots with an _uninitialized_ disk present. This makes working with Ceph tricky, since Ceph wants an uninitialized disk (or partition) to itself.

I recently managed to set up Ceph in a trial home environment on an empty partition (sliced off from a local disk, of which I gave 50GB over to containerd), and it works fine -- but the process of setting that up required manual steps in privileged containers.

It would be nice if Talos provided some extra functionality here:
- The ability to specify a _filesystem_ to format a partition with in the machine config (with "none" as an option)
- Possibly CLI commands to deal with creating, deleting, and formatting local disks. It clearly already knows how to do these things, so it would be helpful to do them on request, instead of just on boot.

**Comment by frezbo** [comment]
I'm not sure of the use case, but usually with ceph, the extra disks are left out of the talos machine config and let ceph handle them completely.

**Comment by myndzi** [comment]
This is mostly a follow-up from a Slack conversation, but I'll elaborate on the use-case:

Ceph, and other storage solutions, have varying requirements. For example, Minio wants unformatted partitions too, while OpenEBS Jiva wants formatted partitions. Ceph, Minio, and Jiva can all use a partition -- in my case, I've sliced off some of an attached NVME disk to give to containerd and used the rest for storage. However, in order to accomplish this I have to manually run a privileged container and execute parted commands by hand. Being able to do this at the machine config level (or perhaps the talosctl level?) would make configuration of a node's storage much less painful.

This is probably less of an issue on resource-wealthy setups, but I'm working with Raspberry Pis, so the NVMe storage is better than the eMMC or sdcard :)

**Comment by netthier** [comment]
Also interested in this, some OpenEBS engines can expect disks to be either LVM or ZFS formatted beforehand.

**Comment by myndzi** [comment]
:(

**Comment by smira** [comment]
Dup of #8367
