### ISSUE TITLE
pre-pulling Kubernetes images on upgrades

### ISSUE THREAD

**Issue by skandragon** [siderolabs/talos#6391]
### Description

When using `talosctl upgrade-k8s --to 1.25.2` prior to the Sidero custom image for that version being available, upgrading puts the cluster into a state where I must manually revert image versions.  This is likely safe when upgrading a patch value, but I'm not entirely sure what would happen if this were (say) 1.26.0 as the target.

The proposal here is that, for the control nodes at least, we know what versions will be necessary.  Pre-pulling these images (like kubeadm can do) solves several issues and adds a significant safety net:

* Pre-pulling makes the following upgrade-downtime shorter, as the images are already present.
* Pre-pulling ensures the upgrade will succeed because everything needed is already present.
* Pre-pulling in a mixed location "kubespan" and an air-gapped setup could be very complex to "prime" to ensure the images are pullable, and the logs from "upgrade-k8s" doesn't indicate when an image is not available, which requires debugging.

When I used kubeadm, I always pre-pulled images.  Always.  I'd like the same safety net for talos.

### Environment

- Talos version: Any (1.2.3 used)
- Kubernetes version: Upgrade phase from 1.25.1 to 1.25.2 (prior to sidero images)
- Platform: N/A

**Comment by kasimon** [comment]
This would be a very desirable addition to talos. We just had the same problem, due to a misconfiguration our repository mirror could not provide the new kubernetes images, this resulted in one broken control plane node which we had to reinstall.

**Comment by smira** [comment]
This sounds like a good feature, I fully agree. Pre-pulling the images will minimize the downtime during the upgrades.

There should be no need to reinstall anything in case of failure, all that `upgrade-k8s` does is that it patches the machine configuration of the node waiting for some health events to proceed between updates. So reverting back is easy.

Also there's a room for higher-level orchestration tools, like [Omni](https://www.siderolabs.com/platform/saas-for-kubernetes/) which provide higher-level integration, picking safe Kubernetes versions to upgrade, providing rollback features, etc.
