### ISSUE TITLE
talosctl get rd isn't as intuitive as kubectl api-resources

### ISSUE THREAD

**Issue by Jackbennett** [siderolabs/talos#6393]
## Feature Request
Add `talosctl api-resources` to replace or supplement `talosctl get rd` with similar formatting/information as the kubectl output

### Description
Only `talosctl get --help` in full has the reference to using "rd" for the resources. `talos get` prints the help but not that line. adding api-resources would make discovery the same as kubectl we're familiar with. At the risk of copying another tool behaviour.

Personally I wouldn't  be worried about the output table being different but I don't see an immediate reason not to match kubectl anyway. That would that be the same workflow when looking to add rbac to the talos api for users.

## Minor Request
At least put the comment about `get rd` within the short-help on the cli.

**Comment by ankitm123** [comment]
I will take a look, if no one else has started looking into it ...

**Comment by smira** [comment]
Adding a top-level command would go wrong way in terms of future of the `talosctl`.

`talosctl get rd` can be aliased to be `talosctl get api-resources`.
