### ISSUE TITLE
Add binfmt_misc kernel support

### ISSUE THREAD

**Issue by DizTortion** [siderolabs/talos#6406]
## Feature Request

Please consider adding CONFIG_BINFMT_MISC in the kernel.

### Description

A requirement for multiarch image builds using podman is to have binfmt_misc support in the kernel. 

smira also mentioned the lack of support [here](https://github.com/siderolabs/talos/pull/4330) so I'm wondering if this has been disabled due to security concerns.

**Comment by andrewrynhard** [comment]
I was literally just wanting this myself the other day 😄 .

**Comment by DizTortion** [comment]
Okay nice, I'll send a PR.

**Comment by andrewrynhard** [comment]
> Okay nice, I'll send a PR.

No guarantee that it will be accepted. We have questions about the security but please still open it.
