### ISSUE TITLE
Sidero Labs Community on Slack should accept GitHub logins

### ISSUE THREAD

**Issue by felsgaertner** [siderolabs/talos#6421]
## Feature Request

Add GitHub as OIDC provider to Sidero Labs Community on slack.

### Description

As I want to ask a question, I am redirected to the slack login page. I could register, but I do not have an account yet, and furthermore I do not to use Google or Apple. GitHub also provides login federation, so it should be possible to use this GitHub login also in the Slack Community.

Otherwise questions should be possible as GitHub issues.

**Comment by smira** [comment]
That's a valid request, we will look into that, also there's https://github.com/siderolabs/talos/discussions for questions with pure GitHub experience

**Comment by felsgaertner** [comment]
What is the status of my request? This issue is open way more than the 180 days mentioned by the bot...

**Comment by smira** [comment]
> There's [siderolabs/talos/discussions](https://github.com/siderolabs/talos/discussions) for questions with pure GitHub experience
