### ISSUE TITLE
Hetzner nodes crashloop during startup 

### ISSUE THREAD

**Issue by kelt1k** [siderolabs/talos#6428]
## Bug Report
VMs conditionally reboot during startup 

### Description
After creating nodes they are going to reboot permanently with error 
![Screenshot 2022-10-20 at 01 26 16](https://user-images.githubusercontent.com/62957498/196819421-0406c9e2-b151-433d-b2a7-2424eb705f4e.png)
here is my controlplane config
[talos-controlplane.txt](https://github.com/siderolabs/talos/files/9824881/talos-controlplane.txt)
### Logs
Unfortunately I can't collect logs during boot 
### Environment

- Talos version: [v1.2.5]
- Kubernetes version: [`none`]
- Platform: Debian11

**Comment by frezbo** [comment]
from the output it says it found unknown keys, seems you're booting an old talos version and trying features only available on newer talos version
