### ISSUE TITLE
Enable CONFIG_INET_DIAG_DESTROY to allow killing connections

### ISSUE THREAD

**Issue by minus7** [siderolabs/talos#6429]
## Feature Request
Please consider enabling the [CONFIG_INET_DIAG_DESTROY](https://cateee.net/lkddb/web-lkddb/INET_DIAG_DESTROY.html) kernel config to allow killing connections of other processes from privileged processes.

This would allow me to spawn a privileged debug container and kill TCP connections in a pod to see how it reacts to broken connections (well, at least one variant of broken connections)

**Comment by mologie** [comment]
Just some supporting information: Ubuntu Linux 22.04 ships with this option enabled in their default kernel:

```
$ uname -rm
5.19.16-76051916-generic x86_64
$ grep CONFIG_INET_DIAG /boot/config-$(uname -r)
CONFIG_INET_DIAG=m
CONFIG_INET_DIAG_DESTROY=y
```

It's compiled as module but loaded from unprivileged userspace automatically, however that works:
```
$ lsmod | ag _diag
$ ss -tuplen
Netid   State    Recv-Q   Send-Q     Local Address:Port      Peer Address:Port  Process                                                                         
udp     [...]
$ lsmod | ag _diag
tcp_diag               16384  0
udp_diag               16384  0
inet_diag              24576  2 tcp_diag,udp_diag
```

(disclaimer: I work with OP on projects that would benefit from this option being enabled.)

**Comment by smira** [comment]
I guess it's still subject to network namespaces, so it should be safe to be enabled

**Comment by minus7** [comment]
The flag enables an additional Netlink message type `SOCK_DESTROY` on `NETLINK_SOCK_DIAG` netlink sockets, so that should very much be subject to namespaces
