### ISSUE TITLE
Hyper-V Daemon

### ISSUE THREAD

**Issue by intersectRaven** [siderolabs/talos#6435]
## Feature Request

Please have a way to enable hypervvssd service in Talos.

### Description

Currently, our backups are throwing warnings due to Hyper-V snapshots failing to create an application consistent checkpoint and instead creating a crash consistent checkpoint. I usually solve this on our other Linux based VMs by just installing hyperv-daemons and enabling the hypervvssd service which takes care of all the stuff but since I can't access the commandline I don't think that's possible currently.

**Comment by smira** [comment]
Disclaimer: I don't have any experience with Hyper-V.

If that's a matter of running a daemon across the nodes, you can do that via Kubernetes DaemonSet (privileged one, I guess).

If that requires deeper integration, Talos offers system extensions and extension services:

* https://github.com/siderolabs/extensions
* https://www.talos.dev/v1.2/advanced/extension-services/

**Comment by willemm** [comment]
I can verify that you can run hyperv-daemons as a daemonset across the nodes and it works fine.

See my implementation for reference:  https://github.com/willemm/hv_kvp_container
