### ISSUE TITLE
Minor issue with certificates after upgrading

### ISSUE THREAD

**Issue by githubcdr** [siderolabs/talos#6462]
## Bug Report

After upgrading to 1.2.6 I ran into this issue.

```
error getting dmesg: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid: current time 2022-10-28T23:27:48+02:00 is before 2022-10-28T22:14:20Z"
```

### Description

Upgrade from 1.2.5 to 1.2.6, it seems a timezone/UTC conflict?

### Environment

- rapsberry pi4
- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: [`kubectl version --short`]
- Platform:

**Comment by smira** [comment]
Not sure what it might be, but usually points at time sync issue on one of the sides. You need to check which timestamp sounds more "correct". `2022-10-28T23:27:48+02:00` is your local time. So UTC 21:27. `2022-10-28T22:14:20Z` is server time (UTC). I think certificate was issued at 22:14 before 21:27. But only you know which way it's wrong.

**Comment by githubcdr** [comment]
Next time I will use --insecure flag, this time I waited for 2 hours ;)
