### ISSUE TITLE
Doc: Talos use case without k8s

### ISSUE THREAD

**Issue by bbros-dev** [siderolabs/talos#6473]
## Feature Request

Is running Talos without k8s a supported use case?
Specifically, in this scenario are any k8s configuration items still required?

**Comment by bbros-dev** [comment]
> The footprint might be minimized by disabling kubelet node registration and running all workloads as static pods, disabling all components but the API server

Thanks for the tip, we'll look in to [static pods](https://www.talos.dev/v1.2/advanced/static-pods/#usage).

> We had some ideas about making Kubernetes "a plugin",

Sounds ideal. The Consul & Nomad communities might be worth approaching?

We'll record any documentation issues here, or close when we have a working setup.

**Comment by smira** [comment]
Yep, Nomad is something we considered, but nothing planned for it yet.

**Comment by kunalsingthakur** [comment]
is there anything update on it

**Comment by langerma** [comment]
is nomad still in consideration?

**Comment by fullmetal-fred** [comment]
I recently started [this discussion](https://github.com/siderolabs/talos/discussions/8343) on the very topic of standalone workers running static pods without a control plane if anyone is interested in furthering it. Certainly I think having the orchestrator be pluggable is an awesome idea...but short of that, just running static pods without needing a control plane would be really helpful. I'm happy to dig in as well, but need a little direction as I'm not fully sure where to start.
