### ISSUE TITLE
Cannot create cluster with custom CIDR

### ISSUE THREAD

**Issue by paddy-hack** [siderolabs/talos#6512]
## Bug Report

Running `talosctl cluster create` works as advertised.  It still does when I add `--cidr 10.7.13.0/24` to the mix.  
However, using `*/24` CIDRs in the `172.16.0.0/12` or `192.168.0.0/16` private IP ranges fails.

### Description

I have been exploring creating Docker-based clusters (behind a corporate proxy).  To work around network latency, I followed the [Air-gapped Environments](https://www.talos.dev/v1.2/advanced/air-gapped/) instructions to set up registry mirrors.  With that out of the way, I attempt to create a cluster as follows:
``` sh
talosctl cluster create --controlplanes 3 --workers 2  --cidr $CIDR.0/24 \
    --registry-mirror docker.io=http://$CIDR.1:6000 \
    --registry-mirror gcr.io=http://$CIDR.1:6000 \
    --registry-mirror ghcr.io=http://$CIDR.1:6000 \
    --registry-mirror k8s.gcr.io=http://$CIDR.1:6000 \
    --registry-mirror quay.io=http://$CIDR.1:6000
```
with various values for CIDR.

Before trying with another `CIDR` value, I clean up with
``` sh
talosclt cluster destroy; rm -rf .talos/ .kube/
```

Since I use a deny-all policy for unsolicited incoming network traffic on my machine, I added rules to allow incoming traffic on Docker's `br-*` interfaces and source addresses in the CIDR range
``` sh
nft add rule inet filter input iifname 'br-*' accept
nft add rule inet filter input ip saddr $CIDR.0/24 ct state new accept
```
\# I forgot the `ct state new` bit for the Docker interfaces :sweat_smile: 

As mentioned above, using `CIDR=10.5.0`, i.e. explicitly setting the default, and `CIDR=10.7.13` works as expected.  However, when I try with, e.g. `CIDR=172.16.13` or `CIDR=192.168.13`, I get
``` console
validating CIDR and reserving IPs
generating PKI and tokens
creating network talos-default
creating controlplane nodes
creating worker nodes
waiting for API
bootstrap error: 4 error(s) occurred:
	rpc error: code = Unavailable desc = last connection error: connection error: desc = "transport: authentication handshake failed: x509: cannot validate certificate for 192.168.13.2 because it doesn't contain any IP SANs"
	rpc error: code = Unavailable desc = last connection error: connection error: desc = "transport: authentication handshake failed: x509: cannot validate certificate for 192.168.13.4 because it doesn't contain any IP SANs"
	rpc error: code = Unavailable desc = last connection error: connection error: desc = "transport: authentication handshake failed: x509: cannot validate certificate for 192.168.13.3 because it doesn't contain any IP SANs"
	timeout
```
I had expected things to work for such CIDR values in the same way as `*/24` CIDR values in the `10.0.0.0/8` block of private IP addresses.  If IP SANs really need to be added, I would have expected there to be a suitable command line option to do so, like the `--additional-sans` option for `talosctl gen config`.

My main reason for trying these other CIDR values is that the corporate network uses IP addresses in both the `10.0.0.0/8` and `172.16.0.0/12` block.  Of course, Docker also uses subnets and IP addresses in the latter block.

### Logs

I don't know which logs are relevant so will not add anything here.  Just let me know which logs, if any, are needed and I'll add them.

### Environment

- Talos version: 
  ```
  Client:
	Tag:         v1.2.6
	SHA:         6ca8b2ac
	Built:       
	Go version:  go1.19.2
	OS/Arch:     linux/amd64
  Server:
  error getting version: rpc error: code = Unavailable desc = last connection error: connection error: desc = "transport: authentication handshake failed: x509: cannot validate certificate for 192.168.13.2 because it doesn't contain any IP SANs"
  ```
- Kubernetes version:
  ```
  Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
  Client Version: v1.25.4
  Kustomize Version: v4.5.7
  The connection to the server localhost:8080 was refused - did you specify the right host or port?
  ```
- Platform: `linux/amd64`
- Docker version: `Docker Engine - Community 20.10.21`

**Comment by smira** [comment]
The problem you're hitting might be that your cluster node CIDR overlaps with the Kubernetes (default) pod/service CIDRs. That's the only thing I can imagine that Talos tries to avoid the address.

**Comment by smira** [comment]
But at the same time it's stange, as default Kubernetes CIDRs are in the `10/8` network.

**Comment by paddy-hack** [comment]
:scream: It's my `no_proxy` settings!

Appending `,172.16.0.0/12,192.168.0.0/16` to my ever increasing list of proxy exemptions fixed the problem.  I already had `10.0.0.0/8` in there to access a few internal hosts by IP address.

Sorry for the noise.  
Oh, and thanks for the feedback :bow:
