### ISSUE TITLE
talosctl get machineconfig && apply failed to parse config: missing kind

### ISSUE THREAD

**Issue by vorburger** [siderolabs/talos#6522]
## Bug Report

As a naive first time noob user, I would have expected the following to work in an OS which "manages machines [like any other Kubernetes CRD](https://github.com/vorburger/LearningKubernetes-CodeLabs/blob/develop/docs/crd.md)"  - even though I see 😈  from reading https://www.talos.dev/v1.2/talos-guides/configuration/editing-machine-configuration/ this may not be the currently intended/supported "flow", but I thought I would raise it here anyway, just FYI, if you want to consider supporting this in the future (eventually, not blocking; I can probably just use `taloctl edit machineconfig` in the meantime):

```
$ talosctl get machineconfig
NODE           NAMESPACE   TYPE            ID         VERSION
192.168.1.123   config      MachineConfig   v1alpha1   1

$ talosctl get machineconfig v1alpha1 -o yaml >mach.yaml

$ talosctl apply -f mach.yaml --mode=no-reboot
error applying new configuration: 1 error occurred:
        * 192.168.1.98: rpc error: code = InvalidArgument desc = failed to parse config: missing kind

$ talosctl apply machineconfig -f mach.yaml --mode=no-reboot
error applying new configuration: 1 error occurred:
        * 192.168.1.98: rpc error: code = InvalidArgument desc = failed to parse config: missing kind
```

BTW that ID `v1alpha1` is surprising... perhaps that should actually be `192.168.1.123`?

### Environment

- Talos version: [`talosctl version --nodes`]

      Client:
              Tag:         v1.2.5
              SHA:         65fab60c
              Built:
              Go version:  go1.19.2
              OS/Arch:     linux/amd64
      Server:
              NODE:        192.168.1.123
              Tag:         v1.2.5
              SHA:         65fab60c
              Built:
              Go version:  go1.19.2
              OS/Arch:     linux/amd64
              Enabled:     RBAC

- Kubernetes version: [`kubectl version --short`]

      Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
      Client Version: v1.25.3
      Kustomize Version: v4.5.7
      Server Version: v1.25.3

@andrewrynhard FYI

**Comment by vorburger** [comment]
That `missing kind` can, of course, be fixed by inserting this at the start of `mach.yaml`, but perhaps that should automatically be there:

    kind: MachineConfigs.config.talos.dev

That then leads to:

    error applying new configuration: 1 error occurred:
            * 192.168.1.98: rpc error: code = InvalidArgument desc = failed to parse config: missing version

I've attempted to fix that by inserting this at the start of `mach.yaml` but that's not right / doesn't help:

    apiVersion: v1alpha1

**Comment by vorburger** [comment]
`version: v1alpha1` isn't right either, and leads to:

    error applying new configuration: 1 error occurred:
            * 192.168.1.98: rpc error: code = InvalidArgument desc = failed to parse config: new config: "MachineConfigs.config.talos.dev" "v1alpha1": not registered

**Comment by andrewrynhard** [comment]
The machine configuration isn't exactly the same format as Kubernetes. The only claim we make is that is is _like_ Kubernetes in that it is declaratively driven. The format is our own format. That being said next year we will likely be breaking up the config and supporting multidoc YAML. When we do that I think we should at least consider having the same format as Kubernetes. Maybe not 100% but close.

**Comment by vorburger** [comment]
Cool! Looking forward.

But perhaps the point I'm really trying to make here is actually less about the "match the Kubernetes format" itself specifically, but more about that `talosctl get ...` and `talosctl appy ...` "should work symmetrically", in an ideal world, to meet user expecations of such a CLI / API.

PS: Not complaining at all, Talos is GREAT; just trying to make helpful a suggestion!

**Comment by smira** [comment]
For historical reasons, `get` returns config as a resource, while `apply-config` accepts raw machine config.

So you need something like: `talosctl get mc -o yaml | yq eval .spec | talosctl apply-config ...`

**Comment by vorburger** [comment]
Oh, right! Looking at `talosctl -h` there actually is no `apply`, and `talosctl apply -h` clearly shows that's just an alias for [`apply-config`](https://www.talos.dev/v1.2/reference/cli/#talosctl-apply-config), and you never meant for that to be a generic "apply" of anything that one can "get" - got it.

I'll try it out... just as as soon as I have my node back 😹  which I just hosed with a `taloctl edit machineconfig` to add a disk; must have made a mistake somewhere; am just learning how to troubleshoot it.

Perhaps I can raise a PR to elaborate `talosctl get mc -o yaml | yq eval .spec | talosctl apply-config ...` e.g. on https://www.talos.dev/v1.2/talos-guides/configuration/editing-machine-configuration/, could that be a welcome contribution?

**Comment by smira** [comment]
if you make a mistake with user disks, Talos will stop on booting, but it will leave `apid` running, so you can re-apply fixed config

**Comment by vorburger** [comment]
> if you make a mistake with user disks, Talos will stop on booting

Yeah, I noticed... it's surprising at first, but I actually like it like this! (I basically ran into #2213 (which is otherwise unrelated to this issue).

> So you need something like: talosctl get mc -o yaml | yq eval .spec | talosctl apply-config ...

FYI `talosctl apply-config` (at least in v1.2.5) doesn't seem to dig pipe from STDIN (says `no filename supplied for configuration`) but e.g. this will do the trick:

    talosctl get mc -o yaml | yq eval .spec | talosctl apply-config -f /dev/stdin

BTW: `eval` seems recent in `yq`, if anyone finding this in the future and tries this and hits `Error: open .spec: no such file or directory` then just upgrade `yq` e.g. from v4.4.1 to 4.30.4.

I'll raise a PR...
