### ISSUE TITLE
`talosctl gen config` to output a single config type

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#6562]
Add a flag to output a single config type (controlplane/worker/talosconfig) instead of a bundle, specify destination file (we can default to stdout).

**Comment by smira** [comment]
Please note that `gen config` already supports creating reproducible base config from a secrets bundle, and add patches on top of it, so this issue is only about changing the output format.

**Comment by andrewrynhard** [comment]
User wants something like:

```
talosctl gen config --from=base.yaml --config-patch=patch.yaml
```

`from` is an existing base machine configuration.

**Comment by smira** [comment]
I don't like `gen config` with `--from`, how about `talosctl machineconfig patch -f base.yaml -p @patch1.yaml` ?
