### ISSUE TITLE
Talos v1.3.0-beta.0 does not boot on RPi3

### ISSUE THREAD

**Issue by dggonz** [siderolabs/talos#6583]
## Bug Report

Talos V1.3.0-beta.0 does not boot on a RPi3 v1.2. I have not tried previous versions. I guess this would work since the release notes suggest it might work. 

This is the link to the image I used: https://github.com/siderolabs/talos/releases/download/v1.3.0-beta.0/metal-rpi_generic-arm64.img.xz

### Description
I flashed the mentioned image to an SDCard using the rpi-imager. Insert the card and boot. Nothing happens...

### Logs
There are no logs. Nothing is displayed on the connected monitor, the monitor is not even detecting a signal.

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: [`kubectl version --short`]
- Platform: Raspberry Pi 3 v1.2

**Comment by codanael** [comment]
I also tried it on an earlier 1.3.0 alpha version. Indeed, when flashing it to an SD card it does nothing.
However, I also flashed the image to a usb drive, and booted the RPI 3B+ from it.
This time, it boots, but I think the image misses the driver for the Ethernet port, because it can't connect to anything, and the lights of the port don't even light up.

I abandoned the idea because I don't think the RPI3B+ has not enough ram to run a basic talos instance.

**Comment by smira** [comment]
I don't think we ever tried with RPi3, the initial support for RPi4. This generic image might work, but it hasn't been tested. And like @codanael says, you would probably need a minimum of 2 GiB to run anything Kubernetes control plane.

**Comment by dggonz** [comment]
My idea was slightly different, I would not want to install Kubernetes on the RPi3. 

My idea was to install on Talos the edge part KubeEdge (edgecore), which has very limited dependencies (namely docker). I wold customize the rootfs by following https://www.talos.dev/v1.2/advanced/customizing-the-root-filesystem/.

Once edgecore is installed and configured I could just deploy onto it containers through KubeEdge. 

By using Talos I can take advantage of its immutability, limited footprint and easiness of upgrade. I understand though that this is not what Talos was build for...

**Comment by frezbo** [comment]
> My idea was to install on Talos the edge part KubeEdge (edgecore), which has very limited dependencies (namely docker). I wold customize the rootfs by following https://www.talos.dev/v1.2/advanced/customizing-the-root-filesystem/.

I'm not sure that would work, Talos boot process expects K8s components, so after the boot timeout it would go into a reboot cycle

**Comment by sanmai-NL** [comment]
@dggonz Is this issue still relevant? It seems to me like a mixture of a feature request and defect report, right?

**Comment by dggonz** [comment]
It can be closed
