### ISSUE TITLE
KVM Worker Node Reboot Cycle - unable to read client-cert /var/lib/kubelet/pki/kubelet-client-current.pem

### ISSUE THREAD

**Issue by kylebrooks-8451** [siderolabs/talos#6584]
### Description

When I apply a worker config to a  Talos VM running on KVM / Proxmox it gets stuck in a reboot loop with the errors below.

### Logs

[ 14.742509] [talos] service[kubelet] (Waiting): Waiting for service "cri" to be “up”
[ 15.010989] [talos] service[cri] (Running): Health check successful
[ 15 .012355] [talos] service[kubelet] (Preparing): Running pre state
[ 15 .038582] [talos] service[kubelet] (Preparing): Creating service runner
[ 15 .076723] [talos] service[apid] (Running): Started task apid (PID 1567) for
container apid
[ 15.275182] [talos] service[kubelet] (Running): Started task kubelet (PID 1614
) for container kubelet
[ 17.096110] [talos] service[kubelet] (Running): Health check successful
[ 19.261467] [talos] service[apid] (Running): Health check successful
[ 19.262827] [talos] task startAllServices (17/71): done, 5.278966766s
[ 19.264005] [talos] phase startEverything (16/18): done, 5.281363996s
[ 19.265143] [talos] phase uncordon (17/18): 1 tasks(s)
[ 19.266149] [talos] task uncordonNode (1/1): starting
[ 19.267896] [talos] retrying error: invalid configuration: [unable to read client-cert /var/lib/kubelet/pki/kubelet-client-current.pem for default-auth due to open /var/lib/kubelet/pki/kubelet-client-current.pem: no such file or directory, unable to read client-key /var/lib/kubelet/pki/kubelet-client-current.pem for default-auth due to open /var/lib/kubelet/pki/kubelet-client-current.pem: no such file or directory]

### Environment

- Talos version: 1.2.7
- Kubernetes version: 1.2.7
- Platform: AMD64 KVM / Proxmox

**Comment by smira** [comment]
This looks like a worker which can't connect to the control plane? What happens is that kubelet is not able to join the node to the cluster, and the node eventually reboots. You have Talos API access, so you can check the logs with `talosctl logs kubelet`.

**Comment by kylebrooks-8451** [comment]
I can't access to logs. I was able to get the logs above by taking a screenshot of the VGA console and running OCR.

When I try to access the logs I get this error:

```bash
talosctl -e 192.168.1.243 logs kubelet
error getting logs: rpc error: code = PermissionDenied desc = no request forwarding
```

**Comment by kylebrooks-8451** [comment]
Thanks @smira, here are the logs from kubelet:

```
192.168.1.243: {"ts":1670174505693.8008,"caller":"cache/reflector.go:424","msg":"vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.RuntimeClass: Unauthorized\n","v":0}
192.168.1.243: {"ts":1670174505693.891,"caller":"cache/reflector.go:140","msg":"vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: Unauthorized\n"}
192.168.1.243: {"ts":1670174505722.5264,"caller":"kubelet/kubelet.go:2448","msg":"Error getting node","err":"node \"talos-proxmox-0\" not found"}
192.168.1.243: {"ts":1670174505823.1409,"caller":"kubelet/kubelet.go:2448","msg":"Error getting node","err":"node \"talos-proxmox-0\" not found"}
192.168.1.243: {"ts":1670174505924.4036,"caller":"kubelet/kubelet.go:2448","msg":"Error getting node","err":"node \"talos-proxmox-0\" not found"}
192.168.1.243: {"ts":1670174506025.0886,"caller":"kubelet/kubelet.go:2448","msg":"Error getting node","err":"node \"talos-proxmox-0\" not found"}
192.168.1.243: {"ts":1670174506125.826,"caller":"kubelet/kubelet.go:2448","msg":"Error getting node","err":"node \"talos-proxmox-0\" not found"}
192.168.1.243: {"ts":1670174506154.7126,"caller":"eviction/eviction_manager.go:256","msg":"Eviction manager: failed to get summary stats","err":"failed to get node info: node \"talos-proxmox-0\" not found"}
192.168.1.243: {"ts":1670174506202.2578,"caller":"kubelet/kubelet.go:2373","msg":"Container runtime network not ready","networkReady":"NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"}
192.168.1.243: {"ts":1670174506226.8987,"caller":"kubelet/kubelet.go:2448","msg":"Error getting node","err":"node \"talos-proxmox-0\" not found"}
```

**Comment by smira** [comment]
I really don't have enough information in your ticket to help you. It might be that you enabled kubelet server certs and nothing approves the CSRs. Or the control plane node is not healthy.

**Comment by kylebrooks-8451** [comment]
I appreciate they help you've given already.  I have 3 control plan nodes and 3 worker nodes already and they are working:

```
k get nodes
NAME            STATUS   ROLES           AGE   VERSION
talos-6cr-0fi   Ready    <none>          11d   v1.25.2
talos-b2m-7a0   Ready    control-plane   11d   v1.25.2
talos-ixc-r5k   Ready    control-plane   11d   v1.25.2
talos-j92-0u1   Ready    <none>          11d   v1.25.2
talos-srn-grj   Ready    <none>          11d   v1.25.2
talos-tu8-r34   Ready    control-plane   11d   v1.25.2
```
I don't see anything wrong that stands out with the network.

**Comment by smira** [comment]
The easiest might be to grab the support bundle from that node and upload it here: `talosctl -n IP support`

**Comment by kylebrooks-8451** [comment]
Here it is:

[support.zip](https://github.com/siderolabs/talos/files/10149692/support.zip)

Looking at the kubelet logs, I see some permissions issues.  For what I can tell the `worker.yaml` has the same tokens / keys except for the `machine.ca.key` which is missing from the worker yaml.  This yaml worked for the other worker nodes.

**Comment by kylebrooks-8451** [comment]
Thanks @smira - I found the problem, the MTU was misconfigured in Proxmox so it was networking issues.
