### ISSUE TITLE
Better `k8s-upgrade` checks for removed api-resources

### ISSUE THREAD

**Issue by frezbo** [siderolabs/talos#6599]
## Feature Request

Better `k8s-upgrade` checks for removed api-resources

### Description

Make sure talosctl fails for resources that are going to be removed in the `upgradeTo` kubernetes version and is having the removed api version as the storage version in api server. Move these checks to the new `upgrade_checks.go`

**Comment by smira** [comment]
After some discussion, we landed on the fact that `kube-apiserver` automatically handles API version translation, so the only concern is the resource type going out completely.
