### ISSUE TITLE
Kubernetes sometimes doesn't come up after reboot

### ISSUE THREAD

**Issue by pQraus** [siderolabs/talos#6633]
## Bug Report
We have a single-node cluster on a bare metal machine. Sometimes k8s isn't starting after the machine had rebooted. In this case there aren't any k8s containers (`talosctl containers -k`) and no k8s-apiserver is running. But the kubelet service will run and is declared as healthy:
```
192.168.1.102   kubelet      Running   OK       1m52s ago     Health check successful
```

### Description
We have been determinating that two of our test-machines (both are used as a single-node cluster) have the problem to run k8s after some reboots. There can be nine reboots where everything works fine but we have also seen the problem on every second reboot. We have five additional test-machines that don't encounted this reboot problem. The obvious differende is that the two machines that don't work have a nvidia gpu built in and different hardware specs (we are unsure if this is related to the problem). 

To reproduce the issue in a minimal setup we have installed talos on a gpu machine without any drivers and extensions (only `talosctl apply --mode interactive ...`).

It looks like that kubelet isn't able to start the kube-api-server (containerd, network problem ???). We have tried to find differences in the logs of kubelet but we can't see a big difference. When the reboot fails we only see a big number of `"kubelet/kubelet.go:2448","msg":"Error getting node","err":"node \"demo-box\" not found"` errors.

For our understanding is that the (basic) expected workflow of kubelet:
1. start kubelet
2. watch for static pods / manifests in `etc/kubernetes/manifests` (where the api-server config is located)
3. tell containerd via cri to deploy the static pods (we think something is lost between step two and three; is the kubelet service directly talking with the cri?)
4. node becomes ready
5. deploy the other workloads which are saved in etcd?

We don't understand this workflow in its entirety. 

We have also tried different talos versions (1.2.0 & 1.2.7) and kubernetes 1.25.0 & 1.25.4. On every version the problem occurs. In this issue you see the logs from our setup with talos 1.2.0 and kubernetes 1.25.0. 

Our Workaround(s) to solve the problem for now:
- restart kubelet `talosctl service kubelet restart`
- reboot (over and over again)
- a system extension which will restart kubelet automatically if the apiserver didn't start :D

(questions in matrix chat: [matrix](https://matrix.to/#/!AgkZYgUvcdbbmiDbMx:matrix.org/$8tUBszpBoT-jPk1yPG2KvaNCpL5QlyLuCLSBPti5LFc?via=matrix.org&via=ungleich.ch&via=tty42.de))

Any ideas to fix that? 

Maybe a kubelet problem?

Maybe a hardware problem?

### Logs (failed reboot)
All logs come from our minimal talos 1.2.0 & k8s 1.25.0 setup (created via `talosctl apply --mode interactive ...`, `ghcr.io/siderolabs/installer:v1.2.0` without any gpu drivers / extensions).

`talosctl dmesg`:
[dmesg-failed-reboot.txt](https://github.com/siderolabs/talos/files/10225737/dmesg-failed-reboot.txt)

`talosctl logs kubelet` (we have set the loglevel via extra args to `--v=6`):
[kubelet-logs-failed-reboot.txt](https://github.com/siderolabs/talos/files/10225739/kubelet-logs-failed-reboot.txt)

`talosctl containers -k`:
```
NODE   NAMESPACE   ID   IMAGE   PID   STATUS
```

`talosctl service`:
```
NODE            SERVICE      STATE     HEALTH   LAST CHANGE   LAST EVENT
192.168.1.102   apid         Running   OK       1m55s ago     Health check successful
192.168.1.102   containerd   Running   OK       2m2s ago      Health check successful
192.168.1.102   cri          Running   OK       1m55s ago     Health check successful
192.168.1.102   etcd         Running   OK       1m49s ago     Health check successful
192.168.1.102   kubelet      Running   OK       1m52s ago     Health check successful
192.168.1.102   machined     Running   ?        2m45s ago     Service started as goroutine
192.168.1.102   trustd       Running   OK       1m54s ago     Health check successful
192.168.1.102   udevd        Running   OK       1m58s ago     Health check successful
```

### Logs (successful reboot)
All logs come from our minimal talos 1.2.0 & k8s 1.25.0 setup (`created via talosctl apply --mode interactive ...`, `ghcr.io/siderolabs/installer:v1.2.0` without any gpu drivers / extensions).

`talosctl dmesg`:
[dmesg-normal-reboot.txt](https://github.com/siderolabs/talos/files/10225738/dmesg-normal-reboot.txt)

`talosctl logs kubelet` (we have set the loglevel via extra args to `--v=6`):
[kubelet-logs-normal-reboot.txt](https://github.com/siderolabs/talos/files/10225729/kubelet-logs-normal-reboot.txt)

### Environment

- Talos version:
    ```
    Client:
        Tag:         v1.2.3
        SHA:         40cb1b49
        Built:       
        Go version:  go1.19.1
        OS/Arch:     linux/amd64
    Server:
        NODE:        192.168.1.102
        Tag:         v1.2.0
        SHA:         c568770c
        Built:       
        Go version:  go1.19
        OS/Arch:     linux/amd64
        Enabled:     RBAC
    ```
- Kubernetes version:
    ```
    Client Version: v1.22.1
    Server Version: v1.25.0
    ```
- Platform: bare metal (single-node)
    - Specs:
        ``````
        NODE            NAMESPACE   TYPE           ID                  VERSION   MANUFACTURER   MODEL         SIZEMIB
        192.168.1.102   hardware    MemoryModule   Controller0-DIMM0   1                                      
        192.168.1.102   hardware    MemoryModule   Controller0-DIMM1   1         Kingston       KF548C38-16   16384
        192.168.1.102   hardware    MemoryModule   Controller1-DIMM0   1                                      
        192.168.1.102   hardware    MemoryModule   Controller1-DIMM1   1         Kingston       KF548C38-16   16384
        
        NODE            NAMESPACE   TYPE        ID        VERSION   MANUFACTURER           MODEL                                 CORES   THREADS
        192.168.1.102   hardware    Processor   LGA1700   1         Intel(R) Corporation   12th Gen Intel(R) Core(TM) i7-12700   12      20
        ``````

**Comment by pQraus** [comment]
👍 
We have installed talos 1.3.0 and k8s 1.26.0. So far, we have made several reboots (~6) and there was no problem with kubernetes. Before we can say that the problem is solved, we would make some more "reboot tests". However, these tests cannot be performed until the new year 🎄
I'll get back to you.

**Comment by pQraus** [comment]
After ~35 reboots with talos 1.3.0 and k8s 1.26.0 we haven't seen the problem again. We think the problem is solved with the new talos version. 

Side note:
It seems that Talos 1.3.0 fixes the problem. Kubernetes 1.25.0 also works fine when using the new talos version (after ~ 15 reboots).

**Comment by smira** [comment]
:+1: thanks for testing it
