### ISSUE TITLE
Publish IONOS Cloud compatible Image

### ISSUE THREAD

**Issue by FischerLGLN** [siderolabs/talos#6638]
## Feature Request
Publishing an [IONOS Cloud](https://cloud.ionos.de/) compatible Image would allow us to use their GDPR secure datacenter via Edge Computing.
### Description
I think the platform dependent code needs to be added here: https://github.com/siderolabs/talos/tree/main/internal/app/machined/pkg/runtime/v1alpha1/platform

I can provide docs instructions how to create LoadBalancer and Server instances via CLI.
Since I have an IONOS Account, how can I build an image for this platform?
Thanks!

**Comment by smira** [comment]
Please see https://github.com/siderolabs/talos/issues/6637#issuecomment-1352902893
