### ISSUE TITLE
cli: talosctl get (without argument) does not autocomplete in 1.3.0

### ISSUE THREAD

**Issue by nberlee** [siderolabs/talos#6646]
## Bug Report
`talosctl get` (without arguments) does not autocomplete. It does work with `talosctl get a`

This worked in previous versions. And i use it a lot...

### Description
I see most code was rewritten here:
https://github.com/siderolabs/talos/commit/9baca49662ae3b542752cb797eaf2c9956149902#diff-a262b85cfb10d7bf31e9c80273372fb9f0308e3bd7ec7c51053f568d42075e7e

I will have a look later this week to try to fix it....

### Logs
```sh
$ talosctl __complete get
get	Get a specific resource or list of resources (use 'talosctl get rd' to see all available resource types).
:4
Completion ended with directive: ShellCompDirectiveNoFileComp
```

### Environment

- Talos version: 1.3.0
- Kubernetes version:  1.25
- Platform:

**Comment by smira** [comment]
I can look into that, I think the major rewrite came with 1.2.x, but still it's a bug

**Comment by smira** [comment]
Looks like complete function isn't even called when args are empty

**Comment by smira** [comment]
My bad, I found the bug
