### ISSUE TITLE
Kubespan symmetric routing

### ISSUE THREAD

**Issue by sergelogvinov** [siderolabs/talos#6665]
## Bug Report

The problem:
When kubespan is broken, workers nodes are trying to reach the kube-api.
They can send request thought the local net (allowDownPeerBypass: true). But API responses thought kubespan interface (It thinks the link is alive).

This patch uses conntrack to mark the packets incoming thought the local network (not kubespan). And skip them in kubespan route block. (handles: 24,21,22)

I can make the PR, but it make sense after #6647
Also it solve the problem then you have VIP address in local network as LB. You need to exclude the VIP in `kubespan. filters`

```
        chain kubespan_prerouting { # handle 1
                type filter hook prerouting priority 0; policy accept;
                meta mark & 0x00000060 == 0x00000020 accept # handle 11
                ip daddr @kubespan_targets_ipv4 meta mark set meta mark & 0xffffffdf | 0x00000040 accept # handle 13
                ip6 daddr @kubespan_targets_ipv6 meta mark set meta mark & 0xffffffdf | 0x00000040 accept # handle 14
        }

        chain kubespan_outgoing { # handle 2
                type route hook output priority 0; policy accept;
                meta mark set ct mark # handle 24
                meta mark & 0x00000060 == 0x00000020 accept # handle 12
                ip daddr @kubespan_targets_ipv4 meta mark set meta mark & 0xffffffdf | 0x00000040 accept # handle 15
                ip6 daddr @kubespan_targets_ipv6 meta mark set meta mark & 0xffffffdf | 0x00000040 accept # handle 16
        }

        chain kubespan_incoming { # handle 20
                type filter hook input priority 0; policy accept;
                ip saddr @kubespan_targets_ipv4 iifname != "kubespan" meta mark set meta mark & 0xffffffbf | 0x00000020 # handle 21
                ip saddr @kubespan_targets_ipv4 iifname != "kubespan" ct mark set meta mark # handle 22
        }
```

### Environment

- Talos version: master
- Kubernetes version: [`kubectl version --short`]
- Platform:

**Comment by smira** [comment]
why does the control plane node think that worker KubeSpan link is up, while it's down? this is the confusing part
