### ISSUE TITLE
Support configuring container `policy.json`

### ISSUE THREAD

**Issue by james-callahan** [siderolabs/talos#6673]
## Feature Request

I hope talos can allow an admin to only allow e.g. signed images to run on the system.

### Description

Documentation of the config file: https://github.com/containers/image/blob/main/docs/containers-policy.json.5.md

`containers-policy.json` allows an administrator to configure various requirements for images, including if the image is signed by specific keys.

I propose a new machine config field that is essentially written out to `containers-policy.json` on the host.
This would be sufficient for gpg signed images.

As a further/later goal, using `sigstoreSigned` in a policy would require that `use-sigstore-attachments` is set in a `containers-registries` configuration for the repository.

**Comment by james-callahan** [comment]
I didn't realise `containerd` doesn't support `policy.json`. Closing for now (please reopen if there's a way forward!)

**Comment by smira** [comment]
This can be done in Kubernetes with image pre-pull hooks and admission plugins in general.

**Comment by james-callahan** [comment]
> This can be done in Kubernetes with image pre-pull hooks and admission plugins in general.

Not if you also want to have policy enforced for the system images.

**Comment by smira** [comment]
We might add something in Talos for it, but so far the container signing landscape is a bit of a mess with too many competing solutions, and not quite compatible with each other.
