### ISSUE TITLE
DOCKER TLS defect

### ISSUE THREAD

**Issue by kbaegis** [siderolabs/talos#6706]
### Description
Defect: HTTP/HTTPS

### Logs
DOCKER_HOST=tcp://172.21.128.1:2376
DOCKER_TLS_VERIFY=1

talosctl cluster create --name sidero-demo -p 69:69/udp,8081:8081:tcp,51821:51821/udp --workers 0 --config-patch '[{"op": "add", "path": "/cluster/allowSchedulingOnMasters", "value": true}]' --endpoint 172.21.128.1 --with-debug
validating CIDR and reserving IPs
generating PKI and tokens
Error response from daemon: Client sent an HTTP request to an HTTPS server.*

### Environment

- Talos version: v1.3.1
- Kubernetes version: v1.26.0
- Platform: Baremetal

**Comment by smira** [comment]
According to the docker client code, it requires `DOCKER_CERT_PATH` to be set to enable TLS.

https://docs.docker.com/engine/security/protect-access/#client-modes
