### ISSUE TITLE
'talosctl gen config' should include aescbcEncryptionSecret for legacy clusters?

### ISSUE THREAD

**Issue by westnet-paul** [siderolabs/talos#6709]
### Description

When running `talosctl gen config --with-secrets` and providing a `secrets.yaml` file containing both an `aescbcencryptionsecret` and a `secretboxencryptionsecret` value, only the secretbox value is written to the generated config templates.

The problem arises when using `talosctl gen config` to generate fresh node templates for a cluster that was created prior to version 1.3, and may already have AESCBC-encrypted secrets stored.

I think I've identified where the problem arises -- in `pkg/machinery/config/contract.go` if secretbox is supported, no attempt is made to import the AESCBC secret even if it exists. I could be wrong, I'm not that familiar with Go.

### Logs

n/a

### Environment

n/a

**Comment by smira** [comment]
Are you using `--talos-version=v1.2` flag to the `talosctl gen config`? This is the flag which provides backwards compatibility for old versions of Talos when using newer `talosctl`.

**Comment by westnet-paul** [comment]
I am now, and it's working. It was suggested in a Slack discussion that a cluster could use both secretbox and aescbd secrets - the former for newly-created secrets and the latter for legacy, but as things are currently written it's either-or.

If it's by design that a cluster created with aescbc secrets shouldn't ever use secretbox secrets, feel free to close this issue and reject the associated pull request.

**Comment by westnet-paul** [comment]
> To enable secretbox you need to add an encryption secret at cluster.secretboxEncryptionSecret after an upgrade to Talos 1.3. You should keep aescbcEncryptionSecret however, even if secretbox is enabled, older data will still be encrypted with AES-CBC.

That's what prompted the issue. The upgrade notes suggest that I can add secretbox and keep aescbc, but that's not how the code works. If the Talos version is < 1.3, secretbox is ignored; if it's >= 1.3 then aescbc is ignored. It doesn't seem to be the case, at least where `gen config` is concerned, that both encryption types are supported.

**Comment by westnet-paul** [comment]
OK, this can be closed so. You can reject the pull request. Cheers.
