### ISSUE TITLE
update Flannel manifest from upstream

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#6730]
Use e.g. https://github.com/flannel-io/flannel/blob/v0.20.2/Documentation/kube-flannel.yml, and transform it to make it compatible with Talos.

We can have `go generate` step which takes upstream manifest, transforms and generates `.go` file with new manifest.

We should use "our" mirrors of upstream Flannel image and our `install-cni` init container.

Flannel manifest tag should match Flannel version used.

**Comment by rgl** [comment]
shouldn't flannel be upgraded to the latest version too (e.g. https://github.com/flannel-io/flannel/releases/tag/v0.21.3)?

**Comment by frezbo** [comment]
> shouldn't flannel be upgraded to the latest version too (e.g. https://github.com/flannel-io/flannel/releases/tag/v0.21.3)?

https://github.com/siderolabs/talos/pull/6949 it is :smile:
