### ISSUE TITLE
 [talos] controller failed 

### ISSUE THREAD

**Issue by alexkayzer** [siderolabs/talos#6736]
## Bug Report
Log Warning
### Description
After install log warning only on controlplane nodes
### Logs
 [talos] controller failed {"component": "controller-runtime", "controller": "k8s.KubeletStaticPodController", "error": "error refreshing pod status: error fetching pod status: Get \x5c"https://127.0.0.1:10250/pods/?timeout=30s\x5c": remote error: tls: internal error"}
### Environment

- Talos version: [v1.3.0]
- Kubernetes version: [v1.26.0]
- Platform: VMware

**Comment by smira** [comment]
Most probably you enabled kubelet server certificate issuing via API server, but nothing approves the CSRs, so your kubelet doesn't have a server TLS cert.

This is a misconfiguration.

Some docs here describe this case https://www.talos.dev/v1.3/kubernetes-guides/configuration/deploy-metrics-server/
