### ISSUE TITLE
kubelet failed to get rootfs info

### ISSUE THREAD

**Issue by oliverwiegers** [siderolabs/talos#6738]
Thank you for your work.

### Description

When trying to run a Talos OS cluster locally using docker created by `talosctl cluster create` the *kubelet* will not come up. The *kubelet* container lacks access to the host systems disks.
This results in the following error message:

```
10.5.0.2: {"ts":1673642752040.5974,"caller":"kubelet/kubelet.go:1466","msg":"Failed to start ContainerManager","err":"failed to get rootfs info: failed to get mount point for device \"/dev/nvme0n1p2\": no partition info for device \"/dev/nvme0n1p2\""}
```

This is the case for every partition on that drive. In my case they are:

```
/dev/nvme0n1p2 on / type f2fs 
/dev/nvme0n1p1 on /boot/efi type vfat 
```

It does not seem to affect filysystems of every type. When running on a system using *luks* and *ext4* volumes it works just fine. 

The docker container itself has access to the disks:

```
❯ talosctl list -lH -n 10.5.0.2 /dev  | grep nvme
10.5.0.2   Dcrw-------   0      0     0 B       12 hours ago   nvme0
10.5.0.2   Drw-rw----    0      9     0 B       12 hours ago   nvme0n1
10.5.0.2   Drw-rw----    0      9     0 B       12 hours ago   nvme0n1p1
10.5.0.2   Drw-rw----    0      9     0 B       12 hours ago   nvme0n1p2
```

[kind](https://kind.sigs.k8s.io/) had similar issue which is to be solved by mounting the disks into the *kubelet* container (described [here](https://kind.sigs.k8s.io/docs/user/known-issues/#failed-to-get-rootfs-info--stat-failed-on-dev)).

Unfortunately this did not work here. I added the following to the *kubelet* section of the *machineconfig*:

```
        extraMounts:
            - destination: /dev/nvme0n1
              source: /dev/nvme0n1
              options:
                - rslave
``` 

Sadly this results only in the following error:

```
Failed to create runner: mkdir /dev/nvme0n1: not a directory
```

Not sure if this is really a bug or I'm missing something. Any way around this?
Do you need something else from me?

### Logs

Anything else needed here?

### Environment

- Talos version: v1.3.0
- Kubernetes version: v1.26.0
- Platform: x86
- Host  OS: Void Linux
- Docker Version 20.10.22

**Comment by smira** [comment]
If running on Linux, and if you're testing Talos, I would highly recommend using [QEMU](https://www.talos.dev/v1.3/talos-guides/install/local-platforms/qemu/), as it provides full Talos experience, and no need to fight with host-to-container device propagation.

I don't have any exact idea on Docker, I would assume a potential workaround is to hide these blockdevices from the container completely, as `kubelet` doesn't actually need them. Not sure if Docker API allows that, but it's certainly possible with OCI spec. That's my only guess, but I don't have anything to test it with right now.

**Comment by oliverwiegers** [comment]
@smira for the sake of being complete: I haven't found a way to hide block devices inside a privileged docker container.
But to be fair every post I found on problems with f2fs in connection with docker / kubernetes has the same result: Don't use f2fs yet. 

I will take another workstation with ext4 as filesystem and note this as known pitfall.

Thank you, feel free to close the issue. If for documentation purposes useful keep it open :)
