### ISSUE TITLE
upgrade-k8s fails, or hangs, when VIP used as endpoint

### ISSUE THREAD

**Issue by magicite** [siderolabs/talos#6796]
### Description
Trying to use upgrade-k8s on a Sidero Metal-provisioned cluster.  I've got a 3 node cluster with a VIP, all control planes, all allowed to run a workload.  Periodically the command hangs, or fails.  Hitting control-c and re-starting typically allows the upgrade to progress further.

I did some digging, and think this is related to using the VIP as a talos endpoint.  Sidero Metal appears to put the VIP into the talosconfig for the cluster by default.  When I take the VIP out of the talosconfig (or explicitly supply a non-VIP endpoint) it appears to work, so far, 100% of the time.

As an experiment, I watched my client node's ARP cache at the same time as doing an upgrade-k8s.  The moment the VIP moved (from the perspective of the ARP cache), upgrade-k8s hung for at least 10 minutes before I gave up and ctrl-c'ed.

### Logs
Here's an example of a failure related to upgrading a kubelet.  .254 is our VIP for the cluster (seen in the error):
```
[root@dill04 demo (⎈|admin@bolt:default)]# http_proxy= https_proxy= talosctl-1.3.0 --talosconfig bolt_talosconfig -n 172.30.223.151 upgrade-k8s --to 1.26.1
automatically detected the lowest Kubernetes version 1.26.0
checking for resource APIs to be deprecated in version 1.26.1
discovered controlplane nodes ["172.30.223.151" "172.30.223.159" "172.30.223.216"]
Checking for removed Kubernetes component flags
discovered worker nodes []
updating "kube-apiserver" to version "1.26.1"
 > "172.30.223.151": starting update
 > update kube-apiserver: v1.26.0 -> 1.26.1
 > "172.30.223.151": machine configuration patched
 > "172.30.223.151": waiting for kube-apiserver pod update
 < "172.30.223.151": successfully updated
 > "172.30.223.159": starting update
 > update kube-apiserver: v1.26.0 -> 1.26.1
 > "172.30.223.159": machine configuration patched
 > "172.30.223.159": waiting for kube-apiserver pod update
 < "172.30.223.159": successfully updated
 > "172.30.223.216": starting update
 > update kube-apiserver: v1.26.0 -> 1.26.1
 > "172.30.223.216": machine configuration patched
 > "172.30.223.216": waiting for kube-apiserver pod update
 < "172.30.223.216": successfully updated
updating "kube-controller-manager" to version "1.26.1"
 > "172.30.223.151": starting update
 > update kube-controller-manager: v1.26.0 -> 1.26.1
 > "172.30.223.151": machine configuration patched
 > "172.30.223.151": waiting for kube-controller-manager pod update
 < "172.30.223.151": successfully updated
 > "172.30.223.159": starting update
 > update kube-controller-manager: v1.26.0 -> 1.26.1
 > "172.30.223.159": machine configuration patched
 > "172.30.223.159": waiting for kube-controller-manager pod update
 < "172.30.223.159": successfully updated
 > "172.30.223.216": starting update
 > update kube-controller-manager: v1.26.0 -> 1.26.1
 > "172.30.223.216": machine configuration patched
 > "172.30.223.216": waiting for kube-controller-manager pod update
 < "172.30.223.216": successfully updated
updating "kube-scheduler" to version "1.26.1"
 > "172.30.223.151": starting update
 > update kube-scheduler: v1.26.0 -> 1.26.1
 > "172.30.223.151": machine configuration patched
 > "172.30.223.151": waiting for kube-scheduler pod update
 < "172.30.223.151": successfully updated
 > "172.30.223.159": starting update
 > update kube-scheduler: v1.26.0 -> 1.26.1
 > "172.30.223.159": machine configuration patched
 > "172.30.223.159": waiting for kube-scheduler pod update
 < "172.30.223.159": successfully updated
 > "172.30.223.216": starting update
 > update kube-scheduler: v1.26.0 -> 1.26.1
 > "172.30.223.216": machine configuration patched
 > "172.30.223.216": waiting for kube-scheduler pod update
 < "172.30.223.216": successfully updated
updating daemonset "kube-proxy" to version "1.26.1"
updating kubelet to version "1.26.1"
 > "172.30.223.151": starting update
 > update kubelet: 1.26.0 -> 1.26.1
 > "172.30.223.151": machine configuration patched
 > "172.30.223.151": waiting for kubelet restart
 > "172.30.223.151": waiting for node update
 < "172.30.223.151": successfully updated
 > "172.30.223.159": starting update
failed upgrading kubelet: error updating node "172.30.223.159": error fetching kubelet spec: rpc error: code = Unavailable desc = error reading from server: read tcp 172.30.223.27:38084->172.30.223.254:50000: read: connection reset by peer
```

### Environment

- Talos version: 1.3.2
- Kubernetes version: 1.26.0-1.26.1
- Platform: Bare metal

### Extra Commentary
Since this is an otherwise healthy cluster, experiencing upgrade-k8s issues only because the VIP is moving around, it would be nice if talosctl could ride this out a little better.  While it's no big deal to just restart the command, I'd expect to not have to do that in this circumstance.  Maybe sidero metal shouldn't put the VIP into the talosconfig endpoints list?  Maybe talosctl could have default retry behavior?  Maybe talosctl could have a timeout associated with actions before retrying?

**Comment by smira** [comment]
This is unsupported configuration - you're using the VIP for the Talos API endpoint. It's a bad idea for many reasons: https://www.talos.dev/v1.3/introduction/getting-started/#decide-how-to-access-the-talos-api

> Do not use Talos Linux’s built in VIP support for accessing the Talos API, as it will not function in the event of an etcd failure, and you will not be able to access the Talos API to fix things.

Talos VIP was designed for Kubernetes API access only.

Talos API should use the endpoints (IPs) of the control plane nodes. What is happening is that the VIP is moving between the nodes, and that breaks the persistent Talos API connection.
