### ISSUE TITLE
bootstrap fails to complete, problem presents with ntp server access

### ISSUE THREAD

**Issue by 524c** [siderolabs/talos#6818]
## Bug Report
After a fresh install, this error appears in the console.
Apparently the bootstrap can't finish, so I can't get any access to try some troubleshooting.

When trying to access the cluster, this message appears stating that the TLS certificate is invalid:
`rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: remote error: tls: bad certificate"
`
### Description
error executing bootstrap: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:50000: connect: connection refused"

I'm in Brazil, and dns `pool.ntp.org` resolves to this IP `200.160.7.193`, which appears as marked for removal:
https://www.pool.ntp.org/zh/scores/200.160.7.193

I don't see an easy solution to this.

I thought about mounting the image and editing the NTP configuration to another ntp host that is functional in my region. If you can guide me I will try this option.

### Environment

- Talos version: v1.3.2, v1.3.3 and v1.4 alpha 2.
- Kubernetes version: v1.26.1
- Platform: arm64 (rpi)

![talos-ntp-error](https://user-images.githubusercontent.com/527641/216684371-4aa6ca17-064b-465b-bfb0-fe5ddc6312d5.jpeg)

**Comment by rsmitty** [comment]
Hey @524c, hope you're well. Some questions here I guess. Is Talos failing to even get to the point of doing an apply-config? 

If you can at least apply a config, you can set the ntp servers manually via [this](https://www.talos.dev/v1.3/reference/configuration/#timeconfig) section of the machine config.

If not, you can specify a single NTP server in the kernel args (hit `e` at grub boot and add to the list of args). See [this](https://www.talos.dev/v1.3/reference/kernel/#ip) for an example that sets DNS and NTP, but you can just leave the DNS ones empty (`ip=:::::::::<ntp0-ip>`).

**Comment by 524c** [comment]
Hey @rsmitty, I'm fine and how are you? 😁

I can't do an apply-config.

I've tried it several times and with the last 3 versions available and with all of them it seems that setup/bootstrap doesn't finish successfully, so I have a broken install. I'm starting now with Talos, so I don't know if NTP is vital for the bootstrap.

I recorded my screen in error. Take a look, please.

https://user-images.githubusercontent.com/527641/216726821-1eafd6c3-5dde-43e0-b9c7-0b58df04166f.mp4

**Comment by 524c** [comment]
Hey @rsmitty, I'm fine and how are you? 😁

I can't do an apply-config.

I've tried it several times and with the last 3 versions available and with all of them it seems that setup/bootstrap doesn't finish successfully, so I have a broken install. I'm starting now with Talos, so I don't know if NTP is vital for the bootstrap.

I recorded my screen in error. Take a look, please.


https://user-images.githubusercontent.com/527641/216727829-b3e66217-068d-4853-bda2-54ad50c6e7dc.mp4

**Comment by rsmitty** [comment]
looks like, from the video, you're already at the point that you've applied a config previously (and then overwrote your configs with the new `gen` command). you'll want to do something like this:

- wipe the sdcard and reflash with the rpi image
- boot the image and wait for it to get into maintenance mode
- gen your configs
- update the controlplane.yaml to include the ntp settings I mentioned earlier
- apply the config
- hopefully profit?

**Comment by rsmitty** [comment]
also, the talosconfig sets 127.0.0.1 as the default endpoint. so after applying the config you'll want to do something like `talosctl config endpoint <ip>` to update that to the rpi's IP.

**Comment by 524c** [comment]
> * wipe the sdcard and reflash with the rpi image
> * boot the image and wait for it to get into maintenance mode
> * gen your configs
> * update the controlplane.yaml to include the ntp settings I mentioned earlier
> * apply the config
> * hopefully profit?



> looks like, from the video, you're already at the point that you've applied a config previously (and then overwrote your configs with the new `gen` command). you'll want to do something like this:
> 
> * wipe the sdcard and reflash with the rpi image
> * boot the image and wait for it to get into maintenance mode
> * gen your configs
> * update the controlplane.yaml to include the ntp settings I mentioned earlier
> * apply the config
> * hopefully profit?

Thank you for your help. I'm going to try these things tomorrow morning and come back here to tell you if I was successful.
I'm really excited about Talos, and hope to get to use it soon 🚀

**Comment by 524c** [comment]
> also, the talosconfig sets 127.0.0.1 as the default endpoint. so after applying the config you'll want to do something like `talosctl config endpoint <ip>` to update that to the rpi's IP.

Yes it's true. I forgot to edit during the video. But during my tests I remembered this and it also fails.

**Comment by 524c** [comment]
More logs, after fix config server address:
`❯ talosctl --nodes 192.168.1.4 apply-config --file controlplane.yaml`
output:
error applying new configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid: current time 2023-02-03T20:26:48-03:00 is after 1970-01-02T00:21:13Z"


`❯ talosctl --nodes 192.168.1.4 apply-config --insecure --file controlplane.yaml`
output:
error applying new configuration: rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: remote error: tls: bad certificate"

**Comment by sanmai-NL** [comment]
Can you set the time on the system you use to generate the certificate, e.g. in the BIOS?

You can tweak the Talos Linux machine config with this `talosctl gen config` `--config-patch` to use a different pool of NTP servers:

```json
[{"op": "add", "path": "/machine/time", "value": {"disabled": false}},
{"op": "add", "path": "/machine/time/servers", "value": ["2.europe.pool.ntp.org"]}]

**Comment by 524c** [comment]
Hey @rsmitty,

I was able to bootstrap by following these steps that you gave me before, thanks! 🎉😁. By interactive mode I can't, so it seems to be a problem with a dead ntp.

I had some difficulty with issues related to the default security policy, but I managed to solve it by following this doc:
https://www.talos.dev/v1.3/kubernetes-guides/configuration/pod-security/

Even so, when creating new pods, after applying a label that changes the default `baseline` policy to `privileged`, alerts continue to appear. Is there a way to turn these alerts off? or should I adjust with some additional configuration to not display these messages?

I used this command:
`kubectl label ns default pod-security.kubernetes.io/enforce=privileged`

I don't know what you think about the NTP question, if something should be done, if it's a bug... should I close the issue?

ps.: I only have a few hours of use, but I've noticed that the cluster responds much faster to my commands. My perception is that it is faster compared to k3s 🚀

**Comment by sanmai-NL** [comment]
> Hey @rsmitty,
> 
> 
> 
> I was able to bootstrap by following these steps that you gave me before, thanks! 🎉😁. By interactive mode I can't, so it seems to be a problem with a dead ntp.
> 
> 
> 
> I had some difficulty with issues related to the default security policy, but I managed to solve it by following this doc:
> 
> https://www.talos.dev/v1.3/kubernetes-guides/configuration/pod-security/
> 
> 
> 
> Even so, when creating new pods, after applying a label that changes the default `baseline` policy to `privileged`, alerts continue to appear. Is there a way to turn these alerts off? or should I adjust with some additional configuration to not display these messages?
> 
> `"Warning:" would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "ubuntu" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "ubuntu" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "ubuntu" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "ubuntu" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")`
> 
> 
> 
> I used this command:
> 
> `kubectl label ns default pod-security.kubernetes.io/enforce=privileged`
> 
> 
> 
> I don't know what you think about the NTP question, if something should be done, if it's a bug... should I close the issue?
> 
> 
> 
> ps.: I only have a few hours of use, but I've noticed that the cluster responds much faster to my commands. My perception is that it is faster compared to k3s 🚀

@524c There's a community Slack with various channels. It's better to use that for other questions. That'd reduce the pressure on the developers and keep the issue tracker more on-topic.

**Comment by smira** [comment]
> Even so, when creating new pods, after applying a label that changes the default `baseline` policy to `privileged`, alerts continue to appear. Is there a way to turn these alerts off? or should I adjust with some additional configuration to not display these messages?

[Documentation](https://www.talos.dev/v1.3/kubernetes-guides/configuration/pod-security/) talks about different levels, you're looking around `audit` level, this level policy generates warnings.
