### ISSUE TITLE
DNS search domains missing

### ISSUE THREAD

**Issue by james-callahan** [siderolabs/talos#6825]
### Description

From a pod, I can lookup `foo.namespace.svc.cluster.local`, but `foo.namespace.svc` doesn't resolve.

I'm not seeing the expected kubernetes DNS search path(s) set anywhere.
Looking at a pod's `/etc/resolv.conf`, I get e.g.
```
search ec2.internal
nameserver 10.0.0.10
options ndots:5
```

Which I think is rendered by https://github.com/siderolabs/talos/blob/82e8c9e1f63371f41b0794b4c1be3209847c5f8b/internal/app/machined/pkg/controllers/network/etcfile.go#L175

Shouldn't the first line of my resolv.conf be e.g.
```
search MYNAMESPACE.svc.cluster.local svc.cluster.local cluster.local ec2.internal
```

The kubernetes documentation has a sample at https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#check-the-local-dns-configuration-first

### Environment

- Talos version: 1.3.3
- Kubernetes version: 1.26.0
- Platform:

**Comment by smira** [comment]
Talos only renders the host `/etc/resolv.conf`, while in a pod `/etc/resolv.conf` is managed by Kubernetes (`kubelet`) and depends on your pod spec. Under normal circumstances it should include both `search` and `nameserver` pointing to service IP of `kube-dns` (CoreDNS).

**Comment by james-callahan** [comment]
> while in a pod `/etc/resolv.conf` is managed by Kubernetes (`kubelet`) and depends on your pod spec.

There's nothing odd about my podspec here. And infact I was able to replicate with the example one from the documentation I linked earlier (https://k8s.io/examples/admin/dns/dnsutils.yaml).

Perhaps there is some argument to kubelet that isn't right?

**Comment by james-callahan** [comment]
> Perhaps there is some argument to kubelet that isn't right?

`--cluster-domain`  
![image](https://user-images.githubusercontent.com/35791147/217224276-a2327924-7d2b-42eb-a168-6f035d8419b1.png)

or [`ClusterDomain`](https://github.com/siderolabs/talos/blob/96aa9638f724d81ba8ef64db0ed7032694e7da5d/pkg/machinery/resources/k8s/kubelet_config.go#L32) seem to be relevant here

I'm going to take a guess and say that similar to https://github.com/siderolabs/talos/issues/6824 there is a problem when the default `dnsDomain` or `cluster.local` is not passed as the `ClusterDomain`.

**Comment by smira** [comment]
this is what it expected to look like:

```
/ # cat /etc/resolv.conf 
search ci.svc.cluster.local svc.cluster.local cluster.local
nameserver 192.168.128.10
options ndots:5
```

I'm not sure about your configuration, but this is how it should like with more or less default config (Serrvice CIDR is different)

**Comment by james-callahan** [comment]
> I'm not sure about your configuration, but this is how it should like with more or less default config (Serrvice CIDR is different)

It does not look like that; as I put in the first post, it looks like:
```
search ec2.internal
nameserver 10.0.0.10
options ndots:5
```

It seems as though if you don't specify a `dnsDomain` in your cluster config then you get that.
This is a bug in talos that a missing/null `dnsDomain` doesn't coerce to `cluster.local` as it should. i.e. https://github.com/siderolabs/talos/pull/6628 was incomplete.

By setting `dnsDomain` to `cluster.local` and rebooting the nodes I was able to get the expected resolv.conf of:
```
search default.svc.cluster.local svc.cluster.local cluster.local ec2.internal
nameserver 10.0.0.10
options ndots:5
```

**Comment by smira** [comment]
Ok, thank you, I'll take a look. It should have been set to the default
