### ISSUE TITLE
interactive console: clean up the `talosctl dashboard` code

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#6841]
1. refactor existing code (TUI, data collection)
2. extract as a separate package usable in `talosctl` and in Talos itself

**Comment by rsmitty** [comment]
Wanted to add (hope this is the right issue), but can we add the UUID of the machine to the console view?

**Comment by utkuozdemir** [comment]
> Wanted to add (hope this is the right issue), but can we add the UUID of the machine to the console view?

Sure, this is the right issue for the time being.

**Comment by utkuozdemir** [comment]
Done in [f55f5df7396b7073e75267c7e10a35814f1185c9](https://github.com/siderolabs/talos/pull/6879)

Continuation in https://github.com/siderolabs/talos/issues/6752
