### ISSUE TITLE
talosctl upgrade and node labels

### ISSUE THREAD

**Issue by sergelogvinov** [siderolabs/talos#6862]
## Feature Request

Upgrade the nodes by node label.

```shell
talosctl upgrade -l topology.kubernetes.io/region=hel1
```

### Description

Kubectl has label selector `kubectl delete po -l labelname=value`.
This method can help safely upgrade your the cluster by group (type of nodes).

**Comment by smira** [comment]
I think `talosctl` shouldn't depend on Kubernetes API directly this way.

Also `talosctl upgrade` at the moment doesn't do any kind of one-by-one upgrades, so if multiple nodes are specified, `talosctl` upgrades them all at the same time.

So it might be way easier for now to a script around it, using `kubectl` to get IPs of the nodes to be upgrade, and upgrade each one using `talosctl`.
