### ISSUE TITLE
talosctl gives rpc error: code = PermissionDenied

### ISSUE THREAD

**Issue by jeka** [siderolabs/talos#6864]
### Description
I am following the guide for deploying talos with Vagrant & Libvirt. The difference is that I am using 1 controller+2 worker nodes and UEFI boot.

I followed the exact steps listed on the page (starting from scratch several times in fact ).
In the end while k8s cluster is reported as ready and is working fine with basic tests, I have problems with issuing talosctl against the nodes (any of them):
For example 4 consecutive executions:
```
[jekov@nuc talos-k8s]$ pwd
/home/jekov/vagrant/talos-k8s
[jekov@nuc talos-k8s]$ echo $TALOSCONFIG
/home/jekov/vagrant/talos-k8s/talosconfig

$ talosctl -n 192.168.192.156 get mc
rpc error: code = PermissionDenied desc = no request forwarding

$ talosctl -n 192.168.192.156 get mc
NODE              NAMESPACE   TYPE            ID         VERSION
192.168.192.156   config      MachineConfig   v1alpha1   1

$ talosctl -n 192.168.192.156 get mc
NODE              NAMESPACE   TYPE            ID         VERSION
192.168.192.156   config      MachineConfig   v1alpha1   1

$ talosctl -n 192.168.192.156 get mc
NODE   NAMESPACE   TYPE   ID   VERSION
1 error occurred:
        * rpc error: code = PermissionDenied desc = no request forwarding
```

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
```
$ talosctl version -n 192.168.192.161
Client:
        Tag:         v1.3.4
        SHA:         ea4ae335
        Built:
        Go version:  go1.19.4
        OS/Arch:     linux/amd64
Server:
error getting version: rpc error: code = PermissionDenied desc = no request forwarding

$ talosctl version -n 192.168.192.161
Client:
        Tag:         v1.3.4
        SHA:         ea4ae335
        Built:
        Go version:  go1.19.4
        OS/Arch:     linux/amd64
Server:
        NODE:        192.168.192.161
        Tag:         v1.3.4
        SHA:         ea4ae335
        Built:
        Go version:  go1.19.4
        OS/Arch:     linux/amd64
        Enabled:     RBAC
```
- Kubernetes version: [`kubectl version --short`]
```
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.26.1
```
- Platform:
```
$ sudo virsh version
Compiled against library: libvirt 8.0.0
Using library: libvirt 8.0.0
Using API: QEMU 8.0.0
Running hypervisor: QEMU 6.2.0
```
Host OS: CentOS Stream 8

```
$ sudo virsh list | grep talos | awk '{print $2}' | xargs -t -L1 sudo virsh domifaddr
sudo virsh domifaddr talos-k8s_worker-node-2
 Name       MAC address          Protocol     Address
-------------------------------------------------------------------------------
 vnet30     52:54:00:71:d0:5a    ipv4         192.168.192.216/24

sudo virsh domifaddr talos-k8s_worker-node-1
 Name       MAC address          Protocol     Address
-------------------------------------------------------------------------------
 vnet31     52:54:00:27:0d:69    ipv4         192.168.192.156/24

sudo virsh domifaddr talos-k8s_control-node
 Name       MAC address          Protocol     Address
-------------------------------------------------------------------------------
 vnet32     52:54:00:a1:1b:9f    ipv4         192.168.192.161/24
```
[controlplane-no-comments.yaml.txt](https://github.com/siderolabs/talos/files/10776969/controlplane-no-comments.yaml.txt)
[worker-no-comments.yaml.txt](https://github.com/siderolabs/talos/files/10776972/worker-no-comments.yaml.txt)
[talosconfig.txt](https://github.com/siderolabs/talos/files/10776970/talosconfig.txt)
[Vagrantfile.txt](https://github.com/siderolabs/talos/files/10776971/Vagrantfile.txt)

**Comment by smira** [comment]
Looking at the errors above, most probably you're trying to use worker nodes as `endpoints` in the `talosconfig`. Endpoints can only be controlplane nodes, worker nodes can't forward requests to other nodes.

So in general, endpoints should only be controlplane nodes - these should be specified in the `talosconfig`.

> Note: If needed, you can access the worker node directly bypassing the controlplane endpoint: `taloctl -e <WORKER> -n <WORKER> ...`

**Comment by jeka** [comment]
@smira Tanks for the update.
As I mentioned I was following the  Vagrant & Libvirt guide, and on that page clearly, all the nodes are passed to talosctl
```
export TALOSCONFIG=$(realpath ./talosconfig)
talosctl config endpoint 192.168.121.203 192.168.121.119 192.168.121.125 192.168.121.69
```
4 nodes (3 controllers + 1 worker)

**Comment by smira** [comment]
I don't know what exactly that guide is, but that part is wrong.

https://www.talos.dev/v1.3/introduction/getting-started/#understand-talosctl-endpoints-and-nodes

**Comment by jeka** [comment]
@smira  Its part of Talos dicumentation
https://www.talos.dev/v1.3/talos-guides/install/virtualized-platforms/vagrant-libvirt/
Also,  **contolplane.yaml**  snipped is wrong. There is no **spec:** in generated YAML file
