### ISSUE TITLE
ISO image installs on disk, Metal image doesn't 

### ISSUE THREAD

**Issue by Dzeri96** [siderolabs/talos#6865]
## Bug Report
This issue has a corresponding [matrix thread](https://matrix.to/#/!AhUnkatMeayVVxZprp:matrix.org/$2RkRyWtsJebsyrtvYkQpShAnZUvCpYSUEGfGAAWh_ZU?via=matrix.org&via=davralin.work) that describes the entire debugging process. Please refer to it if something is unclear.

### Description
I'm playing around with Omni, trying to set up a fresh cluster, and I was having difficulties installing Talos on the machine's internal hard drive. There were at least two problems identified. The one not explained in this thread is the installer picking the wrong disk even though the selector is supplied and the disk is mounted properly. I might open another issue on that.

In this one, however, I want to focus on the differences between the `metal-amd64-v1.3.3-omni-user.tar.gz` and `talos-amd64-v1.3.3-omni-user.iso` images. The former seems to think that Talos is already installed on the target disk, and simply prints `apply config request: mode auto(no_reboot)` in the logs without doing anything. On the other hand, the ISO image actually installs (ignoring the disk selection issue).
I've tried using both the simple disk path, and different `diskSelector`s to no avail.
If it's of any relevancy, the disk originally had another Linux system on it, however the installation did not go through even when the partition table was removed. I also set `wipe` to false.

### Logs

Nothing except `apply config request: mode auto(no_reboot)` when the install config changes. The disk is detected and mounted at boot under `/dev/sda`.

### Environment
Disclaimer: Ran AFTER a successful installation

Talos version: 
```
talosctl version --nodes 3e1a07d0-0e85-11e5-bd7c-14dda9078c3e
Client:
        Tag:         v1.3.4
        SHA:         ea4ae335
        Built:       
        Go version:  go1.19.4
        OS/Arch:     linux/amd64
Server:
error getting version: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.5.0.2:50000: i/o timeout"
```

Kubernetes version: ```
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.26.1
```
Platform: Omni

**Comment by frezbo** [comment]
yes, that's expected behavior, the metal images are already pre-installed with talos, changing the install disk will have no effect, since talos is already installed on the media

**Comment by Dzeri96** [comment]
Can I ask where this is documented? Even people in the matrix support channel did not know about it.

**Comment by smira** [comment]
Please feel free to open PR to improve the documentation, it's never perfect. Any Talos image implies that Talos is already installed (that's what the image is).

Any other boot method (ISO, PXE, ...) requires Talos to be installed, as Talos is not installed to the disk yet.

**Comment by Dzeri96** [comment]
@smira I will start working on a PR regarding the documentation. I guess the term _image_ is what creates confusion. An ISO literally represents a disk image, so when you say Talos image, it's not quite clear what the difference between an x86 ISO, and an x86 metal image is.

To make sure we're on the same page, could you suggest a surefire way for users to identify images that respect the `install` config? If not, at least a list of image types where this does work.

Furthermore, the Omni UI should also be able to disambiguate non-installable vs. installable images when creating a cluster. Currently it always offers an installation disk even though the image does not support installation. I'm sure you can see how this will confuse many users. Maybe there is an API that can check if the system currently running sees itself as already installed?

**Comment by smira** [comment]
Yes, I agree it's confusing. For Talos installed state means that there is a system disk (blockdevice) with a Talos partition table. All disk images are built that way.

ISO is not a disk image, it just contains Talos boot assets, same as PXE booting.

Install disk is not required, that is correct, and it's a limitation of Talos at the moment that it requires specifying it even if Talos is already installed.

We are going to address this confusion in the future version of Talos.
