### ISSUE TITLE
Get `certificate-authority-data` for kubeconfig without getting full kubeconfig

### ISSUE THREAD

**Issue by flokli** [siderolabs/talos#6874]
I'm using a custom `kubeconfig` that's using `kubectl oidc-login` to log into the cluster, so I don't need the Talos-provided kubeconfig.

This means, I'm rendering my own kubeconfig file.

I however still need the CA certificate that's used to sign ssl certs for kube-apiserver.

I currently have to extract this by manually yamldecoding the output and descending into various fields to end up at the ca certificate:

```hcl
# Hacky! Use this to extract the certificate-authority-data only.
# Is there a nicer way?
resource "talos_cluster_kubeconfig" "talos_kubeconfig" {
  talos_config = talos_client_configuration.talosconfig.talos_config
  endpoint = local.cluster_endpoint
  node = local.cluster_endpoint
}

resource "local_file" "kubeconfig" {
  filename = "${path.module}/kubeconfig"
  file_permission = "0644"
  content = yamlencode({
    "apiVersion": "v1",
    "kind": "Config",
    "clusters": [{
      "name" : local.environment,
      "cluster": {
        "server" : "https://${local.cluster_endpoint}:6443",
        "certificate-authority-data": yamldecode(talos_cluster_kubeconfig.talos_kubeconfig.kube_config)["clusters"][0]["cluster"]["certificate-authority-data"],
      }
    }],
    "contexts" : [{
      "name": local.environment,
      "context":  {
        "cluster": local.environment,
        "user": "oidc",
      }
    }],
    "current-context": local.environment,
    "users": [{
      "name": "oidc",
      user: {
        "exec": {
          "apiVersion": "client.authentication.k8s.io/v1beta1",
          "command": "kubectl",
          "args": [
            "oidc-login",
            "get-token",
            "--oidc-use-pkce",
            "--oidc-extra-scope=profile,email,groups",
            "--oidc-client-id=kubeapi-somewhere",
            "--oidc-issuer-url=https://my-issuer-url.test"
          ]
        }
      }
    }]
  })
}
```

One fix would probably to update the `talos_cluster_kubeconfig` resource to expose the CA certificate, or add this in another resource.

This is somewhat related to https://github.com/siderolabs/terraform-provider-talos/issues/47, but that one handles client keys and client certs as well.

**Comment by smira** [comment]
I think a proper way would be to provide access to Talos resources, as they contain this information separated out and nicely parsed. Not sure how it would map to TF, but seems logical.

**Comment by flokli** [comment]
I don't think that's the right fix for the issue. The issue description already describes a way to extract the CA certificate, purely from terraform:

>         "certificate-authority-data": yamldecode(talos_cluster_kubeconfig.talos_kubeconfig.kube_config)["clusters"][0]["cluster"]["certificate-authority-data"],

The problem is it's quite hacky, because it parses the yaml, rather than being able to access the CA certificate as a raw terraform resource output.

The proposed fix is more hacky - it requires running another command, rather than doing everything in terraform, so less desirable. It requires using `talos_client_configuration.talosconfig.talos_config` to write out a `talosconfig` file to disk, containing sensitive key material, and then manually invoke `talosctl` to get the CA crt.

---

I initially linked to the related issue https://github.com/siderolabs/terraform-provider-talos/issues/47, which asked for some of these attributes:

> So i am wondering if there is a better way which i am are missing or if talos_cluster_kubeconfig may should be extended to directly provide host, cluster_ca_certificate, client_certificate and client_key.

It got marked as closed by https://github.com/siderolabs/terraform-provider-talos/pull/65.

Looking at the docs since then, it looks like [`talos_machine_secrets` now exposes a `ca_certificate` output](https://github.com/siderolabs/terraform-provider-talos/blob/main/docs/resources/machine_secrets.md#nested-schema-for-client_configuration). Should this be the fix you meant to propose instead?

**Comment by frezbo** [comment]
> Looking at the docs since then, it looks like [talos_machine_secrets now exposes a ca_certificate output](https://github.com/siderolabs/terraform-provider-talos/blob/main/docs/resources/machine_secrets.md#nested-schema-for-client_configuration). Should this be the fix you meant to propose instead?

correct, the new `talos_cluster_kubeconfig` data resource have a nested k8s output, planning to release an v0.2 alpha of the tf provider this week

**Comment by flokli** [comment]
I tested with v0.2 alpha.

It looks like it must be `talos_machine_secrets.this.client_configuration["ca_certificate"]` though, not `data.talos_cluster_kubeconfig.this.kubernetes_client_configuration.ca_certificate` - the latter seems to be ed25519, [even when not making a stupid mistake of recreating secrets](https://github.com/siderolabs/terraform-provider-talos/issues/70#issuecomment-1503600427)…

**Comment by frezbo** [comment]
all talos certs should be ed25519 though

**Comment by flokli** [comment]
This is `Talos (v1.3.0)` currently, with `v1.27.0-beta.0`. Maybe it was different a while ago?
