### ISSUE TITLE
`talosctl logs` Prints logs from random dead pod

### ISSUE THREAD

**Issue by Gentoli** [siderolabs/talos#6886]
### Description
`talosctl logs` Prints logs from random dead pod when querying a crash looping static pod

Running the same command will give different historical logs (detectable by timestamps). Adding `--tail` or `-f` has the same behaviour. Seems like `-f` also does not stream log after pod restart.

### Logs
Not sure which logs to collect.

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
    ```
  Client:
          Tag:         v1.3.5
          SHA:         03edf8c1
          Built:       
          Go version:  go1.19.6
          OS/Arch:     darwin/amd64
  Server:
          NODE:        192.168.2.205
          Tag:         v1.3.5
          SHA:         03edf8c1
          Built:       
          Go version:  go1.19.6
          OS/Arch:     linux/amd64
          Enabled:     RBAC
  ```
- Kubernetes version: [`kubectl version --short`]
  N/A (playing with kube-apiserver, which is crash looping)
- Platform:
  kubevirt / OKD

**Comment by smira** [comment]
yep, this is a problem right now, and we should fix it.

the workaround is to use `talosctl ls/talosctl read` and get the logs from `/var/log/pods`

**Comment by smira** [comment]
`crictl`
