### ISSUE TITLE
Talosctl secret management

### ISSUE THREAD

**Issue by eaglesemanation** [siderolabs/talos#6892]
## Feature Request
Integrate talosctl with some sort of secret management tool, for example Mozilla's SOPS

### Description
Current implementation of node config prevents it from being stored anywhere publicly, because secrets are being stored among other values. It would be really great to somehow separate all of this data and allow for secrets to be encrypted on store. There is already a tool that allows to do that, maybe it could be somehow upstreamed: https://github.com/budimanjojo/talhelper

**Comment by frezbo** [comment]
The talos cli already allows that, `talosctl gen secrets`, as far as sops is concerned it seems to be not actively maintained https://github.com/mozilla/sops/discussions/927

**Comment by eaglesemanation** [comment]
Correct me if I'm wrong, but even though `gen secrets` generates a separate file, it still requires to then use `gen config --with-secrets` which embeds all secret values into config. I wanted some way to keep secrets and config separate.

**Comment by frezbo** [comment]
correct, you don;t need to store the config at all, it can be generated on the fly and applied to the nodes, config is something that should be considered ephemeral

**Comment by eaglesemanation** [comment]
Is it really though? I kinda see your point, and I'll probably readjust how I want to structure my config, but I found this use case for talhelper and it kind of made sense to me: https://github.com/bjw-s/home-ops/blob/main/infrastructure/talos/cluster-0/talconfig.yaml.
This config is a bit more involved than the default configuration that talosctl generates, and I think it would be helpful to store that stuff, rather than recreating it from scratch in case of catastrophic hardware failure.

**Comment by eaglesemanation** [comment]
Just understood that all of relevant config could be stored as a patch and then just applied during bootstrap, I should've read "Getting started" more carefully. I think this request can be closed

**Comment by frezbo** [comment]
> Just understood that all of relevant config could be stored as a patch

apologies, assumed this was already the case

Yes, patches only needs to be stored
