### ISSUE TITLE
ARM64 Azure Image Doesn't Work

### ISSUE THREAD

**Issue by rsmitty** [siderolabs/talos#6921]
It appears that something is up with our Azure image for ARM64. Upon downloading the asset from a release, you can upload the VHD to blob storage and create an image from it. However, if you go to create a VM from said image, Azure thinks it's x86:

![image](https://user-images.githubusercontent.com/1529818/223204310-b1975e0b-8000-4a2f-92d6-a25a55393b08.png)

We know our ARM images actually work in other places, so I'm not sure that it's that the image itself is broken. Instead it feels more likely that some metadata is missing from the VHD or something. Maybe caused by not having proper options when we call `qemu-img convert` under the hood [here](https://github.com/siderolabs/talos/blob/main/cmd/installer/cmd/image.go#L127)? Googling for a bit hasn't returned anything useful for me yet.

**Comment by sergelogvinov** [comment]
Hi, try `gen2` instance type.
Or you can use this instruction - https://github.com/sergelogvinov/terraform-talos/tree/main/azure/images

**Comment by smira** [comment]
thanks @sergelogvinov!
