### ISSUE TITLE
HTTP proxy variables for kernel arguments

### ISSUE THREAD

**Issue by alexandrem** [siderolabs/talos#6984]
## Feature Request

It would be helpful to add extra kernel command-line arguments so that Talos Linux is able to use an http proxy at the boot process before obtaining the `talos.config` content and before the network is configured.

Potentially, the variables could be named `http_proxy` and `https_proxy`.

### Description

In most of our environments egress capabilities are restricted, particularly during machine provisioning, where the out-of-band network that is used to fetch the boot artifact and boot the machine, also prevents communication to the outside world. It's not possible to reach out to any external http services, whether on the internet or even outside of the server failure domain.

We currently have to store the talos config content on a static file server located in the same network where the machine is located. To use Omni, it means having a L4 proxy server located in that environment that will proxy the requests towards the Omni endpoint, which we have to deploy in each failure domain.

**Comment by smira** [comment]
So in general machine configuration can be split into two parts:

* one part applies to the machine in any phase - network config, environment variables, registry mirrors, etc.
* another part (bigger one) which makes sense only if the machine is part of the cluster - CAs, cluster ID, role, Kubernetes configuration, etcd version, etc.

With multi-doc we can make the first part always available with the node, no matter which phase is runs.

**Comment by smira** [comment]
VLAN/bonding is available via kernel args, and I assume after that you could use `talos.config=` or use `apply-config` to provide  other bits

**Comment by alexandrem** [comment]
Well we can probably do something with `machine.install.extraKernelArgs` in this intermediary phase and trigger a reboot, but we're kind of breaking the zero-touch configuration workflow.

**Comment by smira** [comment]
we need to consider these ideas more, in case of Omni we could use other feature to provide initial network configuraiton in the Omni image, and this might probably include HTTP proxies as well. 

Talos 1.4 will have an option to provide `metal` network config pre-baked into the image

**Comment by smira** [comment]
We don't have any documentation yet, it's not planned yet, and it will come no earlier that Talos 1.5 in Q3.
