### ISSUE TITLE
small fixes to the vtty dashboard

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#6992]
1. In maintenance mode it shows no addresses, probably because it filters out k8s addresses, but at this point it doesn't make sense:

![image](https://user-images.githubusercontent.com/55211/227224293-906eaa92-5e78-4c62-9fa6-bcfb6ce348a2.png)

2. The hostname is not shown (see above).
3. When entering/leaving the network config screen the state is not reset - e.g. the focused element should be the first one after `Save`? Should we switch back to 'Monitor' after save?

**Comment by andrewrynhard** [comment]
> 1. In maintenance mode it shows no addresses, probably because it filters out k8s addresses, but at this point it doesn't make sense:
> 
> 
> ![image](https://user-images.githubusercontent.com/55211/227224293-906eaa92-5e78-4c62-9fa6-bcfb6ce348a2.png)
> 
>     2. The hostname is not shown (see above).
> 
>     3. When entering/leaving the network config screen the state is not reset - e.g. the focused element should be the first one after `Save`? Should we switch back to 'Monitor' after save?

for 3, I feel we should go back to summary. That is where the active networking status is.

**Comment by andrewrynhard** [comment]
I'm also seeing this:

<img width="260" alt="Screen Shot 2023-03-24 at 1 07 41 PM" src="https://user-images.githubusercontent.com/3383143/227628733-23e7037d-a82a-4c2f-a99f-0a9f63c82230.png">
<img width="256" alt="Screen Shot 2023-03-24 at 1 07 52 PM" src="https://user-images.githubusercontent.com/3383143/227628736-a9d27fb6-adda-40e1-b7ea-310eb1d69477.png">

**Comment by smira** [comment]
* `Shift+Tab` doesn't go back
* show all physical links on network config tab, not all up links
