### ISSUE TITLE
Talos shall support upgrades without pulling image at the upgrade phase

### ISSUE THREAD

**Issue by salkin** [siderolabs/talos#7000]
## Feature Request
Provide support for giving "no pull" option to upgrade command, to minimize upgrade downtime. Today Talos is always pulling the image in upgrades.

### Description

In Edge environments that are backed by satellite link the download speed towards internet may be extremly slow, which prolongs the outage time. When a talos upgrade is triggered via staged upgrade it should be possible to do the upgrade without pulling the image. 

A background client would have pulled the image into the system containerd namespace before the it triggers the upgrade.

**Comment by smira** [comment]
To clarify - this is specific to staged upgrade mode (non-default), in the non-staged upgrade, the installer container is pulled before the upgrade starts. As images is pulled to containerd running from `tmpfs`, we need to consider how to preserve the image across the reboot for staged upgrade.

**Comment by salkin** [comment]
Agree this is unique case for Edge with single node where staged upgrade is kind of the only viable option to do unattended upgrades

**Comment by stereobutter** [comment]
> the installer container is pulled before the upgrade starts.

IIRC this is only true for the installer image but not for images of system extensions?

**Comment by smira** [comment]
it is same way for both installer image and system extensions
