### ISSUE TITLE
Connection refused: Waiting for service "etcd" to be "up"

### ISSUE THREAD

**Issue by patrickblackjr** [siderolabs/talos#7014]
### Description
It seems like `etcd` is never starting. The logs from `etcd` point to `cri` which say waiting for network. I confirmed the VM has network. It's receiving DNS and IP from DHCP just like all the other VMs in my hypervisor and is pingable from my local machine. Could I get some guidance on troubleshooting this issue? I pulled a full support log if you need additional information.

### Logs
![Google Chrome-pb-p-prox-hypv-01 - Proxmox Virtual Environment-20230327-203422](https://user-images.githubusercontent.com/13282318/228103859-7cf99f0e-bfc6-409e-84b6-24e2adae3b00.png)

etcd.state
```shell
ID       etcd
STATE    Preparing
HEALTH   ?
EVENTS   [Preparing]: Running pre state (5m46s ago)
         [Waiting]: Waiting for service "cri" to be "up" (5m46s ago)
         [Waiting]: Waiting for service "cri" to be "up", time sync, network, etcd spec (5m47s ago)
```
cri.state
```shell 
ID       cri
STATE    Running
HEALTH   OK
EVENTS   [Running]: Health check successful (5m46s ago)
         [Running]: Process Process(["/bin/containerd" "--address" "/run/containerd/containerd.sock" "--config" "/etc/cri/containerd.toml"]) started with PID 1664 (5m47s ago)
         [Preparing]: Creating service runner (5m47s ago)
         [Preparing]: Running pre state (5m47s ago)
         [Waiting]: Waiting for network (5m47s ago)
```
### Environment

- Talos version: v1.3.6
- Platform: ProxMox, linux/amd64

**Comment by patrickblackjr** [comment]
Well, it didn't before but it did this time, ha. Thanks!

**Comment by airdogvan** [comment]
talosctl bootstrap -e $CONTROL_PLANE_IP:6443
error constructing client: failed to create client connection: failed to resolve configuration context: talos config file is empty

Tried without the port # and with, same result.

Config was generated as per docs with 

talosctl gen config talos-vbox-cluster https://$CONTROL_PLANE_IP:6443 --output-dir _out

then:

talosctl apply-config --insecure --nodes $CONTROL_PLANE_IP --file _out/controlplane.yaml

and it's stuck waiting for etcd to be up.

Tried from IP 192.168.1.68 to ($CONTROL_PLANE_IP) 192.168.1.81

Config was generated with the same IP (192.168.1.81) on 192.168.1.68.

**Comment by smira** [comment]
Commenting on closed unrelated issues isn't a good idea, but in your case you might need to add `--talosconfig=talosconfig`.

https://www.talos.dev/v1.4/introduction/getting-started/#default-configuration-file

**Comment by airdogvan** [comment]
talosctl bootstrap --talosconfig=talosconfig
error constructing client: failed to determine endpoints

I might want to add that I'm doing this in virtualbox.  So the source IP (where I issue the talosctl command) is in one vm and the client (controlplane) is in another vm.
As said did exactly what the documentation says for virtualbox implementation, to the letter.
Thanks for the quick feedback, much appreciated even though didn't work :)

**Comment by smira** [comment]
You probably need to read the documentation first: https://www.talos.dev/v1.4/introduction/getting-started/#understand-talosctl-endpoints-and-nodes
