### ISSUE TITLE
Talos does not boot correctly in /32 subnets

### ISSUE THREAD

**Issue by Gottox** [siderolabs/talos#7020]
### Description

I'm using a Hetzner server with Proxmox installed in routed mode as described [here](https://community.hetzner.com/tutorials/install-and-configure-proxmox_ve#example-of-the-guest-configuration-in-routed-setup)

To install Talos, the [documentation](https://www.talos.dev/v1.3/talos-guides/install/virtualized-platforms/proxmox/) describes the `ip=` kernel parameter, that I set according to the screenshot:

![image](https://user-images.githubusercontent.com/1056976/228463040-0cb51a7c-a1db-49ff-b6e6-ddca357ac67d.png)

For the sake of privacy, I removed the IP addresses. Let's take 192.168.0.2 as the IP address of the gateway and 10.0.0.42 as the IP address of the Talos VM.

After booting, the system does not come up and isn't responding to ping. In tcpdump I can only see ARP requests coming from the vm host.

### Logs

![talos_logs](https://user-images.githubusercontent.com/1056976/228463225-2c61d1ab-7105-435f-8aee-e4449c6bf5e3.png)

### Environment

- Talos version: 1.3.6
- Kubernetes version: none, pre-install environment
- Platform: Hetzner/Proxmox

**Comment by Gottox** [comment]
Update: I set the device to eth0, as described in the talos doc and now I get the following log output:

![image](https://user-images.githubusercontent.com/1056976/228465313-b5e69523-e452-435e-b3f9-e27acc6cd886.png)

**Comment by smira** [comment]
You can't have a default gateway outside of the NIC subnet, there needs to be another route to tell Linux where the default gateway is. We can make a workaround for kernel args for it, but in the machine config you would have to be explicit about it.

**Comment by smira** [comment]
Proxmox supports `nocloud`, but not sure how it does routes there: https://www.talos.dev/v1.3/talos-guides/install/cloud-platforms/nocloud/
