### ISSUE TITLE
Kubelet is not healthy on Google Compute Engine with docker

### ISSUE THREAD

**Issue by GuillaumeMorini** [siderolabs/talos#7035]
## Bug Report

I have tried to deploy a local cluster on a Google Compute Engine instance.
Kubelet is not starting properly on the controlplane, blocking the whole cluster 

### Description

Deployed on a Ubuntu 20.04 instance with 4 vCPUs and 16 GB of RAM and 32 GB of disk

### Logs

$ talosctl -n 10.5.0.2 service
NODE       SERVICE      STATE     HEALTH   LAST CHANGE   LAST EVENT
10.5.0.2   apid         Running   OK       12m18s ago    Health check successful
10.5.0.2   containerd   Running   OK       12m19s ago    Health check successful
10.5.0.2   cri          Running   OK       12m18s ago    Health check successful
10.5.0.2   etcd         Running   OK       12m7s ago     Health check successful
10.5.0.2   kubelet      Running   Fail     12m2s ago     Health check failed: Get "http://127.0.0.1:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused
10.5.0.2   machined     Running   OK       12m19s ago    Health check successful
10.5.0.2   trustd       Running   OK       12m18s ago    Health check successful

$ talosctl -n 10.5.0.2 containers
NODE       NAMESPACE   ID       IMAGE   PID   STATUS
10.5.0.2   system      apid             94    RUNNING
10.5.0.2   system      trustd           95    RUNNING
$ talosctl -n 10.5.0.2 containers -k
NODE   NAMESPACE   ID   IMAGE   PID   STATUS
$ 

Perhaps linked to issue to get certificates to start the kubelet 

10.5.0.2: {"ts":1680267517615.603,"caller":"certificate/transport.go:112","msg":"No valid client certificate is found but the server is not responsive. A restart may be necessary to retrieve new initial credentials.","lastCertificateAvailabilityTime":1680267517615.6106,"shutdownThreshold":"5m0s"}

### Environment

$ talosctl version --nodes 10.5.0.2
Client:
	Tag:         v1.3.6
	SHA:         5b6176d8
	Built:       
	Go version:  go1.19.7
	OS/Arch:     linux/amd64
Server:
	NODE:        10.5.0.2
	Tag:         v1.3.6
	SHA:         5b6176d8
	Built:       
	Go version:  go1.19.7
	OS/Arch:     linux/amd64
	Enabled:     RBAC

[support.zip](https://github.com/siderolabs/talos/files/11122024/support.zip)

**Comment by smira** [comment]
From what it seems, `kubelet` doesn't run the static pods for the controlplane, and the reason is not clear for me. Talos provided the list of static pods via the internal webserver. 

As the static pods don't run, there's no controlplane, and kubelet complains about it, but it should run the static pods still.

If running on Linux, I would recommend trying Talos on QEMU: https://www.talos.dev/v1.3/talos-guides/install/local-platforms/qemu/

**Comment by GuillaumeMorini** [comment]
Thanks for your reply.
Unfortunately, QEMU will require nested virtualisation which is complex to implement and will degrade the performance of the instance. Still investigating on my side. Perhaps some issues with MTU/fragmentation or firewall that blocks some traffic to the certificates or the pod list

**Comment by GuillaumeMorini** [comment]
I have seen the following errors in cri logs

10.5.0.2: {"error":"rpc error: code = Unknown desc = connection error: desc = \"transport is closing\"","expected":"sha256:0337b2960746fc98ebaf15f10b5c3907909ce686f52eae2877798909c2a6884c","level":"error","msg":"(*service).Write failed","ref":"layer-sha256:0337b2960746fc98ebaf15f10b5c3907909ce686f52eae2877798909c2a6884c","time":"2023-03-31T13:59:41.702520440Z","total":7813456}
10.5.0.2: {"error":"rpc error: code = Unknown desc = connection error: desc = \"transport is closing\"","expected":"sha256:dc3e288f6d1f2b70bcd1a1b3bfb1747ba2fd266feffe1eaa73795b240b0d7a43","level":"error","msg":"(*service).Write failed","ref":"layer-sha256:dc3e288f6d1f2b70bcd1a1b3bfb1747ba2fd266feffe1eaa73795b240b0d7a43","time":"2023-03-31T13:59:41.706331953Z","total":4878450}
10.5.0.2: {"error":"rpc error: code = Unavailable desc = transport is closing","expected":"sha256:ea22f9e7f84592143c98726e5c5433bade56be3e2d1a0a33de890515d73d6c74","level":"error","msg":"(*service).Write failed","ref":"layer-sha256:ea22f9e7f84592143c98726e5c5433bade56be3e2d1a0a33de890515d73d6c74","time":"2023-03-31T13:59:41.710534418Z","total":5919141}
10.5.0.2: {"error":"rpc error: code = Unavailable desc = transport is closing","expected":"sha256:e52e27415a6c33d7daf325c72ab788d0f0c135c9c7620a2cf9e442c7886b9811","level":"error","msg":"(*service).Write failed","ref":"layer-sha256:e52e27415a6c33d7daf325c72ab788d0f0c135c9c7620a2cf9e442c7886b9811","time":"2023-03-31T13:59:41.714550854Z","total":112}
10.5.0.2: {"error":"rpc error: code = Unavailable desc = transport is closing","expected":"sha256:52b9c3886085e234306ed95bfe30e5de86ef2a3b7df89e096a3710ae19b1f4b7","level":"error","msg":"(*service).Write failed","ref":"layer-sha256:52b9c3886085e234306ed95bfe30e5de86ef2a3b7df89e096a3710ae19b1f4b7","time":"2023-03-31T13:59:41.718216490Z","total":427}
10.5.0.2: {"error":"rpc error: code = Unknown desc = connection error: desc = \"transport is closing\"","expected":"sha256:b199b19bb415b6fb99dc8d31ec0c100ea994ae276b20fd1fefd14b873fae6fe9","level":"error","msg":"(*service).Write failed","ref":"layer-sha256:b199b19bb415b6fb99dc8d31ec0c100ea994ae276b20fd1fefd14b873fae6fe9","time":"2023-03-31T13:59:41.721760944Z","total":131}
10.5.0.2: {"error":"rpc error: code = Unknown desc = connection error: desc = \"transport is closing\"","expected":"sha256:fc251a6e798157dc3b46fd265da72f39cd848e3f9f4a0b28587d1713b878deb9","level":"error","msg":"(*service).Write failed","ref":"layer-sha256:fc251a6e798157dc3b46fd265da72f39cd848e3f9f4a0b28587d1713b878deb9","time":"2023-03-31T13:59:41.725121453Z","total":795825}

**Comment by GuillaumeMorini** [comment]
I found this error in apid.log

2023/03/31 15:36:37.936685 log.go:94: DeadlineExceeded [/machine.MachineService/Bootstrap] 499.910808ms stream rpc error: code = DeadlineExceeded desc = context deadline exceeded (:authority=172.20.0.2:50000;content-type=application/grpc;proxyfrom=172.20.0.2:50000;runtime=Talos;talos-role=os:admin;user-agent=grpc-go/1.54.0)

It is not present on other working environment

**Comment by smira** [comment]
the last error is normal, Talos wasn't ready for bootstrap, but `talosctl` retries automatically
