### ISSUE TITLE
Talos extensions-e2e doesn't verify loadable modules are loaded

### ISSUE THREAD

**Issue by frezbo** [siderolabs/talos#7049]
## Bug Report

Talos extensions-e2e doesn't verify loadable modules are loaded

### Description

Update the `e2e-extensions` test to also load drbd/gasket modules and verify that their are loaded.

Also add a check to verify modules like nvidia are signed by the key in the running talos version

Probable steps:

* extract the key from running talos kernel
* use crane to extract nvidia modules
* use the script from kernel sources to verrify the module is indeed signed from the keys in running talos kernel

**Comment by smira** [comment]
I think at the very minimum we can test gasket & drbd being loaded, it should be pretty straightforward, and should give us good coverage.
