### ISSUE TITLE
CSI Snapshotter missing?

### ISSUE THREAD

**Issue by uhthomas** [siderolabs/talos#7051]
### Description

The documentation for https://github.com/kubernetes-csi/external-snapshotter suggests that it should be installed by default on all Kubernetes distributions from 1.20.

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: [`kubectl version --short`]
- Platform:

**Comment by frezbo** [comment]
CSI snapshotter is an implementation of the interface, which is included by default for k8s above 1.20, so talos has nothing to do here, K8s already has the support, csi snapshotter needs to be installed separately.
