### ISSUE TITLE
upgrade-k8s doesn't change kube-proxy version tag in machineconfig

### ISSUE THREAD

**Issue by alubbock** [siderolabs/talos#7067]
### Description

When running `talosctl upgrade-k8s`, the image tags for kube-apiserver, kubelet etc. in the node's machineconfig are updated to the new version of Kubernetes, but kube-proxy's tag is not (although the running version of kube-proxy is updated).

This is based on an upgrade from k8s 1.26.2 to 1.26.3 on Talos 1.3.7.

### Logs

Nothing unusual in `upgrade-k8s` output (completed successfully).

### Environment

- Talos version:
```
Client:
	Tag:         v1.3.7
	SHA:         d17c9ee8
	Built:
	Go version:  go1.19.8
	OS/Arch:     darwin/arm64
Server:
	NODE:        10.0.0.4
	Tag:         v1.3.7
	SHA:         d17c9ee8
	Built:
	Go version:  go1.19.8
	OS/Arch:     linux/amd64
	Enabled:     RBAC
```
- Kubernetes version:
```
Server Version: v1.26.3
```
- Platform:
```amd64``` on server

**Comment by smira** [comment]
This is fixed in Talos v1.4+.
