### ISSUE TITLE
Support for AWS EBS CSI Driver

### ISSUE THREAD

**Issue by robd003** [siderolabs/talos#7069]
When deploying Talos on AWS it would be great to have native support for EBS CSI (https://github.com/kubernetes-sigs/aws-ebs-csi-driver)

**Comment by smira** [comment]
What specifically needs to be done on Talos side to have native support?

**Comment by robd003** [comment]
Had to enable **AmazonEBSCSIDriverPolicy** ```arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy``` as a native EC2 IAM role, but then it just worked!
