### ISSUE TITLE
Enable service extensions before machine config is applied

### ISSUE THREAD

**Issue by casdr** [siderolabs/talos#7083]
## Feature Request

We're running Talos clusters within Xenserver Virtual Machines. Xenserver has the [xe-guest-utilities](https://github.com/xenserver/xe-guest-utilities) daemon which provides information about the OS and network interfaces and enables OS power control.

To setup our clusters and apply the machine config automatically, we need to grab the IP-addresses that have been assigned from the Xenserver API. For this information to be available, we need this daemon to be running.

I've created a system extension with a service container which runs this daemon and created a metal image including the extension. The only problem we're encountering is that the container starts after applying the machine config. However, to apply the machine config, we need the information provided by the daemon.

As you might notice, we've stumbled upon a circular dependency issue here :-)

It would be nice to be able to add a service extension that starts before the machine config is applied.

**Comment by TheiLLeniumStudios** [comment]
@casdr is the extension for the daemon open source by any chance? :)

**Comment by ScottKane** [comment]
We are experiencing the same issue while trying to provision a Talos cluster on Proxmox using the Proxmox Terraform provider which will feed into the Talos Terraform provider. Would be great if we can get some love on this issue to possibly enable a flag during the custom image build to allow extensions to start while in maintenance mode.

**Comment by casdr** [comment]
Awesome, thank you @frezbo!
