### ISSUE TITLE
unsupported k8s upgrade path  "1.25.8" to "1.26.0"

### ISSUE THREAD

**Issue by NarubyRiverlione** [siderolabs/talos#7090]
## Bug Report
 talosctl upgrade-k8s --to 1.26.0 --dry-run
automatically detected the lowest Kubernetes version 1.25.8
unsupported upgrade path "1.25->1.26" (from "1.25.8" to "1.26.0"

### Description

I did a successful talos upgrade from 1.2.6 to 1.3.7 and now I want to upgrade k8s from 1.25 to 1.27, with the 1.26 step between.
But I don't see why to 1.26 is not supported ? 

### Logs
```
kg pods -n kube-system -o jsonpath="{.items[*].spec.containers[*].image}" | tr -s '[[:space:]]' '\n' | grep kube

k8s.gcr.io/kube-apiserver:v1.25.8
k8s.gcr.io/kube-apiserver:v1.25.8
k8s.gcr.io/kube-apiserver:v1.25.8
k8s.gcr.io/kube-controller-manager:v1.25.8
k8s.gcr.io/kube-controller-manager:v1.25.8
k8s.gcr.io/kube-controller-manager:v1.25.8
k8s.gcr.io/kube-proxy:v1.25.8
k8s.gcr.io/kube-proxy:v1.25.8
k8s.gcr.io/kube-proxy:v1.25.8
k8s.gcr.io/kube-proxy:v1.25.8
k8s.gcr.io/kube-scheduler:v1.25.8
k8s.gcr.io/kube-scheduler:v1.25.8
k8s.gcr.io/kube-scheduler:v1.25.8
```

### Environment

- Talos version: 
`Client:
	Tag:  v1.2.6   SHA:  6ca8b2ac 	Built: 	Go version:  go1.19.2 	OS/Arch:     darwin/arm64
Server:
	NODE:        192.168.1.80 
	Tag:         v1.3.7 	SHA:         d17c9ee8 	Built:	Go version:  go1.19.8	OS/Arch:     linux/amd64	Enabled:     RBAC`

- Kubernetes version: 
`Client Version: v1.27.1
Kustomize Version: v5.0.1
Server Version: v1.25.8`

**Comment by frezbo** [comment]
please update the version of talosctl

**Comment by NarubyRiverlione** [comment]
Yes indeed that did the truc. tx
