### ISSUE TITLE
Boot loop on old HP Compaq 8000 PC

### ISSUE THREAD

**Issue by Dzeri96** [siderolabs/talos#7091]
### Description
I got my hands on a somewhat old, second-hand compact HP PC (prod. no. AU248AV) and I wanted to repurpose it as a worker node in my cluster. I updated the BIOS to the latest available one (v1.14). In the boot process I can reach the kernel and see the dmsg logs (right after GRUB), but the PC restarts with no specific warning or error message. I've tried booting another linux ISO like Kubuntu 22.04, and can confirm it works, so there must me something that Talos doesn't like.
I'm afraid I can't provide much more information than that unfortunately.

### Environment

- Talos version: 1.37 and 1.40.beta1
- Platform: x86 bare metal

**Comment by frezbo** [comment]
could you provide the dmesg, since it's an old machine one thing that could stand out is lack of entropy, but without complete dmesg it's hard to provide any info

**Comment by Dzeri96** [comment]
The thing is, the boot sequence never reaches Talos, so I can't use the cli. Are boot logs saved to the live usb?

**Comment by netthier** [comment]
Since v1.1.0 Talos requires CPUs to support x86-2: 
> Talos is built for x86-64 architecture with support for [x86-64-v2 microarchitecture level](https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels), so Talos no longer runs on processors supporting only baseline x86-64 microarchitecture (before 2009).
https://github.com/siderolabs/talos/discussions/5788

Is it possible that your PC's CPU is too old?

**Comment by Dzeri96** [comment]
@netthier That's exactly it. The CPU came out in 2008 and it does not support this v2 instruction set. Shame because repurposing old PCs as kubernetes nodes is a pretty common use case. I guess nothing can be done about this?

**Comment by smira** [comment]
@Dzeri96 you can build your own Talos image by supplying `GOAMD64=v1`:

```shell
# clone Talos repo
make imager USERNAME=<foo> PUSH=true GOAMD64=v1
make iso USERNAME=<foo>
```

now you have `_out/talos-amd64.iso` built with `v1`

Same way, build the installer `make installer USERNAME=foo PUSH=true GOAMD64=v1`

You can push to any registry by specifying e.g. `IMAGE_REGISTRY=docker.io`

General setup https://www.talos.dev/v1.4/advanced/developing-talos/

**Comment by otopetrik** [comment]
Found this bug only as I was about to create a new one. Adding serial console log and more details, to make it easier to find this bug:

```
[    4.782219] Freeing unused kernel image (rodata/data gap) memory: 740K
[    4.881947] x86/mm: Checked W+X mappings: passed, no W+X pages found.
[    4.884744] x86/mm: Checking user space page tables
[    4.980153] x86/mm: Checked W+X mappings: passed, no W+X pages found.
[    4.983132] Run /init as init process
This program can only be run on AMD64 processors with v2 microarchitecture support.
[    4.989153] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000100
[    4.992352] CPU: 0 PID: 1 Comm: init Not tainted 6.1.78-talos #1
[    4.994902] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.16.2-0-gea1b7a073390-prebuilt.qemu.org 04/01/2014
[    4.999469] Call Trace:
[    5.000700]  <TASK>
[    5.001799]  dump_stack_lvl+0x44/0x5c
[    5.003509]  panic+0x110/0x2a0
[    5.005035]  do_exit.cold+0x15/0x15
[    5.006668]  do_group_exit+0x2d/0x80
[    5.008358]  __x64_sys_exit_group+0x14/0x20
[    5.010221]  do_syscall_64+0x5c/0x90
[    5.011871]  entry_SYSCALL_64_after_hwframe+0x64/0xce
```

Message `This program can only be run on AMD64 processors with v2 microarchitecture support.` leads to:
```
#ifdef GOAMD64_v2
DATA bad_cpu_msg<>+0x00(SB)/84, $"This program can only be run on AMD64 processors with v2 microarchitecture support.\n"
#endif
```
(from [here](https://go.googlesource.com/go/+/refs/tags/go1.19.4/src/runtime/asm_amd64.s#82))

Searching for issues containing `GOAMD64_v2` does not find anything, because the actual variable name is `GOAMD64`, details [here](https://go.dev/wiki/MinimumRequirements#amd64)

This issue also appears when running Proxmox VM with default `cputype=qemu64`. Changing configuration to `cputype=x86-64-v2` fixes that. Then the VM boots even on and old Wyse 7020 thin client with AMD GX-415GA.
