### ISSUE TITLE
Possible to use expiring tokens instead of certificate in kubeconfig?

### ISSUE THREAD

**Issue by robd003** [siderolabs/talos#7094]
## Feature Request
When running `talosctl --talosconfig talosconfig kubeconfig` it would be great to do something like AWS EKS where it issues a token with a limited TTL rather than a certificate that is perpetually valid.

### Description
Have a way to issue token based authentication for access to the Kubernetes cluster so that it's easier to prevent accidental credential leaks.

OpenID Connect might be a good option. This project looks interesting: https://github.com/dexidp/dex

**Comment by smira** [comment]
`talosctl` provides you with admin-level `kubeconfig` always. You can set up Kubernetes RBAC, OIDC auth, issue yourself limited time service accounts, etc. This is up to the user to set up the access to Kubernetes the way it works the best.

You can consider `talosctl kubeconfig` as break the glass scenario, when it is required to access the cluster when other methods failed.
