### ISSUE TITLE
extraHostEntries or files (containing custom CA) not applied when booting from talos-amd64.iso 1.3.6

### ISSUE THREAD

**Issue by ocean-sm** [siderolabs/talos#7096]
## Bug Report
Applying machine config to freshly booted VM fails to apply entries found in extraHostEntries and fails look up of custom registry.

### Description
Building cluster for working in air-gapped environment and using custom docker registry mirror for hosting images.
When booting from the talos-amd64.iso (1.3.6), the VM gets a network address but when applying the config the connection occurs correctly, but the VM cannot resolve the internal DNS name for the registry mirror.

error=:failed to do request: Head \"https://custom.internal.domain:6000/v2/siderolabs/installer/manifests/v.1.3.6?ns=ghcr.io\": dial tcp: lookup custom.internal.domain on <internal dns ip>: no such host" host="custom.internal.domain"

   # Control Plane excerpt:
    network:
        # `interfaces` is used to define the network interface configuration.
        interfaces:
            - interface: eth0 # The interface name.
              mtu: 0 # The interface's MTU.
              dhcp: true # Indicates if DHCP should be used to configure the interface.
              # Virtual (shared) IP address configuration.
              vip:
                ip: 10.10.42.222 # Specifies the IP address to be used.

      # Allows for extra entries to be added to the `/etc/hosts` file
        extraHostEntries:
            - ip: 10.10.42.202 # The IP of the host.
              # The host alias.
              aliases:
                - custom.internal.domain
                - custom.otherinternal.domain
    # Used to configure the machine's container image registry mirrors
    registries:
        # Specifies mirror configuration for each registry.
        mirrors:
            docker.io:
                # List of endpoints (URLs) for registry mirrors to use.
                endpoints:
                    - https://custom.internal.domain:6000/
            gcr.io:
                # List of endpoints (URLs) for registry mirrors to use.
                endpoints:
                    - https://custom.internal.domain:6000/
            ghcr.io:
                # List of endpoints (URLs) for registry mirrors to use.
                endpoints:
                    - https://custom.internal.domain:6000/

Interesting part is that this works fine when I configure a VMware environment.
### Environment

- Talos version: 1.3.6
- Kubernetes version: 1.26.2
- Platform: Hyper-V VM booting talos-amd64.iso v1.3.6

**Comment by smira** [comment]
During the boot when Talos is not installed, `/etc/hosts` is not populated yet. This might be considered a bug though.

Workaround might be to use a resolvable DNS name

**Comment by ocean-sm** [comment]
Thanks @smira .

I thought as much, so thanks for the clarification.
Is there another way to implement a host lookup if that is the case of no /etc/hosts file?

When deploying with the VMware ova this works perfectly fine, and I assume then that due to a different boot process that it actually does initialise the /etc/hosts file after config application.

Unfortunately though, this build is for deploying a solution that will be completely stand alone and most likely air-gapped, so resolvable domains become challenging.
It is a scripted install, so I can possibly use the IP for the initial deployment and then update the config with the resolvable name... or just thinking about it now, I can add multiple mirrors. I am just trying to keep it clean and without using IP references if possible.

I will leave this open to understand if this may be a bug or just a limitation.

Thanks

**Comment by smira** [comment]
Registry mirror certs can be configured on the registry config, this way should always work, even if you don't put to the root CA list.

**Comment by smira** [comment]
I'm not sure whether it got fixed, or worked in the first place, but I can't reproduce this problem with `main`.
