### ISSUE TITLE
talosctl memory command for workers

### ISSUE THREAD

**Issue by rsidhaarth** [siderolabs/talos#7108]
## Bug Report

When we execute talosctl memory for workers, we get the following error

### Description

![image](https://user-images.githubusercontent.com/16856248/232947584-14faf5d2-a09c-4c37-b385-dffff5e2008d.png)

### Environment

talosctl 1.3.7 and 1.4.0
talosos 1.3.7 and 1.4.0

I have tested in both

![image](https://user-images.githubusercontent.com/16856248/232947698-621fd8e7-a206-4d80-aacc-e85d74e0ee40.png)

- Kubernetes version: 1.27.1

**Comment by smira** [comment]
This is a bug in Talos, but looks like you're setting both endpoints & nodes to the worker node. You should be able to keep endpoints to be control plane node, while node as worker node - this should not fail.
