### ISSUE TITLE
Support SBC Pine64 SOQuartz

### ISSUE THREAD

**Issue by Pythoner6** [siderolabs/talos#7112]
### Description

I'm really quite interested in trying out running talos for my small k8s cluster, but I'm currently my available hardware is a few SOQuartz modules (which I'm running on the SOQuartz blade breakout boards) https://wiki.pine64.org/wiki/SOQuartz.

**Comment by frezbo** [comment]
We don't have the hardware to test, if you have the hardware you could start looking at the existing pine64 code as headstart. The basic requirement is to have upstream u-boot support for the SOQuartz

**Comment by Pythoner6** [comment]
Ah, ok. Yeah I don't think there's upstream uboot for the soquartz at the moment (or even generally for the rk3566 chip it uses in general). Later this year I should be getting some raspberry pis so in all likelihood I'll probably just end up waiting for that.

**Comment by frezbo** [comment]
> Hey all! So, it appears we have support for rk3566 in mainline now, not sure if we have full support for soquartz or not, but I'd like to start porting the needed code to get a soquartz to boot :) Are there any guidelines/porting guides for new hardware?

by mainline if you meant LTS, then that should be good (Talos uses LTS kernel)

Basically you'd need u-boot support for the board and upstream kernel to provide dtbs.

**Comment by pl4nty** [comment]
looks like it's supported in LTS kernel v6.1.36, but [patches haven't been merged to u-boot yet](https://patchwork.ozlabs.org/project/uboot/list/?series=&submitter=&state=&q=soquartz&archive=&delegate=)

**Comment by pl4nty** [comment]
I've written a [u-boot pkg with SOQuartz CM4 support](https://github.com/siderolabs/pkgs/compare/main...pl4nty:talos-pkgs:main), but it needs `CONFIG_TOOLS_LIBCRYPTO=y` to fix build errors. I'm not sure how to design for multiple flavours though (CM4, Blade, Model A) with vendored DDR/ATF binaries. But my [Talos port](https://github.com/siderolabs/talos/compare/main...pl4nty:talos:main) builds, so I'll test it tomorrow after I find a power supply

**Comment by pl4nty** [comment]
Got lucky with a power supply, and the SOQuartz boots fine. DHCPv4 fails though, could be my network (v6-native) but I don't have any other Talos-compatible devices to test

**Comment by g5pw** [comment]
I have three boards in a turingpi2, any tests you want me to run?

**Comment by pl4nty** [comment]
@g5pw thanks! it'd be great if you can flash a board with that image and try adding it to a cluster (or bootstrapping a new one). mine's in a Turing Pi 2 as well but I haven't tested peripherals, only ethernet and BMC

**Comment by g5pw** [comment]
I finally got some time to flash the image an try to boot it. The boot completes fine, and  I see UART works OK. However, the boot then hangs trying to get ethernet connectivity. It looks like the system is trying to acquire an address via DHCP, but gets no response. I'm unable to get a shell to do further testing, but I could to a dump on the router to see if the packet gets through or not.

**Comment by pl4nty** [comment]
Sounds similar to the issue I saw, can you try getting a dump from your router? Mine doesn't support much debugging unfortunately. I'll try building an image with additional logging too

**Comment by g5pw** [comment]
I fiddled a bit with a capture on my router, however I see no packets going out :/

**Comment by pl4nty** [comment]
The patches were accepted and released in u-boot 2023.10-rc2, so I rebased and built a [new image](https://1drv.ms/u/s!AsBXom1QqK_lkvN4K8jlydXYGHYbOw). But I'm still seeing similar logs to you, along with this:

```
[ 1268.815670] [talos] request/renew failed {"component": "controller-runtime", "controller": "network.OperatorSpecController", "operator": "dhcp4", "error": "unable to receive an offer: got an error while the discovery request: no matching response packet received", "link": "enx1a9c0dafc579"}
```

**Comment by pl4nty** [comment]
I rechecked the [Quartz64 dev page](https://wiki.pine64.org/wiki/Quartz64_Development), patches for ethernet GMAC and Motorcomm PHY have been submitted but not accepted. I've built a [new image](https://1drv.ms/u/s!AsBXom1QqK_lkvN5fyRhiA1_g_PHGg) with them but still get the same logs. Also tried IPv6 DNS/NTP via kernel params with no success

**Comment by g5pw** [comment]
I'll give it another go, but it would be nice to have some kind of shell to poke around, have you tried booting with a shell as /bin/init or in systems rescue mode?

**Comment by pl4nty** [comment]
I wouldn't know where to start trying to get a shell, it doesn't ship with one. `/dev/sdaX` is missing from the BMC too so I'm not sure how to get filesystem access

**Comment by pl4nty** [comment]
I've spent quite a few hours on this with no progress. Would be great if someone can test with different hardware (ie not Turing Pi 2). I don't see a dhcp4 DHCP ACK after the REQUEST log, and v6 isn't reachable although it briefly displays `this machine is reachable at: [address]`

**Comment by Christos822** [comment]
Hi, is there any image for rock pi cm3?
