### ISSUE TITLE
CoreDNS, cluster role and `nodes`

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#7113]
See https://github.com/siderolabs/omni-feedback/issues/36

Compare https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#does-coredns-have-sufficient-permissions

And https://github.com/coredns/helm/blob/master/charts/coredns/templates/clusterrole.yaml

**Comment by nberlee** [comment]
:eyes: chrisohaver is a coredns maintainer
https://github.com/kubernetes/kubernetes/commit/0cfb4bbe2cb2e3d64ec7f281bf86c439da611f73

**Comment by smira** [comment]
Thanks, I guess it makes sense, it's an easy fix on Talos side, I just wanted to be sure we're not missing something

**Comment by nberlee** [comment]
I am not sure if it suppose to be there, this is file which coredns uses for testing:
https://github.com/coredns/deployment/blob/master/kubernetes/coredns.yaml.sed which doesn't have it

**Comment by smira** [comment]
yep, same for me, and I indeed saw sometimes `coredns` not resolving some of the names it should be resolving. It doesn't seem to be a problem adding `get` on `Nodes`. Something to check next week.

**Comment by nberlee** [comment]
here it is removed in coredns, but this change never came to `kubernetes/kubernetes`:
https://github.com/coredns/deployment/commit/916d90420df83ad7d2ab9135a409ea80780af9e0

which is part of the federation cleanup: https://github.com/coredns/deployment/issues/222

**Comment by smira** [comment]
@nberlee looks like you're right, and I couldn't reproduce the issue.
