### ISSUE TITLE
Talos 1.4.0 breaks on Hetzner Cloud with Ampere servers

### ISSUE THREAD

**Issue by cschmatzler** [siderolabs/talos#7119]
### Description

Now that Hetzner released their new Ampere-based servers, I wanted to play around with them, including setting up a small k8s cluster to verify multiplatform image availability.
While Talos 1.3.7 worked just perfectly, upgrading to 1.4.0 *or* installing it from zero both results in the nodes failing to boot.

#### Upgrade path

1. Install Talos 1.3.7 on a `cax11` server. I used the Packer file from the [documentation](https://www.talos.dev/v1.4/talos-guides/install/cloud-platforms/hetzner/) except for downloading the `hcloud-arm64.tar.xz` asset and using the `cax11` server for provisioning. `var.talos_version` is set to `1.3.7`.
2. Run `talosctl bootstrap` on the node and wait for everything to come up.
3. Run `talosctl upgrade  --image ghcr.io/siderolabs/installer:v1.4.0 --preserve=true`
4. The upgrade fails with the following logs and the server fails to boot from this point on
<img width="556" alt="image" src="https://user-images.githubusercontent.com/8415974/233621733-b2839f8b-18b7-4a52-9968-268e1de89037.png">

#### Installation path
1. Install Talos 1.4.0 on a `cax11` server. I used the Packer file from the [documentation](https://www.talos.dev/v1.4/talos-guides/install/cloud-platforms/hetzner/) except for downloading the `hcloud-arm64.tar.xz` asset and using the `cax11` server for provisioning. `var.talos_version` is set to `1.4.0`.
2. The server never boots up, there is never any display output to fetch logs.

### Environment

- Platform: Hetzner Cloud - Ampere

**Comment by smira** [comment]
My only guess it's something with the new Linux 6.1 and specific to Hetzner. Talos 1.4.0 runs just fine on Ampere servers in Equinix Metal.

**Comment by cschmatzler** [comment]
I just installed Linux 6.1.6 on Ubuntu 22.04.2 and that boots up properly. 

> Welcome to Ubuntu 22.04.2 LTS (GNU/Linux 6.1.6-060106-generic aarch64)

**Comment by smira** [comment]
> The server never boots up, there is never any display output to fetch logs.

This is strange, you should see at least UEFI boot sequence and GRUB before it loads the LInux kernel.

**Comment by jeroenkolk** [comment]
> > The server never boots up, there is never any display output to fetch logs.
> 
> This is strange, you should see at least UEFI boot sequence and GRUB before it loads the LInux kernel.

You can see the UEFI boot sequence and GRUB. After booting into the Talos 1.4.0 you won't get a display output.
Also looking into the graphs in the Hetzner Cloud platform, all cpu's are at itle, so it seems stuck somewere.

Ive also tried to get some form of logs but it does not seem to work.

**Comment by frezbo** [comment]
Seems the console settings for Hetzner are different and just missing logs, or it could be the UEFI implementation of the particular hardware has issues with kexec, try disabling kexec first and see if it fixes it

**Comment by frezbo** [comment]
hmm seems similar

**Comment by frezbo** [comment]
this must be different since it's bare metal and not sure if it needs virtio console :thinking:

**Comment by smira** [comment]
it's not clear from the issue itself, but as it's using `hcloud` image, I would assume it's a VM. bare-metal Hetzner machines won't run on `hcloud` image iirc
