### ISSUE TITLE
DHCP with Multiple Gateway

### ISSUE THREAD

**Issue by rsidhaarth** [siderolabs/talos#7162]
### Description

I have a switch which is a DHCP server for one of my interfaces, and there are multiple gateways in my DHCP server. When I am configuring the server with dhcp: true then, we get the following error.

`[talos] controller failed {"component": "controller-runtime", "controller": "network.RouteSpecController", "error": "3 errors occurred:\x5cn\x5ct* error adding route: netlink receive: file exists, message {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:0 Protocol:3 Scope:0 Type:1 Flags:0 Attributes:{Dst:<nil> Src:10.15.0.52 Gateway:10.15.0.2 OutIface:8 Priority:1024 Table:254 Mark:0 Pref:<nil> Expires:<nil> Metrics:<nil> Multipath:[]}}\x5cn\x5ct* error adding route: netlink receive: file exists, message {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:0 Protocol:3 Scope:0 Type:1 Flags:0 Attributes:{Dst:<nil> Src:10.15.0.52 Gateway:10.15.0.3 OutIface:8 Priority:1024 Table:254 Mark:0 Pref:<nil> Expires:<nil> Metrics:<nil> Multipath:[]}}\x5cn\x5ct* error adding route: netlink receive: file exists, message {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:0 Protocol:3 Scope:0 Type:1 Flags:0 Attributes:{Dst:<nil> Src:10.15.0.52 Gateway:10.15.0.4 OutIface:8 Priority:1024 Table:254 Mark:0 Pr...`

### Environment

- Talos version: 1.4.1
- Kubernetes version: 1.26.4
- Platform: Bare Metal

**Comment by smira** [comment]
you can't have two default gateways with the same priority for the same IP family.

**Comment by smira** [comment]
https://unix.stackexchange.com/questions/337332/how-does-linux-choose-between-multiple-default-gateways

Linux will not stop using 10.5.0.2 if it becomes "down", as it has no way to know that.
