### ISSUE TITLE
Two Interface with Different Gateway

### ISSUE THREAD

**Issue by rsidhaarth** [siderolabs/talos#7163]
### Description

Consider we have Two Interfaces.

**eth0:** 

For LAN and we use NAT with Host to provide internet.

**eth1:**

For Public IP 

Now I have this setting.

>       interfaces:
>         - interface: eth0
>           addresses:
>             - 10.15.0.53/24
>           routes:
>             - network: 10.15.0.0/24
>               gateway: 10.15.0.1
>               metric: 100
>             - network: 0.0.0.0/0
>               gateway: 10.15.0.2
>               metric: 200
>             - network: 0.0.0.0/0
>               gateway: 10.15.0.3
>               metric: 300
>             - network: 0.0.0.0/0
>               gateway: 10.15.0.4
>               metric: 400
>           mtu: 9000
>         - interface: eth1
>           addresses:
>             - a.a.a.a/32
>           routes:
>             - network: 0.0.0.0/0
>               gateway: b.b.b.b
>               metric: 500
> 
> 

But Talos is ignoring the GW from eth1, which only shows the eth0 GW now, which means that Public IP is unreachable.

### Environment

- Talos version: 1.4.1
- Kubernetes version: 1.26.4
- Platform: Bare Metal

**Comment by smira** [comment]
Linux picks up the route with minimum metric (priority). I'm not sure what you're asking about.

**Comment by smira** [comment]
The dashboard doesn't show all gateways, if you want to see the routing table, you can use `talosctl get routes`.

https://www.talos.dev/v1.4/learn-more/networking-resources/#observing-state

**Comment by steverfrancis** [comment]
If you wish to override the default gateway, you need to add routes for the subnets that should be routed elsewhere, not just add another default. Only one default route will be active.
