### ISSUE TITLE
Label node with active Virtual IP 

### ISSUE THREAD

**Issue by Preisschild** [siderolabs/talos#7166]
### Description

Currently, there is no (straightforward) way to see which node currently has the VIP assigned over the Kubernetes API.

Letting the VIP controller label the active node would open up new use-cases for this controller, such as using the VIP as a Cluster NAT IP with [Cilium's Egress Gateway Feature](https://docs.cilium.io/en/latest/network/egress-gateway/). This is extremely helpful when a cloud-provider doesn't have a NAT Gateway itself, but has VIPs, such as Hetzner Cloud. 

For this to work, the Cilium `EgressGateway` needs a [nodeSelector](https://doc.crds.dev/github.com/cilium/cilium/cilium.io/CiliumEgressGatewayPolicy/v2@v1.13.2#spec-egressGateway-nodeSelector) configured to forward cluster traffic to the node where you have your NAT IP configured. This requires a label on the node with the VIP.

**Comment by smira** [comment]
It doesn't have to be part of Talos itself, just deploy a Kubernetes controller pod which does the job.

Use [this feature](https://www.talos.dev/v1.4/advanced/talos-api-access-from-k8s/) to enable access to Talos API from Kubernetes.

Use equivalent of `talosctl get members` to find controlplane nodes, find where the VIP by watching `talosctl get addresses`, and update Kubernetes labels using service account.
