### ISSUE TITLE
CNI gets wrong Info

### ISSUE THREAD

**Issue by rsidhaarth** [siderolabs/talos#7167]
### Description

Hi,

I am using Bare Metal and I have set the following config with my all my nodes

> 
>         nodeIP:
>           validSubnets:
>             - 10.15.0.0/24
>     # Provides machine specific network configuration options.
>     network:
>       hostname: master-01
>       nameservers:
>         - 8.8.8.8
>         - 1.1.1.1
>       interfaces:
>         - interface: eth0
>           addresses:
>             - 10.15.0.52/24
>           routes:
>             - network: 10.15.0.0/24
>               gateway: 10.15.0.1
>             - network: 0.0.0.0/0
>               gateway: 10.15.0.2
>               metric: 200
>             - network: 0.0.0.0/0
>               gateway: 10.15.0.3
>               metric: 300
>             - network: 0.0.0.0/0
>               gateway: 10.15.0.4
>               metric: 400
>           mtu: 9000
>         - interface: eth1
>           addresses:
>             - 111.111.111.111/26
>           routes:
>             - network: 0.0.0.0/0
>               gateway: 255.255.255.192
>               metric: 100
> 

But Flannel or Calico both setting the IP as 111.111.111.111

Issues

1) Internet not working in any of the pods other than the one placed on node-01
2) There is no connectivity between the pods

Solution:

> kubectl annotate node $NODE_NAME flannel.alpha.coreos.com/public-ip-overwrite=$PRIVATE_IP --overwrite
> kubectl annotate node $NODE_NAME flannel.alpha.coreos.com/public-ip=$PRIVATE_IP --overwrite

This is for Flannel

And I will try for Calico and then update.

### Environment

- Talos version: 1.4.1
- Kubernetes version: 1.26.4
- Platform: Bare Metal

**Comment by smira** [comment]
This doesn't have anything to do with Talos btw, it's all about the CNI configuration which doesn't depend on the OS.

With Flannel, `kubectl annotate node $NODE_NAME flannel.alpha.coreos.com/public-ip-overwrite=$PRIVATE_IP --overwrite` is enough, and Flannel pods should be restarted to pick up the changes.

What should be set on Talos side for multi-homed nodes is: proper tuning for the kubelet node IP (to pick it from the right subnet), and etcd peering address (all via machine configuration).

**Comment by smira** [comment]
> Still why Flannel did not picked the correct IP ?

you probably need to ask the question in Flannel project. AFAIK Flannel picks up the first IP address it finds. There's nothing that Talos can do about it right out of the box.

https://github.com/flannel-io/flannel/blob/master/Documentation/troubleshooting.md#interface-selection-and-the-public-ip
