### ISSUE TITLE
talos cluster create waits on k8s nodes at port 6443 ignoring the specified --control-plane-port cmd parameter

### ISSUE THREAD

**Issue by nvp152** [siderolabs/talos#7171]
### Description
The talos cluster create commands hangs when a custom control-plane-port is specified. The logging indicates that k8s status node check may still be trying to hit the default port: 6443 and ignoring the cmd parameter.... 
This is not a show stopper since it is possible to control-c and the docker containers are actually up and stay up.

Here is the cmd
```
talosctl cluster create --control-plane-port 6444
```
### Logs
```
....
validating CIDR and reserving IPs
generating PKI and tokens
creating network talos-default
creating controlplane nodes
creating worker nodes
renamed talosconfig context "talos-default" -> "talos-default-14"
waiting for API
bootstrapping cluster
waiting for etcd to be healthy: OK
waiting for etcd members to be consistent across nodes: OK
waiting for etcd members to be control plane nodes: OK
waiting for apid to be ready: OK
waiting for all nodes memory sizes: OK
waiting for all nodes disk sizes: OK
waiting for kubelet to be healthy: OK
waiting for all nodes to finish boot sequence: OK
◱ waiting for all k8s nodes to report: Get "https://127.0.0.1:6443/api/v1/nodes"
....
```
### Environment
- Talos version: v1.4.1
- Kubernetes version: v1.27.1
- Platform: Macos Monterey

**Comment by smira** [comment]
This feature doesn't fully work with Docker clusters, only with QEMU ones.

**Comment by nvp152** [comment]
Which feature are you referring to exactly: "kubectl cluster create" with Docker ? If so, that is a bit confusing because the Getting quickstart guide here (https://www.talos.dev/v1.4/introduction/quickstart/) suggests otherwise.

My apologies in advance, if i am missing something.

**Comment by nvp152** [comment]
Got it. Thanks for clarifying.
