### ISSUE TITLE
Logging in 1.4.1 is very chatty

### ISSUE THREAD

**Issue by szinn** [siderolabs/talos#7179]
## Bug Report

Logging (for dashboard?) is very chatty with about 1000's of messages per minute. These messages seem more like debug-level rather than info level. The volume of messages hides other issues of Talos and other applications being logged as well.

### Description

See https://taloscommunity.slack.com/archives/CG25RPZNE/p1683048112262849

A related feature request would be to set not just the logging URL but the logging level as well - e.g., info or debug or error.
### Logs

See https://taloscommunity.slack.com/archives/CG25RPZNE/p1683048112262849

### Environment

- Talos version: 1.4.1
- Kubernetes version: 1.27.1
- Platform: bare-metal

**Comment by smira** [comment]
Not sure what exactly is int the screenshot, better to have it in the issue. 

What I see there is expected, it's `apid`/`machined` logs. If they pop up in the server console, you have `debug: true` enabled in the machine configuration.

**Comment by szinn** [comment]
I have debug: false set in the machine configuration.

These logs are sent via machine.logging setting to Grafana via vector / Loki

**Comment by smira** [comment]
In that case you have `talos-service` field in the log you can use to filter messages if you want to. But these logs describe exactly what is happening at the moment. You can also disable the dashboard via kernel args if you don't need it.

**Comment by steverfrancis** [comment]
Comparing a 1.3.7 idle talos node, and a 1.4.1 idle talos node, the 1.3 system logs 417 lines in 10 seconds with
`talosctl  logs machined -f`
the 1.4.1 system logs 8701 in the same 10 seconds.
Both with just default config (talosctl gen config).
That's a big increase in logging.


```
192.168.64.36: machined/authz/authorizer authorized ([os:admin os:operator os:reader] includes [os:admin])
192.168.64.36: machined OK [/machine.MachineService/Version] 175.583µs unary Success (:authority=localhost;content-type=application/grpc;runtime=Talos;talos-role=os:admin;user-agent=grpc-go/1.54.0)
192.168.64.36: machined OK [/machine.MachineService/Memory] 19.6323ms unary Success (:authority=localhost;content-type=application/grpc;runtime=Talos;talos-role=os:admin;user-agent=grpc-go/1.54.0)
192.168.64.36: machined OK [/machine.MachineService/CPUInfo] 83.9674ms unary Success (:authority=localhost;content-type=application/grpc;runtime=Talos;talos-role=os:admin;user-agent=grpc-go/1.54.0)
192.168.64.36: machined OK [/machine.MachineService/SystemStat] 85.717647ms unary Success (:authority=localhost;content-type=application/grpc;runtime=Talos;talos-role=os:admin;user-agent=grpc-go/1.54.0)
192.168.64.36: machined OK [/machine.MachineService/Processes] 190.799845ms unary Success (:authority=localhost;content-type=application/grpc;runtime=Talos;talos-role=os:admin;user-agent=grpc-go/1.54.0)
192.168.64.36: machined/authz/injector parsed metadata [os:admin] as [os:admin] (unknownRoles = [])
192.168.64.36: machined/authz/injector parsed metadata [os:admin] as [os:admin] (unknownRoles = [])
192.168.64.36: machined/authz/injector parsed metadata [os:admin] as [os:admin] (unknownRoles = [])
192.168.64.36: machined/authz/authorizer authorized ([os:admin os:operator os:reader] includes [os:admin])
192.168.64.36: machined/authz/authorizer authorized ([os:admin os:operator os:reader] includes [os:admin])
192.168.64.36: machined/authz/authorizer authorized ([os:admin os:operator os:reader] includes [os:admin])
192.168.64.36: machined/authz/injector parsed metadata [os:admin] as [os:admin] (unknownRoles = [])
192.168.64.36: machined/authz/authorizer authorized ([os:admin os:operator os:reader] includes [os:admin])
192.168.64.36: machined OK [/machine.MachineService/Version] 521.041µs unary Success (:authority=localhost;content-type=application/grpc;runtime=Talos;talos-role=os:admin;user-agent=grpc-go/1.54.0)
192.168.64.36: machined/authz/injector parsed metadata [os:admin] as [os:admin] (unknownRoles = [])
```

**Comment by smira** [comment]
There is no increase in logging, though we can say whether some logging can be optimized (log less per request). There is increase in API request rate.Iit's just the dashboard using the API. If something else is using the API, it will be similar amount of logs.
