### ISSUE TITLE
talosctl gen config does not validate for legal cluster name

### ISSUE THREAD

**Issue by steverfrancis** [siderolabs/talos#7180]
## Bug Report
talosctl gen config will accept a cluster name of "1.3", but this fails to create a valid cluster as its of type numeric.
### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: [`kubectl version --short`]
- Platform:

**Comment by smira** [comment]
This is actually a bug in `kubeconfig` generation that we need to fix (the cluster name itself of "1.3" should be fine).
