### ISSUE TITLE
In-cluster internal Kubernetes controlplane endpoint

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#7191]
Run `go-loadbalancer` based TCP loadbalancer on `localhost:<some-port>` with the following endpoints:

* cluster endpoint (from machine config)
* `localhost:6443` for cp nodes
* `talosctl get members` | `grep controlplane` -> control plane endpoints + `:6443`

(we need to know control plane port, which might not be available on workers (?))

We can use this endpoint for `kubeconfig-in-cluster` -> `kube-proxy` DaemonSet.

`kubelet` on worker nodes could use this Kubernetes endpoint (or even controlplane nodes).

`go-loadbalancer` runs the health checks against all endpoints, and picks only the ones which are reachable.

**Comment by frezbo** [comment]
Should we also include the vip endpoint?

**Comment by smira** [comment]
VIP endpoint is the controlplane endpoint, but we don't know about VIPs on the worker nodes (only controlplane endpoint).

**Comment by ruifung** [comment]
I just saw this, and I'm curious if this will work independent of kube-proxy? I.e. for cilium in it's kube-proxy free mode which requires specifying the control plane endpoint and port.

**Comment by frezbo** [comment]
> I just saw this, and I'm curious if this will work independent of kube-proxy? I.e. for cilium in it's kube-proxy free mode which requires specifying the control plane endpoint and port.

yes, that's one the use cases, you'd specify this endpoint for cilium and since it's localhost it would just happily work.
