### ISSUE TITLE
NO_FILE ulimit decreases from 1048576 to 1024 when upgrading to v1.4.2

### ISSUE THREAD

**Issue by jonkerj** [siderolabs/talos#7198]
### Description

When I upgrade from v1.4.1 to v1.4.2, the default ulimit for `NO_FILE` decreases from 1048576 to 1024:

1. Deploy single node Talos on QEMU using official ISO
2. Exec into any pod: `ulimit -n`, which should show 1048576
3. Upgrade to v1.4.2
4. Repeat 2 and observe 1024

My trigger case was InfluxDB (which really loves FDs), complaining about "too many open files", just after I upgraded to v1.4.2 but any pod shows this behavior. After having downgraded to v1.4.1, everything is OK again.

### Logs
n/a

### Environment

- Talos version: v1.4.2
- Kubernetes version: 1.26.3
- Platform: QEMU

**Comment by frezbo** [comment]
The issue is that now Go honors default RLIMIT for forked processes (which is actually correct). https://github.com/golang/go/issues/46279#issuecomment-1470813960

The fix would be to set a sensible default from Talos when running processes from machined
