### ISSUE TITLE
[Proxmox] - Talos v1.4.0 bootlooping

### ISSUE THREAD

**Issue by zulhfreelancer** [siderolabs/talos#7202]
## Bug Report

When I launched a Proxmox VM using Talos v1.4.0 ISO, it's bootlooping

https://github.com/siderolabs/talos/assets/3416976/c901ee7f-48a7-45c7-8d86-ab3dd933583e

### Description

ISO:
https://github.com/siderolabs/talos/releases/download/v1.4.0/talos-amd64.iso

Proxmox/PVE:
v7.3-3

### Logs

As per in the clip above

### Environment

- Talos version: v1.4.0
- Kubernetes version: N/A
- Platform: Proxmox/X86

**Comment by zulhfreelancer** [comment]
Tried again using ISO from latest ([v1.4.2](https://github.com/siderolabs/talos/releases/tag/v1.4.2)) release. Problem persist.


https://github.com/siderolabs/talos/assets/3416976/d5072698-bab1-4ef4-a9b7-398b382d2538

**Comment by zulhfreelancer** [comment]
Went all the way down to release [v0.7.0-beta.0](https://github.com/siderolabs/talos/releases/tag/v0.7.0-beta.0) as per in [this](https://www.youtube.com/watch?v=MyxigW4_QFM) tutorial video — it's not bootlooping with this `v0.7.0-beta.0` ISO. I can see private IP on my Promox VNC console. I wonder what's the latest stable ISO for Proxmox is?

**Comment by frezbo** [comment]
Have you set the cpu v2 microarchitecture as mentioned here: https://www.talos.dev/v1.4/talos-guides/install/virtualized-platforms/proxmox/#create-vms?

**Comment by zulhfreelancer** [comment]
> Have you set the cpu v2 microarchitecture as mentioned here: https://www.talos.dev/v1.4/talos-guides/install/virtualized-platforms/proxmox/#create-vms?

Thanks. Setting the Processor Type to `host` worked for me.
