### ISSUE TITLE
(docs) enabling system extensions on the Raspberry Pi

### ISSUE THREAD

**Issue by mirceanton** [siderolabs/talos#7218]
## Feature Request

Document the need for in-place upgrade to enable system extensions (like iscsi) on the Pi (and probably other SBCs as well, I assume).

### Description

I had a bit of trouble understanding why my system extensions were not enabled on my Pi 4 cluster, even though they were configured in the file. Upon further investigation, I found out that I have to do an in-place upgrade after the install in order to enable the extensions, since on the Pi I am not actually installing the os to the drive when doing the config apply.

Maybe mentioning this in the docs, in the Raspberry Pi setup guide, would be a good addition?

**Comment by OGKevin** [comment]
https://www.talos.dev/v1.4/talos-guides/configuration/system-extensions/#building-a-talos-image-with-system-extensions can also be used to build a rpi image with the extension enabled. So that you don't have to do an in place upgrade.

**Comment by mirceanton** [comment]
Yep, that just seemed like more trouble than the upgrade since the SD cards were already flashed and in the Pis.

I was mostly referring to this page https://www.talos.dev/v1.4/talos-guides/install/single-board-computers/rpi_4/ as well as some of the YouTube videos on the Sidero channel about the Pi4 which showcase `dd`-ing the image to the SD card directly.

**Comment by OGKevin** [comment]
Yea so if you dd your custom image with the extensions installed, then you don't need to do the upgrade. 

I think this can be closed however, I'm favor of #5956.
