### ISSUE TITLE
Option on talosctl time to perform a clock sync

### ISSUE THREAD

**Issue by szinn** [siderolabs/talos#7250]
## Feature Request

Add a flag to the talosctl time command to sync the node's clock to the NTP server.

### Description

After upgrades / reboots, even though the node syncs the clock, there sometimes is a noticable difference (100's ms) in the nodes. I know that talos does sync the clock on some schedule, but that means issues like rook reporting a time skew doesn't get resolved until talos decides to sync clocks.

This option would trigger that time sync immediately to resolve any time differences.

I do notice that even though all nodes are using the same NTP server, in my case, local, that they sometimes get out of skew.

**Comment by smira** [comment]
Talos syncs the clock using Linux kernel interfaces to slow down/speed up system clock to catch up with the skew. This avoids time jumps which might be destructive for workloads. I'm not sure what exactly Rook monitors, but I would look into why you would ever get 100s of ms of time difference after a reboot, this is not normal.
