### ISSUE TITLE
Kubernetes Upgrade Error: "No Controlplane Nodes Discovered"

### ISSUE THREAD

**Issue by obi12341** [siderolabs/talos#7253]
Hello,

I'm facing an issue when trying to upgrade Kubernetes on my Talos Linux system. During the upgrade process, I encounter the following error message: "no controlplane nodes discovered."

This error message appears when I execute the upgrade-k8s command. I've checked and all the master nodes seem to be properly configured and are running as expected. Moreover, network connections among nodes are intact and the firewall settings seem to allow inter-node communications.

In addition, I've made sure that the talosctl tool is correctly configured and has access to all the Controlplane nodes. Yet, the problem persists.

Here are the versions I'm currently using:

    Talos version: v1.4.4
    Kubernetes version: 1.27.1
    Platform: Hetzner Cloud

Could you provide some guidance on this issue? What could be causing the error and how can I resolve it?

Thank you in advance for your help.

Best regards,

obi12341

Log:
```
# talosctl --talosconfig talosconfig --nodes <control plane node> upgrade-k8s
automatically detected the lowest Kubernetes version 1.27.1
no controlplane nodes discovered
```

**Comment by frezbo** [comment]
the endpoint is probably set to a worker node, please use a `controlplane` ip as the endpoint

**Comment by obi12341** [comment]
nope the endpoint i am using is definitly a control plane. I have also tried with every 3 controlplane endpoint ips.

**Comment by frezbo** [comment]
is a worker endpoint is set in the talosconfig?

**Comment by frezbo** [comment]
please try using `--endpoint` to the talosctl command explicitly

**Comment by obi12341** [comment]
same error:
```
# talosctl --talosconfig talosconfig --nodes <controlplane IP> --endpoint <controlplane IP> upgrade-k8s --dry-run
automatically detected the lowest Kubernetes version 1.27.1
no controlplane nodes discovered
```

**Comment by frezbo** [comment]
oh, you might have discovery service disabled, in that case you'd have to manually edit the machineconfig for now

**Comment by obi12341** [comment]
hmm i enabled the kuberentes registry discovery now and node gets the annotation `cluster.talos.dev/node-id: <id>` but still the error persists. Even `talosctl get members` lists all of my nodes

**Comment by smira** [comment]
`talosctl upgrade-k8s` does the equivalent of `kubectl get nodes` and looks for `Node` resources with `controlplane` label. So something should be off in your cluster if it doesn't find anything.

the `-n` (`--nodes`) flag should be set to one of the controlplane nodes.

please post `kubectl get nodes -o wide` for this cluster is the problem persists

**Comment by obi12341** [comment]
Thanks for your answer, it still persists:

```
❯ talosctl -n 95.xx.xx.xx upgrade-k8s --dry-run
automatically detected the lowest Kubernetes version 1.27.1
no controlplane nodes discovered

❯ kubectl get nodes -o wide
NAME                    STATUS   ROLES           AGE   VERSION   INTERNAL-IP   EXTERNAL-IP       OS-IMAGE         KERNEL-VERSION   CONTAINER-RUNTIME
talos-control-plane-1   Ready    control-plane   10d   v1.27.1   <none>        95.xx.xx.xx    Talos (v1.4.4)   6.1.28-talos     containerd://1.6.21
talos-control-plane-2   Ready    control-plane   10d   v1.27.1   <none>        128.xx.xx.xx    Talos (v1.4.4)   6.1.28-talos     containerd://1.6.21
talos-control-plane-3   Ready    control-plane   10d   v1.27.1   <none>        167.xx.xx.xx   Talos (v1.4.4)   6.1.28-talos     containerd://1.6.21
talos-worker-1          Ready    <none>          10d   v1.27.1   <none>        162.xx.xx.xx    Talos (v1.4.4)   6.1.28-talos     containerd://1.6.21
talos-worker-2          Ready    <none>          10d   v1.27.1   <none>        162.xx.xx.xx    Talos (v1.4.4)   6.1.28-talos     containerd://1.6.21
talos-worker-3          Ready    <none>          10d   v1.27.1   <none>        128.xx.xx.xx    Talos (v1.4.4)   6.1.28-talos     containerd://1.6.21

**Comment by smira** [comment]
hold on... could it be that the `Node`s have no `InternalIP` in the `status:`?

**Comment by smira** [comment]
ah, yes, that's the case, I can see it from the output. interesting case... we can do a fix for it

**Comment by obi12341** [comment]
yeah thats the case. I think following this tutorial: https://www.talos.dev/v1.4/talos-guides/install/cloud-platforms/hetzner/ there will be no internal network just an external one
