### ISSUE TITLE
Talosctl option for troubleshooting

### ISSUE THREAD

**Issue by tba77** [siderolabs/talos#7255]
Sometimes we have some issues with our talos cluster which is not related to any miss-configuration or mistake but rather due to some issues in other services like dns, network etc... So I would suggest to add some troubleshooting commands to talosctl to be able to ping other servers, query dns or check a tcp  port.
It would be great to have commands like

```
talosctl ping <ip address>
talosctl trace(route) <ip address>
talosctl nc <ip_address> <tcp_port>
talosctl dig @dns-server domaine_name type
```

**Comment by netthier** [comment]
Not what you proposed but talosctl has a `pcap` subcommand which could prove useful for troubleshooting.
And if the cluster isn't too broken, it should be possible to generate the appropriate ICMP/DNS/TCP traffic from within pods.

**Comment by tba77** [comment]
Yes we can do that with pods also, but it thought it could be interesting to have some useful diagnostic commands, as you said sometimes we can't create pods for that purpose.
