### ISSUE TITLE
Multiple boot options

### ISSUE THREAD

**Issue by frezbo** [siderolabs/talos#7258]
## Feature Request

once https://github.com/systemd/systemd/pull/27358 is merged we can have multiple boot options like in existing Talos (Eg: to wipe talos)

**Comment by smira** [comment]
Can we add e.g. ISO option to wipe all disks?

**Comment by frezbo** [comment]
> Can we add e.g. ISO option to wipe all disks?

not as of now, we;d need https://github.com/systemd/systemd/issues/24539 or a new uki with that cmdline
