### ISSUE TITLE
No RENEW requests on DHCP server from Talos

### ISSUE THREAD

**Issue by RussianFox** [siderolabs/talos#7263]
## Bug Report
Talos cant renew IP address with DHCP. No requests on server from Talos

### Description
I have Centos 8 and ISC DHCP on server

Talos v1.4.1
### Logs
DHCPDISCOVER request in logs look like this:

10.2.64.21: 2023-05-22T21:05:51.692Z DEBUG DHCP REQUEST {"component": "controller-runtime", "controller": "network.OperatorSpecController", "operator": "dhcp4", "link": "eth0"}
10.2.64.21: 2023-05-22T21:05:51.697Z DEBUG DHCP ACK {"component": "controller-runtime", "controller": "network.OperatorSpecController", "operator": "dhcp4", "link": "eth0", "dhcp": "opcode: BootReply, hwtype: Ethernet, hopcount: 0, transaction ID: 0x265ffbf4, num seconds: 0, flags: Unicast (0x00), client IP: 0.0.0.0, your IP: 10.2.64.57, server IP: 0.0.0.0, gateway IP: 0.0.0.0, client MAC: 00:50:56:94:89:94, server hostname:, bootfile name:, options:, Subnet Mask: ffffff00, Router: 10.2.64.1, Domain Name Server: 192.168.1.248, 10.2.94.248, Domain Name: k8s.local, IP Addresses Lease Time: 10m0s, DHCP Message Type: ACK, Server Identifier: 10.2.64.10"}

server IP: 0.0.0.0

And DHCP RENEW request sending to 0.0.0.0

In logs:

10.2.64.21: 2023-05-22T21:02:46.687Z DEBUG DHCP RENEW {"component": "controller-runtime", "controller": "network.OperatorSpecController", "operator": "dhcp4", "link": "eth0"}
10.2.64.21: 2023-05-22T21:03:21.691Z WARN request/renew failed {"component": "controller-runtime", "controller": "network.OperatorSpecController", "operator": "dhcp4", "error": "got an error while processing the request: no matching response packet received", "link": "eth0"}

If I use dnsmasq all work fine.

10.2.64.21: user: warning: [2023-05-23T06:09:31.686353605Z]: [talos] DHCP RENEW {"component": "controller-runtime", "controller": "network.OperatorSpecController", "operator": "dhcp4", "link": "eth0"}
10.2.64.21: user: warning: [2023-05-23T06:09:31.690401605Z]: [talos] DHCP ACK {"component": "controller-runtime", "controller": "network.OperatorSpecController", "operator": "dhcp4", "link": "eth0", "dhcp": "opcode: BootReply, hwtype: Ethernet, hopcount: 0, transaction ID: 0x2fff7d4d, num seconds: 0, flags: Unicast (0x00), client IP: 10.2.64.177, your IP: 10.2.64.177, server IP: 10.2.64.10, gateway IP: 0.0.0.0, client MAC: 00:50:56:94:dc:af, server hostname:, bootfile name:, options:, Subnet Mask: ffffff00, Router: 10.2.64.1, Domain Name Server: 192.168.1.248, 10.2.94.248, Domain Name: k8s.local, Broadcast Address: 10.2.64.255, IP Addresses Lease Time: 5m0s, DHCP Message Type: ACK, Server Identifier: 10.2.64.10, Renew Time Value: [0 0 0 138], Rebinding Time Value: [0 0 0 250]"}

server IP: 10.2.64.10

**Comment by RussianFox** [comment]
I mean, trouble there:

**Comment by smira** [comment]
RFC: https://www.ietf.org/rfc/rfc2131.txt, section 4.3.2:

```
   o DHCPREQUEST generated during RENEWING state:

      'server identifier' MUST NOT be filled in, 'requested IP address'
      option MUST NOT be filled in, 'ciaddr' MUST be filled in with
      client's IP address. In this situation, the client is completely
      configured, and is trying to extend its lease. This message will
      be unicast, so no relay agents will be involved in its
      transmission.  Because 'giaddr' is therefore not filled in, the
      DHCP server will trust the value in 'ciaddr', and use it when
      replying to the client.

      A client MAY choose to renew or extend its lease prior to T1.  The
      server may choose not to extend the lease (as a policy decision by
      the network administrator), but should return a DHCPACK message
      regardless.
```

RENEW request goes as unicast, so the server IP should be filled in.

**Comment by smira** [comment]
@twelho any ideas?

**Comment by netthier** [comment]
Also experiencing this with Talos v1.4.4 and OPNsense as the DHCP server.

**Comment by smira** [comment]
I wonder if the fix should be not to use `RENEW` if the server IP is not known
