### ISSUE TITLE
add driver for cisco VIC enic driver

### ISSUE THREAD

**Issue by melbruki** [siderolabs/talos#7279]
## Feature Request

add enic driver in kernel config 
set enic_config=y
This will allow talos to detect Cisco ucs vic card

**Comment by smira** [comment]
I guess this is https://cateee.net/lkddb/web-lkddb/ENIC.html, so `CONFIG_ENIC=y`. Please verify with your hardware (PCI IDs). 

This can be enabled in the next version of Talos, but you can also modify and build a custom image as well today.

**Comment by smira** [comment]
https://www.talos.dev/v1.4/advanced/customizing-the-kernel/

**Comment by melbruki** [comment]
Thank you , when do you think the next version of talos will be released with this change in it ?

**Comment by smira** [comment]
> Thank you , when do you think the next version of talos will be released with this change in it ?

This will be only available in Talos 1.5, somewhere Aug-Sep
