### ISSUE TITLE
Accidentally creating a folder via MachineFiles is irreversible

### ISSUE THREAD

**Issue by btrepp** [siderolabs/talos#7284]
## Bug Report

Create a file like
```  files:
    - content: 10.96.0.0/12
      permissions: 0644
      path: /var/etc/tailscale
      op: create
```

Release oops, I forgot one level of the structure. Edit your machine config

```
  files:
    - content: 10.96.0.0/12
      permissions: 0644
      path: /var/etc/tailscale/env/TS_ROUTES
      op: create
```

You are now stuck, you can't delete the folder, (no shell) the talos apply command doesn't appear to remove items that are in /var/. So this file can never be created

### Description

It's a bit unclear if there is a good 'immutable' store for files in talos. Internally it seems to use system and overlay things on boot (fantastic) but when configuring your machine, you don't quite get that luxury. /var/ seems to persist over reboots, so while you can write to it, you get a very 'stateful' situation, and there's no 'delete' command.

In some cases you could wipe the node, but if you have a single node master, it becomes scary and a bit of the supported path 

I have most likely missed something, but the only way I have found out is to re-image the machine from the talos binaries.

### Discussion

Is there a place where we can store files that maybe needed, and to say the folder structure looks exactly like *this* on reboot?.
/var seems for 'stateful' data.
Unfortunately /etc and /system don't seem to work with MachineFiles, I assume on reboot talos is setting that to a known state, but would be great if I could include my files for that too, or I messed this up and failed to write to etc properly

**Comment by frezbo** [comment]
Currently the files controller is not fully reactive, we've some plans to make `/var` be more easily manageable for a future version of Talos
