### ISSUE TITLE
3G modem support

### ISSUE THREAD

**Issue by mglants** [siderolabs/talos#7298]
### Description
   3G Modem plugged as modem, but not appearing as serial device
   As seen from logs driver not loaded
### Logs
```
 lsusb
Bus 003 Device 011: ID 05e3:0626 Genesys Logic, Inc. USB3.1 Hub
Bus 003 Device 002: ID 174c:1153 ASMedia Technology Inc. ASM1153 SATA 3Gb/s bridge
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 017: ID 12d1:1506 Huawei Technologies Co., Ltd. Modem/Networkcard
Bus 002 Device 011: ID 05e3:0610 Genesys Logic, Inc. Hub
Bus 002 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
```
ls -la /dev/ttyUSB*
ls: cannot access '/dev/ttyUSB*': No such file or director
```
```
        |__ Port 2: Dev 11, If 0, Class=Hub, Driver=hub/4p, 480M
            |__ Port 4: Dev 17, If 0, Class=Vendor Specific Class, Driver=, 480M
            |__ Port 4: Dev 17, If 1, Class=Vendor Specific Class, Driver=, 480M
            |__ Port 4: Dev 17, If 2, Class=Vendor Specific Class, Driver=, 480M
            |__ Port 4: Dev 17, If 3, Class=Vendor Specific Class, Driver=, 480M
```

### Environment
- Talos version: v1.3.7
- Kubernetes version: Server Version: v1.25.9
- Platform: arm64

**Comment by MGlants** [comment]
Found some information about modprobbing form other forums
#!/bin/bash
/sbin/modprobe option
/usr/bin/echo '12d1 1506' > /sys/bus/usb-serial/drivers/option1/new_id

But how to implement it in talos?

**Comment by MGlants** [comment]
CONFIG_USB_SERIAL_OPTION=y
should be enabled for achieve that

**Comment by smira** [comment]
I don't have an exact answer, but it would be nice if that addition to the kernel config could be compiled as a module.

If you have a working solution, please open a PR to `pkgs` to update the kernel config.

**Comment by MGlants** [comment]
@smira as i need to enable one more serial driver for linux kernel compile is it enough, or it should be added aside in packages?
My question is what the best way to do it.
Also insctructions in talos about rebuilding kernel is limited, because it's only corresponds to talos installer, but i have sidero with external link to vmlinuz from talos releases

**Comment by mglants** [comment]
Done by impementing extensions with modem support
