### ISSUE TITLE
Extension not loading after shutdown but loads up after reboot

### ISSUE THREAD

**Issue by nebula-it** [siderolabs/talos#7306]
### Description
DRBD extension is not loading after a shutdown. But loads properly after a reboot using `talosctl reboot`

### Logs
Initiate shutdown of node (this is triggered from hypervisor (Hyper-V in this case)
```
10.0.0.0: kern:    info: [2023-06-01T05:12:00.771811718Z]: hv_utils: Shutdown request received - graceful shutdown initiated
10.0.0.0: user: warning: [2023-06-01T05:12:04.088343718Z]: [talos] shutdown via API received. actor id: xxxxx
```
On the next reboot, DRBD extension does not load. This is the log from dmesg:
```
10.0.0.0: user: warning: [2023-06-01T05:13:38.402101077Z]: [talos] controller failed {"component": "controller-runtime", "controller": "runtime.KernelModuleSpecController", "error": "error loading module \x5c"drbd\x5c": module not found"}
```
Running a `talosctl reboot -n 10.0.0.0` for that node fixes it and DRBD block device loads up fine
```
> talosctl read /proc/modules
drbd_transport_tcp 28672 - - Live 0xffffffffc057b000 (O)
drbd 655360 - - Live 0xffffffffc04c4000 (O)
```
### Environment

- Talos version: [`v1.4.4`]
- Kubernetes version: [`Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.27.1`]
- Platform: AMD64 on Hyper-V

**Comment by smira** [comment]
This looks like potentially booting from a different media - e.g. you have ISO mounted or PXE booting vs. booting from disk. Extensions are only installed on disk, and `reboot` does `kexec` which forces boot from disk essentially.

**Comment by nebula-it** [comment]
Confirmed that was the issue. I still had the ISO attached to VM. Thank you :)
