### ISSUE TITLE
Unable to `upgrade-k8s` when running non-persistant installation

### ISSUE THREAD

**Issue by james-callahan** [siderolabs/talos#7365]
### Description

We deploy our AWS nodes using the officially provided AMI.

Trying to upgrade kubernetes using `talosctl upgrade-k8s` fails when persistence is turned off.

We already rolled the nodes to the new AMI (and hence have actually already upgraded kube-apiserver and etcd); but we still need to upgrade other system components, e.g. kube-flannel, kube-proxy, coredns.
As far as I can see, `upgrade-k8s` is the only way to get the new (e.g.) recommended flannel manifests which e.g. removed changed from `privileged: true` to `privileged: false` between Talos 1.3.x and 1.4.x.

### Logs

```
$ talosctl --talosconfig talosconfig.admin -n 10.16.128.4 upgrade-k8s --upgrade-kubelet=false --from 1.26.1 --to  1.27.1 --dry-run
WARNING: 10.16.128.4: server version 1.4.1 is older than client version 1.4.4
discovered controlplane nodes ["10.16.128.4" "10.16.136.4" "10.16.144.4"]
checking for removed Kubernetes component flags
checking for removed Kubernetes API resource versions
updating "kube-apiserver" to version "1.27.1"
 > "10.16.128.4": starting update
failed updating service "kube-apiserver": error updating node "10.16.128.4": error patching node config: config persistence is disabled, patching is not supported
```

### Environment

- Talos version: 1.4.5
- Kubernetes version: 1.26.1/1.27.2
- Platform: AWS

**Comment by frezbo** [comment]
`persist: false` should not  be used (this was a setting from way earlier), if used this is expected, since there is no source of truth saved anywhere

**Comment by james-callahan** [comment]
> `persist: false` should not be used (this was a setting from way earlier), if used this is expected, since there is no source of truth saved anywhere

Yes that's what I expected.
But I still need a way to get e.g. the updated Flannel manifests out of e.g. `talosctl`
Whether that's some new flag to `talosctl` to make it spit out the manifests; or if it does a `kubectl apply` for me (skipping the kube-apiserver when it's already running an adequate version or when `persist: false`)

**Comment by smira** [comment]
This is already documented, but I would advise not to use `persist: false` https://www.talos.dev/v1.4/kubernetes-guides/upgrading-kubernetes/#bootstrap-manifests
