### ISSUE TITLE
Support configurable resources for control-plane static pod components

### ISSUE THREAD

**Issue by LukasAuerbeck** [siderolabs/talos#7379]
## Feature Request

Add possbility to configure control-plane component resources to match the actual required load.

### Description

Currently all control-plane components that are deployed with a static pod configuration ([apiserver](https://github.com/siderolabs/talos/blob/8c071b5796db05ecb17e46295eb2140827a58ca8/internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go#L431), [scheduler](https://github.com/siderolabs/talos/blob/8c071b5796db05ecb17e46295eb2140827a58ca8/internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go#L738), [controller-manager](https://github.com/siderolabs/talos/blob/8c071b5796db05ecb17e46295eb2140827a58ca8/internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go#L604)) have hardcoded kubernetes resource requests. The resource usage, however, depends on the cluster size, which causes the hard-coded values and the actual used Memory/CPU to be off.

This usually doesn't have an effect, since the control-plane nodes usually shouldn't run any non-control-plane applications. However, it can mess with monitoring. For example, alerting if pods are using >100% of their requested resources, especially memory since this can lead to OOM kills of pods on the same node, causes false/non-fixable alerts. While it is possible to ignore them, it is not really a good solution to not monitor important components of the cluster.

A simple and straight forward solution would be to make the resources configureable in the clusterConfig. If this works for you, I would be happy to provide a PR to configure the resources for all three components.

**Comment by smira** [comment]
@LukasAuerbeck yep, this makes perfect sense to me, please do a PR!
