### ISSUE TITLE
Istio 1.18 and Ambient Mesh Support for Talos Kubernetes

### ISSUE THREAD

**Issue by distributethe6ix** [siderolabs/talos#7380]
## Feature Request
This is a feature request to have support for Istio 1.18 and it's Ambient Mesh Profile.
Ambient Mesh is a new additional mode of Istio, and offers a sidecar-less approach while still offering the capabilities of the Istio Service Mesh. We want to demonstrate that a combo of Talos + Istio Ambient provides a robust and secure approach to running microservices, while offering up a virtually non-existent surface area of attack. 

### Description
In Ambient Mesh, the sidecar functionality is shifted towards the **_ztunnel_**, which is a node-level and per-SA proxy that provides mTLS and L4 policy on behalf of a co-located pod. When the Ambient profile is enabled, the ztunnel is deployed as a daemonset, along with the Istio-CNI which is also deployed as a daemonset. The Istio-CNI is responsible for redirecting co-located pod traffic towards the ztunnel towards a destination service on another node in the same cluster. 

The additonal purpose of this request is that any attempt to install Istio Ambient on Talos fails, and this may have to do with the way the Istio-CNI leverages IPtables for redirection of traffic towards the ztunnel and Talos disallows any node-level network reconfiguration.

**Comment by frezbo** [comment]
> attempt to install Istio Ambient on Talos fails, and this may have to do with the way the Istio-CNI leverages IPtables for redirection of traffic towards the ztunnel and Talos disallows any node-level network reconfiguration.

Hey Marino :wave: ,

Talos doesn't prevent modifications using iptables. I think it could be ztunnel tried to load a module? Talos doesn;t allow loading modules by K8s workloads. Could you also provide the logs of the failed pod/daemonset?

**Comment by linsun** [comment]
Do you know what CNI Talos k8s is using?  also does this work with default profile?

**Comment by frezbo** [comment]
Do you know what CNI Talos k8s is using? 

talos uses flannel by default, but it can be disabled to install a cni of choice

also does this work with default profile?

not sure I get that, you mean K8s pod security profiles/seccomp profiles?

**Comment by distributethe6ix** [comment]
> > attempt to install Istio Ambient on Talos fails, and this may have to do with the way the Istio-CNI leverages IPtables for redirection of traffic towards the ztunnel and Talos disallows any node-level network reconfiguration.
> 
> Hey Marino 👋 ,
> 
> Talos doesn't prevent modifications using iptables. I think it could be ztunnel tried to load a module? Talos doesn;t allow loading modules by K8s workloads. Could you also provide the logs of the failed pod/daemonset?


> > Do you know what CNI Talos k8s is using?
> 
> talos uses flannel by default, but it can be disabled to install a cni of choice
> 
> > also does this work with default profile?
> 
> not sure I get that, you mean K8s pod security profiles/seccomp profiles?

Hi Noel!! How are you? Great to hear from you 😄 !!!

Lin is referring to the Istio installation profiles such as Default and Ambient, which proceed to install the necessary components of Istio.

Let me see if I can dig into some logs and share what I find.
