### ISSUE TITLE
installation.disk isn't honored on 1.4.5

### ISSUE THREAD

**Issue by rkbennett** [siderolabs/talos#7381]
## Bug Report
When deploying a new bare-metal node with the iso on a USB, if you've set the installation.disk to an nvme (nvme0n0) and apply the configuration, it will ignore the setting.

### Description
When deploying a new bare-metal node with the iso on a USB, if you've set the installation.disk to an nvme (nvme0n0) and apply the configuration, it will ignore this and still create partitions on the usb (/dev/sda in this instance) without ever performing the "install" on the target disk. I've tried also using the disk filters, but it always ends up on the usb instead of the nvme drive. 

### Environment
Talos version 1.4.5
kubernetes 1.27.2
nuc 12 w/ nvme drive

**Comment by frezbo** [comment]
do you have an existing install on the usb ?

**Comment by rkbennett** [comment]
I believe it ends up with one once I deploy it, but I've tried starting in maintenance mode as well where it has no configs. For reference when creating the usb I used rufus w/ the dd mode.

**Comment by frezbo** [comment]
i think rufus has a raw mode or something, are you using that?

**Comment by rkbennett** [comment]
That's what the dd mode is, It failed when trying to create it with rufus's "recommended" method.

**Comment by rkbennett** [comment]
Ahh, I completely rebuilt the usb and it ended up working, apparently maintenance mode didn't do what I thought it did. Should be all good now.
