### ISSUE TITLE
Support "Orange Pi 5" (rk3588s)

### ISSUE THREAD

**Issue by carnei-ro** [siderolabs/talos#7382]
## Feature Request

I'd like to run Talos on my Orange Pi 5, it is a pretty decent SBC with 16GB of RAM and 8 CPUs, also, it has TPU/NPU https://github.com/rockchip-linux/rknpu2

**Comment by jwhy89** [comment]
Talos is pretty kick ass! I would like this as well.

**Comment by jwhy89** [comment]
@carnei-ro this fella, https://github.com/milas/rock5-talos/issues/7,  seemed to have gotten it to work for another rk3588s sbc. Hopefully someone here can figure this out 🙏🏼

**Comment by Lenael** [comment]
I'm also waiting for that! Would be awesome to run few Talos nodes on Orange PI :-)

**Comment by TimJones** [comment]
By change we were recently donated a board so I'm working on adding it :smile:

**Comment by jwhy89** [comment]
> By chance we were recently donated a board so I'm working on adding it 😄

@TimJones lmk if you need another tester for the image and I can test it out. I just spun up a home lab cluster and have my orange pi 5 laying around collecting dust.

**Comment by TimJones** [comment]
Unfortunately, neither the Rockchip RK3588 nor the OrangePi 5 have been submitted to the upstream maintainers of the Linux kernel, so we won't be able to support it directly with a Talos build.

It looks as if the Manjaro maintainers have managed to port the 5.10 kernel firmware to 6.2 and released a kernel, so it should be possible to [customise the kernel](https://www.talos.dev/v1.4/advanced/customizing-the-kernel/) and patch in support that way.

**Comment by mister2d** [comment]
@TimJones the Rockchip RK3588 appears viable now in upstream Linux kernel. Any chance this work can resume? I'm really looking forward to moving my workloads to a low power cluster (greener) cluster.

**Comment by frezbo** [comment]
> @TimJones the Rockchip RK3588 appears viable now in upstream Linux kernel. Any chance this work can resume? I'm really looking forward to moving my workloads to a low power cluster (greener) cluster.

Talos ships LTS kernel, so might be a while until it lands in the next LTS which is probably next year

**Comment by frezbo** [comment]
> > > @TimJones the Rockchip RK3588 appears viable now in upstream Linux kernel. Any chance this work can resume? I'm really looking forward to moving my workloads to a low power cluster (greener) cluster.
> > 
> > 
> > Talos ships LTS kernel, so might be a while until it lands in the next LTS which is probably next year
> 
> I see.
> 
> Are there build instructions that I can use an RC kernel with? The documentation isn't too clear on how to choose a kernel branch from upstream.

https://github.com/siderolabs/pkgs/tree/main/kernel change the kernel used here and build a custom installer referencing that kernel
