### ISSUE TITLE
Talosctl reboot behaves unexpectedly with statefulsets

### ISSUE THREAD

**Issue by btrepp** [siderolabs/talos#7385]
## Bug Report

Running
```
talosctl -n mynode reboot
```

Successfully reboots the node, but stateful sets end up being in 'Complete', causing the services to not run up again. Even if there are other nodes available they could run on.

### Description

I imagine this is a Kubernetes behaviour, as the stateful set might hold onto the PVC, so won't be scheduled until the completed pod is removed, but it's a bit unexpected.

I'm unsure if this the specific way that talos is causing items to be rebooted?.

The workaround at the moment I have is to run.
```
kubectl delete pod --field-selector=status.phase==Succeeded
```

for the various namespaces

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
```
Client:
	Tag:         v1.4.4
	SHA:         168114fc
	Built:       
	Go version:  go1.20.4
	OS/Arch:     darwin/arm64
Server:
	NODE:        rpi2
	Tag:         v1.4.4
	SHA:         168114fc
	Built:       
	Go version:  go1.20.4
	OS/Arch:     linux/arm64
	Enabled:     RBAC
```
- Kubernetes version: [`kubectl version --short`]
```
kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.27.1
```
- Platform: rpi2/macOS

**Comment by frezbo** [comment]
This seems similar to https://github.com/kubernetes/kubernetes/issues/117018

Thinking it's a bug on k8s side

**Comment by nberlee** [comment]
I am tracking https://github.com/kubernetes/kubernetes/issues/118310 fortthis

**Comment by stereobutter** [comment]
Also hit this surprising issue today with a StatefulSet. Is there any timeline on when/in which Kubernetes version this is going to be fixed?

**Comment by smira** [comment]
> Also hit this surprising issue today with a StatefulSet. Is there any timeline on when/in which Kubernetes version this is going to be fixed?

Check the Kubernetes issue https://github.com/kubernetes/kubernetes/issues/118310 above, it has all the information, this is not a Talos issue.
