### ISSUE TITLE
Document issue in vagrant setup

### ISSUE THREAD

**Issue by godsarmy** [siderolabs/talos#7386]
## Bug Report
Incorrect yaml path to setup cluster by Vagrant in document.

### Description
I am new user of Talos to evaluate this charming product. I tried to setup a basic cluster with vagrant but found a minor issue in document ( https://www.talos.dev/v1.4/talos-guides/install/virtualized-platforms/vagrant-libvirt/#installing-talos )

Apparently the yaml file controlplane.yaml generated by command "talosctl gen config" does not have top level key "spec". 
According to my shallow understanding, spec is only available in machine configuration dump (e.g. generated by command "talosctl -n <node-ip> get machineconfig -o yaml)

If you confirm it should be corrected, I am more than happy to provide a PR to fix it. I see the contents are in following files in repo

website/content/v1.2/talos-guides/install/virtualized-platforms/vagrant-libvirt.md 
website/content/v1.3/talos-guides/install/virtualized-platforms/vagrant-libvirt.md 
website/content/v1.4/talos-guides/install/virtualized-platforms/vagrant-libvirt.md 
website/content/v1.5/talos-guides/install/virtualized-platforms/vagrant-libvirt.md 

Thank you.

### Logs
N/A

### Environment

- Talos version: Client:
	Tag:         v1.4.5
	SHA:         45679b0e
	Built:       
	Go version:  go1.20.4
	OS/Arch:     linux/amd64
Server:
	NODE:        192.168.121.131
	Tag:         v1.4.5
	SHA:         45679b0e
	Built:       
	Go version:  go1.20.4
	OS/Arch:     linux/amd64
	Enabled:     RBAC

- Kubernetes version: 

Client Version: v1.27.3
Kustomize Version: v5.0.1
Server Version: v1.27.2

- Platform:
Linux (ubuntu 22.04)

**Comment by frezbo** [comment]
Thank you, fixes are always welcome ❤️
