### ISSUE TITLE
OS Installer Fails to Set Correct Default Boot Option on UEFI Systems with NVMe Drive

### ISSUE THREAD

**Issue by melbruki** [siderolabs/talos#7391]
Description
Upon completing the installation of talos on a system with UEFI firmware and an NVMe drive, the system fails to boot automatically from the correct .efi boot file. As a result, the system does not start the operating system as expected after installation and upon restart.

Steps to Reproduce
Perform a fresh installation of talos on a system with UEFI firmware and an NVMe drive.
Follow the installation process to completion and restart the system as prompted.
Expected Behavior
After the system restarts, it should automatically boot the newly installed operating system without any additional user intervention.

Actual Behavior
Upon restart, the system does not automatically boot into the installed operating system. Instead, manual intervention is required to boot from the correct .efi file in the UEFI shell.

Additional Information
The system can be booted manually by navigating to the correct .efi boot file in the UEFI shell. This suggests that the system and drive are capable of supporting the boot process, but the automatic boot configuration set during the installation is not functioning as expected.

**Comment by frezbo** [comment]
I think this is probably due to the UEFI not honoring the EFI variable

**Comment by melbruki** [comment]
> I think this is probably due to the UEFI not honoring the EFI variable

Is this something that will be fixed in the future?

**Comment by ishankhare07** [comment]
I havw this issue as well. How do I fix this?
