### ISSUE TITLE
Unable to change `cluster.serviceAccount` on running clusters

### ISSUE THREAD

**Issue by flokli** [siderolabs/talos#7418]
## Bug Report
We're using [amazon-eks-pod-identity-webhook](https://github.com/aws/amazon-eks-pod-identity-webhook) to use Kubernetes Service account tokens to assume roles in AWS.

It turns out AWS doesn't like the ES256 id tokens:

```
<ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidIdentityToken</Code>
    <Message>The ID Token provided is not a valid JWT. (You may see this error if you sent an Access Token)</Message>
  </Error>
  <RequestId>916adaf6-0760-4900-890f-eb8c4cb54a6b</RequestId>
</ErrorResponse>
```

We compared the ID tokens, and saw the ones created by EKS clusters use `RS256` in `alg`, whereas the ones created by Talos use `ES256`.

The private key used for service account token generation can be explicitly passed with the `cluster.serviceAccount.key` parameter: https://www.talos.dev/v1.4/reference/configuration/#clusterconfig

### Description
Changing the `cluster.serviceAccount.key` parameter in an existing cluster doesn't change anything.

`talosctl -n $node read /system/secrets/kubernetes/kube-apiserver/service-account.pub` keeps showing the old key material.

Recreating the cluster from scratch, with different `cluster.serviceAccount.key` specified on creation does work.

I'd expect this to be possible to update at runtime, and `kube-apiserver` to be restarted (or reloaded if supported).

### Environment

- Talos version: v1.4.5
- Kubernetes version: v1.27.1
- Platform: x86_64

**Comment by frezbo** [comment]
it should, from: https://www.siderolabs.com/blog/workload-identity-for-kubernetes-on-gcp/

```bash
RSA_KEY_ENCODED=$(openssl genrsa 4096 2> /dev/null | base64 -w 0)

# first get the IP's of control plane nodes
CONTROL_PLANE_NODE_ADDRESSES=$(kubectl --kubeconfig kubeconfig get nodes --output json | jq -r '.items[] | select(.metadata.labels."node-role.kubernetes.io/control-plane" == "").status.addresses[] | select(.type == "ExternalIP").address')

# now patch each control plane node
for NODE_ADDRESS in ${CONTROL_PLANE_NODE_ADDRESSES}; do
    talosctl \
        --talosconfig talosconfig \
        --nodes "${NODE_ADDRESS}" \
        patch mc \
        --immediate \
        --patch "[{\"op\": \"add\", \"path\": \"/cluster/apiServer\", \"value\": {\"extraArgs\": {\"api-audiences\": \"https://kubernetes.default.svc.cluster.local,iam.googleapis.com/${OIDC_PROVIDER_URL}\", \"service-account-issuer\": \"https://storage.googleapis.com/${BUCKET_NAME}\", \"service-account-jwks-uri\": \"https://storage.googleapis.com/${BUCKET_NAME}/keys.json\"}}}, {\"op\": \"add\", \"path\": \"/cluster/serviceAccount\", \"value\": {\"key\": \"${RSA_KEY_ENCODED}\"}}]"
done

```

**Comment by flokli** [comment]
Could this have been a recent fix?

This was done through the terraform provider, via a `talos_machine_configuration_apply` resource and a `config_patches` in it.

I definitely saw Terraform showing changes changes, and Talos API complaining about missing base64 encoding initially, but the `talosctl -n $node read /system/secrets/kubernetes/kube-apiserver/service-account.pub` output didn't seem to have updated. I can try with another cluster later this week, and wait a bit longer?

**Comment by frezbo** [comment]
> Could this have been a recent fix?

this used to be long ago.

wrt TF, using v1? the old version had bugs around applying patches needing a second run.

> output didn't seem to have updated. I can try with another cluster later this week, and wait a bit longer?

hmm if it doesn't update, definitely a bug

**Comment by flokli** [comment]
Ok, indeed it does recreate certificates, it just took a minute or two until it was done and then started restarting `kube-apiserver` pods. Reverting that change in terraform also successfully moved things back to ES256, so all in all it seems to be working.

Sorry for the noise! :laughing:
