### ISSUE TITLE
rename 'in-cluster Kubernetes API load balancer' to KubePrism

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#7432]
Rename:

* machine config feature name
* release notes
* controllers/resources as appropriate

**Comment by TimJones** [comment]
Or (Talos|Kube)Prism ...

**Comment by sergelogvinov** [comment]
Is it possible to customize the listen IP address too?

**Comment by smira** [comment]
> Is it possible to customize the listen IP address too?

no, it will always listen on localhost (never exposing it to the outside world)
