### ISSUE TITLE
talosctl dashboard errors out.

### ISSUE THREAD

**Issue by steverfrancis** [siderolabs/talos#7438]
## Bug Report
talosctl dashboard results in local panic 
### Description
talosctl dashboard  -e 192.168.64.51 --nodes 192.168.64.51 --talosconfig=./talosconfig
panic: open /proc/cmdline: no such file or directory

This is on Server:
	NODE:        192.168.64.51
	Tag:         v1.4.6
	SHA:         8615b213
	Built:       
	Go version:  go1.20.5
	OS/Arch:     linux/arm64
	Enabled:     RBAC
running in qemu on Mac on ARM.

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: [`kubectl version --short`]
- Platform:

**Comment by frezbo** [comment]
This should have been fixed in v1.4.6 :thinking:

**Comment by smira** [comment]
This is the 4th issue on this one, looks like the feature is popular, and yes, it was fixed in 1.4.6
