### ISSUE TITLE
Unable to Apply extraManifest Due to gRPC Max Message Size Limit

### ISSUE THREAD

**Issue by dnugmanov** [siderolabs/talos#7482]
## Bug Report
When attempting to apply extraManifest files larger than approximately 3.5MB, I encounter an issue due to the gRPC max message size being limited to 4MB.

### Logs
❯ t upgrade-k8s --dry-run --to 1.26.3
automatically detected the lowest Kubernetes version 1.26.3
discovered controlplane nodes ["10.232.55.195" "10.232.55.196" "10.232.55.197"]
discovered worker nodes ["10.232.55.198" "10.232.55.199"]
updating "kube-apiserver" to version "1.26.3"
 > "10.232.55.195": starting update
 > "10.232.55.196": starting update
 > "10.232.55.197": starting update
updating "kube-controller-manager" to version "1.26.3"
 > "10.232.55.195": starting update
 > "10.232.55.196": starting update
 > "10.232.55.197": starting update
updating "kube-scheduler" to version "1.26.3"
 > "10.232.55.195": starting update
 > "10.232.55.196": starting update
 > "10.232.55.197": starting update
updating kube-proxy to version "1.26.3"
 > "10.232.55.195": starting update
 > skipped in dry-run
 > "10.232.55.196": starting update
 > skipped in dry-run
 > "10.232.55.197": starting update
 > skipped in dry-run
updating kubelet to version "1.26.3"
 > "10.232.55.195": starting update
 > "10.232.55.196": starting update
 > "10.232.55.197": starting update
 > "10.232.55.198": starting update
 > "10.232.55.199": starting update
rpc error: code = ResourceExhausted desc = grpc: received message larger than max (5330853 vs. 4194304)

## Environment

- Talos version: \`talosctl version --nodes <problematic nodes>\`
- `talosctl version` output:
  ```plaintext
  Client:
    Tag:         v1.4.6
    SHA:         8615b213
    Built:
    Go version:  go1.20.5
    OS/Arch:     darwin/amd64
  Server:
    NODE:        10.232.55.195
    Tag:         v1.4.6
    SHA:         8615b213
    Built:
    Go version:  go1.20.5
    OS/Arch:     linux/amd64
    Enabled:     RBAC
- Kubernetes version: [`kubectl version --short`] - 1.26.3
- Platform: openstack

**Comment by smira** [comment]
We should probably document it better, but certainly there should be a limit to the `extraManifest` size. There might be some workarounds we could enable with compression, but at some size the manifests should be managed via some other form of automation.
