### ISSUE TITLE
Enable dm-raid module to support LVM mirror LVs

### ISSUE THREAD

**Issue by vladimirfx** [siderolabs/talos#7483]
### Discussed in https://github.com/siderolabs/talos/discussions/7481

<div type='discussions-op-text'>

<sup>Originally posted by **eshikhov** July 15, 2023</sup>
Hi!

To provide PV we use https://github.com/metal-stack/csi-driver-lvm, when using storageclass csi-driver-lvm-linear everything works, but when using csi-driver-lvm-mirror it gives the error: 
```
"Failed to load existing device cache from /etc/lvm/cache/.cache
    Executing: /sbin/modprobe dm-raid
modprobe: module dm-raid not found in modules.dep
  /sbin/modprobe failed: 1
  raid1: Required device-mapper target(s) not detected in your kernel.
  Run `lvcreate --help' for more information."
```
Tried to add via KernelConfig.modules add dm-raid talos gives error:
 ```
 "user: warning: [2023-07-14T21:06:37.868957414Z]: [talos] controller failed {" component": "controller-runtime", "controller": "runtime.KernelModuleSpecController", "error": "error loading module \x5c"md-raid\x5c": module not found"}"
``` 
it is possible to load the dm-raid module ?
</div>

**Comment by smira** [comment]
yes, this is something we can do. 

In the Talos security design, workloads can't load modules, but it can be loaded via Talos machine config.

So it can either be built into Talos, or built as a kernel module (requires explicit loading). Not sure what is the best way, as DM_MIRROR is built in already.

**Comment by vladimirfx** [comment]
> yes, this is something we can do.
> 
> In the Talos security design, workloads can't load modules, but it can be loaded via Talos machine config.
> 
> So it can either be built into Talos, or built as a kernel module (requires explicit loading). Not sure what is the best way, as DM_MIRROR is built in already.

I think it should be build in, because this module is just an API bridge (adapter) between LVM and mdraid which both are build in.

**Comment by vladimirfx** [comment]
> the way to use it will be to load it explicitly in the machine config:
> 
> ```yaml
> machine:
>     kernel:
>         modules:
>             - name: dm-raid
> ```

OK, it is usable but slightly strange from user's point of view:
`LVM` is built into kernel, `mdraid` is built in either. Specific type of LVM logical volume is require some configuration that is just 'glue' `lvm` and `mdraid`.

Is `dm-raid` resource intensive or open some attack surface?

**Comment by smira** [comment]
@vladimirfx previously we didn't have a good way to make Talos Linux kernel modular, but now we do, so we would rather push new stuff as modules, as we certainly don't want to compile in everything.
