### ISSUE TITLE
gVisor example extension image doesn't exist

### ISSUE THREAD

**Issue by ipuustin** [siderolabs/talos#7551]
### Description

When Talos configuration is generated with `talos gen config`, the config files contain commented-out code for loading gvisor extension. However, the image reference `ghcr.io/siderolabs/gvisor:20220117.0-v1.0.0` doesn't exist in the registry. Could you update the example code to refer to an existing image, such as `ghcr.io/siderolabs/gvisor:20231214.0-v1.4.6` for Talos 1.4.6? Thanks!

### Logs

```
$ talosctl upgrade -n 192.168.122.3
◲ watching nodes: [192.168.122.3]
    * 192.168.122.3: 1 error(s) occurred:
    sequence error: sequence failed: error running phase 10 in upgrade sequence: task 1/1: failed, 1 error(s) occurred:
    failed to pull image "ghcr.io/siderolabs/gvisor:20220117.0-v1.0.0": failed to resolve reference "ghcr.io/siderolabs/gvisor:20220117.0-v1.0.0": ghcr.io/siderolabs/gvisor:20220117.0-v1.0.0: not found
```

### Environment

- Talos version: v1.4.6

**Comment by evanrich** [comment]
I wonder, why was this commented out? it seems like having gvisor installed would be a good thing?   Always wondered  why, but can't find any documentation to indicate the reason why.

**Comment by smira** [comment]
Examples are not always supposed to work exactly the way they are, but I wish they were this way. 

For current version of the extension matching your Talos version please see https://github.com/siderolabs/extensions
