### ISSUE TITLE
Use RuntimeDefault as default seccomp profile

### ISSUE THREAD

**Issue by uhthomas** [siderolabs/talos#7575]
### Description

I believe the current default is the Unconstrained profile. It would be nice to use RuntimeDefault by default and force users to opt-in to the Unconstrained profile instead.

https://kubernetes.io/docs/tutorials/security/seccomp/#enable-the-use-of-runtimedefault-as-the-default-seccomp-profile-for-all-workloads

**Comment by frezbo** [comment]
This has been the default since Talos 1.2

**Comment by uhthomas** [comment]
> This has been the default since Talos 1.2

Are you sure? I don't see any documentation or code for it.

I know seccomp profiles were enabled by default in https://github.com/siderolabs/talos/issues/5293, but I am not sure Talos uses RuntimeDefault by default?

**Comment by frezbo** [comment]
https://github.com/siderolabs/talos/releases/tag/v1.2.0 it's in the release notes.

Kubelet is configured with the flag https://github.com/siderolabs/talos/blob/0f1920bdda5b7f2e2291e75d14453cf81a1b6cd6/internal/app/machined/pkg/controllers/k8s/kubelet_spec.go#L271

It's in the kubelet config file, you might have searched for the cli flags

**Comment by uhthomas** [comment]
Ah, I see, thank you! This is great to know.

I wonder why Kubernetes complains about containers which don't explicitly set the seccomp profile to RuntimeDefault. I guess that's a bug which should be filed with Kubernetes.

Thank you again.

**Comment by frezbo** [comment]
> I wonder why Kubernetes complains about containers which don't explicitly set the seccomp profile to RuntimeDefault. I guess that's a bug which should be filed with Kubernetes.

That's just a warning since Pod security admission is enabled
