### ISSUE TITLE
ISO install does not work

### ISSUE THREAD

**Issue by tjeske** [siderolabs/talos#7604]
### Description

I have tried to install talos on an amd64 bare metal box and I am getting some weird connection issues.

This what I have done:
(1) boot from ISO
(2) `talosctl gen secrets -o secrets.yaml`
(3) `talosctl gen config --with-secrets secrets.yaml taloscluster https://<myserverip>:6443`
(4) `talosctl apply-config --insecure -n <myserverip>  --file controlplane.yaml`
(5) READY on the dashboard is always false

(I have also tried a different kubernetes version (1.25.4), no success)

### Logs

![grafik](https://github.com/siderolabs/talos/assets/14035220/7269dc06-88bf-4237-836f-b20f76a63ba7)

### Environment

- Talos version: 1.4.5
- Kubernetes version: 1.27.4 / 1.25.4
- Platform: amd64

**Comment by frezbo** [comment]
you have't run `talosctl bootstrap` yet and etcd is waiting to be up

**Comment by tjeske** [comment]
This does not work. `talosctl bootstrap -n <myserverip> --talosconfig=./talosconfig` outputs `error executing bootstrap: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: context deadline exceeded"`. IP address is correct.

**Comment by frezbo** [comment]
if you scroll up in the dashboard, it would print the IP address against to issue bootstrap

**Comment by smira** [comment]
you're probably not setting the endpoint right, please refer to the guide https://www.talos.dev/v1.4/introduction/getting-started/#understand-talosctl-endpoints-and-nodes
