### ISSUE TITLE
Ability to remove image-default kernel args

### ISSUE THREAD

**Issue by vladimirfx** [siderolabs/talos#7613]
## Feature Request

Please add 'removeKernelArgs' setting to install config which removes specified arg from image default kernel args. Args to remove should match exactly. 

### Description

Sometimes default kernel args can break boot. See https://github.com/siderolabs/talos/discussions/7465

**Comment by smira** [comment]
Probably going to be replaced by dropping console args in Talos 1.6 for `metal` platform

**Comment by vladimirfx** [comment]
> Probably going to be replaced by dropping console args in Talos 1.6 for `metal` platform

Yes, it is fixed our case. But this issue is more generic - it balances kernel args modification functionality. It up to you how to proceed 👍

**Comment by smira** [comment]
One idea: allow `-argument` and `-argument=value` notations, the first removes all `argument` values, and the second one removes just one value. Support it throughout the kernel arg handling/merging code.

**Comment by vladimirfx** [comment]
Thanks
