### ISSUE TITLE
Missing info in iscsi-tools documentation (Kubernetes -> Local Storage)

### ISSUE THREAD

**Issue by kevinhalgren** [siderolabs/talos#7616]
## Bug Report
Using example from Talos documentation, I am unable to apply the iscsi-tools patch.  It reports "missing kind"

### Description
When attempting to apply the patch.yaml from the listed example, I get the notice `missing kind`.  This appears to be an attribute that is now mandatory, however it is unclear what the kind field should be in this case.

https://github.com/siderolabs/talos/blob/release-1.5/website/content/v1.5/kubernetes-guides/configuration/replicated-local-storage-with-openebs-jiva.md#preparing-the-nodes

### Logs
Example from page above saved to `iscsi-patch.yaml`

```
khalgren@[redacted[:~/talos$ talosctl -e 192.168.68.[x] -n 192.168.68.[x] patch mc -p iscsi-patch.yaml
missing kind
```

### Environment
- Talos version:
```
Client:
        Tag:         v1.5.0-beta.1
        SHA:         bd44bf02
        Built:
        Go version:  go1.20.7
        OS/Arch:     linux/amd64
Server:
        NODE:        192.168.68.132
        Tag:         v1.5.0-beta.1
        SHA:         bd44bf02
        Built:
        Go version:  go1.20.7
        OS/Arch:     linux/amd64
        Enabled:     RBAC

```
- Kubernetes version:
```
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.28.0-rc.0
WARNING: version difference between client (1.26) and server (1.28) exceeds the supported minor version skew of +/-1
```
- Platform: metal-amd64

**Comment by smira** [comment]
I wonder if you had your patch mis-formatted, as the error means it wasn't parsed properly. I just verified it, and the patch is recognized in all modes.

**Comment by kevinhalgren** [comment]
Apologies, I apparently did misformat the command, I missed the "@" in my entry and completely failed to recognize it at the time retrying it again today it worked.  I'll close this issue.  Thanks!

talosctl -e 192.168.68.[x] -n 192.168.68.[x] patch mc -p @iscsi-patch.yaml
