### ISSUE TITLE
Talos v1.5.0 failing to deploy from ova template

### ISSUE THREAD

**Issue by agmtr** [siderolabs/talos#7627]
### Description
Hello! When I try to deploy ova, the template wants to allocate 8192.0 TB on the datastore and then fails.

### Logs
`The operation failed due to File [nfs_default_1] talos-vmware-1.5.0/talos-vmware-1.5.0.vmdk is larger than the maximum size supported by datastore 'nfs_default_1' 
`
### Environment

- Talos version: 1.5.0
- Kubernetes version: [`kubectl version --short`]
- Platform: VMware

**Comment by smira** [comment]
Thanks for reporting this, it's going to be fixed in 1.5.1. In the meantime you can extract `vmdk` as `tar` archive, and edit the capacity in `.ovf` file to be `8192`, and `tar` it back.

**Comment by agmtr** [comment]
> In the meantime you can extract `vmdk` as `tar` archive, and edit the capacity in `.ovf` file to be `8192`, and `tar` it back.

I already did this, thanks for the advice!

**Comment by axlroden** [comment]
I tried this, and it's erroring out when importing, is there a special order in doing this? Do you need to update the checksum as well ?
