### ISSUE TITLE
Upgrade to 1.5.0 on rpi_4 fails

### ISSUE THREAD

**Issue by githubcdr** [siderolabs/talos#7632]
## Bug Report

Upgrade fails with this error

```
talos-1rm-dzf.eigenhuis.lan: user: warning: [2023-08-17T20:05:00.067736937Z]: 2023/08/17 20:05:00 running Talos installer v1.5.0
talos-1rm-dzf.eigenhuis.lan: user: warning: [2023-08-17T20:05:00.074514937Z]: Error: unsupported board: "rpi_4"
talos-1rm-dzf.eigenhuis.lan: user: warning: [2023-08-17T20:05:00.079565937Z]: Usage:
talos-1rm-dzf.eigenhuis.lan: user: warning: [2023-08-17T20:05:00.082271937Z]:   installer install [flags]
```

### Description

```
talosctl upgrade --image ghcr.io/siderolabs/installer:v1.5.0 -n talos-1rm-dzf.eigenhuis.lan --preserve=true
```

from 1.4.8

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: [`kubectl version --short`]
- Platform:

**Comment by linuxmaniac** [comment]
Yes, same here

```
192.168.4.4: user: warning: [2023-08-17T22:04:37.087203496Z]: [talos] task upgrade (1/1): performing upgrade via "ghcr.io/siderolabs/installer:v1.5.0"
192.168.4.4: user: warning: [2023-08-17T22:04:37.103931496Z]: [talos] pulling extension "ghcr.io/siderolabs/iscsi-tools:v0.1.4"
192.168.4.4: user: warning: [2023-08-17T22:04:41.280997496Z]: 2023/08/17 22:04:17 running Talos installer v1.5.0
192.168.4.4: user: warning: [2023-08-17T22:04:41.287880496Z]: Error: unsupported board: "rpi_4"
192.168.4.4: user: warning: [2023-08-17T22:04:41.293375496Z]: Usage:
```

**Comment by frezbo** [comment]
This was an oversight when we removed the deprecated `rpi_4` board. So the fix for now is add an `extraKernelArgs` with `talos.platform=rpi_4` do an upgrade to v1.4.8 (upgrading to same version is fine), then upgrade to v1.5.0.

**Comment by frezbo** [comment]
oops, apologies, i meant to add `rpi_generic`

**Comment by nberlee** [comment]
kernel parameter `talos.board=rpi_generic` is working for me (please note, this is not `talos.platform=`)

**Comment by frezbo** [comment]
> kernel parameter `talos.board=rpi_generic` is working for me (please note **.board**, this is not `talos.platform=`)

Thank you, I got this messed up

**Comment by smira** [comment]
we need to implement a proper migration path here.
