### ISSUE TITLE
Talosctl get temperature

### ISSUE THREAD

**Issue by DreamingRaven** [siderolabs/talos#7639]
## Feature Request
Talos resourcedefinition to log system temperature stats

### Description
As a sysadmin I would like to be able to check system temperatures in talos, so that even before a kubernetes cluster is bootstrapped I can confirm things like the CPU, GPU, RAM, and motherboard temperature. This would be especially useful as I could then hook into this resource from kubernetes to setup continous monitoring in case a system approaches warning levels, for future automation like emails etc.

Please let me know if such a thing is currently possible as I could not find the relevant resourcedefinition or cli command to achieve this in 1.5.0.

```[tasklist]
### Tasks
- [ ] https://github.com/siderolabs/talos/issues/7646
```

**Comment by smira** [comment]
This might need kernel drivers to fetch the data first, which might not be available for all types of sensors atm.

If the kernel drivers are present, pulling temperature should work if it's available somewhere under `/sys` filesystem, but Talos doesn't have support to report that as a resource.

**Comment by DreamingRaven** [comment]
Hey Smira thanks for the expedient response and for the info, I will try this out to see if I can get the sensors with modules directly for now. Cheers.
