### ISSUE TITLE
Talos 1.5.0 doesn't support fully specified docker images for kubelet or etcd

### ISSUE THREAD

**Issue by james-callahan** [siderolabs/talos#7640]
### Description

After upgrading to Talos 1.5.0 it seems like you can't use a fully qualified image (i.e. with repository, tag and digest) for kubelet or etcd images any more.

If I drop the tag or digest, then it does work.

### Logs

Trying to use a fully qualified image gives me e.g.:

```
10.24.128.4: 2023/08/21 00:27:00.640656 [talos] service[etcd](Failed): Failed running service: error opening runner: image "gcr.io/etcd-development/etcd:v3.5.9@sha256:8c956d9b0d39745fa574bb4dbacd362ffdc1109479432f54094859d4cf984b17": not found
10.24.128.4: 2023/08/21 00:27:10.587930 [talos] service[kubelet](Failed): Failed running service: error opening runner: image "ghcr.io/siderolabs/kubelet:v1.28.0@sha256:50710f2cd3328c23f57dfc7fb00940d8cfd402315e33fc7cb8184fc660650a5c": not found
```

### Environment

- Talos version: 1.5.0
- Kubernetes version: 1.28.0
- Platform: aws

**Comment by smira** [comment]
I will take a look, probably image now gets stored in a canonical format, i.e. the tag is dropped if the digest is present.
