### ISSUE TITLE
Talos 1.5.0 does not seem to be compatible with k8s 1.26.6/.7

### ISSUE THREAD

**Issue by rgl** [siderolabs/talos#7648]
### Description

Talos 1.5.0 does not seems to be compatible with k8s 1.26.6/.7 (which is a supported version accordingly with https://www.talos.dev/v1.5/introduction/support-matrix/)

Works fine with k8s 1.27.4 and 1.28.0. I did not try other versions.

It would be nice to have some kind of periodic CI/CD test matrix that covers all the versions described at https://www.talos.dev/v1.5/introduction/support-matrix/.

### Logs

```console
$ talosctl logs kubelet
10.17.3.10: E0821 17:07:17.690542    2971 run.go:74] "command failed" err="failed to validate kubelet flags: the container runtime endpoint address was not specified or empty, use --container-runtime-endpoint to set"
```

### Environment

- Talos version:
```
Client:
	Tag:         v1.5.0
	SHA:         429a2de8
	Built:       
	Go version:  go1.20.7
	OS/Arch:     linux/amd64
Server:
	NODE:        10.17.3.10
	Tag:         v1.5.0
	SHA:         429a2de8
	Built:       
	Go version:  go1.20.7
	OS/Arch:     linux/amd64
	Enabled:     RBAC
```
- Kubernetes version: N/A
- Platform: nocloud

**Comment by smira** [comment]
Looks like we dropped it too early, thanks for reporting it, it only got properly handled to be part of the kubelet config in 1.27

**Comment by mirceanton** [comment]
+1 on this

Ran into it yesterday and I couldn't figure out what was wrong with my config. I wanted to deploy a 1.26.7 cluster for Rancher but couldn't get it to work. Ended up going back to 1.4
