### ISSUE TITLE
error connecting to CRI: context deadline exceede

### ISSUE THREAD

**Issue by FalkWinkler** [siderolabs/talos#7667]
I have a cluster on three proxmox nodes with the noncloud image and am using terraform to install the cluster.
- https://github.com/FalkWinkler/home-ops/tree/develop/terraform/proxmox

This works fine

If I install the cluster with flux, the cluster is broken after a few minutes.
- https://github.com/FalkWinkler/home-ops/tree/develop/kubernetes

error getting container list: 1 error occurred:
        * 192.168.10.31: rpc error: code = DeadlineExceeded desc = error connecting to CRI: context deadline exceeded

root ➜ /workspaces/home-ops/terraform/proxmox (develop) $ talosctl -n 192.168.10.31,192.168.10.32,192.168.10.33 --talosconfig talosconfig get svc
NODE            NAMESPACE   TYPE      ID           VERSION   RUNNING   HEALTHY   HEALTH UNKNOWN
192.168.10.31   runtime     Service   apid         2         true      true      false
192.168.10.31   runtime     Service   containerd   3         true      false     false
192.168.10.31   runtime     Service   cri          3         true      false     false
192.168.10.31   runtime     Service   dashboard    1         true      false     true
192.168.10.31   runtime     Service   etcd         3         true      false     false
192.168.10.31   runtime     Service   kubelet      57        true      false     false
192.168.10.31   runtime     Service   machined     2         true      true      false
192.168.10.31   runtime     Service   trustd       2         true      true      false
192.168.10.31   runtime     Service   udevd        2         true      true      false
192.168.10.32   runtime     Service   apid         2         true      true      false
192.168.10.32   runtime     Service   containerd   35        true      false     false
192.168.10.32   runtime     Service   cri          27        true      false     false
192.168.10.32   runtime     Service   dashboard    1         true      false     true
192.168.10.32   runtime     Service   etcd         9         true      true      false
192.168.10.32   runtime     Service   kubelet      10        true      true      false
192.168.10.32   runtime     Service   machined     2         true      true      false
192.168.10.32   runtime     Service   trustd       2         true      true      false
192.168.10.32   runtime     Service   udevd        2         true      true      false
192.168.10.33   runtime     Service   apid         2         true      true      false
192.168.10.33   runtime     Service   containerd   30        true      false     false
192.168.10.33   runtime     Service   cri          23        true      false     false
192.168.10.33   runtime     Service   dashboard    1         true      false     true
192.168.10.33   runtime     Service   etcd         7         true      true      false
192.168.10.33   runtime     Service   kubelet      38        true      true      false
192.168.10.33   runtime     Service   machined     2         true      true      false
192.168.10.33   runtime     Service   trustd       2         true      true      false
192.168.10.33   runtime     Service   udevd        2         true      true      false

**Comment by smira** [comment]
It's hard to guess, but most probably you're out of memory/disk/CPU.

**Comment by FalkWinkler** [comment]
That's it, now everything is up and running. I gave the control nodes more ram and cpu. I didn't even think about that.
