### ISSUE TITLE
Show Secureboot/TrustedBoot status in Talos Dashboard

### ISSUE THREAD

**Issue by frezbo** [siderolabs/talos#7675]

**Comment by smira** [comment]
probably also encrypted status (?) for the disks

**Comment by frezbo** [comment]
> probably also encrypted status (?) for the disks

yes, I was not sure if the dashboard shows secureboot and trustedboot explicitly

should we add trustedboot also as a field to securitystate?

**Comment by smira** [comment]
I mean in general encrypted state might be nice... probably we need to show encryption method as well (?)

**Comment by frezbo** [comment]
> I mean in general encrypted state might be nice... probably we need to show encryption method as well (?)

okay, this makes more sense, show encrypted state and method used
