### ISSUE TITLE
Cannot encrypt ephemeral partition (and bootloop)

### ISSUE THREAD

**Issue by uhthomas** [siderolabs/talos#7676]
### Description

I followed [the guide](https://www.talos.dev/v1.5/talos-guides/configuration/disk-encryption/#ephemeral-partition) for encrypting the ephemeral partition, but Talos is now stuck in a boot loop where it says the partition is not empty and cannot be encrypted.

I made this change:

```yaml
systemDiskEncryption:
  ephemeral:
    keys:
    - nodeID: {}
      slot: 0
```

Then ran:

```
❯ talosctl -n 192.168.1.78 apply-config -f machineconfig.yaml --mode=staged
Staged configuration to be applied after the next reboot
❯ talosctl -n 192.168.1.78 reset --system-labels-to-wipe EPHEMERAL --reboot=true
```

### Logs

![IMG_2177](https://github.com/siderolabs/talos/assets/9749173/830e9773-a45b-44cb-801a-591634eeaf36)

### Environment

- Talos version: v1.5.1
- Kubernetes version: 1.28.1
- Platform: bare metal (z790-p i5 13600k)

**Comment by frezbo** [comment]
disk encryption cannot be enabled on already installed disks as the error says, it can only be enabled at install time and not afterwards.

**Comment by uhthomas** [comment]
@frezbo Please reopen this - the docs I linked explicitly say otherwise.

**Comment by frezbo** [comment]
It's explicitly stated in the docs:

```text
There is no in-place encryption support for the partitions right now, so to avoid losing data only empty partitions can be encrypted.
```

**Comment by frezbo** [comment]
so the flow would be a staged apply and then wipe

**Comment by uhthomas** [comment]
> so the flow would be a staged apply and then wipe

Yes, and that is exactly what I did as I wrote in the original description of this issue.

**Comment by frezbo** [comment]
Apologies, I missed that completely

**Comment by frezbo** [comment]
I cannot reproduce this locally, I wonder if the wipe failed

**Comment by frezbo** [comment]
I can try on a machine with nvme disk on monday

**Comment by uhthomas** [comment]
@frezbo Before I fully wipe this disk to start from scratch, are there any logs I can get from it to help?

**Comment by frezbo** [comment]
> I can try on a machine with nvme disk on monday

I cannot reproduce this on an nvme also. I think the `reset` failed and talos tried to encrypt the a non-empty partition.

**Comment by smira** [comment]
either way, it's easier to wipe the node completely and apply machine config from the very beginning

**Comment by uhthomas** [comment]
@smira Can this not be closed without amending the documentation or something?

I don't understand why you aren't able to reproduce it.
