### ISSUE TITLE
Unicode characters are rendered as escape sequences

### ISSUE THREAD

**Issue by uhthomas** [siderolabs/talos#7678]
### Description

Characters like µ are rendered as escape sequences, which are not really useful to humans.

![image](https://github.com/siderolabs/talos/assets/9749173/1e079139-82b6-4b01-9ebc-88d31ce71d8e)

### Environment

- Talos version: v1.5.1
- Kubernetes version: [`kubectl version --short`]
- Platform:

**Comment by uhthomas** [comment]
no stale

**Comment by smira** [comment]
This should have been fixed some time in Talos 1.6/1.7 timeframe, if not, please re-open.
