### ISSUE TITLE
Make kernel version configurable to generate kernel module dependency tree for imager extensions

### ISSUE THREAD

**Issue by alexandrem** [siderolabs/talos#7684]
## Feature Request

Currently, the kernel version is defined as a constant `DefaultKernelVersion` inside the pkgs/machinery/constants package. This is used by the imager in `ProvidesKernelModules` to determine whether the system extension image contains kernel lib modules.

This prevents to use the imager to bundle system extensions that contain kernel modules for a different kernel version than the one hardcoded inside the imager binary, as the "preparing to run depmod to generate kernel modules dependency tree" sequence is skipped during the imaging.

For context, it may be desirable for customers to build a custom installer/imager with a different kernel version than the one pinned upstream, so it would be nice to not have this hardcoded into the Talos Linux imager in order to generate disk images with extensions that have the matching kernel modules.

### Description

Ideally, this could become a command-line argument to the imager, or the imager could determine the kernel version in the initramfs file when unpacking during rebuild.

Note that I'm not sure about the implications of this proposed change for the the Talos Linux upgrade operation.

**Comment by smira** [comment]
The problem will be that Talos itself will use `DefaultKernelVersion` to load kernel modules, so building a different version would most probably require a change to Talos at the moment. The request makes sense, but it should probably be a bigger change than just `imager`.

**Comment by smira** [comment]
(The `imager` part still makes sense, as it should be able to provide support for different versions of Talos still)

**Comment by alexandrem** [comment]
> The problem will be that Talos itself will use DefaultKernelVersion to load kernel modules

Curious, but where does that happen? Is it related to extensions images?

Talos Linux seems to work fine when I bake a different kernel version in the installer initramfs, even with other pkgs like nonfree-kmod-nvidia into a customization layer, even with the dynamic modules since the last few months.

**Comment by smira** [comment]
ah yes, I remember now, it takes kernel version from the running kernel, so if modules match, it should be okay.

so yes, what you're asking about is part of #7612
