### ISSUE TITLE
k8s.local in node name prevents workers from successfully installing

### ISSUE THREAD

**Issue by oliverwiegers** [siderolabs/talos#7685]
### Description

I have a similar issue like #7615. 
When setting the node name and hostname of Talos to `worker01.homelab.k8s.local` the cp nodes come up like intended and installation is successful. The worker nodes however have some strange issues from no containers are able to boot including the kubelet and so on to disk space full errors.
As soon as  I replace `k8s.local` with for example `oliverwiegers.com` producing nodes like `worker01.homelab.oliverwiegers.com` everything is fine.
Also using underscores in the hostnames does not seem to work properly either. 

Do you need anything more?

### Environment

- Talos version: 1.50.0
- Kubernetes version: v1.28.0
- Platform: libvirt

Thank you for your work and time.

**Comment by smira** [comment]
it's hard to say what's wrong as there're no details in the issue.

If you could grab `support.zip` from `talosctl support`, we could look into the issue

**Comment by ohauer** [comment]
- per RFC '_' are not allowed in hostnames or domains, the '_' is reserved for e.g. special SRV dns records
( [see additional some quick search results](https://www.google.com/search?q=hostname+allowed+characters) )
- the .local domain is similar case [for resons see](https://en.wikipedia.org/wiki/.local)
