### ISSUE TITLE
allow overriding SMBIOS UUID via META

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#7694]
Quite often bare-metal machines comes with invalid UUIDs (all zeroes, or duplicate values).

Omni and Sidero Metal use UUIDs to identify machines, and duplicate UUIDs break this scheme.

Allow overriding the UUID by writing to an (optional) `META` field which will replace the UUID in all subsequent UUID-based operations.

Example flow:

* machine boots with UUID of all zeroes
* machine establishes SideroLink connection
* Omni (or other orchestrator) discovers invalid UUID, and using Talos API writes META value with new UUID
* machine reconnects with new UUID

Notes:

* if Talos is not installed yet, META is preserved in memory, and will be flushed on next install

Steps:

* allow overriding via META (in SystemInformation resource)
* check that all places use UUID coming from SystemInformation resource
* allow META APIs in maintenance mode (only via SideroLink)

**Comment by DmitriyMV** [comment]
Closed in https://github.com/siderolabs/talos/pull/7935
