### ISSUE TITLE
Module dm-thin-pool not found

### ISSUE THREAD

**Issue by CompPhy** [siderolabs/talos#7695]
## Bug Report
I'm attempting to create a simple LINSTOR pool with `lvmThinPool` as outlined here:  https://github.com/piraeusdatastore/piraeus-operator/blob/v2/docs/reference/linstorsatelliteconfiguration.md#specstoragepools

It works just fine with `lvmPool`, but want to have this one setup as `lvmThinPool` for testing purposes.  Is there a plan to support this module?  I tried looking at the System Extension modules but I don't see any of the LVM/DM modules listed there either.  I am familiar with loading modules, and have dbrd loaded already, but don't see these others as an available option at the moment.

Storage pool configuration.
```
spec:
  storagePools:
    - name: pool1
      lvmThinPool: {}
      source:
        hostDevices:
          - /dev/sdb
```

Here's the output from LINSTOR error report.
```
Description:
    Failed to create lvm volume
Additional information:
    Command 'lvcreate --config devices { filter=['a|/dev/sdb|','r|.*|'] } -l 100%FREE -T -n vg1/thin' returned with exitcode 3. 

    Standard out: 


    Error message: 
    modprobe: FATAL: Module dm-thin-pool not found in directory /lib/modules/6.1.46-talos
      /sbin/modprobe failed: 1
      thin-pool: Required device-mapper target(s) not detected in your kernel.
      Run `lvcreate --help' for more information.
```

- Talos version:
  ```
  Client:
	  Tag:         v1.5.1
	  SHA:         40a22cdf
	  Built:       
	  Go version:  go1.20.7
	  OS/Arch:     linux/amd64
  Server:
	  NODE:        10.10.21.200
	  Tag:         v1.5.1
	  SHA:         40a22cdf
	  Built:       
	  Go version:  go1.20.7
	  OS/Arch:     linux/amd64
	  Enabled:     RBAC
  ```
- Kubernetes version:
  ```
  Client Version: v1.28.0
  Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
  Server Version: v1.28.0
  ```
- Platform: `VMWare`

**Comment by frezbo** [comment]
https://github.com/siderolabs/pkgs/pull/791/files i guess this is what you're looking for?

I'll get it in as an extension soon

**Comment by tendaworld** [comment]
After I attempted to create an lvmthin pool which fails according to the original opened issue. I then tried to create a LVM pool as below which also fails, as below.

```
➜  cloud git:(main) kubectl linstor physical-storage create-device-pool --pool-name ssd_lvm_pool LVM twl-cluster-talos-worker-kk3r /dev/sdb --storage-pool ssd_pool
ERROR:
Description:
    (Node: 'twl-cluster-talos-worker-kk3r') Failed to pvcreate on device: /dev/sdb
Details:
    Command 'pvcreate --config devices { filter=['a|/dev/sdb|','r|.*|'] } /dev/sdb' returned with exitcode 5. 
    
    Standard out: 
    
    
    Error message: 
      Can't initialize physical volume "/dev/sdb" of volume group "linstor_lvm_thin_pool" without -ff
      /dev/sdb: physical volume not initialized.
    
command terminated with exit code 10
```
Do you have any instructions to rollback this command, so I can use a different pool option?
#### Create device pool on a blank (no partitation table!) disk on node01
kubectl linstor physical-storage create-device-pool --pool-name nvme_lvm_pool LVM node01 /dev/nvme0n1 --storage-pool nvme_pool
