### ISSUE TITLE
Remote docker defect with TLS

### ISSUE THREAD

**Issue by kbaegis** [siderolabs/talos#7700]
## Bug Report
Nearly silent failure when docker TLS is enabled.

### Description
Unable to communicate with configured docker socket

### Logs
```
talosctl cluster create \
  --name sidero-demo \
  -p 67:67/udp,69:69/udp,8081:8081/tcp,51821:51821/udp \
  --workers 0 \
  --config-patch '[{"op": "add", "path": "/cluster/allowSchedulingOnControlPlanes", "value": true}]' \
  --endpoint $HOST_IP

validating CIDR and reserving IPs
generating PKI and tokens
Error response from daemon: Client sent an HTTP request to an HTTPS server.
```

### Environment
env|grep DOCKER
DOCKER_HOST=tcp://172.19.0.1:2376
DOCKER_TLS_VERIFY=1

- Platform: MacOS 13.5.1
- Target: x86 server

**Comment by smira** [comment]
`talosctl` is using Docker client library, in your case you don't have it configured correctly.

You should have `DOCKER_CERT_PATH` set in the environment to enable TLS.
