### ISSUE TITLE
`talosctl edit mc` requires saving twice

### ISSUE THREAD

**Issue by frezbo** [siderolabs/talos#7713]
## Bug Report

Doing a `talosctl edit mc` requires saving twice. Also any changes made are not shown in the editor on save. Have to run `edit mc` again to show that.

**Comment by smira** [comment]
It was most probably caused by having multiple `--nodes` (or `config nodes`), as `talosctl` iterates over each node

**Comment by frezbo** [comment]
Closing now, if I see it again, will re-open
