### ISSUE TITLE
Clumsy to unset net.ifnames=0 after upgrading to 1.5

### ISSUE THREAD

**Issue by yoctozepto** [siderolabs/talos#7716]
### Description

Previous version: 1.4.7

After upgrading to 1.5.1, talos has set `net.ifnames=0` (as advertised) and does not allow me to unset that easily by setting `net.ifnames=1` using `machineconfig`. The kernel `cmdline` is forcibly modified to include `net.ifnames=0`.

Example: `talos.platform=metal talos.config=none console=tty0 init_on_alloc=1 slab_nomerge pti=on consoleblank=0 nvme_core.io_timeout=4294967295 printk.devkmsg=on ima_template=ima-ng ima_appraise=fix ima_hash=sha512 net.ifnames=1 net.ifnames=0`

### Logs

N/A

### Environment

- Talos version: 1.5.1
- Kubernetes version: N/A
- Platform: Metal, AMD64

### Workaround

Upgrade to the same version *two times more* and the installer will finally leave only `net.ifnames=1` and all will be great.

**Comment by frezbo** [comment]
kernel args needs an upgrade to take effect, you can upgrade to same version of talos

**Comment by yoctozepto** [comment]
Interestingly, doing the 3rd upgrade leaves only `net.ifnames=1` - oh my, that is a really confusing behaviour. 😅

**Comment by frezbo** [comment]
> /me aware - the effect is the following example `cmdline`: `talos.platform=metal talos.config=none console=tty0 init_on_alloc=1 slab_nomerge pti=on consoleblank=0 nvme_core.io_timeout=4294967295 printk.devkmsg=on ima_template=ima-ng ima_appraise=fix ima_hash=sha512 net.ifnames=1 net.ifnames=0`

ahh sorry, yeh it's a little messy now, have to remove existing, upgrade, add new

**Comment by yoctozepto** [comment]
I updated the bug report with the clumsy workaround.
