### ISSUE TITLE
document etcd and kubelet subnet configuration

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#7718]
When a machine has multiple networks (e.g. private/public, IPv6/IPv4), or additional networks created dynamically (e.g. by the Kubernetes workloads), it's critical to make sure that

* kubelet IP is stable
* etcd IP is stable (this is very important)

Talos can handle changes to the addresses, but for `etcd` it might have completely undesired consequences.

Document that in the production notes: how to specify correct addresses/subnets.

**Comment by yoctozepto** [comment]
I can take over. I have done this properly for myself.
