### ISSUE TITLE
Adding an in-tree kernel module workflow broken after upgrading to 1.5

### ISSUE THREAD

**Issue by yoctozepto** [siderolabs/talos#7719]
### Description

Before 1.5, I could rebuild the kernel image to include the desired extra in-tree modules and rebuild the installer image using it. Now, I have found out that I need to also modify the hackish (I would call it such even if it was not in the /hack path 😛 ): `hack/modules-amd64.txt` (and analogously for arm64). [BTW, I don't get why you would build some modules and then discard them. Why build in the first place..? Or are you splitting it out into extensions somehow? - I could not follow.]

Imager does not seem to help here. I think a more thorough (re-)analysis of image customisation workflow needs to happen (especially considering the related issues and support request). I'm happy to collaborate and will think about something in the following weeks.

### Logs

N/A

### Environment

- Talos version: 1.5.1
- Kubernetes version: N/A
- Platform: N/A

### Workaround

Edit appropriately `hack/modules-amd64.txt` or `hack/modules-arm64.txt` to include the desired module.

**Comment by frezbo** [comment]
> BTW, I don't get why you would build some modules and then discard them. Why build in the first place..? Or are you splitting it out into extensions somehow? - I could not follow.]

Some modules gets split into extensions, eg: https://github.com/siderolabs/pkgs/tree/main/usb-modem-drivers

**Comment by yoctozepto** [comment]
This is generally solved by https://github.com/siderolabs/talos/pull/8220
