### ISSUE TITLE
Clarification on Handling Duplicate Internal IPs in Hybrid Network with Talos CTL

### ISSUE THREAD

**Issue by hugos99** [siderolabs/talos#7726]
### Description
I'm using Talos CTL in a hybrid network environment that includes KubeSpan. I've noticed that the node identifier provided by Talos CTL is based on the internal IP. However, I'm concerned about what would happen if two nodes in my network happen to have the same internal or local IP address.

I would appreciate some clarification on how Talos CTL handles this scenario and what actions or precautions I should take to ensure smooth operation in cases of duplicate internal IPs.

Thank you for your assistance in understanding this aspect of Talos CTL's behavior in a hybrid network. I also noticed the Slack invite link in GitHub, and the docs does not appear to be working.

- Talos version: v1.5.1
- Kubernetes version: v1.28.0
- Platform: metal

**Comment by smira** [comment]
KubeSpan will not be able to work correctly if two nodes have same advertised IPs. Basically if node X wants to talk to IP `10.1.1.1`, and that IP is advertised by both nodes A and B, KubeSpan has no way to tell which node to forward the traffic to.

Duplicate addresses will cause issues in other Kubernetes components as well.

In case of IP overlap, KubeSpan will degrade by ignoring one or another (undefined) conflicting addresses.

**Comment by hugos99** [comment]
Ok is it possible in the future to create an internal KubeSpan IP that serves to identify the machine in the talos cluster. That is the same way the CNI creates and internal IP pool for nodes create one for nodes?

would you be looking for help implementing this feature?

In the meanwhile I assume a pure wireguard setup is more flexible in this regard and allows for the machines to share local IPs?

**Comment by smira** [comment]
Please see my reply above, there's no way you can have duplicate IPs in your Kubernetes cluster, unless you don't use/advertise them at all.

CNI doesn't help with that, it still relies on node IPs being unique and routable.

**Comment by hugos99** [comment]
I think we can close this issue then, I would love to be able to have Talos machines cross networks that can operate with same IP but it appears to be a limitation of KubeSpan, if there is any way I can help to add this functionality or create a solid workaround please let me know.

**Comment by smira** [comment]
It's not a limitation of KubeSpan, you can't have duplicate IPs in the same cluster without KubeSpan either. It's more of the way networking works in general.

**Comment by hugos99** [comment]
I understand that all nodes need their individual IPs to support basic networking, I was just wondering if KubeSpan would be able to create a virtual network where all nodes are assigned specific IPs, for example in a wireguard network all nodes can have an internal  wireguard IPs regardless of their local IP, that way even if the machine in datacenter A and machine B in datacenter B have the same local Ip the machines can both be support in the cluster (by binding to their wireguard IP )

**Comment by smira** [comment]
KubeSpan design didn't include a feature or aliasing node IPs, but rather to be transparent overlay network. It doesn't affect the way nodes are assigned IPs, or the way they talk to the public Internet, but transparently moves traffic over KubeSpan when the traffic is node-to-node.

**Comment by hugos99** [comment]
Ok would it be possible to support such feature, can I help implement such a feature ?

For some clarification, we are looking to use talos to deploy machines in our clients datacenters and I highly doubt we would be able to force/convince clients to support or adapt to our network topology

**Comment by smira** [comment]
I don't think it's that simple to start with, and will require lots of configuration and changes. It might be equivalent effect to assign some other set of "shadow" unique IPs to the nodes and deal with NAT for public Internet access. If you force `kubelet` to pick up the node IP to be "shadow" IP, the KubeSpan will take care of the rest. But it still requires dealing with public outbound.

**Comment by hugos99** [comment]
Sounds Like a smart solution I will try to see or at least estimate the effort required for this possible feature

**Comment by smira** [comment]
This is not a feature really, you should be able to do that today with Talos.

**Comment by hugos99** [comment]
Ok perfect then I will try to report my results/attempts in the slack then
