### ISSUE TITLE
SecureBoot image

### ISSUE THREAD

**Issue by uhthomas** [siderolabs/talos#7728]
### Description

The documentation says a signed image was to be published last month, was it?

> Sidero Labs is going to provide Talos images signed with the Sidero Labs Secureboot key in August 2023, but until then, you can use the following instructions to build your own.

https://www.talos.dev/v1.5/talos-guides/install/bare-metal-platforms/secureboot/

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: [`kubectl version --short`]
- Platform:

**Comment by frezbo** [comment]
yes, but this is still work in progress, apologies.

**Comment by smira** [comment]
Takes more time, it should be in September. Documentation provides a way with your own PKI.

**Comment by uhthomas** [comment]
Thanks both. Is there any ETA on when this will be available? I'm keen to use the Sidero signed image rather than my own just because it's way easier and means I don't have to build my own images for each new release. I'm sort of blocked on standing up a new cluster until this is available.

**Comment by smira** [comment]
I would say probably first week of October in beta.

**Comment by uhthomas** [comment]
Okay, thank you so much! I am unfortunately impatient, so is there anything I can do in the meantime? If I build my own signed image, will it then not be possible to upgrade with the official Talos signed image?

**Comment by smira** [comment]
You could, but you'd have to enroll new set of keys to your firmware.
