### ISSUE TITLE
East Eighth Zone

### ISSUE THREAD

**Issue by wsy0101** [siderolabs/talos#7734]
Hello, I would like to specify the time zone of Talos when installing it. After Talos deployment is completed, the operating system's time zone will use the time zone of East Eighth Zone. How do I configure this in the machine configuration file? Or do you want to set it in the kernel boot file?

**Comment by smira** [comment]
Sorry, Talos is hardcoded to use UTC timezone only server-side. Inside the container image you can have whatever timezone you'd like via environment variables and timezone database.

**Comment by wsy0101** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by rismalrv** [comment]
any technical reason not supporting changing talos timezone? just curious

**Comment by smira** [comment]
As it simplifies things and has less issues in general due to TZ differences.
