### ISSUE TITLE
Renew a Kubernetes certificate with a 10-year expiration date

### ISSUE THREAD

**Issue by stronger123456789** [siderolabs/talos#7737]
Does the talos based kubernetes can has the way to have a 10-year expiration data for certificate ?

**Comment by smira** [comment]
Which Kubernetes certificate are you asking about?

**Comment by stronger123456789** [comment]
I mean the certificate of between cluster nodes. From my environment to see it will 1 year expiration.

**Comment by smira** [comment]
I'm not sure what is the certificate between nodes, but all server-side certificates are managed and rotated automatically by Talos.

Client-side admin `kubeconfig` can be refreshed with `talosctl kubeconfig`.
