### ISSUE TITLE
talosctl disks --insecure --nodes x.x.x.x --endpoints x.x.x.x returns nothing 

### ISSUE THREAD

**Issue by ugurmendi** [siderolabs/talos#7749]
### Environment

- Talos version: [
Client:
	Tag:         v1.5.2
	SHA:         318c66b9
	Built:       
	Go version:  go1.20.8
	OS/Arch:     linux/amd64
Server:
error constructing client: failed to determine endpoints
]
- Kubernetes version: [`1.28`]
- Platform: Vmware 
- I am applying metal iso which is 1.5.2 version 

Hello I am trying to install  production cluster with using the talos linux, I have generated configuration with:
talosctl gen config mycluster https://master_node_ip:6443
after that I apply:
talosctl apply-config --insecure  --file controlplane.yaml  -n master_node_ip --endpoints https://master_node_ip:6443 

I got error: 
error applying new configuration: rpc error: code = InvalidArgument desc = configuration validation failed: 1 error occurred:
	* specified install disk does not exist: "/dev/sda

When ı dive in to documentation 

I executed the command
talosctl disks --insecure --nodes master_node_ip --endpoints https://master_node_ip:6443 

it returns nothing.
I need a solution about that thanks

**Comment by smira** [comment]
please format the code blocks, they are unreadable.

from what I can see you only need `-n` with `--insecure` (no need for `--endpoints`), and your machine config install disk doesn't match the hardware.

https://www.talos.dev/v1.5/introduction/getting-started/#modifying-the-machine-configs

**Comment by ugurmendi** [comment]
Hello smira sorry for the mass  I will edit code blocks I notice the same problem,
talosctl disks --insecure -n ip_address_of_nodes returns nothing it is not throwing error or giving me the output of the error.

**Comment by ugurmendi** [comment]
I will check the storage side for this problem maybe provisioning strategy cause this problem, can I monitor the disk partition in an alternative way for example dashboard or something else ? If I find /dev/x I can continue to setup.
Kind Regards
