### ISSUE TITLE
Fail fast on extension pull and validation failures

### ISSUE THREAD

**Issue by andrewrynhard** [siderolabs/talos#7758]
If a system extension fails to pull for whatever reason we should fail fast instead of going through a reboot. In my case I was hitting following when upgrading:

```
[  484.668094] [talos] fatal sequencer error in "upgrade" sequence: message:"sequence failed: error running phase 10 in upgrade sequence: task 1/1: failed, failed to parse image reference \"docker.io/andrewrynhard/stargz-snapshotter:v0.14.3-v1.6.0-alpha.0-10-g0749684@sha256:7e1cbbca2a94530655eb82e2f8d6744bbbd60c7b97e16d855ecce89\": invalid checksum digest length"
[  484.703964] [talos] controller runtime finished
```

This could cause unnecessary downtime.

**Comment by smira** [comment]
This is no longer the recommended way to install system extensions: https://www.talos.dev/v1.5/talos-guides/install/boot-assets/
