### ISSUE TITLE
Unable to enable Kubespan on existing cluster - unknown keys found during decoding

### ISSUE THREAD

**Issue by s04** [siderolabs/talos#7761]
## Bug Report

Thanks for taking a look. Likely user error.

talosctl apply-config -e <IP-Controlplane> -n <IP-Controlplane> -f controlplane.yaml

When enabling Kubespan in the controlplane.yaml and then using talosctl apply-config I get an error:

```
# 1 error occurred:
# 	* <IP-Controlplane>: rpc error: code = InvalidArgument desc = unknown keys found during decoding:
# machine:
#     kubespan:
#         enabled: true # Enable the KubeSpan feature
```

Nothing else was changed in the config, I removed the curly braces after the network so it would find the kubespan key otherwise all is left the same.

### Environment

- Talos version: 1.5.0 on nodes, 1.5.2 on talosctl [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: v1.28.1 [`kubectl version --short`]
- Platform: Hetzner, setup from the guide.

**Comment by andrewrynhard** [comment]
Should be 

```
machine:
  network:
    kubespan:
      enabled: true
```

**Comment by s04** [comment]
Cheers! The `machine:` was there but `kubespan:` was on the same indentation level as `network:`. Should work now, will test later.
