### ISSUE TITLE
:bug: Talos does not change the network configuration before installation

### ISSUE THREAD

**Issue by uhthomas** [siderolabs/talos#7808]
### Description

It's usually a good idea to use DNS instead of an IP address for the control plane endpoint, but higher the barrier for entry given the need for an external DNS provider.

A simple solution to avoid this is to use [extraHostEntries](https://www.talos.dev/v1.5/reference/configuration/#extrahost) which resolves the domain name locally. Unfortunately, this is not possible to do during installation as the network configuration is not updated.

### Logs

Lots of logs about not being able to resolve the domain name, I don't have a picture - sorry.

### Environment

- Talos version: v1.5.3
- Kubernetes version: N/A
- Platform: bare metal

**Comment by smira** [comment]
something I could look into at some point, but with KubePrism changing control plane should be super easy and non-disruptive

**Comment by devantler** [comment]
Hi, it seems the /etc/hosts is not populated during installation. This is a bit problematic for us, as we aim to use Talos in an airgapped environment, where DNS and NTP is not available at install. We rely on the `extraHostEntries` to reach a docker registry that can provide the installation images.

@trarbr

**Comment by smira** [comment]
First of all, please open a new issue and submit the logs which describe the issue. It's quite impossible to understand what is going on so far.

Plus, for docker images you can use registry mirrors feature to redirect.

I'm pretty sure that `/etc/hosts` is populated, so I need to see the actual logs to understand the problem better.

**Comment by devantler** [comment]
That makes sense! I will create an issue with the necessary context/logs next week :-)
