### ISSUE TITLE
No hostname in talos.config request

### ISSUE THREAD

**Issue by CRASH-Tech** [siderolabs/talos#7817]
## Bug Report

I'm using my custom talos.config server, and if DHCP server do not sends hostname to talos, talos sends request to talos.config server without aut-generated hostname
### Description
PXE config:
```
talos.config=http://10.171.120.1:8888/register?cluster=k-test&pool=cp&token=xa0fyr.v8t2s4wb8b1l13cn&uuid=${uuid}&hostname=${hostname}&mac=${mac}&serial=${serial}
```

### Logs
Server logs:
```
Register query received: 10.171.110.24 map[cluster:k-test host:10.171.110.24 hostname: mac:ce:b9:31:07:d1:8c pool:cp serial: token:xa0fyr.v8t2s4wb8b1l13cn uuid:e40eea6a-3f0c-460f-bcaf-33550b18682f]
```

### Environment

- Talos version: 1.5.2
- Kubernetes version: 1.27.2
- Platform: metal

**Comment by smira** [comment]
This is not a bug, but a design choice, as Talos at this point has no machine configuration, it can't figure out what should be the default hostname (IP-based or stable), so it can't produce a default hostname. You can set hostname via DHCP server, or via `talos.hostname` kernel arg.
