### ISSUE TITLE
Secure Boot keys are not enrolled automatically

### ISSUE THREAD

**Issue by uhthomas** [siderolabs/talos#7830]
### Description

Following from https://github.com/siderolabs/talos/issues/7828, I managed to figure out how to install Talos successfuly.

I was using [Ventoy](https://www.ventoy.net/en/index.html), but had to use a dedicated USB stick instead. I imagine this is because Talos got confused about thought the keys were already enrolled, when they weren't. I started again, and noticed the option to enroll keys which was set to 'auto'. I continued with the installation, but secure boot was not enabled when Talos rebooted. Instead, I had to start again (again) and enroll the keys manually, which then worked.

https://www.talos.dev/v1.5/talos-guides/install/bare-metal-platforms/secureboot/

### Environment

- Talos version: v1.6.0-alpha.0-66-g336aee0fd
- Kubernetes version: N/A
- Platform:

**Comment by smira** [comment]
This will be an issue with your UEFI firmware and systemd-boot. It works fine on UEFI firmwares we tested with. Manual enrollment is always an option though.

**Comment by uhthomas** [comment]
I don't know. I am using a [Z790-P](https://www.asus.com/uk/motherboards-components/motherboards/prime/prime-z790-p/) which is not rare or from a non reputable manufacturer.

**Comment by maxpain** [comment]
@uhthomas I have [ASUS Z690](https://rog.asus.com/us/motherboards/rog-maximus/rog-maximus-z690-extreme-glacial-model/), and even after pressing this button I'm still getting `SecureBoot: False`
<img width="641" alt="image" src="https://github.com/siderolabs/talos/assets/5875582/22d6d103-bb4a-4a55-8bae-94db53a23dd5">

How did you manage to fix it?

**Comment by uhthomas** [comment]
@maxpain secure boot on these motherboards is really painful. They often will not actually do what you tell it to do.

Make sure to go to your BIOS and then Boot > Secure Boot. Select Windows UEFI and do not use the default keys. It should say it's in setup mode eventually. It may take a few restarts for it to actually work.

**Comment by maxpain** [comment]
@uhthomas Hmm, my current mode is "Other OS." I didn't know that I actually needed "Windows UEFI".

**Comment by uhthomas** [comment]
@maxpain Yeah, it's really silly. If you read the documentation then "Other OS" actually means "Disable Secure Boot".
