### ISSUE TITLE
Provide a way to validate /scan security of Talos Linux

### ISSUE THREAD

**Issue by steverfrancis** [siderolabs/talos#7833]
## Feature Request
As a platform engineer, I want a scap-compatible interface for assessing compliance with a DISA STIG and for checking for vulnerabilities for my deployed instance of Talos Linux.

Given I have access to this interface,
When I request scap-compatible (or CVE vulnerability) scan results for a deployed instance of Talos Linux,
Then these results are made available to me in all the formats normally available with the "openscap" tool (i.e. xml, html, xccdf, et cetera.

### Description
One solution I would suggest looking into is shipping Talos Linux with the oscap-daemon (https://github.com/OpenSCAP/openscap-daemon/blob/master/README.md) and setting up a configuration option for toggling it on/off in the Talos configs. If toggled on, talosctl (or another tool) could then be used to initiate scans, pulling the results down via an API call. Remediation suggestions for non-compliant items could suggest to administrators to update certain configuration options to mod/redeploy Talos in a way that is more compliant.

Pros of this approach:

- Everything is still configured via config file
- Everything is still available through API, not SSH
- Solves the problem of providing compliance scan results to a user requesting them
- Opens up Talos Linux to a new audiences with less-flexible compliance auditing standards
- (note: these audiences may need paid support, which subsidizes further open-source work

Cons of this approach:
- The openscap daemon requires python and a few python libs (not sure if this is already available, or you have stuck with more cloud native langs like golang)
- The openscap daemon might require access to a shell to run evals (or a small mod to its code) (but I don't know this for sure without digging into the code a bit)
- The openscap daemon might need a temporary/ephemeral location to stash scan results on disk
- The openscap daemon requires access to fresh vulnerability definitions on occasion, so Talos would need a way to fetch these (internet-connected) or mount these (air-gapped);  you could also pass them each time a scan is run as a input to the API so that they don't have to be mounted
- Requires some additional config options to be implemented
- Requires the new feature to be implemented on the backend (i.e. openscap-daemon)
- Requires a new API endpoint and/or options to be implemented to access the new feature
- Requires some additions to the client to interface with the new API endpoints/options

**Comment by steverfrancis** [comment]
In addition to the openscap-daemon, the openscap client is another potential solution. It is written in C, so it has a lot of the same pros as the daemon, without as many of the cons, (namely, the python and dbus dependencies). As a result, it would probably be a lot easier to incorporate, and the only thing you'd lose is the ability to do automated/timed scans that occur in between API requests via a nice daemon interface. Not that you couldn't just call cron (or systemd timers) to do that for you though, if you really wanted to pre-cache scan results to serve when API calls request them.

**Comment by smira** [comment]
As Talos rootfs is read-only, I'm not sure what is the benefit of running a scan on the system, as the scan could pretty much run on the contents of the rootfs. 

I don't think these daemons are able to correctly scan container workload images, as this will be the piece which needs more work imho.
