### ISSUE TITLE
Too easy to break VMware-based clusters.

### ISSUE THREAD

**Issue by haraldnh** [siderolabs/talos#7836]
When running a Talos cluster on VMware, it would be nice if it wasn't quite as easy to break things...  This is still a problem on 1.5.3.

The issue, as indicated in #3003 and #3143, is really about the combination of vmxnet3 and vxlan.  When installing the OVA file from any recent release, it creates an ESXi 6.5-compatible VM which works well enough.

Once the system is then up and running, VMware has a nice friendly button asking if it should "upgrade vm hardware compatibility to match host".  Since ESXi 7.0 U2 introduced a version of vmxnet3 with offload-suport for vxlan and a reported almost 5x speedup, this is a tempting thing to do.

But even though the vmxnet3 driver in the linux kernel reportedly got updated for this change a long time ago, flannel stops working and all cluster networking between the nodes go down.

It would be nice if this is at least highlighted in the docs, and also mentioning that if this happens it is possible to bring the cluster back by switching the nic emulation to e.g. E1000E (with associated performance loss).  But even better would be if the issue was fixed, so we can all get the nice vxlan speedup on VMware-hosted clusters.

**Comment by smira** [comment]
PRs to the documentation are welcome!
