### ISSUE TITLE
Huge image size

### ISSUE THREAD

**Issue by sergelogvinov** [siderolabs/talos#7851]
## Bug Report

The size of images has changed (~8Gb vs 1.2Gb) after the 1.5 release.

Some clouds are experiencing issues when uploading large raw images. Additionally, I have observed that the scaling-up process now requires more time than it did previously. 
This issue appears to affect only the RAW image format.

The typical sizes of cloud images are as follows:

- Debian 11: 2GB
- Ubuntu 22.04: 3GB
- Fedora 38: 5GB

Is it possible to change the default image size for different platforms or perhaps add a `--size` parameter to the `imager` tool?

### Environment

- Talos version: 1.5
- Kubernetes version:
- Platform:

**Comment by smira** [comment]
we increased image size to avoid issues with users creating a VM with same default disk size and leading to errors on pulling images. definitely possible to override the size, that should be easy

**Comment by sergelogvinov** [comment]
I believe that this issue may primarily arise on bare metal platforms and some less known cloud providers.
The majority of well-known cloud providers typically offer a minimal boot size of at least 10 gigabytes.

Would it be possible to consider adjusting the size based on the specific cloud provider, perhaps reducing it to 3 gigabytes, for instance?

Thanks.

**Comment by smira** [comment]
> I believe that this issue may primarily arise on bare metal platforms and some less known cloud providers. The majority of well-known cloud providers typically offer a minimal boot size of at least 10 gigabytes.

it's even a problem on GCP for example

> Would it be possible to consider adjusting the size based on the specific cloud provider, perhaps reducing it to 3 gigabytes, for instance?

yes, it's a map per platform: https://github.com/siderolabs/talos/blob/c3e418200032be376aa30f6db133f2dcbf8b67c2/pkg/imager/profile/default.go#L84-L96
