### ISSUE TITLE
Upgrade Linux to 6.4 LTS

### ISSUE THREAD

**Issue by gerhard** [siderolabs/talos#7856]
## Feature Request

Would it be possible to bump the Linux kernel to `6.4` LTS?

### Description

I've hit this bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1033398 on Talos `1.4.5` running Linux `6.1.30`

While the latest Talos `1.5.3` is not that far ahead in terms of Linux version - `6.1.54` - I would be a lot more comfortable running production on an LTS Linux kernel, currently `6.4`

FWIW:
- https://github.com/parca-dev/parca-agent/pull/2070
- https://github.com/parca-dev/parca-agent/issues/1675

Thank you!

cc @javierhonduco @brancz

**Comment by smira** [comment]
Linux 6.4 is not LTS, it's EOL: https://kernel.org/

![image](https://github.com/siderolabs/talos/assets/55211/ae312a87-026f-49a6-9931-6ace3c28189f)

Linux 6.1 is LTS, and the latest version of Talos comes with latest version of Linux LTS available at the moment of the release.

Bugfixes are most usually backported to Linux LTS releases, so I won't be surprised it will be or has already been backported.

The next LTS Linux is probably going to be Linux 6.6, and Talos 1.7 will come with Linux 6.6.

We always encourage users to run the latest Talos relase (1.5.3), as this brings the latest security and bug fixes.

**Comment by gerhard** [comment]
OK! `6.1` is what we want then. Thank you!
