### ISSUE TITLE
Bootloop when a new NVMe device is added with secure boot

### ISSUE THREAD

**Issue by uhthomas** [siderolabs/talos#7857]
### Description

I have Talos installed with secure boot and TPM encryption, but cannot add new NVMe disks as Talos will bootloop. I don't really understand why - it gets all the way to the containerd phase and then just reboots with a blank screen. The logs show the original disk was decrypted successfully. I am not sure it's a general problem of changing hardware, as I was able to add a PCI card and have it boot okay. Just whenever I add an nvme disk - I tried two, albeit both Samsung 970 evo 2TB.

I did see:

```
nvme nvme1: missing or invalid SUBNQN field.
```

But I'm unsure if it's related - I was using these one of the devices on a different Talos deployment before just fine, the other is brand new. I securely erased them before adding them to this installation.

### Environment

- Talos version: https://github.com/siderolabs/talos/commit/336aee0fdb1302443f627f848bed8081bdb0d9b0
- Kubernetes version: N/A
- Platform: bare metal

**Comment by smira** [comment]
We might need the logs to understand _why_.

**Comment by uhthomas** [comment]
@smira I understand - it's just tricky to share logs for nodes which aren't accessibly remotely (i.e because of a bootloop). Any advice on how best to share this would be appreciated. I did take some photos, but didn't see much interesting.

**Comment by uhthomas** [comment]
![image](https://github.com/siderolabs/talos/assets/9749173/d7335499-2ee3-445a-95f1-a2b84e262ff6)

**Comment by uhthomas** [comment]
![image](https://github.com/siderolabs/talos/assets/9749173/25416169-177d-433f-ba93-ca3b5009320e)

**Comment by uhthomas** [comment]
So it gets most of the way through unsealing, and then fails at the last step?

https://github.com/siderolabs/talos/blob/38ce3c827a06c44e0399cd0a3d8a396687001b20/internal/pkg/secureboot/tpm2/unseal.go#L256

https://github.com/google/go-tpm/blob/ee6cbcd136f878df2c2f36b4a085d2115330f379/tpm2/reflect.go#L39C1-L39C1

**Comment by uhthomas** [comment]
I tried adding a hard disk instead of an nvme device and initially it seemed to have the same problem, but it eventually succeeded after rebooting maybe 5 times? It seems like there could be some sort of race condition or something as it doesn't really seem deterministic. I did try the same thing with an nvme device, but can try again as it may just need a bit more time.

**Comment by uhthomas** [comment]
I let it reboot for about an hour with a nvme disk and the TPM eventually went into lockout mode.
