### ISSUE TITLE
Add ability to get ethernet adapter information

### ISSUE THREAD

**Issue by red-lichtie** [siderolabs/talos#7862]
### Discussed in https://github.com/siderolabs/talos/discussions/7861

Add ethernet device names to dashboard beside the IP addresses so that network configuration is easier.

Optionally add an `ip` module to `talosctl`, so the network devices could be displayed using `talosctl ip a`.

<div type='discussions-op-text'>

<sup>Originally posted by **red-lichtie** October 17, 2023</sup>
In the installation documentation, there should be a mention of the ability to configure the kernel options before installing a node, especially with regards to ethernet adapters.

I followed the [Proxmox guide](https://www.talos.dev/v1.5/talos-guides/install/virtualized-platforms/proxmox/).

In various examples "eth0" is used as the NIC device name but in fact, the default image uses predictable network interface names for the devices.

The documentation should indicate that controlplane.yaml and worker.yaml can be edited before the installation, especially with regards to `extraKernelArgs`.

e.g.
```yaml
machine:
    install:
        extraKernelArgs:
            - net.ifnames=0
```

In the [Virtual (shared) IP guide](https://www.talos.dev/v1.5/talos-guides/network/vip/) there is also no mention of `eth0` not being the default device name.

The guide should warn that the device name **will** be something other than `eth0` and that they can use `talosctl dmesg --nodes ${CONTROLPLANE_NODE_NAME | grep eth0}` to see what the name was changed to.

It would be nice to have the device name(s) in the summary dashboard beside the IP address(es).</div>

**Comment by vaizki** [comment]
I don't think an "ip module" is necessary as you can already get link and IP address info from a node, also in maintenance mode / before install, just use the `-i` or `--insecure` flag. Below examples from a freshly booted Talos ISO under VMware:
See network adapters:
```
$ talosctl -n 10.0.20.244 get link -i
NODE   NAMESPACE   TYPE         ID        VERSION   TYPE       KIND     HW ADDR                                           OPER STATE   LINK STATE
       network     LinkStatus   bond0     1         ether      bond     be:9e:af:54:2c:3d                                 down         false
       network     LinkStatus   dummy0    1         ether      dummy    62:2a:23:5a:a0:6b                                 down         false
       network     LinkStatus   ens32     3         ether               00:0c:29:5f:39:c1                                 up           true
       network     LinkStatus   ens33     3         ether               00:0c:29:5f:39:cb                                 up           true
       network     LinkStatus   ip6tnl0   1         tunnel6    ip6tnl   00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00   down         false
       network     LinkStatus   lo        2         loopback            00:00:00:00:00:00                                 unknown      true
       network     LinkStatus   sit0      1         sit        sit      00:00:00:00                                       down         false
       network     LinkStatus   teql0     1         void                                                                  down         false
       network     LinkStatus   tunl0     1         ipip       ipip     00:00:00:00                                       down         false
```

And IPs:
```
$ talosctl -n 10.0.20.244 get address -i
NODE   NAMESPACE   TYPE            ID                                  VERSION   ADDRESS                       LINK
       network     AddressStatus   ens32/10.0.20.244/24                1         10.0.20.244/24                ens32
       network     AddressStatus   ens32/fe80::20c:29ff:fe5f:39c1/64   2         fe80::20c:29ff:fe5f:39c1/64   ens32
       network     AddressStatus   ens33/fe80::20c:29ff:fe5f:39cb/64   2         fe80::20c:29ff:fe5f:39cb/64   ens33
       network     AddressStatus   lo/127.0.0.1/8                      1         127.0.0.1/8                   lo
       network     AddressStatus   lo/::1/128                          1         ::1/128                       lo
```

Some fields are not in the table so `-o yaml` for all of it.

**Comment by red-lichtie** [comment]
> I don't think an "ip module" is necessary as you can already get link and IP address info from a node, also in maintenance mode / before install, just use the `-i` or `--insecure` flag. Below examples from a freshly booted Talos ISO under VMware:
> 
> See network adapters:
> 
> ```
> $ talosctl -n 10.0.20.244 get link -i
That is exactly the information that I was wanting to access, thanks.
