### ISSUE TITLE
recovery keys for secure boot tpm

### ISSUE THREAD

**Issue by uhthomas** [siderolabs/talos#7868]
### Description

The TPM will be reset if the bios is upgraded and would make talos unbootable. Is it possible to recover from this situation? I imagine the best thing to do would be to add a second key to the encryption configuration?

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: [`kubectl version --short`]
- Platform:

**Comment by frezbo** [comment]
> The TPM will be reset if the bios is upgraded 

hmm that seems unexpected, and should just work, as the key re-created should be same as per spec, i wonder if the bios upgrade does something weird with changing some tpm stuff

you can enroll a static key also, in that way if tpm unlock fails it should fall back to static key

**Comment by philhug** [comment]
> you can enroll a static key also, in that way if tpm unlock fails it should fall back to static key
At the moment you'd have to put the static key in the config which is then stored unencrypted on disk, which kinds of defeats the idea of TPM encryption.

To do that we'd need an option to manually enroll a key.
Something like this:
```
state:
  provider: luks2
  keys:
  - tpm: {}
    slot: 1
  - static:
      passphrase: verysecret
      volatile: true
    slot: 2
```

setting volatile to true could then enroll the key once, but not store the passphrase in the config and also not try to unlock using that slot.
maybe it's better to use a separate key provider though. (e.g. -manual)

**Comment by smira** [comment]
yes, I'd guess we need an interactive way to acquire the passphrase, so it's never in the machine config at all, but we're not there yet
