### ISSUE TITLE
Applying controlplane.yaml to node with isc dhcp causes assigned IP address to change

### ISSUE THREAD

**Issue by killroy1971** [siderolabs/talos#7872]
### Description
When building a new clusterusing the isc dhcp server, the act of applying a machine config to a node, i.e. controlplane.yaml, causes that node's IP address to change, which leads to a failed control plane cluster build.

### Logs
ISC DHCP Logs
```
Oct 17 10:42:06 satellite dhcpd[516280]: DHCPDISCOVER from 06:55:c2:ee:24:30 via eth0
Oct 17 10:42:07 satellite dhcpd[516280]: none: host unknown.
Oct 17 10:42:07 satellite dhcpd[516280]: DHCPOFFER on 192.168.4.73 to 06:55:c2:ee:24:30 (talos-4nx-8be) via eth0
Oct 17 10:42:07 satellite dhcpd[516280]: DHCPREQUEST for 192.168.4.73 (192.168.4.26) from 06:55:c2:ee:24:30 (talos-4nx-8be) via eth0
Oct 17 10:42:07 satellite dhcpd[516280]: DHCPACK on 192.168.4.73 to 06:55:c2:ee:24:30 (talos-4nx-8be) via eth0
Oct 17 10:42:38 satellite dhcpd[516280]: DHCPDISCOVER from 5e:ac:33:a2:a2:ce via eth0
Oct 17 10:42:39 satellite dhcpd[516280]: DHCPOFFER on 192.168.4.68 to 5e:ac:33:a2:a2:ce (talos-ae5-lma) via eth0
Oct 17 10:42:39 satellite dhcpd[516280]: DHCPREQUEST for 192.168.4.68 (192.168.4.26) from 5e:ac:33:a2:a2:ce (talos-ae5-lma) via eth0
Oct 17 10:42:39 satellite dhcpd[516280]: DHCPACK on 192.168.4.68 to 5e:ac:33:a2:a2:ce (talos-ae5-lma) via eth0
Oct 17 10:42:40 satellite dhcpd[516280]: DHCPDISCOVER from 36:55:b3:a8:ee:af via eth0
Oct 17 10:42:41 satellite dhcpd[516280]: DHCPOFFER on 192.168.4.72 to 36:55:b3:a8:ee:af (talos-2yg-o4d) via eth0
Oct 17 10:42:41 satellite dhcpd[516280]: DHCPREQUEST for 192.168.4.72 (192.168.4.26) from 36:55:b3:a8:ee:af (talos-2yg-o4d) via eth0
Oct 17 10:42:41 satellite dhcpd[516280]: DHCPACK on 192.168.4.72 to 36:55:b3:a8:ee:af (talos-2yg-o4d) via eth0
```

### Environment

- Talos version: 1.53
- Kubernetes version: 1.27.2
- Platform: x86_64

### Background

I'm building a new Talos cluster, and I've added a few items to my controlplane.yaml file. Nothing that should be impactful, but I've included it just in case they are.
```
    extraArgs:
      rotate-server-certificates: true
    network:
      interfaces:
        dhcp: true
        vip:
          - ip: 192.168.4.101

    extraManifests:
      - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
      - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
```

* A previous build using PFSense's build-in dhcp server did not produce this error. I think that build started out as v 1.4.8.
* I've confirmed that pfsense's dhcp server does not cause this issue.
* The dhcp server's lease time is 72 hours.
* When I assign static leases to the control plane nodes, the deployment is successful. I have not had an issue with worker nodes, but I didn't expect to. The deployment issue appears to be when the control plane nodes attempt to access the identified endpoint node, only the IP address has changed. I was attempting to set up an api vip, but that doesn't get deployed even when I have static dhcp leases...but that's another issue.

If there are other useful logs that I should attach, please let me know. As I try other things, I'll add the details to this issue

**Comment by smira** [comment]
There are three different MACs and three different IPs in the logs, It's not exactly clear what is wrong?

**Comment by killroy1971** [comment]
That's what I'm trying to figure out. The MACs obviously don't change. The only difference is the type of DHCP server used.
