### ISSUE TITLE
Unable to destroy talos cluster on Podman

### ISSUE THREAD

**Issue by Chan9390** [siderolabs/talos#7881]
### Description

I had setup Talos using talosctl on Podman (v4.7.1) rootful machine. It installed fine but when destroying the cluster using `talosctl cluster destroy` I get the error `strconv.Atoi: parsing "": invalid syntax`

### Logs

```
strconv.Atoi: parsing "": invalid syntax
```

### Environment

- Talos version: v1.5.4
- Kubernetes version: -
- Platform: Mac M2

**Comment by BobyMCbobs** [comment]
I have the same error

**Comment by sanmai-NL** [comment]
More modern versions of Podman have increasingly better CLI compat with Docker Engine CLI. Apart from that, I prefer to issue container management commands manually rather than letting `talosctl cluster` do opaque things.

**Comment by FalconerTC** [comment]
Also seeing this on talosctl v1.7.6, Mac M2, Podman 5.2.2
