### ISSUE TITLE
Talos iso hangs on bare-metal servers when kernel parameters contain console=ttyS0

### ISSUE THREAD

**Issue by MathiasPius** [siderolabs/talos#7883]
## Bug Report
When attempting to boot Talos on a bare-metal server, either after `dd`ing the contents of talos iso to a disk and booting from it, or by mounting the talos iso as a CD through Raritan KVM, the machine will hang immediately after showing "Booting Talos ISO" (or similar) message after selecting Talos from the GRUB menu.

### Description
Downloading the talos iso, mounting it and removing the `console=ttyS0` line from `/grub/grub.cfg` before writing the iso to disk resolves the issue.

My suspicion is that the server might not have a serial port available, which is what's causing the kernel to hang when attempting to initialize it, but my understanding of how the kernel interacts with serial ports and consoles is not deep enough to say for sure.

One coincident observation is that Hetzners "Virtual KVM" solution (which I believe relies on this same missing serial port) also does not work for the affected machines.

[Same problem was reported to systemd](https://github.com/systemd/systemd/issues/15656) but declared out of scope, since it is a kernel issue. I am not sure if there is a corresponding report to the Linux kernel itself.

### Logs
None, just hangs at `Booting Talos ISO..` after selecting Talos ISO in grub.

### Environment

- Talos version: 1.4.1, 1.5.3, 1.5.4, 1.6.0-alpha.1 (probably others)
- Kubernetes version: Irrelevant
- Platform: Hetzner EX44 bare metal server, ASUS Motherboard (Unknown model), EFI boot.

**Comment by petertiedemann** [comment]
Just want to add that I have also encountered this issue (and nearly gave up on Talos), on both AX102 and EX44 servers. I would also like to clarify that this is not a KVM problem. With or without KVM, the server will not become reachable by either ping or talosctl if the problematic `console=ttyS0` argument is present.

I am currently using this approach to workaround this issue:
```bash
# stop raid and wipe disks
mdadm --stop /dev/md/*
wipefs -fa /dev/nvme*n1

# Download bare metal disk image
wget https://github.com/siderolabs/talos/releases/download/v1.5.4/metal-amd64.raw.xz
xz -d metal-amd64.raw.xz

dd if=metal-amd64.raw of=/dev/nvme0n1 && sync

# work-around for this issue
mkdir /mnt/boot
mount /dev/nvme0n1p3 /mnt/boot
GRUB_CFG="/mnt/boot/grub/grub.cfg"
sed -i 's/console=ttyS0//g' $GRUB_CFG

reboot --reboot
```

**Comment by smira** [comment]
I feel we should remove this arg,as the kernel should auto-detect better, need to figure out all edge cases

**Comment by petertiedemann** [comment]
@sms-system Thanks for the tip, that will make it easier for me to upgrade Talos. But I still see it as a work-around, I really don't want to use a KVM for every server we set up (normally i just do ssh, then dd the talos image).

**Comment by frezbo** [comment]
> @sms-system Thanks for the tip, that will make it easier for me to upgrade Talos. But I still see it as a work-around, I really don't want to use a KVM for every server we set up (normally i just do ssh, then dd the talos image).

Upcoming Talos 1.6 supports removing kernel args, I guess this can be closed then?

**Comment by frezbo** [comment]
Closing for now, if any issues after 1.6, please re-open

**Comment by grantral** [comment]
> I feel we should remove this arg,as the kernel should auto-detect better

@smira Will it be done?

> if any issues after 1.6, please re-open

@frezbo I've installed Talos v1.7.0-alpha.1 on the Hetzner EX44 server, and the behavior hasn't changed.

**Comment by frezbo** [comment]
> > I feel we should remove this arg,as the kernel should auto-detect better
> 
> @smira Will it be done?
> 
> > if any issues after 1.6, please re-open
> 
> @frezbo I've installed Talos v1.7.0-alpha.1 on the Hetzner EX44 server, and the behavior hasn't changed.

You can generate a metal image with the arg removed, 1.6 has the ability to drop kernel arguments with `-` prefixed args, so can use image factory to  generate metal images with the arg removed

**Comment by grantral** [comment]
> > > I feel we should remove this arg,as the kernel should auto-detect better
> > 
> > 
> > @smira Will it be done?
> > > if any issues after 1.6, please re-open
> > 
> > 
> > @frezbo I've installed Talos v1.7.0-alpha.1 on the Hetzner EX44 server, and the behavior hasn't changed.
> 
> You can generate a metal image with the arg removed, 1.6 has the ability to drop kernel arguments with `-` prefixed args, so can use image factory to generate metal images with the arg removed

Yes, I know, thanks. But recently, @smira wanted to remove this arg from the image.

**Comment by frezbo** [comment]
> Yes, I know, thanks. But recently, @smira wanted to remove this arg from the image.

That's only if there was a way to know what needs to be set, removing it would break other systems that used it, so the decision to support removing with `-`.

**Comment by grantral** [comment]
> > Yes, I know, thanks. But recently, @smira wanted to remove this arg from the image.
> 
> That's only if there was a way to know what needs to be set, removing it would break other systems that used it, so the decision to support removing with `-`.

So, if we find a new way to auto-detect, we can remove this arg, right?

**Comment by frezbo** [comment]
> So, if we find a new way to auto-detect, we can remove this arg, right?

oh yes, that would make this ideal, and not have to worry about console args at all
