### ISSUE TITLE
Stop using pool.ntp.org by default

### ISSUE THREAD

**Issue by willglynn** [siderolabs/talos#7892]
Talos currently hardcodes `pool.ntp.org` as a default time server. [The NTP Pool for vendors](https://www.ntppool.org/en/vendors.html) page expressly forbids operating system vendors from doing this:

> ## Audience for this document
> Anyone distributing an appliance, operating system or some other kind of software using NTP.
>
> * Appliance vendors (Netgear, D-Link, Linksys, ...)
> * Operating System vendors (Debian, RedHat, FreeBSD, m0n0wall, ...)
> * Software vendors

…

> ## Get your vendor zone
> To allow you to use the pool as the default time service in your application, we will set you up with special hostnames, for example `0.vendor.pool.ntp.org`, `1.vendor.pool.ntp.org`, `2.vendor.pool.ntp.org` and `3.vendor.pool.ntp.org`.
>
> You **must absolutely not use the default pool.ntp.org zone names** as the default configuration in your application or appliance.

The constant is aware of this requirement:

https://github.com/siderolabs/talos/blob/a009f5c60c9506dd5064106bbef38fe36813db64/pkg/machinery/constants/constants.go#L701-L705

The comment dates to [early 2019](https://github.com/siderolabs/talos/commit/3693cff14f1aac1b164bbe1f55785b976f771b43#diff-431294aa14b9bdb92cc87b2e3dfe923170d62ab0a0f17564cea0b88dd08b70cfR23-R26). I'm not sure what naming needed sorting, but I imagine it's been resolved in the interim.

**Comment by smira** [comment]
we tried multiple times to apply, but never had a response back, happy to make a change if you have a way to push that request through

**Comment by willglynn** [comment]
Hmm… I tried filling out the form, and it says it's already in use:

<img width="581" alt="talos is already used" src="https://github.com/siderolabs/talos/assets/118362/1b5dcff9-2f29-447c-9041-677538576059">

Querying `0.talos.pool.ntp.org IN A` returns NXDOMAIN, so it's already in use but it doesn't exist.

I'll send an email. The `vendors@` link goes to `ask@`, so I'll address both.

**Comment by onedr0p** [comment]
Since talos is taken could you all apply for a sidero pool name?

**Comment by steverfrancis** [comment]
The "Talos" zone is taken by us - we applied for it well over a year ago, and our application has been stuck in "pending" since, despite repeated emails
<img width="279" alt="image" src="https://github.com/siderolabs/talos/assets/67986293/c42aeda1-f873-43b8-b87d-e1c94e3c5c59">

**Comment by willglynn** [comment]
This was resolved via #8396 and [released as 1.7.0](https://www.talos.dev/v1.7/introduction/what-is-new/).

**Comment by willglynn** [comment]
I can see that `talos.pool.ntp.org` resolves, though I have no details on the Sidero Labs <-> NTP Pool communications. I opened this issue because Talos was using `pool.ntp.org` against the explicit guidance of the NTP Pool, and Talos no longer does that, so I was happy to close it when prompted by the stale tag 🤷‍♂️

**Comment by smira** [comment]
> It defaults to cloudflare ntp servers but I thought the original ask was to use a talos.pool.ntp.org address when available? I figured that using the cloudflare ntp server was a workaround until then?

See #8396 for reasons, Talos default is what it is. You can override that with whatever setting makes sense in your environment.

NTP Pool never came back to us, but it's not relevant anymore.

**Comment by liljenstolpe** [comment]
I think it may not be wise to ship with something as key as time tied to a specific vendor as the default.  If cloudflare were to ever sunset the service, there would be a whole lot of zombied sysetems out there.  pool.ntp.org is a community service that has been specifically setup for this and is not tied to any specific vendor or person.  Also, the clocks are not tied to any specific entity - harder to manipulate.  

If there is a problem with talos.pool.ntp.org, that can probably be resolved - I would be happy to take it up with the pool operators, if that would swing this back to pool.

**Comment by smira** [comment]
I understand that concern, it's hard to offer something that would satisfy everyone. `pool.ntp.org` doesn't have IPv6 by default. 

I think the best course of action is to use NTP server in your infrastructure if you're serious about it. VMs can sync to the hypervisor clock bypassing NTP (Talos supports that), bare-metal machines should probably use a local time source. 

The edge deployments are tricky, as they need some kind of an external service.

Whatever the change was, it just changes the default, you are free to use `pool.ntp.org` if you prefer it over Cloudflare.
