### ISSUE TITLE
talosctl shutdown doesn't error if no talosconfig is passed.

### ISSUE THREAD

**Issue by iMartyn** [siderolabs/talos#7900]
## Bug Report

I ended up in a terminal where I hadn't exported `TALOSCONFIG` and issued a `talosctl shutdown` command and nothing happened.  I assumed it was an async command and waited... and waited.

### Description

There should be an error message if you issue a `talosctl shutdown` command without either an explicit `--talosconfig` or a `TALOSCONFIG` env var.

### Logs

```
/home/martyn [martyn@i9worker] [22:16]
> unset TALOSCONFIG

/home/martyn [martyn@i9worker] [22:16]
> talosctl shutdown -n 192.168.1.206 -e 192.168.1.206 --force

/home/martyn [martyn@i9worker] [22:16]
```
(no output seen on shutdown command)

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`] 1.5.4
- Kubernetes version: [`kubectl version --short`] v1.28.2
- Platform: metal-pine64

**Comment by smira** [comment]
you probably have a default `talosconfig` which has some (unreachable?) nodes, which `talosctl is using`.

`talosctl config info` to help, not an issue in the CLI.

**Comment by iMartyn** [comment]
No, I don't, and this is still an error that the CLI should handle, no matter what the cause!

```
/home/martyn [martyn@i9worker] [13:38]
> talosctl config info
no context is set

/home/martyn [martyn@i9worker] [13:38]
> talosctl shutdown -n 192.168.1.206 -e 192.168.1.206 --force

/home/martyn [martyn@i9worker] [13:39]
>
```
This is actually an issue in the CLI - no context should always return an error, not silently fail!

Please reopen.

**Comment by smira** [comment]
yep, looks like error reporting is broken there

**Comment by smira** [comment]
@utkuozdemir I think something is wrong here

https://github.com/siderolabs/talos/blob/ef5056122b38a168dd8ee429a6bc4cad0860177d/cmd/talosctl/pkg/talos/action/tracker.go#L210-L213

and many commands using this code path are broken same way

**Comment by utkuozdemir** [comment]
@smira Yes, seems like it. I'll submit a fix.
