### ISSUE TITLE
Inconsistencies between factory generated installer image vs default ghcr.io installer image

### ISSUE THREAD

**Issue by buroa** [siderolabs/talos#7908]
## Bug Report

The images have large differences between archive compressions (initramfs) and missing items.

Factory generated installer image: `factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba:v1.5.4`
Default installer image: `ghcr.io/siderolabs/installer:v1.5.4`

### Description

I'd imagine them to be very similar, if not the same.

Factory image: `initramfs.xz: ASCII cpio archive (SVR4 with no CRC)`
Default image: `initramfs.xz: XZ compressed data, checksum CRC32`

The factory image does not contain a `rootfs.sqsh` or `init` inside `initramfs.xz`; it seems to be completely off.

**Comment by frezbo** [comment]
Image factory is still not publically announced, still WIP, thanks for reporting the issue though.

**Comment by smira** [comment]
it's hard to analyze `initramfs.xz` correctly with regular file tools, as it contains several concatenated images. the easiest way is to try to use it to do the actual upgrade; Image Factory installer image will not be ever byte-by-byte identical to the "vanilla" image, as it contains additional bits identifying schematics. if you have a problem _using_ the installer image, please report it here.

**Comment by smira** [comment]
In fact `unmkinitramfs` has a limit on the structure of the `initramfs`, so it can't uncompress everything that we produce.
