### ISSUE TITLE
Imager: allow specifying extension without tag

### ISSUE THREAD

**Issue by buroa** [siderolabs/talos#7912]
## Feature Request

I would like a way to generate assets with imager without including the system extension image tag for official extensions; it can look it up instead if not specified.

**Comment by smira** [comment]
It is already supported via Talos Image Factory (to be launched soon), so we do not plan to make part of Talos imager to keep it simple.

If you do not want to use Talos Image Factory, you script it following the instructions in the extensions repo on determining compatible versions.
