### ISSUE TITLE
Node refused to be ready when having wrong hostname

### ISSUE THREAD

**Issue by budimanjojo** [siderolabs/talos#7928]
### Description
I learned the hard way when trying to create a new cluster with `machine.network.hostname` set to `master_microserver_62`.
The `kubelet` in READY state forever with kubernetes cluster not starting.
The problem is `hostname` according to RFC1123 should only contains:
- `[a-zA-Z0-9-]`, can't start and end with `-`
- Not more than 255 characters
- Each label is separated by `.` and can't be longer than 63 characters

Basically it should be a valid DNS. I think there should be a validation check just like `cluster.network.dnsDomain` but then I found out that the current [validation of DNS](https://github.com/siderolabs/talos/blob/813442dd7a08b2781829ef190b110aa38c725932/pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go#L346) doesn't seem to be correct according to RFC1123 too (although I tried creating a new cluster with invalid domain and it starts just fine).

My suggestion is to fix the current `isValidDNSName()` function and then use that function to also validate `machine.network.hostname` (I can create a PR if needed).

### Logs
`talosctl health` shows this:
```
discovered nodes: ["192.168.200.72"]
waiting for etcd to be healthy: ...
waiting for etcd to be healthy: OK
waiting for etcd members to be consistent across nodes: ...
waiting for etcd members to be consistent across nodes: OK
waiting for etcd members to be control plane nodes: ...
waiting for etcd members to be control plane nodes: OK
waiting for apid to be ready: ...
waiting for apid to be ready: OK
waiting for all nodes memory sizes: ...
waiting for all nodes memory sizes: OK
waiting for all nodes disk sizes: ...
waiting for all nodes disk sizes: OK
waiting for kubelet to be healthy: ...
waiting for kubelet to be healthy: OK
waiting for all nodes to finish boot sequence: ...
waiting for all nodes to finish boot sequence: OK
waiting for all k8s nodes to report: ...
waiting for all k8s nodes to report: Get "https://192.168.200.72:6443/api/v1/nodes": dial tcp 192.168.200.72:6443: connect: connection refused
```

Thanks before!

**Comment by smira** [comment]
It's actually not accurate, `hostname` in Linux has no restrictions, while `nodename` in Kubernetes should be a DNS name.

Talos 1.6 will do automatic fixups for nodenames: https://github.com/siderolabs/talos/pull/7649

**Comment by budimanjojo** [comment]
So this means in v1.6 this problem wouldn't occur and I just get a cluster with the node named `master-microserver-62` instead? Thanks!
