### ISSUE TITLE
Define system extensions in the machine config and automatically generate installer image

### ISSUE THREAD

**Issue by mirceanton** [siderolabs/talos#7962]
## Feature Request

In the previous versions of Talos, we were able to clearly define the system extensions in the Machine Config, but this feature has now been deprecated in favor of the image factory. The problem here is that it now makes it more difficult to handle upgrades.

I think that the system extensions should still be clearly defined in the Machine Config, and one option to do it this way is to list them in the format that is expected by the image factory, such as

```yaml
machine:
  install:
    systemExtensions:
      officialExtensions:
        - siderolabs/i915-ucode
```

And then have either Talos or the `talosctl` utility send an API call to the image factory endpoint to get the image name to pull.

### Description

Here is a bit of context:

I did the initial bootstrapping with an installer image that had some extensions, but since the OS was already installed (I did a `talosctl reset` from a previous test), the extensions were not loaded.

Then, I ran a `talosctl upgrade` on the nodes, but since I did not specify the installer image again, I did not get extensions installed.

Okay then... I ran a `talosctl upgrade --image=...` while specifying the image with the extensions in it, and I did eventually get them installed.

Now if I run a `talosctl upgrade` again, with no image specified then the extensions are now gone. This means I now have to be extra careful for  upgrade commands not to nuke all my extensions.

Since we have the yaml configuration file which is supposed to be a manifest of what the OS should look like, it is a bit confusing not to have the system extensions also in that manifest and require us to manually generate a new image via the factory website on every upgrade. It also makes it more likely that users forget to generate an image and uninstall all their extensions.

**Comment by smira** [comment]
I fully understand your concern, but there are many issues with building an image on the host:

* Talos can't find required extensions e.g. when in air-gapped
* this is not compatible with SecureBoot (asset should be signed outside of the machine)
* this doesn't solve the problem of having extension on the initial boot (e.g. extra required firmware)
* it requires lots of RAM to unpack and build the final image (it runs without disk mounted)

We recommend to use the Image Factory which completely solves the issue as long as you follow right schematic for the machine. (See documentation: https://www.talos.dev/v1.5/talos-guides/install/boot-assets/#image-factory)

As a higher-level integration which hides the complexity, [Omni](https://www.siderolabs.com/platform/saas-for-kubernetes/) will soon full transparent integration with Image Factory.

There might be some level of integration outside of Talos for those who is not planning to use Omni, but not inside Talos.

**Comment by mirceanton** [comment]
@smira i wasn't proposing to build the image locally. Rather, I was thinking to have a flag for the upgrade command which would instruct the talosctl utility to send a POST request to the image factory API in order to fetch the hash for the image and use that as the input to `--image`.

Basically, you would be able to either: 
- specify your own image built with whatever method you prefer and pass it to `--image`
- specify the extensions and kernel params in the machine config and pass the `--generate-factory-image` or something like that to fetch the correct image name from the factory API

**Comment by smira** [comment]
@mirceanton that is doable, we haven't got yet to that point, and what the API should look like.

**Comment by mirceanton** [comment]
@smira for now I managed to work around this by improving https://github.com/budimanjojo/talhelper to allow generating `talosctl` commands for upgrades

I still think it would be nice if `talosctl` would be able to handle it OOTB

**Comment by btrepp** [comment]
I think I hit this recently that 'talosctl upgrade' is now a massive foot-gun.

Before you would have the extensions installed, now talosctl upgrade goes for a blank image, without any extensions, which can cause your machine to no-longer work if you required an extension. I was expecting that it would use the image key in install, but it wasn't.

That is fine, but does make me wonder what machine.install.image is used for, it's a very specific case now of initial talos running (but has your extensions) and then installing to disk.
