### ISSUE TITLE
Add sending host to logging

### ISSUE THREAD

**Issue by myoung34** [siderolabs/talos#7963]
## Feature Request

I would like to enrich the logs so that the json output for machine and server logging indicates which host is sending the logs

### Description

In [the docs](https://www.talos.dev/v1.5/talos-guides/configuration/logging/) there are samples of logs:

```
{
  "msg": "[talos] apply config request: immediate true, on reboot false",
  "talos-level": "info",
  "talos-service": "machined",
  "talos-time": "2021-11-10T10:48:49.294858021Z"
}
```
and
```
{
  "clock":6252819, // time relative to the kernel boot time
  "facility":"user",
  "msg":"[talos] task startAllServices (1/1): waiting for 6 services\n",
  "priority":"warning",
  "seq":711,
  "talos-level":"warn", // Talos-translated `priority` into common logging level
  "talos-time":"2021-11-26T16:53:21.3258698Z" // Talos-translated `clock` using current time
}
```
but neither indicate the host, which makes it hard from my receiver to know which node to investigate

If you do `dmesg` on a node the CLI indicates which nodes are producing what data:

```
➜  talos git:(main) ✗ talosctl dmesg -n 192.168.1.21,192.168.1.22 | grep IPv6 
192.168.1.22: kern:    info: [2023-11-17T15:59:01.828235563Z]: IPv6: ADDRCONF(NETDEV_CHANGE): veth0edccae0: link becomes ready
192.168.1.21: kern:    info: [2023-11-16T21:06:28.719452351Z]: IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
```

It would be nice to have this in the JSON output as well. the key does not matter such as adding `"node": "192.168.1.21"`

**Comment by myoung34** [comment]
Can we keep this open for the static tag for sender configuration then?

**Comment by smira** [comment]
@myoung34 please create a new issue for that, this issue has a different topic.
