### ISSUE TITLE
Deploying metrics server causes kubelet crash loop

### ISSUE THREAD

**Issue by rochecompaan** [siderolabs/talos#7977]
## Bug Report

Installing metrics server in a running cluster causes kubelet crash loop

### Description

I had a running cluster and installed the metrics server as per the instructions at https://www.talos.dev/v1.5/kubernetes-guides/configuration/deploy-metrics-server/. 

Now all health checks fail and my cluster is unusable.
```
❯ talosctl --talosconfig talosconfig health
healthcheck error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp x.x.x.x:50000: i/o timeout"
```
And I see the following in the console logs:
```
[ 1108.631020] [talos] service[kubelet](Waiting): Error running Containerd(kubelet), going to restart forever: task "kubelet" failed: exit code 1
[ 1109.336118] [talos] controller failed {"component": "controller-runtime", "controller": "k8s.NodeApplyController", "error": "1 error(s) occurred:\n\terror getting node: Get \"https://localhost:6443/api/v1/nodes/ip-172-16-21-201.ec2.internal?timeout=30s\": dial tcp [::1]:6443: connect: connection refused"}
[ 1110.296581] [talos] task startAllServices (1/1): service "kubelet" to be "up"
[ 1112.447103] [talos] controller failed {"component": "controller-runtime", "controller": "k8s.ManifestApplyController", "error": "error creating mapping for object /v1/Namespace/kubelet-serving-cert-approver: Get \"https://localhost:6443/api?timeout=32s\": dial tcp [::1]:6443: connect: connection refused"}
[ 1113.780089] [talos] service[kubelet](Running): Started task kubelet (PID 16360) for container kubelet
[ 1113.934620] [talos] service[kubelet](Waiting): Error running Containerd(kubelet), going to restart forever: task "kubelet" failed: exit code 1
[ 1119.156911] [talos] service[kubelet](Running): Started task kubelet (PID 16434) for container kubelet
```

### Environment

- Talos version:
```
Client:
	Tag:         v1.5.4
	SHA:         9cf7980e
	Built:
	Go version:  go1.20.10
	OS/Arch:     linux/amd64
Server:
error getting version: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate signed by unknown authority"
```
- Kubernetes version: v1.28.2
- Platform: AWS (deployed with a terraform config based on https://github.com/siderolabs/contrib/tree/main/examples/terraform/aws with ccm disabled.

**Comment by smira** [comment]
You have a mix of problems in this ticket:

* `error getting version: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate signed by unknown authority"` using wrong client-side `talosconfig` to access the cluster
* `healthcheck error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp x.x.x.x:50000: i/o timeout"` your firewall blocks the access? hard to guess? 
* `[ 1113.934620] [talos] service[kubelet](Waiting): Error running Containerd(kubelet), going to restart forever: task "kubelet" failed: exit code 1` hard to guess, but the kubelet is not happy about the config you applied, `talosctl -n <IP> logs kubelet` should tell you more.

**Comment by rochecompaan** [comment]
Please ignore the cluster connection errors because as I indicated, the cluster was working fine before I installed metrics server. From the EC2 console logs, this line stands out for me:
 ```
 [ 1112.447103] [talos] controller failed {"component": "controller-runtime", "controller": "k8s.ManifestApplyController", "error": "error creating mapping for object /v1/Namespace/kubelet-serving-cert-approver: Get \"https://localhost:6443/api?timeout=32s\": dial tcp [::1]:6443: connect: connection refused"}
```
My Terraform config contains a `talos_cluster_health` check that has passed each time I made changes, right up to the point where I applied the following patch:
```
cluster:
  extraManifests:
    - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
    - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
```
I can't use talosctl to extract any logs due to the connection error ...

**Comment by smira** [comment]
You can't have connection errors talking to controlplane because of the `kubelet`. The `kubelet` failure might cut off only workers in case your firewall is misconfigured, but controlplanes are always running Talos API.

As the kubelet doesn't run, you don't have Kubernetes API server running, and that means you will see errors accessing `[::1]:6443`. 

So go backwards, resolve Talos API access, and go from it.

**Comment by rochecompaan** [comment]
I double-checked and the firewall is not blocking the talosapi. The error below suggests that the problem lies with auth:
```
error getting version: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate signed by unknown authority
```

Is it possible that enabling certificate rotation invalidated the client certificate in my talosconfig?

Specifically this part in the "Deploy Metrics Server" docs:
```
machine:
  kubelet:
    extraArgs:
      rotate-server-certificates: true
```

**Comment by rochecompaan** [comment]
Ignore the above error, I was missing `--talosconfig talosconfig` when I ran `talosctl`. I got access to the kubelet logs and the error does indeed relate to the `rotate-server-certificates` setting:
```
44.201.31.159: Flag --container-runtime-endpoint has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
44.201.31.159: E1122 12:18:38.387137    8162 run.go:74] "command failed" err="failed to parse kubelet flag: unknown flag: --rotate-server-certificate"
```

I think the setting was applied before metrics server was successfully installed. Let me investigate further ...

**Comment by rochecompaan** [comment]
I patched the kubelet to remove the `extraArgs` and the kubelet is running on all nodes again:
```
❯ talosctl patch machineconfig --nodes x.x.x.x --patch @remove-kubelet-args.patch
```

The patch was simply:
```
[
  { "op": "remove", "path": "/machine/kubelet/extraArgs" }
]
```

I got my cluster back up, but I'm not sure how to deploy metrics server now. Can I omit the `rotate-server-certificates` kubelet arg and expect it to work?

**Comment by smira** [comment]
```
44.201.31.159: E1122 12:18:38.387137    8162 run.go:74] "command failed" err="failed to parse kubelet flag: unknown flag: --rotate-server-certificate"
```

flag name is misspelled

**Comment by rochecompaan** [comment]
I can't believe it :facepalm: Thank you for your help and your patience!
