### ISSUE TITLE
[images] Factory/Image-Repo unstable

### ISSUE THREAD

**Issue by Ornias1993** [siderolabs/talos#7986]
### Description

I've worked on writhing documentation and tooling to streamline our deployment of Talos on a small on-premise cluster.
This, obviously, includes thoroughly testing every step. Including actually bootstrapping and applying a test cluster.

During testing I've seen troublesome results with the factory or image host.
Some images (code created by factory) don't pull at all and throw HTTP 500, others randomly don't pull. (see example 2).

The download process for iso's from the factory is also dog-shit slow, maybe the unreliable behavior is related when it comes to image pulls?

This is hard to put into documentation/scripting, because we now need to take into account cases where the pull doesn't work nicely. Which should be an absolute edgecase and not something happening this frequently.

### Logs

Example 1:
Frequent http 500 errors, which go away when using a slightly different factory image.

Example 2:
<img width="950" alt="image" src="https://github.com/siderolabs/talos/assets/7613738/1dfa14c2-92f7-4c57-ab38-28e258d5a0a3">

### Environment

- Talos version: 1.5.5
- Kubernetes version:  1.28.3
- Platform: Linux-talosctl, Talos-talos

**Comment by Ornias1993** [comment]
Besides the above, I noticed talosOS does absolutely zero attempts of retrying on image pull failure.
I would expect a timer, then retry at least 2, preferably 3 times.

What would be even better if upgrade and initial-apply get a response if the image pull worked out or not.

**Comment by smira** [comment]
Talos does retry image pulls.

If you have an issue with specific Image Factory image pull, please create an issue with reference (without images).

**Comment by Ornias1993** [comment]
> Talos does retry image pulls.
> 
> If you have an issue with specific Image Factory image pull, please create an issue with reference (without images).

It does, at least, not show this in the logs though... So that could be more clear...

Anyway the reference:
 192.168.10.141: rpc error: code = Unknown desc = error validating installer image "factory.talos.dev/installer/f7ae046f90d0ff4ac315a1810c77e5cf7357fe68e2181aad4a6175f5d6defc0b:v1.5.5": 2 error(s) occurred:
    failed to pull image "factory.talos.dev/installer/f7ae046f90d0ff4ac315a1810c77e5cf7357fe68e2181aad4a6175f5d6defc0b:v1.5.5": failed to resolve reference "factory.talos.dev/installer/f7ae046f90d0ff4ac315a1810c77e5cf7357fe68e2181aad4a6175f5d6defc0b:v1.5.5": pulling from host factory.talos.dev failed with status code [manifests v1.5.5]: 500 Internal Server Error
