### ISSUE TITLE
Protect `talosctl` command that do modifications

### ISSUE THREAD

**Issue by chevdor** [siderolabs/talos#7996]
## Feature Request

`talosctl reset` should not:
- trigger a reset on all nodes by default
- trigger any reset at all without some confirmation

### Description

Many `talosctl` commands do not support multinodes, so invoking them does nothing and shows the help. This is actually fine. This is convenient to the point that one may get used to issusing `talosctl <command>` without `--help` to get help about a command.

Some rather desctructive commands such as `reset` however, work all fine, on multiple nodes, and require 0 confirmation !

I got bit ! I expected `reset` to behave the same as many other command and issued a `talosctl reset` command, not even expecting for a second it would actually perform the reset immediately, and on ALL nodes... (It actually failed and reset only 2/3 nodes). It is also probably not advisbable to start a reset simultaneously on all nodes unless this "extrem" reset is wanted.

The reset command is critical enough, I would suggest making mandatory to provide the nodes for the reset command:
- `talosctl reset` -> fails or show help
- `talosctl reset -n $IP1` does reset node with IP $IP1
- `talosctl reset -n $IP1 -n $IP2` fails, simultaneous reset is not recommended
- `talosctl reset -n $IP1 -n $IP2 --simultaneous` does reset nodes with IP $IP1 and $IP2

**Comment by smira** [comment]
Yes, this behavior is documented and not recommeded to do so:

> The node is the target node on which you wish to perform the API call. While you can configure the target node (or even set of target nodes) inside the ’talosctl’ configuration file, it is recommended not to do so, but to explicitly declare the target node(s) using the -n or --nodes command-line parameter.

https://www.talos.dev/v1.5/learn-more/talosctl/

Resetting a node is a destructive action, so resetting more than a single node only makes sense if the whole cluster is about to be destroyed, otherwise a user should wait for the cluster to recover fully before proceeding to the next machine.

**Comment by smira** [comment]
(I don't want to say that the change is not needed, but just providing some extra context).

**Comment by chevdor** [comment]
> While you can configure the target node (or even set of target nodes) inside the ’talosctl’ configuration file, it is recommended not to do so

I see.

The trade off is that NOT adding nodes to the config means having to provide the node(s) as extra flags almost all the time which is a pain when you just want to **read** data.

(The naming of the flags/ENV below are only examples to illustrate the idea ...)

IMHO: Destructive actions should be always gated, no matter what the config contains.

That can be done easily globally with a flag such as `--yes` that can be overriden by an ENV such as `TALOS_ALWAYS_YES`. I am not sure why anyone would like to take the risk of setting that ENV, besides for testing and automation maybe.

Ideally, it should be OK to tell talos about the nodes in the config, and destructive actions should only provide a summary of what is about to be done (with a link to the doc if required since the doc already contains a lot of good content), mentioning that nothing will be done until `--yes` is provided.

**Comment by smira** [comment]
Yes, `operator` doesn't allow destructive actions, so you can't e.g. reset all nodes, but you can still reboot all of them.
