### ISSUE TITLE
ARP flooding on unrelated interface

### ISSUE THREAD

**Issue by ruifung** [siderolabs/talos#7997]
### Description
So apparently, while troubleshooting something else with wireshark. I noticed my worker nodes were sending an enormous amount of ARP requests for the control plane nodes out of their secondary interface connected to my IoT VLAN (eth1.55). For obvious reasons, I do not have the control plane nodes on this VLAN.

Every node seems to be sending like 1 arp broadcast for each control plane node every second.
This only seems to occur as long as it's not receiving any arp responses to the broadcast.
If I configure my router to respond for those addresses, the rate seems to reduce significantly.
This seems similar to #7690 in that it appears to be some kind of healthcheck instead of legitimate ARP traffic. 

All nodes are reachable over eth0 (10.229.97.0/24)

### Logs
For reference, here's the output from talos get address on one worker node
```
NODE           NAMESPACE   TYPE            ID                                                 VERSION   ADDRESS                                    LINK
10.229.97.34   network     AddressStatus   cilium_geneve/fe80::b2:4bff:fea6:6207/64           2         fe80::b2:4bff:fea6:6207/64                 cilium_geneve
10.229.97.34   network     AddressStatus   cilium_host/10.96.4.160/32                         1         10.96.4.160/32
         cilium_host
10.229.97.34   network     AddressStatus   cilium_host/fd96:619:6b75:105::f670/128            1         fd96:619:6b75:105::f670/128                cilium_host
10.229.97.34   network     AddressStatus   cilium_host/fe80::c76:1cff:fede:b59d/64            1         fe80::c76:1cff:fede:b59d/64                cilium_host
10.229.97.34   network     AddressStatus   cilium_net/fe80::b8ca:8aff:feb8:a026/64            1         fe80::b8ca:8aff:feb8:a026/64               cilium_net
10.229.97.34   network     AddressStatus   eth0/10.229.97.34/24                               1         10.229.97.34/24
         eth0
10.229.97.34   network     AddressStatus   eth0/fd96:619:97:0:be24:11ff:fe54:fee6/64          2         fd96:619:97:0:be24:11ff:fe54:fee6/64       eth0
10.229.97.34   network     AddressStatus   eth0/fe80::be24:11ff:fe54:fee6/64                  2         fe80::be24:11ff:fe54:fee6/64               eth0
10.229.97.34   network     AddressStatus   eth1.55/fd96:619:4:0:be24:11ff:fe43:7727/64        2         fd96:619:4:0:be24:11ff:fe43:7727/64        eth1.55
10.229.97.34   network     AddressStatus   eth1.55/fe80::be24:11ff:fe43:7727/64               2         fe80::be24:11ff:fe43:7727/64               eth1.55
10.229.97.34   network     AddressStatus   eth1/fe80::be24:11ff:fe43:7727/64                  2         fe80::be24:11ff:fe43:7727/64               eth1
10.229.97.34   network     AddressStatus   lo/127.0.0.1/8                                     1         127.0.0.1/8
         lo
10.229.97.34   network     AddressStatus   lo/::1/128                                         1         ::1/128
```
Wireshark capture screenshot
![image](https://github.com/siderolabs/talos/assets/1073945/d6be497d-355a-4374-a9a9-8461793e2992)

### Environment

- Talos version:
```
Client:                                                                                                                                           Tag:         v1.5.4                                                                                                                       SHA:         9cf7980e                                                                                                                     Built:
        Go version:  go1.20.10
        OS/Arch:     windows/amd64
Server:
        NODE:        10.229.97.36
        Tag:         v1.5.5
        SHA:         ad7361c7
        Built:
        Go version:  go1.20.11
        OS/Arch:     linux/amd64
        Enabled:     RBAC
        NODE:        10.229.97.34
        Tag:         v1.5.5
        SHA:         ad7361c7
        Built:
        Go version:  go1.20.11
        OS/Arch:     linux/amd64
        Enabled:     RBAC
        NODE:        10.229.97.35
        Tag:         v1.5.5
        SHA:         ad7361c7
        Built:
        Go version:  go1.20.11
        OS/Arch:     linux/amd64
        Enabled:     RBAC
```
- Kubernetes version:
```
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3
```
- Platform: metal (Proxmox)

**Comment by ruifung** [comment]
Yeah except that interface it's sending the arp on, is configured to have no address, and no dhcp disabled, meant for use with multus-cni.

It's literally trying to reach the 10.229.97.0/24 network, on the interface with no addresses, connected to the 10.229.4.0/24 network. And 10.229.97.0/24 isn't anywhere on the routing table for that interface either.

**Comment by smira** [comment]
I can't really provide any help with that, but Talos userspace doesn't manage the way ARP requests are sent. ARP requests are sent by Linux kernel based on the configuration of the network.

**Comment by smira** [comment]
So if there's anything that Talos misconfigures on the networking layer - we should certainly fix that. I believe ARP requests will only be sent to the link which has a matching subnet assigned to it.

**Comment by ruifung** [comment]
NODE           NAMESPACE   TYPE            ID                                                 VERSION   ADDRESS                                    LINK
10.229.97.34   network     AddressStatus   cilium_geneve/fe80::b2:4bff:fea6:6207/64           2         fe80::b2:4bff:fea6:6207/64                 cilium_geneve
10.229.97.34   network     AddressStatus   cilium_host/10.96.4.160/32                         1         10.96.4.160/32
         cilium_host
10.229.97.34   network     AddressStatus   cilium_host/fd96:619:6b75:105::f670/128            1         fd96:619:6b75:105::f670/128                cilium_host
10.229.97.34   network     AddressStatus   cilium_host/fe80::c76:1cff:fede:b59d/64            1         fe80::c76:1cff:fede:b59d/64                cilium_host
10.229.97.34   network     AddressStatus   cilium_net/fe80::b8ca:8aff:feb8:a026/64            1         fe80::b8ca:8aff:feb8:a026/64               cilium_net
10.229.97.34   network     AddressStatus   eth0/10.229.97.34/24                               1         10.229.97.34/24
         eth0
10.229.97.34   network     AddressStatus   eth0/fd96:619:97:0:be24:11ff:fe54:fee6/64          2         fd96:619:97:0:be24:11ff:fe54:fee6/64       eth0
10.229.97.34   network     AddressStatus   eth0/fe80::be24:11ff:fe54:fee6/64                  2         fe80::be24:11ff:fe54:fee6/64               eth0
10.229.97.34   network     AddressStatus   eth1.55/fd96:619:4:0:be24:11ff:fe43:7727/64        2         fd96:619:4:0:be24:11ff:fe43:7727/64        eth1.55
10.229.97.34   network     AddressStatus   eth1.55/fe80::be24:11ff:fe43:7727/64               2         fe80::be24:11ff:fe43:7727/64               eth1.55
10.229.97.34   network     AddressStatus   eth1/fe80::be24:11ff:fe43:7727/64                  2         fe80::be24:11ff:fe43:7727/64               eth1
10.229.97.34   network     AddressStatus   lo/127.0.0.1/8                                     1         127.0.0.1/8
         lo
10.229.97.34   network     AddressStatus   lo/::1/128                                         1         ::1/128

This is the address list as seen from talos get address, I was running wireshark ssh to my router on vlan 55. eth0 is connected to vlan 97 in proxmox, and eth1 trunk.

So, of interest is, when I enabled dhcp on the vlan subinterface, the arp messages I see becomes something like WHO HAS 10.229.97.31 TELL 10.229.4.100 or something like that.

So it does seem like something is off?

**Comment by smira** [comment]
I don't know about your setup, but `eth0` is certainly not VLAN on Talos side, and it has address assigned, so packets will go there. Proxmox setup - that's out of Talos scope here.

**Comment by ruifung** [comment]
In conclusion, my testing has yielded the following results:
If the node is started with DHCPv4 and SLAAC enabled on eth1, ARP healthchecks are not sent there.
If the node is started with only DHCPv4 enabled on eth1, ARP healthchecks are not sent there.
If the node is started with only SLAAC enabled on eth1, ARP healthchecks are sent there.

Which leads me to the thought, how does KubePrism send it's ARP healthchecks. I know for example, the arping command on linux can have it's interface specified, so I wonder if there's something similar going on here.

**Comment by smira** [comment]
KubePrism doesn't do anything ARP-related specifically, it rather does TCP probes of the endpoints of the controlplane it can discover.

If your controlplane has IPs of IP1, IP2 and port 6433, it will try to connect to `IP1:6443`, `IP2:6443`, etc. If it can't connect, it will drop the endpoint from the list, but keep running healthchecks in the background.
