### ISSUE TITLE
gen config doesn't set the endpoints or update the correct files.

### ISSUE THREAD

**Issue by Mechputer** [siderolabs/talos#8000]
### Description
talosctl gen config <cluster-name> <endpoint> doesn't set the endpoint or update the correct files.

erik@Bruiser:~$ talosctl gen config arachne https://10.0.0.36:6443 --force
generating PKI and tokens
Created /home/erik/controlplane.yaml
Created /home/erik/worker.yaml
Created /home/erik/talosconfig
erik@Bruiser:~$ 
erik@Bruiser:~$ talosctl config contexts
CURRENT   NAME            ENDPOINTS   NODES
*         talos-default   127.0.0.1   
erik@Bruiser:~$ kubectl config get-contexts
CURRENT   NAME                  CLUSTER         AUTHINFO              NAMESPACE
*         admin@talos-default   talos-default   admin@talos-default   default
erik@Bruiser:~$ sudo talosctl gen config arachne https://spider:6443 --force
[sudo] password for erik: 
generating PKI and tokens
Created /home/erik/controlplane.yaml
Created /home/erik/worker.yaml
Created /home/erik/talosconfig
erik@Bruiser:~$ kubectl config get-contexts
CURRENT   NAME                  CLUSTER         AUTHINFO              NAMESPACE
*         admin@talos-default   talos-default   admin@talos-default   default
erik@Bruiser:~$ talosctl config contexts
CURRENT   NAME            ENDPOINTS   NODES
*         talos-default   127.0.0.1   
erik@Bruiser:~$ ls
controlplane.yaml  talosconfig  worker.yaml
erik@Bruiser:~$ echo $TALOSCONFIG

erik@Bruiser:~$ echo ${TALOSCONFIG}

erik@Bruiser:~$ TALOSCONFIG=~/.talos/config
erik@Bruiser:~$ echo ${TALOSCONFIG}
/home/erik/.talos/config
erik@Bruiser:~$ KUBECONFIG=~/.kube/config
erik@Bruiser:~$ talosctl gen config arachne https://spider:6443 --force
generating PKI and tokens
Created /home/erik/controlplane.yaml
Created /home/erik/worker.yaml
Created /home/erik/talosconfig
erik@Bruiser:~$ talosctl config contexts
CURRENT   NAME            ENDPOINTS   NODES
*         talos-default   127.0.0.1   
erik@Bruiser:~$ kubectl config get-contexts
CURRENT   NAME                  CLUSTER         AUTHINFO              NAMESPACE
*         admin@talos-default   talos-default   admin@talos-default   default
erik@Bruiser:~$ sudo talosctl gen config arachne https://spider:6443 --force
generating PKI and tokens
Created /home/erik/controlplane.yaml
Created /home/erik/worker.yaml
Created /home/erik/talosconfig
erik@Bruiser:~$ kubectl config get-contexts
CURRENT   NAME                  CLUSTER         AUTHINFO              NAMESPACE
*         admin@talos-default   talos-default   admin@talos-default   default
erik@Bruiser:~$ kubectl config get-contexts
CURRENT   NAME                  CLUSTER         AUTHINFO              NAMESPACE
*         admin@talos-default   talos-default   admin@talos-default   default
erik@Bruiser:~$ talosctl config contexts
CURRENT   NAME            ENDPOINTS   NODES
*         talos-default   127.0.0.1   
erik@Bruiser:~$

### Environment

- Talos version: 1.5.5
- Kubernetes version: 1.28.3
- Platform: Various

**Comment by smira** [comment]
Please use proper GitHub markdown formatting to make your issue more readable.

Besides that, I don't see an issue with `talosctl gen config`:

1. It generates `talosconfig`, but it doesn't merge it into the default location (`talosctl --talosconfig=talosconfig config get-contexts` would be correct).
2. It doesn't know `endpoints`, as they are not the input to the command (endpoints are addresses of the controlplane nodes).
3. It doesn't generate `kubeconfig` at all (it can be pulled with `talosctl kubeconfig`).

You might want to look into the [documentation](https://www.talos.dev/v1.5/introduction/getting-started/) and [advanced version of it](https://www.talos.dev/v1.5/introduction/prodnotes/).
