### ISSUE TITLE
Preview option for the `patch` command

### ISSUE THREAD

**Issue by chevdor** [siderolabs/talos#8002]
## Feature Request

new `--preview` flag.

```
talosctl patch mc \
        --preview \                       # <---- HERE
        --nodes $IP1 \
        --patch @patch.yaml
```

### Description

Current, `talosctl patch` allows using `--dry-run` with a basic diff output.
There are better tools to do yaml diffing but those require an input that is currently not available since `--dry-run` already does the diffing.

The idea is that `--preview' simply generates the new machine config and sends it to stdout, making it possible to pipe to other tools such as `dyff` etc...

This would also allow custom validation and further testing on the machine config as we could then:
- generate the new mc candidate with `--preview`
- run some testing on the new yaml (ie, in my cluster, the key `/foo/bar/baz` **must** have the value `zxy`)
- either accept the new maching config and hand over to talosctl or reject and discard the change

**Comment by smira** [comment]
You can already do what you're looking for with `talosctl config patch` which is an offline config patcher, preview/diff/whatever, and then apply with `talosctl apply-config`. We recommend to manage machine configuration in a [reproducible manner](https://www.talos.dev/v1.5/introduction/prodnotes/#configure-talos) with base secrets and config patches, so it can be regenerated with new set of patches at any point in time.

**Comment by chevdor** [comment]
My issue is about the machine config, not the config and its contexts.
I don't see any `talosctl config patch` subcommand available in the help.
I am using:
```
Client:
        Tag:         v1.5.5
        SHA:         ad7361c7
        Built:       
        Go version:  go1.20.11
        OS/Arch:     darwin/amd64
```

**Comment by smira** [comment]
Sorry, `talosctl machineconfig patch`. 

See https://www.talos.dev/v1.5/introduction/prodnotes/#machine-configs-as-templates

**Comment by chevdor** [comment]
It is easy to confuse `talosctl mc patch` and `talosctl patch mc` 😃 
It indeed solves what I want to do.
