### ISSUE TITLE
Support for `deviceSelector` on Bridge interfaces

### ISSUE THREAD

**Issue by JJGadgets** [siderolabs/talos#8020]
### Description
Currently, bridge interfaces must declare the interfaces to be included in device name format, e.g. `eno1` or `eth0` or `enp1s0`.

Being able to define which interfaces to include in the bridge with a `deviceSelector` array would be nice, so _all_ matching deviceSelectors in the array would be added to the bridge.

Something like this: https://github.com/JJGadgets/Biohazard/blob/eee8324852b030068190ee9bbcdc93438a80d085/kube/clusters/nuclear/talos/talconfig.yaml#L44L53 (see the commented deviceSelector key)

**Comment by smira** [comment]
This was already implemented: https://www.talos.dev/v1.7/talos-guides/network/device-selector/#using-device-selector-for-bonding

**Comment by JJGadgets** [comment]
@smira the documentation you linked is referring to bond interfaces, does it also work with bridge interfaces?

(I'm not currently on 1.7 so I can't try this out yet)

**Comment by BobyMCbobs** [comment]
This issue should still be relevant
