### ISSUE TITLE
:bug: talos 1.6.0-beta.0 cannot boot in qemu/kvm

### ISSUE THREAD

**Issue by rgl** [siderolabs/talos#8023]
### Description

While trying to upgrade to talos 1.6.0-beta.0 at https://github.com/rgl/terraform-libvirt-talos/tree/upgrade-to-talos-1.6 (in qem/kvm VMs), talos cannot boot in qemu/kvm due to:

![image](https://github.com/siderolabs/talos/assets/43356/d5600171-fa88-4796-ba2d-f3c2c49d5735)

digging a little bit at the grub prompt with `ls (hd0,gpt3)/grub/x86_64-efi/`, it seems there's a bug somewhere trying to find files with the `error: invalid XFS directory entry` error:

![image](https://github.com/siderolabs/talos/assets/43356/bac48545-0a8c-48a6-afb6-fc2523f5e77b)

it seems this kind of bug is being reported elsewhere, I found these might help understand/fix the problem:

* https://github.com/siderolabs/pkgs/commit/70919d8
* https://savannah.gnu.org/bugs/?64376
* https://github.com/calamares/calamares/issues/2166
* https://git.savannah.gnu.org/cgit/grub.git/commit/?id=aa7c1322671eef48ba72d3b733da37e63eb37328
* https://git.savannah.gnu.org/cgit/grub.git/commit/?id=ad7fb8e2e02bb1dd0475ead9919c1c82514d2ef8

### Environment

- Talos version: talos 1.6.0-beta.0
- Kubernetes version: 1.27.8
- Platform: qemu/kvm

**Comment by frezbo** [comment]
We've decided to revert the grub version since it's the fix for large initramfs is not backportable, we'll be moving towards possible grub meaintained by redhat for  bios implementations and use systemd-boot for all UEFI going forward (Talos 1.7)
