### ISSUE TITLE
talosctl cluster destroy does not clean up non-default networks

### ISSUE THREAD

**Issue by steverfrancis** [siderolabs/talos#8078]
## Bug Report
talosctl cluster destroy does not clean up non-default networks
### Description
Create a cluster with a non-default name:
talosctl cluster create \
  --name datalonga-demo 

That will work, but talosctl cluster destroy does not destroy the network, only the containers.
So another attempt to create a cluster will fail due to the existing network.
### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: [`kubectl version --short`]
- Platform:

**Comment by frezbo** [comment]
I think we need to use `talosctl cluster destroy --name <>`

**Comment by rothgar** [comment]
This appears to have been fixed in 0081ac5fac40dcc7b5b8d9f3a2c049ced4a3f88a
