### ISSUE TITLE
talosctl memory shows different results than kubectl top node

### ISSUE THREAD

**Issue by camaeel** [siderolabs/talos#8081]
## Bug Report
`talosctl memory` shows different results than `kubectl top node`

### Description

When I run: `talosctl memory` shows:
```
❯ talosctl memory -n 192.168.189.128
NODE              TOTAL   USED   FREE   SHARED   BUFFERS   CACHE   AVAILABLE
192.168.189.128   2956    1010   206    54       0         1739    1911
```

Metrics-server shows: 
```
❯ kubectl top node  talos-dev-master-0
NAME                 CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
talos-dev-master-0   73m          3%     1813Mi          68%
```

It would maybe make sense if `talos memory` reported less - because of additional talos containers running. 

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
    ```
    ❯ talosctl version --nodes  192.168.189.128
    Client:
	    Tag:         v1.6.0
	    SHA:         eddd188c
	    Built:
	    Go version:  go1.21.5 X:loopvar
	    OS/Arch:     darwin/amd64
    Server:
	    NODE:        192.168.189.128
	    Tag:         v1.6.0
	    SHA:         eddd188c
	    Built:
	    Go version:  go1.21.5 X:loopvar
	    OS/Arch:     linux/amd64
	    Enabled:     RBAC
    ```
- Kubernetes version: [`kubectl version --short`]
    ```
    ❯ k version
    Client Version: v1.28.2
    Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
    Server Version: v1.28.3
    ```
- Platform:
    Talos nocloud image running in proxmox.

**Comment by smira** [comment]
These commands report different points of view on memory resource usage, both are valuable. There is no big reason to duplicate what kubectl says.

Talosctl reports Linux kernel point of view, kubelet reports cgroup reservations.
