### ISSUE TITLE
talos-1.6.0 is not booting on Raspberry Pi CM board

### ISSUE THREAD

**Issue by jlec** [siderolabs/talos#8082]
### Description

Flashing the 1.6.0 results in an unbootable state. I followed the identical recipe which works for <1.6. most likely we are missing critical firmware.

### Logs

Cannot get even an early boot log.

### Environment

- Platform: Raspberry Pi CM4

**Comment by smira** [comment]
It might have already been fixed, let's check back for 1.6.1

**Comment by jlec** [comment]
Any eta for 1.6.1?

**Comment by reitermarkus** [comment]
It seems like none of the SBC images were built/released for 1.6.0, i.e. https://github.com/siderolabs/talos/releases/download/v1.6.0/metal-rpi_generic-arm64.raw.xz doesn't exist.

**Comment by reitermarkus** [comment]
I see it's already tracked: https://github.com/siderolabs/talos/discussions/8073#discussioncomment-7884543

**Comment by smira** [comment]
E.g. for RPi: https://factory.talos.dev/image/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba/v1.6.0/metal-rpi_generic-arm64.raw.xz

**Comment by jlec** [comment]
I can confirm, the latest images from the factory are good and working.

**Comment by tuxpeople** [comment]
Not sure if I ran into the same error. I tried to set up Talos on a CM4 in my TuringPi2. v1.6.1 arm64 is working, but it seems like v1.6.2 arm64 isn't booting at all. From what I can tell, it looks like a boot loop.

**Comment by rouke-broersma** [comment]
> Not sure if I ran into the same error. I tried to set up Talos on a CM4 in my TuringPi2. v1.6.1 arm64 is working, but it seems like v1.6.2 arm64 isn't booting at all. From what I can tell, it looks like a boot loop.

I have the and on rpi 4b (not cm4). It does boot I think but it crashes somewhere during init. Unfortunately I have no way to collect those logs as talos api has not yet started.

**Comment by tuxpeople** [comment]
I found another (?) issue, please let me know if I shall explain the details here, or open a new issue for it. 

Neither Talos 1.5.5 nor Talos 1.6.1 are booting on my setup (TuringPi 2 with CM4) as long as I have my mPCIe SATA cards connected to the CM4s. U-Boot is crashing.

**Comment by jlec** [comment]
> Neither Talos 1.5.5 nor Talos 1.6.1 are booting on my setup (TuringPi 2 with CM4) as long as I have my mPCIe SATA cards connected to the CM4s. U-Boot is crashing.

That's reported in #7358 already
