### ISSUE TITLE
IP address is not properly registered in discovery service

### ISSUE THREAD

**Issue by jlec** [siderolabs/talos#8099]
### Description

Using a fresh image to install a controlplane node I am running into the following issue; Somehow the discovery service is not getting my IP address registered

There is an IP address assigned

```shell
➜  t get address
NODE             NAMESPACE   TYPE            ID                      VERSION   ADDRESS            LINK
rpi4a.jlec.xyz   network     AddressStatus   eth0/10.100.100.23/24   1         10.100.100.23/24   eth0
rpi4a.jlec.xyz   network     AddressStatus   lo/127.0.0.1/8          1         127.0.0.1/8        lo
```

yet I see the following problems

```shell
➜  t get members
NODE             NAMESPACE   TYPE     ID      VERSION   HOSTNAME         MACHINE TYPE   OS               ADDRESSES
rpi4a.jlec.xyz   cluster     Member   rpi4a   3         rpi4a.jlec.xyz   controlplane   Talos (v1.6.0)   []

➜  t health
healthcheck error: rpc error: code = Unknown desc = no IP address found for member: rpi4a
```

As a consequence, I assume, boostrapping and kubelet start fails.

I tested using DHCP IPv4 as well as hard coded IPv4

### Logs

Please let me know specific logs which would help.

### Environment

- Talos version:

```shell
➜  t version
Client:
	Tag:         v1.6.0
	SHA:         eddd188c
	Built:
	Go version:  go1.21.5 X:loopvar
	OS/Arch:     darwin/arm64
Server:
	NODE:        rpi4a.jlec.xyz
	Tag:         v1.6.0
	SHA:         eddd188c
	Built:
	Go version:  go1.21.5 X:loopvar
	OS/Arch:     linux/arm64
	Enabled:     RBAC
```

- Platform: RPI 4b 

Image used  `metal-rpi_generic-arm64-v1.6.0-6798e16dddd3c63666eafd737c350e34d7088af8c56aa76c9b038e17352bceed.raw.xz`

**Comment by smira** [comment]
Please see [docs](https://www.talos.dev/v1.6/introduction/troubleshooting/#conflict-on-kubernetes-and-host-subnets).

> Talos default machine configuration specifies the following Kubernetes pod and subnet IPv4 CIDRs: 10.244.0.0/16 and 10.96.0.0/12. If the host network is configured with one of these subnets, change the machine configuration to use a different subnet.

**Comment by jlec** [comment]
OMG - I have read the docs up and down and not spotted this.
