### ISSUE TITLE
Talos doesn't fallback to other disk encryption keys if TPM policy fails

### ISSUE THREAD

**Issue by uhthomas** [siderolabs/talos#8100]
### Description

I have a few disk encryption methods enabled; TPM, node key and static passphrase. It seems that if the TPM fails then none of of the other methods are attempted.

### Environment

- Talos version: v1.6.0
- Kubernetes version: [`kubectl version --short`]
- Platform: amd64

**Comment by smira** [comment]
This should be fixed in 1.9.0
