### ISSUE TITLE
Cilium doesn't work with Secure Boot enabled

### ISSUE THREAD

**Issue by wouterbouvy** [siderolabs/talos#8117]
## Bug Report

Cilium CNI pod doesn't start with Secure Boot enabled

### Description

After I enable Secure Boot, the kernel goes in lockdown mode and Cilium, which relies on BPF doesn't work anymore.
Is there a way to disable (certain) lockdown features but keep Secure Boot enabled?

[kernel lockdown man page](https://man7.org/linux/man-pages/man7/kernel_lockdown.7.html)

### Logs

`10.0.88.3: kern:  notice: [2023-12-28T15:24:56.462748671Z]: Lockdown: bpftool: use of bpf to read kernel RAM is restricted; see man kernel_lockdown.7`

### Environment

- Talos version:
`❯ talosctl version -n 10.0.88.3
Client:
	Tag:         v1.6.1
	SHA:         0af17af3
	Built:
	Go version:  go1.21.5 X:loopvar
	OS/Arch:     darwin/arm64
Server:
	NODE:        10.0.88.3
	Tag:         v1.6.1
	SHA:         0af17af3
	Built:
	Go version:  go1.21.5 X:loopvar
	OS/Arch:     linux/amd64
	Enabled:     RBAC`
- Kubernetes version:
`❯ kubectl version
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0`
- Platform: amd64

**Comment by wouterbouvy** [comment]
Seems an issue on my end. I deployed my cluster first without Secure Boot enabled and enabled it in the BIOS afterwards. After a re-deploy Cilium works fine.

**Comment by smira** [comment]
It's supposed to use kernel lockdown mode in SecureBoot to make it properly secured, so some stuff might not work as expected, including BPF.

**Comment by veshant** [comment]
> Seems an issue on my end. I deployed my cluster first without Secure Boot enabled and enabled it in the BIOS afterwards. After a re-deploy Cilium works fine.

Were you able to get Cilium to work with secureboot enabled talos? We're having the same issue.

Lockdown: bpftool: use of bpf to read kernel RAM is restricted; see man kernel_lockdown.7

**Comment by wouterbouvy** [comment]
> > Seems an issue on my end. I deployed my cluster first without Secure Boot enabled and enabled it in the BIOS afterwards. After a re-deploy Cilium works fine.
> 
> @wouterbouvy Were you able to get Cilium to work with secureboot enabled talos? We're having the same issue.
> 
> Lockdown: bpftool: use of bpf to read kernel RAM is restricted; see man kernel_lockdown.7

@veshant  Yes, as far as I can tell Cilium is working properly despite the errors thrown

**Comment by veshant** [comment]
@wouterbouvy glad to hear. thanks
