### ISSUE TITLE
error copying vmlinuz.efi.signed

### ISSUE THREAD

**Issue by si458** [siderolabs/talos#8122]
### Description

using the latest 1.6.0+ ISO images generate a random **error copying**  message when using the secureboot iso?
https://factory.talos.dev/image/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba/v1.6.1/metal-amd64-secureboot.iso (default one with no system extensions, have also tried WITH system extensions)

whats also weird is it doesnt actually install/setup?
it fails to install, then restarts, where i have to run the apply-config command again for it to then apply my config
where it then restarts a 2nd time for me to then bootstrap the cluster a final time

~~i think the issue is because its looking for a folder `/boot/EFI/EFI/Linux/` when it should `/boot/EFI/Linux/`~~

~~i think this commit is the possible reason for the failing to copy - https://github.com/siderolabs/talos/commit/b8fb55d5c2e0433df46ac7bc3eeaea08e12d572d~~
~~you are adding an extra "EFI" string to the `EFIMountPoint`, but i could be mistaken~~

~~i think also this line is correct, so it is indeed the other commit thats the issue and the extra `EFI` strings needs to be removed~~
https://github.com/siderolabs/talos/blob/8dc112f36bd77ec72e5c501755aa4f056803efd0/pkg/machinery/constants/constants.go#L160

### Logs
```
[25265.222298] 2024/01/01 00:18:14 copying /usr/install/amd64/vmlinuz.efi.signed to /boot/EFI/EFI/Linux/Talos-v1.6.1.efi
[25265.224787] Error: error copying /usr/install/amd64/vmlinuz.efi.signed ->/boot/EFI/EFI/Linux/Talos-v1.6.1.efi: open /usr/install/amd64/vmlinuz.efi.signed: no such file or directory
. . .
[25265.328931] [talos] task install (1/1): failed: task "upgrade" failed: exit code 1
[25265.3302721] [talos] phase install (2/11): failed
[25265.331118] [talos] install sequence: failed
```

![Screenshot 2024-01-01 at 00-21-57 hp1 - Proxmox Virtual Environment](https://github.com/siderolabs/talos/assets/765314/02f512c7-0c66-4744-b712-c8ef19adb329)

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`] 1.6.0+
- Kubernetes version: [`kubectl version --short`] any
- Platform: Proxmox VM using ISO to boot

**Comment by si458** [comment]
i have a feeling i might be wrong with my PR, so ive closed it
ive never tried to create EFI before so thats all new to me, ive only ever just used it?
as i checked my ubuntu setup and they have the folders `/boot/efi/EFI/ubuntu/` so it is indeed correct
but i have also just realised its complaing saying `open /usr/install/amd64/vmlinuz.efi.signed: no such file or directory`
so the efi.signed file is missing from inside the iso which seems odd?

**Comment by si458** [comment]
ok i have figured out my problem!
the docs arent very helpful, they say to 'Generate machine configuration'
and give u a command, but what i didnt realise is you MUST SET the install-image!?
this should be changed int he docs to explain that this step is REQUIRED,
or if you are using an existing controlplane.yaml to update the image link in your yaml!
(like i was as i was testing without secureboot, then with secure boot)

**Comment by smira** [comment]
It is documented: https://www.talos.dev/v1.7/talos-guides/install/bare-metal-platforms/secureboot/
