### ISSUE TITLE
No video output on metal after grub boot

### ISSUE THREAD

**Issue by imle** [siderolabs/talos#8127]
## Bug Report
Stuck in boot after `kern/efi/sb.c:111: UEFI Secure Boot state: Disabled` is printed.

### Description
Trying to boot into 1.6.1 or 1.4.4 version of Talos on a `HP Elitedesk 705 G4 DM`. Without `set debug=all`, the machine hangs with a black screen and an underscore. After enabling the debug option, the boot process hangs immediately after printing the above log line.

I have attempted the boot process with all drives removed and a single stick of ram to eliminate as many variables as possible and this happens with all 3 of the machines I have.

### Logs
![PXL_20240102_153129451.jpg](https://github.com/siderolabs/talos/assets/4809109/946c5171-c264-4ff1-ade5-e664d38e6662)

**Comment by imle** [comment]
Only mention I can find of a similar issue anywhere:
https://forums.gentoo.org/viewtopic-p-8755201.html?sid=7b3162f6c0ec892d909661710c21fb5f

**Comment by imle** [comment]
Also want to note that trying to set `set debug=all,-mmap` does not seem to be working.

https://www.gnu.org/software/grub/manual/grub/html_node/debug.html

**Comment by imle** [comment]
Ok, upon further work, it does seem that it is booting, but just nothing is coming out of either display port.

**Comment by smira** [comment]
Usually it's related to the `console=` settings, you can try tweaking it, removing `console=ttyS0`, changing to `console=tty1`.

Unfortunately it's hardware dependent.

**Comment by runningman84** [comment]
I have the exact same issue with my n100 board from asrock. I can boot any other Linux distribution like Ubuntu just fine.

**Comment by runningman84** [comment]
![image](https://github.com/siderolabs/talos/assets/1699128/bdaf507f-55a5-4a15-81bb-40c162085da2)

with talos 1.7.0 beta 0 that is the output.

**Comment by smira** [comment]
Try removing `console=ttyS0` boot argument.

**Comment by runningman84** [comment]
Removing all console= parameters it boots just fine with version 1.6.7 and 1.7.0.beta.0.  Are these settings persistent after the install? Why do all linux distros work out of the box but talos has issues like this?

**Comment by runningman84** [comment]
These settings get lost after the initial install so I have to modify the grub parameters for each boot. How can I persist that in talos?

**Comment by smira** [comment]
Console argument issue is a hard one, see https://www.talos.dev/v1.6/introduction/what-is-new/#kernel-arguments on how to remove default args.

**Comment by runningman84** [comment]
Thanks that worked for me!
