### ISSUE TITLE
Support Secure Boot in OVMF Environment

### ISSUE THREAD

**Issue by la7eralus** [siderolabs/talos#8131]
## Feature Request
Support Secure Boot in OVMF Environment
### Description
I'm running Talos in Proxmox (QEMU), and want to enable Secure Boot and TPM Encryption. Unfortunately the Keys cant be enrolled automatically: 
![image](https://github.com/siderolabs/talos/assets/113297102/91a94018-104f-4992-9ba0-a6b3fd265107)

So I tried to import the keys manually (loader/keys/auto/*.auth):
![image](https://github.com/siderolabs/talos/assets/113297102/b33034ac-45d9-489e-873e-493f646dfc37)
![image](https://github.com/siderolabs/talos/assets/113297102/8fc10e1a-189d-4ab0-bcef-1f1e1f6219e8)

It seems like OVMF only supports Keys in der format (and not pem).

**Comment by frezbo** [comment]
from the error it seems it failed to write the EFI variables, seems the firmware is passed in as readonly as opposed to read/write.

Talosctl supports generating keys in DER format `talosctl gen secureboot`

**Comment by 5olu7ion** [comment]
I created the UEFI disk without pre enrolled Keys, so I think it should be in setup mode?

Are you sure, that the default keys (the one that ship with the talks secure boot iso) are in DER format?

**Comment by frezbo** [comment]
> Are you sure, that the default keys (the one that ship with the talks secure boot iso) are in DER format?

probably not the ones in the iso, but you can always generate your own keys

**Comment by 5olu7ion** [comment]
Yes, this seems doable, but it's ultimately forcing me to operate or provide a private registry for the custom built talos image. Is there a chance to provide the secure iso with keys, that work with OVMF?

**Comment by frezbo** [comment]
Yeh, i think we can fix that

**Comment by 5olu7ion** [comment]
Awesome, thank you 😁

**Comment by 5olu7ion** [comment]
@frezbo This should be fixed with 1.6.2 right? -> https://github.com/siderolabs/talos/commit/3576d113c

**Comment by frezbo** [comment]
yeh, the fix was not correct, will get it fixed

**Comment by frezbo** [comment]
We still need to inlcude those files in the iso, I'll take care of that

**Comment by frezbo** [comment]
@5olu7ion I took a look at the issue again, from the image it seems it reported a security violation
![image](https://github.com/siderolabs/talos/assets/18496730/8019f393-c419-4046-994e-13647532f767)

I wonder if even manually enrolling would even fail with the same error :thinking: , could you confirm you can manually enroll any random key from a usb stick?

**Comment by 5olu7ion** [comment]
Yeah, you are right, I also stumbled over this particular message. I tried importing it manually (screenshots 2/3). There I got the DER compatibility issue.

**Comment by frezbo** [comment]
> Edit: I remember, that importing the db.auth worked fine

did that enroll the key?

**Comment by 5olu7ion** [comment]
Nope, it still threw the security violation. I checked it again, and I see, that enrolling the the db.auth, also enrolls the kek.auth, but not the PK.auth. When enrolling the *.auth files in OVMF, you have to switch to custom mode, but this seems to reset to standard after an unsuccessful (security violation) boot. I set up OVMF without default keys. Maybe I'm doing something fundamentally wrong, but the fact, that OVMF complains about PEM format, and you currently don't ship DER certificates led me to create this issue.

**Comment by frezbo** [comment]
We'll add the der certs to the iso, do you if there's some standard path where it should exist, or will just put it under something like `keys/secureboot`

**Comment by 5olu7ion** [comment]
I'm sorry, there is no hint in the whitepaper: https://www.linux-kvm.org/downloads/lersek/ovmf-whitepaper-c770f8c.txt
If you want, you can send me a prebuilt iso, and I can test it on my end.

**Comment by frezbo** [comment]
@la7eralus could you test a custom iso? I can share on the talos slack

**Comment by la7eralus** [comment]
Yeah sure, do you have a link to the channel?

**Comment by la7eralus** [comment]
If someone stumbles over this issue: The signing cert is located under EFI/keys/uki-signing-cert.der in all secureboot iso's since 1.7.0. 

Big shoutout to Siderolabs and especially frezbo for making this work :-)
