### ISSUE TITLE
ExtraArgs on etcd fails after upgrade to Talos 1.6

### ISSUE THREAD

**Issue by Chewie** [siderolabs/talos#8132]
## Bug Report

After upgrading talos from 1.5.5 to 1.6.1, the following config fails:

```yaml
cluster:
  etcd:
    extraArgs:
      listen-metrics-url: http://0.0.0.0:2381
```

### Description

It seems the config adds the argument with a single dash (i.e. `-listen-metrics-url`) instead of a double dash (i.e. `--listen-metrics-url`), as the following logs show.

It's unclear to me whether this is a new behavior of the argument parser, or an update to the bundled etcd which does not allow this format. Looking at the etcd docs, the flags have changed from single dash to double dash in 3.5, but according to the release notes, Talos 1.5.5 already ran with etcd 3.5.10, so I'm not sure which component is the culprit.

### Logs
`talosctl logs etcd` shows the following:

```
10.0.10.10: flag provided but not defined: -listen-metrics-url
10.0.10.10: Usage:
10.0.10.10:
10.0.10.10:   etcd [flags]
10.0.10.10:     Start an etcd server.
10.0.10.10:
10.0.10.10:   etcd --version
10.0.10.10:     Show the version of etcd.
10.0.10.10:
10.0.10.10:   etcd -h | --help
10.0.10.10:     Show the help information about etcd.
10.0.10.10:
10.0.10.10:   etcd --config-file
10.0.10.10:     Path to the server configuration file. Note that if a configuration file is provided, other command line flags and environment variables will be ignored.
10.0.10.10:
10.0.10.10:   etcd gateway
10.0.10.10:     Run the stateless pass-through etcd TCP connection forwarding proxy.
10.0.10.10:
10.0.10.10:   etcd grpc-proxy
10.0.10.10:     Run the stateless etcd v3 gRPC L7 reverse proxy.
```
### Environment

- Talos version: v1.6.1
- Kubernetes version: v1.29.0
- Platform: linux/amd64

**Comment by frezbo** [comment]
I can't seem to reproduce this, could you provide the support bundle? `talosctl support`

**Comment by Chewie** [comment]
Thanks for looking at this!

Sure thing, please find the support bundle below:

[support.zip](https://github.com/siderolabs/talos/files/13842973/support.zip)

**Comment by smira** [comment]
The etcd logs are confusing, but Talos works correctly here. The problem is that you're using wrong flag name -- it should be "listen-metric-urls": https://etcd.io/docs/v3.5/op-guide/configuration/

Looks like a change on `etcd` side.
