### ISSUE TITLE
[Feature Request] Enable cloud-init support for Talos ISO.

### ISSUE THREAD

**Issue by mlinares1998** [siderolabs/talos#8140]
## Feature Request
Enable cloud-init support in Talos ISO.
### Description
I'm running Talos in Proxmox and want to automate the deployment using Terraform, right now the only supported way to do so is using nocloud image which doesn't seem to be supported by now in Image Factory to bundle QEMU GA on it. 

It would be a lot more convenient having direct cloud-init support on Talos ISO without further modifications. 
i have successfully tested it by building a custom ISO with imager and patching the grub cmdline to enter on nocloud mode.

Thanks!

![image](https://github.com/siderolabs/talos/assets/15200008/92c7f9d6-1bbb-4f44-bab4-91b61559442e)
![image](https://github.com/siderolabs/talos/assets/15200008/b01f72fe-fb43-4216-8e00-20286619aaad)
![image](https://github.com/siderolabs/talos/assets/15200008/15555043-24f8-490d-848d-a7f3cbfecbcd)

**Comment by smira** [comment]
`cloud-init` will never be supported on Talos, as Talos doesn't have neither Python nor any kind of shell.

Image Factory supports `nocloud` platform without any issues - just change `metal` to `nocloud` for example.
