### ISSUE TITLE
Bad IP address allocation with the wrong IP inside CIDR subnet

### ISSUE THREAD

**Issue by fturlan** [siderolabs/talos#8174]
## Bug Report
Bad IP address allocation with the CIDR subnet 

### Description
We moved from Talos version 1.3.7 to Talos version 1.4.8.
Since the reboot, the 6 physical Dell servers are taking an address from the CIDR subnet.
The 9 physical Huawei servers and the 3 VMwares work as before and use the IP address defined in the machine config.

How can we resolve the problem on our Dell servers so that they take into account the IP address that we defined in our machine config.

In our configuration , the expected IP address is XX.XX.193.10 ( as configured in our machine config) , but after reboot,  as shown in  the logs  , he is taking an IP address from podCIDR  which is  XX.XX.2.71.

        interfaces:
          - interface: bond0 # The interface name.
            # Assigns static IP addresses to the interface.
            addresses:
              - <notre ip>/24

### Logs
```
XX.XX.2.71: kern:    info: [2024-01-19T10:41:17.655296675Z]: bond0: active interface up!
XX.XX.2.71: user: warning: [2024-01-19T10:41:17.910305675Z]: [talos] service[kubelet](Running): Started task kubelet (PID 5777) for container kubelet
XX.XX.2.71: user: warning: [2024-01-19T10:41:18.271029675Z]: [talos] service[apid](Running): Started task apid (PID 5770) for container apid
XX.XX.2.71: user: warning: [2024-01-19T10:41:18.742811675Z]: [talos] service[kubelet](Waiting): Error running Containerd(kubelet), going to restart forever: task "kubelet" failed: exit code 1
XX.XX.2.71: user: warning: [2024-01-19T10:41:21.887269675Z]: [talos] service[apid](Running): Health check successful
XX.XX.2.71: user: warning: [2024-01-19T10:41:23.772965675Z]: [talos] controller failed {"component": "controller-runtime", "controller": "k8s.StaticEndpointController", "error": "error resolving \x5c"kube.infra.pack.valentine.sfr.com\x5c": lookup kube.infra.pack.valentine.sfr.com on 8.8.8.8:53: read udp XX.XX.193.10:59574->8.8.8.8:53: i/o timeout"}
XX.XX.2.71: user: warning: [2024-01-19T10:41:24.221654675Z]: [talos] service[kubelet](Running): Started task kubelet (PID 5923) for container kubelet
XX.XX.2.71: user: warning: [2024-01-19T10:41:24.798833675Z]: [talos] service[kubelet](Running): Health check successful
XX.XX.2.71: user: warning: [2024-01-19T10:41:24.877074675Z]: [talos] task startAllServices (1/1): done, 8.594246564s
XX.XX.2.71: user: warning: [2024-01-19T10:41:24.952065675Z]: [talos] phase startEverything (18/20): done, 8.737999728s
XX.XX.2.71: user: warning: [2024-01-19T10:41:25.029231675Z]: [talos] phase uncordon (19/20): 1 tasks(s)
XX.XX.2.71: user: warning: [2024-01-19T10:41:25.029264675Z]: [talos] task uncordonNode (1/1): starting
XX.XX.2.71: user: warning: [2024-01-19T10:41:25.041044675Z]: [talos] retrying error: node not ready
XX.XX.2.71: kern:    info: [2024-01-19T10:41:43.100369675Z]: IPv6: ADDRCONF(NETDEV_CHANGE): cilium_net: link becomes ready
XX.XX.2.71: kern:    info: [2024-01-19T10:41:43.181673675Z]: IPv6: ADDRCONF(NETDEV_CHANGE): cilium_host: link becomes ready
XX.XX.2.71: user: warning: [2024-01-19T10:41:43.299622675Z]: [talos] node IP skipped, please use .machine.kubelet.nodeIP to provide explicit subnet for the node IP {"component": "controller-runtime", "controller": "k8s.NodeIPController", "address": "XX.XX.193.10"}
```

### Environment

- Cilium:   Version:  1.13.8 (v1.13.8-96f0558d)
- Kubernetes Version : 1.25.14 
- CNI : Cilium
- Platform: Talos Version 1.4.8
- Dell Barre Metal servers

**Comment by steverfrancis** [comment]
Do you have a support contract? Talos 1.3 and 1.4 are out of community support, but supported if you have a support contract.
However, it sounds like, as the log indicates, you just need to set 
machine:
  kubelet:
    nodeIP:
      validSubnets:
        - 192.168.0.0/16 (To whatever subnet)
        - 
https://www.talos.dev/v1.6/introduction/prodnotes/#multihoming-and-kubelets

**Comment by smira** [comment]
You need to make sure that Talos machine configuration has `podSubnets` and `serviceSubnets` matching your CNI config, this way Talos will never try to use them as node IPs.
