### ISSUE TITLE
feat: KubePrism: no way to choose used interfaces

### ISSUE THREAD

**Issue by yoctozepto** [siderolabs/talos#8180]
## Feature Request

Currently, KubePrism is not able to filter endpoints based on interfaces (or subnets or ...). Thus, it makes it impractical in multihomed scenarios as it tries to use all the addresses it sees on control plane hosts.

**Comment by yoctozepto** [comment]
As I understand it, it entails enhancing the discovery mechanism as it simply lacks this notion.

**Comment by smira** [comment]
You can use the firewall if you want to prefer some addresses vs. others, but in general KubePrism finds the shortest route and uses it.

**Comment by yoctozepto** [comment]
In my case these extra addresses are not reachable so it's a waste of resources to try to check them. Similarly, it would be when firewalling ports.
