### ISSUE TITLE
Support bigger META values via `INSTALLER_META` environment variable

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#8186]
Talos support for compression of `INSTALLER_META` values to handle big META values which overflow kernel cmdline.

**Comment by frezbo** [comment]
> Talos support for compression of `INSTALLER_META` values to handle big META values which overflow kernel cmdline.

doesn't kernel also has a limit on the length of the cmdline, i remember reading something similar

**Comment by smira** [comment]
> > Talos support for compression of `INSTALLER_META` values to handle big META values which overflow kernel cmdline.
> 
> doesn't kernel also has a limit on the length of the cmdline, i remember reading something similar

hmm... this is exactly what this sentence says, doesn't it?

**Comment by frezbo** [comment]
> > > Talos support for compression of `INSTALLER_META` values to handle big META values which overflow kernel cmdline.
> > 
> > 
> > doesn't kernel also has a limit on the length of the cmdline, i remember reading something similar
> 
> hmm... this is exactly what this sentence says, doesn't it?

i interpreted it differently, thinking this was overflowing some meta size limit
