### ISSUE TITLE
Support for the Turing RK1

### ISSUE THREAD

**Issue by jphastings** [siderolabs/talos#8187]
## Feature Request

I'd really appreciate [Turing RK1](https://docs.turingpi.com/docs/turing-rk1-specs-and-io-ports) support for Talos. (They've started shipping!)

### Description

It looks as though @pl4nty has already been working on [support for the RK1](https://github.com/siderolabs/talos/commit/461ae69720b1f10bdf7c6e180200e38fdcee4ac4) — but I'm not sure what the next steps would be! I'm happy to help if I can!

**Comment by pl4nty** [comment]
Work has centralised on @nberlee's [fork](https://github.com/nberlee/talos), pending #8065. I think the main focus is testing - it would be great if you can install and report any issues. I haven't touched the project in a while since my modules haven't arrived yet

**Comment by jphastings** [comment]
As soon as mine arrives I shall!

**Comment by nberlee** [comment]
Thank you @pl4nty,

The versions released in this repository are quite stable, and are usually released a few hours after they are released here. Our primary goal was to achieve a stable release, which we have now accomplished. Therefore, this repository will remain active until the release of Talos 1.7, which will include kernel 6.6 and support for the SBC community.

But if you have any problems, please report them so it can be fixed. HDMI/video codecs will not be supported as it is too much to patch from Kernel 6.6, the rest will just work as you expect from any Talos Image.

**Comment by bhuism** [comment]
Works perfectly for me

**Comment by DrummyFloyd** [comment]
as soon as i get mine , will test too ( but dunnon when , because i order 3 RK1 with 32Go so bit of delay regarding them .. =)

**Comment by danbanta** [comment]
Thank you @nberlee for the [fork](https://github.com/nberlee/talos). I currently have a cluster up with 4 RK1 modules on the Turning Pi 2. I set mine up with Cilium so I hope to add to [camrossi](https://github.com/camrossi)'s [Example With Cilium](https://github.com/nberlee/talos/issues/1) soon.

> But if you have any problems, please report them so it can be fixed. HDMI/video codecs will not be supported as it is too much to patch from Kernel 6.6, the rest will just work as you expect from any Talos Image.

I am very interested in seeing what is involved with getting the HDMI / video codecs (GPU) up and encoding / decoding. If you have any information to share or advise; I would gladly listen. Thank you!

**Comment by nberlee** [comment]
@usrbinkat You are raising a specific issue here, could you create a seperate issue on nberlee/talos if the following failed?

A minor caution, i see `net.ifnames=0` in your kernel parameters, it has not been applied yet, as your interface is not `eth0`. The first time you run `talosctl upgrade`  your networkdevice will be renamed to  `eth0` and your bridge config will fail. (as enx is part of it, not eth0)

Maybe this will work:

looking at https://lkml.org/lkml/2023/10/24/691 eee (energy efficent ethernet) needs to disabled. Which makes no sense at it is the link between the RK1 and the switchchip on the Turing Pi board. But it may be worth the try:

Before adding the bridge config: (in this example i use `eth0`, use your own network interface name)
```
$ kubectl debug node/yournodename --profile=netadmin --image=alpine -it -n kube-system
Creating debugging pod node-debugger-yournodename-wwvnc with container debugger on node yournodename.
If you don't see a command prompt, try pressing enter.
/ # ethtool --set-eee eth0 eee off
/ # 
```
your container will exit as the network interface is reset.

check if it worked:
```
$ kubectl debug node/yournodename --profile=netadmin --image=alpine -it -n kube-system
Creating debugging pod node-debugger-yournodename-wwvnc with container debugger on node yournodename.
If you don't see a command prompt, try pressing enter.
/ # apk add ethtool
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/community/aarch64/APKINDEX.tar.gz
(1/2) Installing libmnl (1.0.5-r2)
(2/2) Installing ethtool (6.6-r0)
Executing busybox-1.36.1-r15.trigger
OK: 8 MiB in 17 packages
/ # ethtool --show-eee eth0
EEE settings for eth0:
	EEE status: disabled
	Tx LPI: disabled
	Supported EEE link modes:  100baseT/Full
	                           1000baseT/Full
	Advertised EEE link modes:  Not reported
	Link partner advertised EEE link modes:  Not reported
```

Then try to apply your bridge config. 

Networking on the Turing took some kernel patches to make it work fine. For instance VLAN tag support and going >600Mbit. This is included in the fork, but I there may be an upstream additional patch for your bridge problem. So please open an issue if this does not work
