### ISSUE TITLE
Unable to update existing file using configmap in talos cluster

### ISSUE THREAD

**Issue by sagh0900** [siderolabs/talos#8269]
## Bug Report
Unable to update existing file using configmap
### Description
We have noticed an issue using talos cluster in our environment. When we are mounting a file through configmap which is not already there in the pod/container, the mount operation is successful and we can see the file as well in the container. But when we are trying to override the existing file through configmap, we noticed the following error

### Logs
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/var/lib/kubelet/pods/744ccfe1-e40d-458d-ab6d-6f66d912e25a/volumes/kubernetes.io~configmap/zabbix-util" to rootfs at "/usr/share/zabbix/vendor/onelogin/php-saml/src/Saml2/Utils.php": mount /var/lib/kubelet/pods/744ccfe1-e40d-458d-ab6d-6f66d912e25a/volumes/kubernetes.io~configmap/zabbix-util:/usr/share/zabbix/vendor/onelogin/php-saml/src/Saml2/Utils.php (via /proc/self/fd/6), flags: 0x5001: not a directory: unknown

### Steps to reproduce:
Mount the volume using configmap to override the already available file within the pod/container.

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]: 
$ talosctl version --nodes 10.11.165.10
Client:
	Tag:         v1.6.3
	SHA:         d53e07c1
	Built:       
	Go version:  go1.21.6 X:loopvar
	OS/Arch:     linux/amd64
Server:
	NODE:        10.11.165.10
	Tag:         v1.6.1
	SHA:         0af17af3
	Built:       
	Go version:  go1.21.5 X:loopvar
	OS/Arch:     linux/amd64
	Enabled:     RBAC
- Kubernetes version: [`kubectl version --short`]
kubectl version
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1
- Platform:

**Comment by smira** [comment]
Please attach steps to reproduce the issue.

**Comment by sagh0900** [comment]
Thanks for your response. We setup new talos test cluster and tried to
repeat what was failing  in our original cluster, surprisingly volume
mounts are smooth and successful this time. But we still didn't find the
cause or answer to the question why its failing only in original cluster.There
are known two differences between the clusters but that didn't help us to
find the cause.

   1. Original cluster was allowed to have work loads in master nodes but
   the test cluster where volume mounts are successful have dedicated worker
   nodes.
   2. The new test cluster is deployed with talosctl client 1.6.3 and
   original cluster client is 1.6.1 where as server versions are same for both
   clusters 1.6.1

**Comment by sagh0900** [comment]
Please close this issue. It was a mistake from our side, without being
aware that we used wrong file name while creating configmaps, we were
trying to update the file in the pod which caused this error. Had nothing
to do with either K8s or Talos.
