### ISSUE TITLE
Please add CONFIG_IKHEADERS to the Talos kernel

### ISSUE THREAD

**Issue by mwheckmann** [siderolabs/talos#8277]
## Feature Request

CONFIG_IKHEADERS required for eBPF tooling.

### Description

eBPF tracing tools like [BCC tools](https://github.com/iovisor/bcc) require the kernel headers in order to compile the eBPF programs (see below). It would useful to have CONFIG_IKHEADERS as a module which could be loaded as needed for such occasions.

```
bash-5.1# /usr/share/bcc/tools/tcptracer
modprobe: module kheaders not found in modules.dep
Unable to find kernel headers. Try rebuilding kernel with CONFIG_IKHEADERS=m (module) or installing the kernel development package for your running kernel version.
chdir(/lib/modules/6.1.73-talos/build): No such file or directory
Traceback (most recent call last):
  File "/usr/share/bcc/tools/tcptracer", line 637, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python3.10/site-packages/bcc/__init__.py", line 475, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>
```

**Comment by smira** [comment]
Talos supports BTF info which is a better way to compile BPF programs against. Not sure about BCC tools, but I hope they do support it. Either way, BTF can be converted to Linux headers on the fly.

BTF is already in the kernel, so nothing needs to be enabled.

**Comment by mwheckmann** [comment]
ok, makes sense. See https://www.brendangregg.com/blog/2020-11-04/bpf-co-re-btf-libbpf.html.
