### ISSUE TITLE
Watchdog timer (WDT) support

### ISSUE THREAD

**Issue by dsseng** [siderolabs/talos#8284]
## Feature Request
Support hardware/firmware watchdog. This could increase resilience and help fulfill requirements some users might add to their systems.

### Description
Just as systemd is able to do it Talos init process should be able to arm and feed the watchdog if one is detected and configured by the user. If the system hangs (for example due to a driver crashing the kernel or hardware instability) WDT trips after not being fed for a timeout and resets the system, recovering it from a freeze. As hardware or firmware might be quirky I wouldn't risk enabling it in default config.

I want to try myself at implementing this feature in case it's approved.

**Comment by smira** [comment]
That'd be nice!

**Comment by smira** [comment]
If you have some high-level overview of API changes required (e.g. new configuration, kernel args, etc.), it might be nice to bootstrap the discussion.

**Comment by dsseng** [comment]
Perhaps just an option in `machine` or `machine.install` for a timeout, measured in seconds. [systemd](https://www.freedesktop.org/software/systemd/man/latest/systemd-system.conf.html#RuntimeWatchdogSec=) has multiple timeout options, but unsure how often are they used and whether they'd be more useful than confusing.

**Comment by dsseng** [comment]
What would be the right place in the `internal/app/machined` code to enable the watchdog and start a goroutine + ticker to feed it?

**Comment by smira** [comment]
The controller is the best path, as it would consume the machine config once it's available, and control the timer based on the config (which might change on the fly).

**Comment by smira** [comment]
you need to use modern buildkit runners, you can look [here](https://www.talos.dev/v1.6/advanced/developing-talos/#prepare) and also `make help` in the `pkgs` repo

**Comment by dsseng** [comment]
That fixed it. Unsure why didn't that command persist from the Talos build (perhaps env var or something). Thank you!

**Comment by dsseng** [comment]
For some reason I can't get modules installed using these commands:
pkgs > `make kernel REGISTRY=127.0.0.1:5005 PUSH=true PLATFORM=linux/amd64`
talos > `make kernel initramfs PKG_KERNEL=127.0.0.1:5005/siderolabs/kernel:v1.7.0-alpha.0-22-g0ec4cc3-dirty` (rebuilt installer after that as well)
talos > same qemu run command as previously, with the built installer tag

Will build i6300esb as built-in for now to test.

**Comment by smira** [comment]
Hard to say, it _should_ work

**Comment by dsseng** [comment]
Also failing to update kernel which has the same tag (`v1.7.0-alpha.0-22-g0ec4cc3-dirty`) but it's updated within the same non-committed changeset, because buildkit uses cache of an old one. Maybe it's not even updated in the container registry. Anyway it should work after I reinit those things
