### ISSUE TITLE
Feature request - change the defaults for podsubnets and servicesubnets

### ISSUE THREAD

**Issue by gecube** [siderolabs/talos#8298]
## Feature Request

Change the defaults for podsubnets and servicesubnets from `10.244.0.0/16` and `10.96.0.0/12` respectively to `100.64.0.0/16` and `100.96.0.0/16`

### Description

Good day! 
I am asking for such a change because many host providers are using 10.0.0.0/8 for the host network: google, hetzner etc. It leads to the state when pod networks overlaps the host network leading to the bunch of the issues. Also I have never seen somebody, who is using CG-NAT addresses from 100.64.0.0/10 network. It could be some big providers, but they definitely will need additional configuration of k8s networks, so the change won't break anything.

**Comment by Griznah** [comment]
No need to change the defaults, just do your proper config: https://www.talos.dev/v1.6/reference/configuration/v1alpha1/config/#Config.cluster.network

**Comment by smira** [comment]
I'd guess there are no defaults that would work for everyone unfortunately. 

100.x space is used by Tailscale for example.

**Comment by rothgar** [comment]
talos 1.8.0 adds some additional network diagnostics that should help catch issues where the pod/service CIDR overlaps the node CIDR and displays an error in the dashboard.
