### ISSUE TITLE
forward local DNS to the CoreDNS pod as upstream

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#8329]
Forward local DNS to the CoreDNS by listening on K8s service IP (need to research which exactly), but e.g. `10.96.0.9:53` (once the config is available) and use that in CoreDNS as an upstream.

**Comment by smira** [comment]
This should help to implement #8303

**Comment by frezbo** [comment]
What about a link local ipv6?

**Comment by smira** [comment]
> What about a link local ipv6?

IPv6 can be disabled.

**Comment by smira** [comment]
https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/3070-reserved-service-ip-range
