### ISSUE TITLE
Generating `installer` with an overlay

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#8352]
Imager can generate `installer` from an overlay.

Imager will output an extra layer for the `installer` which contains following files:

```
/overlay/artifacts/ (copied from the overlay image)
/overlay/installers/default (copied from the overlay installers by name)
/overlay/extra-options (marshalled YAML)
```

Once installer runs, it detects the presence of `/overlay/installers/default`, and performs same steps when doing an install, but without profile and additional options, just calling fixed overlay installer, passing extra options, etc.

**Comment by frezbo** [comment]
Fixes by #8383
