### ISSUE TITLE
Custom SecureBoot installer-image cannot be installed

### ISSUE THREAD

**Issue by pQraus** [siderolabs/talos#8357]
## Bug Report
My goal ist to create an installer-image with the secureBoot feature and custom (system) extensions. The creation of the image was successful (with the `imager` tool) but I can't install it on the bare metal machine (see logs).

### Description
(For this bug report I just created a secureboot image without extensions, but with my own UKI- and PCR-Key)

I have tried it for talos version 1.5.4 and 1.6.4.

The procedure was as follows:
1. generate the keys and create the secureboot ISO + the secureboot installer as described in the docs: 
    - https://www.talos.dev/v1.6/talos-guides/install/bare-metal-platforms/secureboot/#secureboot-with-custom-keys
    - https://www.talos.dev/v1.5/talos-guides/install/bare-metal-platforms/secureboot/#secureboot-with-custom-keys
2. write the ISO to an usb-stick
3. boot from the stick and roll out the keys
4. boot Talos in maintenance mode and ensure that secureBoot has been activated (via `talosctl get securitystate --insecure`)
5. create a machine config `talosctl gen config --install-image <my-secure-boot-installer> demo-secure-boot https://demo-secure-boot:6443`
6. apply the config to the machine (`talosctl apply config`)
7. the image is pulled and then the error occurs
8. the machine reboots and start in the maintenance mode

Have I forgotten something special?

### Logs

![1](https://github.com/siderolabs/talos/assets/70561328/de71cd53-adc6-4cf5-8bc7-b516c746dc05)

(sorry I have only this picture)

```
error running phase 3 in install sequence: task 1/1: failed, failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/installer": stat /bin/installer: no such file or directory: unknown
```

### Environment

- Talos version: 1.5.4, 1.6.4
- Kubernetes version: -
- Platform: bare metal (secureBoot)

**Comment by smira** [comment]
It's not clear what is the issue, but certainly the image you referenced is not a Talos installer. (or wrong architecture?)

**Comment by pQraus** [comment]
I created the image this way:
```console
$ docker run --rm -t -v $PWD/_out:/secureboot:ro -v $PWD/_out:/out ghcr.io/siderolabs/imager:v1.5.4 secureboot-installer
profile ready:
arch: amd64
platform: metal
secureboot: true
version: v1.5.4
input:
  kernel:
    path: /usr/install/amd64/vmlinuz
  initramfs:
    path: /usr/install/amd64/initramfs.xz
  sdStub:
    path: /usr/install/amd64/systemd-stub.efi
  sdBoot:
    path: /usr/install/amd64/systemd-boot.efi
  baseInstaller:
    imageRef: ghcr.io/siderolabs/installer:v1.5.4
  secureboot:
    signingKeyPath: /secureboot/uki-signing-key.pem
    signingCertPath: /secureboot/uki-signing-cert.pem
    pcrSigningKeyPath: /secureboot/pcr-signing-key.pem
    pcrPublicKeyPath: /secureboot/pcr-signing-public-key.pem
    platformKeyPath: /secureboot/PK.auth
    keyExchangeKeyPath: /secureboot/KEK.auth
    signatureKeyPath: /secureboot/db.auth
output:
  kind: installer
  outFormat: raw
skipped initramfs rebuild (no system extensions)
kernel command line: talos.platform=metal console=ttyS0 console=tty0 init_on_alloc=1 slab_nomerge pti=on consoleblank=0 nvme_core.io_timeout=4294967295 printk.devkmsg=on ima_template=ima-ng ima_appraise=fix ima_hash=sha512 lockdown=confidentiality
UKI ready
installer container image ready
output asset path: /out/metal-amd64-secureboot-installer.tar
```

I have uploaded the test image to my private docker-account: https://hub.docker.com/repository/docker/pqraus/talos-installer/general

**Comment by smira** [comment]
I don't think we can resolve it in GitHub issue unless you make your image public.

You can look yourself into the image, and I guess it won't look like regular installer image. 

My guess you pushed something wrong, but it's a guess.

**Comment by pQraus** [comment]
Thanks for the hint. I looked at the image (which was in a public repo on my private Docker account 😉 ) 
I imported the tar from Docker the wrong way 🙈 

With `docker image load -i <tarball-from-imager>` everything works fine
