### ISSUE TITLE
documentation feature request: single pdf of all product documentation

### ISSUE THREAD

**Issue by d3287t328** [siderolabs/talos#8360]
### Description

I would like to reach each Sidero products documentation in a single pdf document (one for Talos, one for Omni, etc). It is easier to read and faster to search this way. At present it requires scraping the Sidero websites to do this which I have done but that is not ideal. I think a better format documentation standard would be similar to the EKS User Guide viewable at https://docs.aws.amazon.com/pdfs/eks/latest/userguide/eks-ug.pdf

**Comment by steverfrancis** [comment]
This is available now.
Go to the top of the documentation (e.g. https://www.talos.dev/v1.6/ page) then click "Print Entire Section" in the top right.
