### ISSUE TITLE
Avoid boot loop on old CPUs (and cputype-misconfigured VMs)

### ISSUE THREAD

**Issue by otopetrik** [siderolabs/talos#8361]
## Bug Report

Figuring out the boot loop and then ending at already existing bug [#7091](https://github.com/siderolabs/talos/issues/7091#issuecomment-1963107798) was needlessly difficult.
The issue appears even when running on recent-enough CPU, with misconfigured VM `cputype`.

### Description

Immediate reboot owerwrites the error message, and actually getting the log requires logging serial console to a file (e.g. running `qm terminal 123` in `screen -L`).

Any chance of patching [this](https://go.googlesource.com/go/+/refs/tags/go1.19.4/src/runtime/asm_amd64.s#366) in the `/init` process to just hang? Terminating the init process causes immediate reboot.
Or likely better way, doing the x86-64-v2 check in kernel and printing the error message and stopping there?

### Logs

needlessly difficult to obtain

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: [`kubectl version --short`]
- Platform:

**Comment by smira** [comment]
The only way I can think of is building the first `init` without `x86-64-v2` and doing the check there, but it'd be a good idea.

**Comment by smira** [comment]
https://github.com/HenrikBengtsson/x86-64-level/blob/develop/x86-64-level
