### ISSUE TITLE
Kernel Panic on qemu64 boot

### ISSUE THREAD

**Issue by discostur** [siderolabs/talos#8371]
## Bug Report
I'm trying to boot the latest Talos Linux on SmartOS via KVM. However, if i set cpu_type to host it freezes completely just after GRUB and when i set cpu_type to qemu64 i get a kernel crash on the first boot (see screenshot attached). 

### Description
- latest SmartOS / joyent_20240222T001232Z
- latest Talos ISO or just dd raw file to zvol / disk (v1.6.5)

### Logs
- Screenshot

<img width="719" alt="Bildschirmfoto 2024-02-26 um 18 44 22" src="https://github.com/siderolabs/talos/assets/2615420/1941fbad-caf1-4ee6-b7ce-bbf2d82b300d">

**Comment by smira** [comment]
Please provide a full kernel log (via serial console) to start debugging the issue.

Make sure you setup the VM to support at least x86_64-v2 level, as Talos is compiled with that.

**Comment by discostur** [comment]
@smira ok that makes sense, because i set cpu to "qemu64" which is a quite old cpu type. However, if i set cpu_type to "host" (which should be ok, i'm running a Intel(R) Xeon(R) Silver 4310 CPU) i can only see "Booting 'A - Talos v1.6.5'". Is there any option for grub to enable more debug output? 

I already dig a "set debug=all" to grub and the last lines i see are attached via screenshot. I'm still trying to get the serial console to run to get a full debug output ... 

<img width="719" alt="Bildschirmfoto 2024-02-28 um 11 32 20" src="https://github.com/siderolabs/talos/assets/2615420/8c454ad8-c8f7-45e4-ba22-338f2d80fac8">

**Comment by smira** [comment]
what you posted looks like console issue, try disabling `console=ttyS0` in the grub command line, using UEFI boot, etc.

**Comment by discostur** [comment]
didn't get it running - temporarily closed
