### ISSUE TITLE
kube-controller-manager won't start on IPv6-only nodes

### ISSUE THREAD

**Issue by attilaolah** [siderolabs/talos#8378]
## Bug Report

Since f70b47dddc2599a618c68d8b403d9b37c61f2b71 KubePrism won't start if there are no IPv4 addresses.

### Description

I'm disabling DHCP and not configuring any IPv4 addresses, to get SLAAC IPv6 addresses and gateway using RA on my node. Since the above commit, KubePrism has hard-coded 127.0.0.1, which apparently doesn't exist now, not even on the loopback interface? (Or rather, my API server only seems to bind to the IPv6 port).

### Logs

```
 user: warning: [2024-02-28T11:09:31.894096556Z]: [talos] controller failed {"component": "controller-runtime", "controller": "k8s.KubeletStaticPodController", "error": "error refreshing pod status: error fetching pod status: an      
 error on the server (\"Authorization error (user=apiserver-kubelet-client, verb=get, resource=nodes, subresource=proxy)\") has prevented the request from succeeding"}                                                                   
 user: warning: [2024-02-28T11:09:39.553744556Z]: [talos] controller failed {"component": "controller-runtime", "controller": "k8s.ManifestApplyController", "error": "error checking resource existence: Get \"https://127.0.0.1:7445/   
 api/v1/namespaces/kube-system/configmaps/coredns\": EOF"}                                                                                                                                                                                
```

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]

```
Client:
        Tag:         v1.6.4
        SHA:         undefined
        Built:       
        Go version:  go1.21.7
        OS/Arch:     linux/amd64
Server:
        NODE:        2001:171b:c9b8:8d40:ee8e:b5ff:fe6f:41d2
        Tag:         v1.6.5
        SHA:         22803bc5
        Built:       
        Go version:  go1.21.6 X:loopvar
        OS/Arch:     linux/amd64
        Enabled:     RBAC
```

- Kubernetes version: [`kubectl version --short`]

```
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.2
```

- Platform: arm64/metal

**Comment by smira** [comment]
This is not related, as 127.0.0.1 does always exist. 

Your problem is something different.

**Comment by attilaolah** [comment]
Thanks for the info. You're right that currently it is not possible to disable IPv4 in the Linux kernel, so the loopback interface will always have an IPv4 address (and you cannot remove an address from the loopback interface, nor can you disable the loopback as far as I'm aware.)

In that case, do you think the EOF at `api/v1/namespaces/kube-system/configmaps/coredns` might be an issue? It seems that the controller-manager doesn't come up healthy, but even with KubePrism disabled, in flips between healthy and unhealthy.

I'll update the issue title, but then I have no idea what the underlying cause is.

**Comment by attilaolah** [comment]
I think the issue is with the mask sizes of networks I configured. I'll close for now while I investigate, and reopen if it turns out to be something else.

**Comment by attilaolah** [comment]
So the issue is definitely with the mask size. If I pass in anything < 108, I get the error:

```
2001:171b:c9b8:8d40:ee8e:b5ff:fe6f:41d2: 2024-02-28T12:34:55.549164102Z stderr F I0228 12:34:55.548963       1 options.go:222] external host was not specified, using 2001:171b:c9b8:8d40:ee8e:b5ff:fe6f:41d2
2001:171b:c9b8:8d40:ee8e:b5ff:fe6f:41d2: 2024-02-28T12:34:55.549404841Z stderr F E0228 12:34:55.549304       1 run.go:74] "command failed" err="specified --service-cluster-ip-range is too large; for 128-bit addresses, the mask must be >= 108"
```

However, if I pass in something >= 108, then the API server starts, but the controller manager fails since it got a mask larger than `node-cidr-mask-size-ipv6`, which defaults to 64.

**Comment by smira** [comment]
Yes, you need to configure Kubernetes correctly for it to come up healthy, I guess this makes sense ;)

**Comment by smira** [comment]
This is not specific to Talos, it's all Kubernetes.

I guess in your case you're trying to remove IPv4 subnets, and you might need to clean up the Nodes manually

**Comment by attilaolah** [comment]
You're right. Sorry for routing this to the wrong place, I was put off by that KubePrism change and thought this was due to KubePrism alone. Indeed this is a Kube configuration issue. I'm still figuring out how to properly bootstrap Cilium in IPv6-only mode.

Currently I also have IPv4 routing enabled during bootstrap in order to reach some container registries like factory.talos.dev, which don't currently provide AAAA records, but apart from the bootstrap/update procedures, I don't really need the IPv4 routing.

**Comment by attilaolah** [comment]
Also this is a non-production cluster so instead of cleaning up nodes manually, I tend to just update the config and reset & bootstrap again, so I don't spend too much time manually configuring nodes.

**Comment by smira** [comment]
Yes, we have a long way to support IPv6 in factory.talos.dev unfortunately. cc @TimJones

**Comment by TimJones** [comment]
Actually Image Factory works fine with IPv6, but Azure, where it is hosted, has more issues with IPv6 in Kubernetes clusters :)
