### ISSUE TITLE
`talosctl dashboard` doesn't work if $TERM=screen-256color after the 1.5.3->1.6.5 upgrade

### ISSUE THREAD

**Issue by rtim75** [siderolabs/talos#8398]
### Description

I'm using tmux.
After downloading the latest talosctl version, `talosctl dashboard` fails with `terminal type unsupported`.  Manually changing $TERM envvar to `xterm-256color` fixes the issue.

### Logs

```
13:35:55 ❯ echo $TERM
screen-256color
13:36:01 ❯ talosctl dashboard
terminal type unsupported
13:36:24 ❯ export TERM=xterm-256color
13:36:30 ❯ talosctl dashboard # this will work
```

### Environment

- Talos version: 
    ```
    13:12:17 ❯ talosctl version
    Client:
        Tag:         v1.6.5
        SHA:         22803bc5
        Built:
        Go version:  go1.21.6 X:loopvar
        OS/Arch:     darwin/arm64
    ```

**Comment by smira** [comment]
What is the bug here? The terminal `screen-256color` is not supported with dashboard.

**Comment by rtim75** [comment]
understood. Closing it then.

**Comment by smira** [comment]
It might be the case that the error wasn't reported before.

**Comment by rtim75** [comment]
could be the case, yeah. Since it stopped working after the upgrade I assumed that it might be unexpected behavior. But sicne you're saying that `screen-256color` is not supported, obviously that's not the case.
