### ISSUE TITLE
nvidia gpu-operator compatibility

### ISSUE THREAD

**Issue by d44b** [siderolabs/talos#8402]
## Feature Request

Make Talos compatible with nvidia gpu-operator

### Description

I'd love to be able to run gpu-operator managing drivers and/or container runtime, as it's possible in different distros.

https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/overview.html

https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/platform-support.html#supported-operating-systems-and-kubernetes-platforms

Right now, the driver daemonset fails with

```Unmounting NVIDIA driver rootfs...
Installing NVIDIA driver kernel modules...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package linux-objects-nvidia-535-server-6.1.51-talos
E: Couldn't find any package by glob 'linux-objects-nvidia-535-server-6.1.51-talos'
E: Couldn't find any package by regex 'linux-objects-nvidia-535-server-6.1.51-talos'
E: Unable to locate package linux-signatures-nvidia-6.1.51-talos
E: Couldn't find any package by glob 'linux-signatures-nvidia-6.1.51-talos'
E: Couldn't find any package by regex 'linux-signatures-nvidia-6.1.51-talos'
E: Unable to locate package linux-modules-nvidia-535-server-6.1.51-talos
E: Couldn't find any package by glob 'linux-modules-nvidia-535-server-6.1.51-talos'
E: Couldn't find any package by regex 'linux-modules-nvidia-535-server-6.1.51-talos'
Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Unmounting NVIDIA driver rootfs...
```

**Comment by frezbo** [comment]
This is already supported, please refer to https://www.talos.dev/v1.6/talos-guides/configuration/nvidia-gpu/

**Comment by frezbo** [comment]
> This is already supported, please refer to https://www.talos.dev/v1.6/talos-guides/configuration/nvidia-gpu/

To be clear, Talos will not support the gpu-operator since it wants to manage building and loading modules which is not going to be supported by Talos
