### ISSUE TITLE
Ability to add system extensions without rebuilding node

### ISSUE THREAD

**Issue by arno4000** [siderolabs/talos#8416]
## Feature Request

Is it possible to add system extensions without rebuilding the talos VM? Prior to talos 1.5 it was possible to add the extensions in the machineconfig and then apply the new machineconfig to the node. But after talos 1.5 this is deprecated, so what is the new way to install extensions without building a new node?

Talos Docs: https://www.talos.dev/v1.6/talos-guides/configuration/system-extensions/

**Comment by frezbo** [comment]
Extensions always needed a node upgrade, the new approach is to use [image factory](https://factory.talos.dev) and use the custom installer image to upgrade

**Comment by arno4000** [comment]
Ah, thank you, it worked perfectly by upgrading the node, I am closing this issue.
