### ISSUE TITLE
Modify VIP is not working

### ISSUE THREAD

**Issue by pau-campana** [siderolabs/talos#8421]
## Bug Report
I would like to be able to modify the VIP from an existing cluster. After editing the machineconfig and I set the new VIP, The new VIP is not responding. Running `talosctl reboot` does not solve the problem.

### Info about the environment:
I'm using talos v1.6.5. I'm using single cluster nodes using type init. We use custom ISO where we set the kernel argument:
`'ip=$VIP::$GATEWAY:$MASK::$INTERFACE_NAME:none:8.8.8.8::'`. 
In the machineconfig, VIP is specified in the following places:
- `machine.network.interfaces[0].vip`
- `machine.install.extraKernelArgs`: `'ip=$VIP::$GATEWAY:$MASK::$INTERFACE_NAME:none:8.8.8.8::'`
- `cluster.controlPlane.endpoint`

When I edit the machineconfig and I set a new VIP, I see the address is correctly assigned to the cluster:
```
talosctl get addresses | grep eth0
$NODE_IP   network     AddressStatus   eth0/$NEW_VIP/32                               1         $NEW_VIP/32                    eth0
$NODE_IP   network     AddressStatus   eth0/$OLD_VIP/24                               1         $OLD_VIP/24                    eth0
$NODE_IP   network     AddressStatus   eth0/$NODE_IP/24                               1         $NODE_IP/24                    eth0
$NODE_IP   network     AddressStatus   eth0/xxxx::xxxx:xxxx:xxxx:xxxx/64              2         xxxx::xxxx:xxxx:xxxx:xxxx/64   eth0
```

However, the new $NEW_VIP is not working, and the $OLD_VIP is still working.

### Environment

- Talos version: 
```
>talosctl version --short
Client:
Client v1.6.1
Server:
	NODE:        192.168.31.172
	Tag:         v1.6.5
	SHA:         22803bc5
	Built:
	Go version:  go1.21.6 X:loopvar
	OS/Arch:     linux/arm64
	Enabled:     RBAC
```
- Kubernetes version: 
```
>kubectl version
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.6
```
- Platform:
Baremetal talos. Using the ISO.

**Comment by smira** [comment]
VIP should never be assigned to the machine statically (via kernel args/machine config). it should only be mentioned exactly once `machine.network.interfaces[0].vip` - Talos will manage its lifecycle automatically. What you have is a static address config.

**Comment by smira** [comment]
https://www.talos.dev/v1.6/talos-guides/network/vip/

**Comment by pau-campana** [comment]
I will remove the VIP from kernel params. But why not using the VIP in the `cluster.controlPlane.endpoint`?  I understand that the endpoint IP should be the IP that will redirect traffic to all CP, which in this case is the VIP

**Comment by smira** [comment]
`cluster.controlPlane.endpoint` can be perfectly a VIP, but this doesn't assign the address.

using kernel args means that even if your remove the IP in the machine config, it will stay assigned (as it's in the kernel args).

VIP does automatic elections and assigns the IP to a single machine announcing the IP on layer 2 network automatically.
