### ISSUE TITLE
:bug: service framework: service fails to run with context cancelled

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#8423]
This is a bug in Talos system/services framework, where a race condition might lead to a service trying to start with a cancelled context.

The way contexts are handled should be rewritten.

**Comment by smira** [comment]
![Image](https://github.com/siderolabs/talos/assets/55211/409088f2-0be9-42d5-b56c-4b647ac451b7)

**Comment by frezbo** [comment]
ohhh, i had seen this when testing extensionserviceconfig :hankey:

**Comment by smira** [comment]
This one might require a pretty big rewrite of the service framework @utkuozdemir 

We could probably do a hack session with @DmitriyMV next week or so on it

**Comment by utkuozdemir** [comment]
Oh, ok, I thought it could be a simple race condition. I'll drop this for now then.
