### ISSUE TITLE
Talos constantly reports service "ext-zpool-importer" to be "up" 

### ISSUE THREAD

**Issue by runningman84** [siderolabs/talos#8466]
## Bug Report
Since usage of the zfs extensions all nodes constantly writes logs. 

### Description
My goal is to attach some zfs disk in the future. Therefore I applied the zfs extension.

Btw. what is the correct procedure to apply a system extension? I had to reset the node and apply the config again, this activated the extension. 

### Logs
 user: warning: [2024-03-19T19:41:17.518388937Z]: [talos] task startAllServices (1/1): service "ext-zpool-importer" to be "up"                                                                                                                       
 user: warning: [2024-03-19T19:41:32.518188937Z]: [talos] task startAllServices (1/1): service "ext-zpool-importer" to be "up"                                                                                                                       
 user: warning: [2024-03-19T19:41:47.517853937Z]: [talos] task startAllServices (1/1): service "ext-zpool-importer" to be "up"                                                                                                                       
 user: warning: [2024-03-19T19:42:02.518777937Z]: [talos] task startAllServices (1/1): service "ext-zpool-importer" to be "up"                                                                                                                       
 user: warning: [2024-03-19T19:42:17.519633937Z]: [talos] task startAllServices (1/1): service "ext-zpool-importer" to be "up"                                                                                                                       
 user: warning: [2024-03-19T19:42:32.518334937Z]: [talos] task startAllServices (1/1): service "ext-zpool-importer" to be "up"                                                                                                                       
 user: warning: [2024-03-19T19:42:47.518829937Z]: [talos] task startAllServices (1/1): service "ext-zpool-importer" to be "up"                                                                                                                       
 user: warning: [2024-03-19T19:43:02.521498937Z]: [talos] task startAllServices (1/1): service "ext-zpool-importer" to be "up"                                                                                                                       
 user: warning: [2024-03-19T19:43:17.521394937Z]: [talos] task startAllServices (1/1): service "ext-zpool-importer" to be "up"     

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`] 1.6.6
- Kubernetes version: [`kubectl version --short`] 1.29.2
- Platform: virtualbox

**Comment by frezbo** [comment]
Did you enable the zfs module ?

**Comment by runningman84** [comment]
How can I enable it? Thought it is automatically enabled by using the zfs system extension?

**Comment by frezbo** [comment]
> How can I enable it? Thought it is automatically enabled by using the zfs system extension?

you'd need a machineconfig patch:

```yaml
machine:
  kernel:
    modules:
      - name: zfs
```
