### ISSUE TITLE
Document how to activate extensions on existing nodes

### ISSUE THREAD

**Issue by runningman84** [siderolabs/talos#8467]
## Feature Request
I have added extensions to existing nodes. Talosctl reported that extensions were applied without a reboot. It would be nice to ge a hint what needs to be done to really apply them.

My current approach is reset and apply again which is not very convenient. Is there some reinstall command?

I also noticed that after a stop of my 3 test vms and start the nodes seem to have lost the extensions. Is this some bug or my fault?

**Comment by smira** [comment]
We don't know what you were doing exactly, so we can't say whether it was right or wrong.

If you want to update existing nodes, just use [Image Factory](https://www.talos.dev/v1.6/talos-guides/install/boot-assets/#image-factory) and use a proper schematic to get the installer image reference, then do a Talos upgrade to that installer.

**Comment by runningman84** [comment]
hmm it looks like the issue is that if you have inserted the install media afterwards the cluster will roll back to the version from the install media

**Comment by runningman84** [comment]
hmm it looks like the upgrade command just uses the default image and do not use any extensions or other stuff from the machine config

**Comment by smira** [comment]
Please follow the [documentation](https://www.talos.dev/v1.6/talos-guides/install/boot-assets/#image-factory).

The upgrade command _requires_ an image from the Image Factory.
