### ISSUE TITLE
talosctl (v1.6.7) is not running on old AMD64 CPU. It requires AMD64 processors with v2 microarchitecture support.

### ISSUE THREAD

**Issue by davidpelfree** [siderolabs/talos#8505]
## Bug Report
`talosctl ` is not working on old AMD64 CPUs.

### Description
I have an old i5-3470 CPU. I run a dev VM inside Proxmox.
I downloaded the `talosctl` tool using the official shell installer as described in the docs.
I am getting this message:
```
$ talosctl --help
This program can only be run on AMD64 processors with v2 microarchitecture support.
```

A quick Google revealed that this error message comes from the Go binary.  See: https://github.com/golang/go/blob/master/src/runtime/asm_amd64.s#L82

My understanding is that the `talosctl` tool was compiled by Go for the AMD64 v2 micro-architecture, assuming a newer CPU. 

I guess that to resolve this issue, another executable release need to created with `GOAMD64=1`.  
And during the installation script, some check need to be done on the `/proc/cpuinfo` file to detect the CPU level, then, download the specific binary matching the microarchitecture level of the CPU. (See example AWK code here: https://unix.stackexchange.com/questions/631217/how-do-i-check-if-my-cpu-supports-x86-64-v2)

This issue may be related to: https://github.com/siderolabs/talos/issues/7091#issuecomment-1519886673

### Logs
```
$ talosctl --help
This program can only be run on AMD64 processors with v2 microarchitecture support.
```

### Environment

- Talos version: 1.6.7
- Kubernetes version: N/A
- Platform: Ubuntu 23.10 on VM on Proxmox with i5-3470 CPU

**Comment by smira** [comment]
In your particular case, configure Proxmox VM to use host CPU - it exposes very basic CPU back to the VM.

Your CPU can run v2 code.

**Comment by davidpelfree** [comment]
Confirmed to work with Proxmox CPU set to `host`. Thanks.
