### ISSUE TITLE
 shasum.txt doesn't match binary name

### ISSUE THREAD

**Issue by shinebayar-g** [siderolabs/talos#8512]
### Description

[sha256sum.txt](https://github.com/siderolabs/talos/releases/download/v1.6.7/sha256sum.txt) file looks like this
`99540b1d3bbc4d7bd41e8dfd5027941bed5eb29eff09756aed513b41e391eac9  _out/talosctl-linux-amd64`

However, uploaded binary to the releases is named [talosctl-linux-amd64](https://github.com/siderolabs/talos/releases/download/v1.6.7/talosctl-linux-amd64)

This causes some automation tool to fail shasum check. For example, this ansible code fails on checksum.

```yaml
- name: Download talosctl
  ansible.builtin.get_url:
    url: https://github.com/siderolabs/talos/releases/download/v1.6.7/talosctl-linux-amd64
    dest: ~/.local/bin/talosctl
    mode: '0755'
    checksum: sha256:https://github.com/siderolabs/talos/releases/download/v1.6.7/sha256sum.txt
```

### Logs

Ansible failure error

```log
TASK [talosctl : Download talosctl] **********************************************************************************************************************************************************
Sunday 31 March 2024  02:32:54 -0700 (0:00:00.236)       0:00:18.520 **********
fatal: [127.0.0.1]: FAILED! => changed=false
  msg: Unable to find a checksum for file 'talosctl-linux-amd64' in 'https://github.com/siderolabs/talos/releases/download/v1.6.7/sha256sum.txt'
```

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: [`kubectl version --short`]
- Platform:

**Comment by smira** [comment]
I understand that what we publish is hard to use with Ansible, but it's the way current release machinery works, and we can't change it right now. We will migrate Talos CI in the next release cycle, which should hopefully address this as well.
