### ISSUE TITLE
talosctl apply-config reconfigures network too fast?

### ISSUE THREAD

**Issue by zviratko** [siderolabs/talos#8566]
### Description

I have a script that respins my LAB environment with few Talos nodes quite often.
One of the steps is to apply-config to all the nodes that were booted with PXE. This not only installs Talos to disk but also changes network configuration drastically (the PXE network it has is no longer used but instead a VLAN is configured with static address).
I am currently running it like this
`timeout 10 talosctl apply-config --mode=reboot --talosconfig "${SOMEWHERE}/talosconfig" --file "${SOMEWHERE/talos-nodes/${NAME}.yaml" --endpoints "${PXEIP}" -n "${PXEIP}" --insecure || true
`

Sometimes, in maybe <1% of the cases, this command hangs. Not because it isn't successful, but (at least from what I can see) because the node changes its network configuration too fast and never has a chance to reply to talosctl. 

It might be a race condition but should it even start reconfiguring anything with --mode=reboot before the reboot? I couldn't even find a "mode" that would reliably ackowledge the config so that I could distinguish between a real failure and the node just applying the config too fast (not that I really need to, to the credit of Talos, I don't think it ever actually failed, but that "|| true" is bothering me :-))

Thanks.

### Environment

- Talos version: 1.6.6, 1.6.7, 1.7.0-beta.0
- Platform: amd64

**Comment by smira** [comment]
Usually you don't need to specify `--mode`, as Talos will figure out things automatically, and yes, it does reconfigure on the fly, so there's a chance that it becomes unavailable. The only suggestion is to keep the old IP around and then reconfigure once again using new IP, there's no guarantee that the IP will be up in time to send the response back.

Another option is to use SideroLink tunnel (we should have some docs for 1.7) so that re-IP procedure doesn't cause issues, as Wireguard tunnel will survive.

**Comment by zviratko** [comment]
I thought about keeping the IP, but that isn't very "declarative", is it? Couldn't the connection be cleanly closed after validating the config but before reconfiguring anything?

Sidero Metal looks sweet, but it's not for me. Too much complexity (on top of already having too much complexity). I guess || true will have to do.

Please think about just fixing the race condition...

**Comment by smira** [comment]
If you want machine config to be strictly applied after a reboot, there's `--mode=staged` followed by a reboot.

**Comment by zviratko** [comment]
That one is not supported in maintenance mode :(
