### ISSUE TITLE
Power savings not possible only state c1-c3 is available

### ISSUE THREAD

**Issue by runningman84** [siderolabs/talos#8595]
## Bug Report
I build a new test system using a very power efficient n100 board from asrock. In Manjaro the power consumption is something like 6 watt in idle, the same system needs about 10 watt using talos.

It turns out that for some reason only state C1-C3 is supported:

````
PowerTOP 2.14     Overview   Idle stats   Frequency stats   Device stats   Tunables   WakeUp                            


           Pkg(OS)  |            CPU(OS) 0
Powered On  0.0%    | POLL        0.0%    0.1 ms
C1         11.1%    | C1         11.2%    0.2 ms
C2         27.1%    | C2         37.6%    0.9 ms
C3         53.2%    | C3         42.7%    3.6 ms
RC6pp       0.0%    |

                    |            CPU(OS) 1
                    | POLL        0.0%    0.0 ms
                    | C1          7.8%    0.1 ms
                    | C2         24.8%    1.1 ms
                    | C3         57.4%    2.9 ms
                    |

                    |            CPU(OS) 2
                    | POLL        0.0%    0.0 ms
                    | C1          8.6%    0.2 ms
                    | C2         29.3%    1.1 ms
                    | C3         53.7%    5.6 ms
                    |

                    |            CPU(OS) 3
                    | POLL        0.0%    0.0 ms
                    | C1         16.5%    0.3 ms
                    | C2         16.6%    1.2 ms
                    | C3         58.4%    5.6 ms
                    |

                    |             GPU     |
                    | Powered On100.0%    |
                    | RC6         0.0%    |
                    | RC6p        0.0%    |
                    | RC6pp       0.0%    |
                    |                     |



````

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`] v1.6.7 and v1.7.0-beta.1
- Kubernetes version: [`kubectl version --short`]
- Platform: Asrock N100 ITX

**Comment by runningman84** [comment]
It looks like the intel idle driver is not used by talos:
https://www.golinuxhub.com/2018/06/what-cpu-c-states-check-cpu-core-linux/

I think it might make sense to include the intel idle driver because a lot of edge usecases use low powered intel stuff.

**Comment by smira** [comment]
PRs to [pkgs](siderolabs/pkgs) repo are welcome!

**Comment by runningman84** [comment]
ok, I can try that. From an outside perspective it is difficult to see how these modules are beeing build. I could just copy this folder https://github.com/siderolabs/extensions/blob/main/drivers/thunderbolt and replcae the thunderbolt stuff with the intel_idle stuf. How would I know that that approach works? How could I debug that?

**Comment by smira** [comment]
These drivers should be small, so if you know which kernel options to enable, that would be enough.

**Comment by smira** [comment]
(no need to do an extension)

**Comment by runningman84** [comment]
it is just the CONFIG_INTEL_IDLE option  https://cateee.net/lkddb/web-lkddb/INTEL_IDLE.html
can you just add that?

**Comment by smira** [comment]
Please create an issue with `pkgs` repo for tracking. Thanks you.
