### ISSUE TITLE
Include i915  firmware in extensions

### ISSUE THREAD

**Issue by runningman84** [siderolabs/talos#8596]
## Feature Request
Booting a talos node with some very common stuff like an intel cpu creates error like these:
````
[    1.010017] [talos] [initramfs] bind mounting /lib/firmware
[    5.855505] i915 0000:00:02.0: [drm] *ERROR* GT0: GuC firmware i915/tgl_guc_70.bin: fetch failed -ENOENT
[    5.855513] i915 0000:00:02.0: [drm] GT0: GuC firmware(s) can be downloaded from https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915
[    5.856067] i915 0000:00:02.0: [drm] GT0: GuC firmware i915/tgl_guc_70.bin version 0.0.0
[    5.859117] i915 0000:00:02.0: Direct firmware load for i915/adlp_dmc.bin failed with error -2
[    5.859132] i915 0000:00:02.0: Direct firmware load for i915/adlp_dmc_ver2_16.bin failed with error -2
[    5.859135] i915 0000:00:02.0: [drm] Failed to load DMC firmware i915/adlp_dmc.bin. Disabling runtime power management.
[    5.859139] i915 0000:00:02.0: [drm] DMC firmware homepage: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915
````

**Comment by smira** [comment]
It is already part of Talos system extensions.

**Comment by runningman84** [comment]
I only see this extension?
https://github.com/siderolabs/extensions/tree/main/firmware/i915-ucode

**Comment by smira** [comment]
Is it a wrong one? It's not quite clear what you're asking about. `i915` is not an Intel CPU.

**Comment by runningman84** [comment]
From my understanding i915 is the driver name for intel graphics. The system is complaining about missing firmware files for the intel graphics. So my idea was that this is a very common firmware, there should be some extension to include the firmware files. So I looked into the extensions repo for i915 stuff and only found the ucode stuff...

**Comment by smira** [comment]
ok, to make it clear: `i915-ucode` system extensions provides firmware for `i915` Intel Graphics - this is most probably what you're looking for.
