### ISSUE TITLE
Scaleway Bare Metal doesn't want to boot Talos

### ISSUE THREAD

**Issue by syrm** [siderolabs/talos#8608]
I tried to boot on the metal-amd64.iso on a bare metal Scaleway without success.
It always stuck at « Booting Talos ISO »

- Talos version: 1.6
- Kubernetes version: N/A
- Platform: Scaleway Elastic Metal (EM-A410X-SSD)

**Comment by smira** [comment]
Please try removing console= kernel args

**Comment by syrm** [comment]
Now the screen display « Booting a command list »

**Comment by smira** [comment]
As any bare-metal system, you have to know what are the settings which work for your particular machine. There is not much we can do on Talos side.

**Comment by syrm** [comment]
Any iso works except Talos :/

**Comment by syrm** [comment]
I made it working... waiting 20mn.
Sorry for the disturbance

Thank you
