### ISSUE TITLE
IPv6 on OpenStack using SLAAC does not set route correctly

### ISSUE THREAD

**Issue by MindTooth** [siderolabs/talos#8619]
## Bug Report

Continuation of https://github.com/siderolabs/talos/issues/8558.

### Description

It all started with:
```
control-plane-1: user: warning: [2024-04-19T12:33:36.812989927Z]: [talos] controller failed {"component": "controller-runtime", "controller": "network.RouteSpecController", "error": "1 error occurred:\n\t* error adding route: netlink receive: file exists, message {Family:10 DstLength:0 SrcLength:0 Tos:0 Table:0 Protocol:4 Scope:0 Type:1 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gateway:<ipv6_address>::1 OutIface:8 Priority:1024 Table:254 Mark:0 Pref:<nil> Expires:<nil> Metrics:<nil> Multipath:[]}}\n\n"}
```

I did however look at the source code of Talos, and noticed the following:

https://github.com/siderolabs/talos/blob/d7c3a0735eab85dd24e86fe3e0872253067e8f10/internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go#L242-L243

From my network dump. ` "type": "ipv6_slaac"`.  I'm not sure if it's related, but I noticed that `ipv6_slaac` was not even part of the test data.

### Logs

- OpenStack network metadata dump
- Talos boot logs
- Dump of the route specs

[route_logs.tgz](https://github.com/siderolabs/talos/files/15040532/route_logs.tgz)  - _Must decrypt._

### Environment

```
$ talosctl --talosconfig talosconfig version -n 10.10.10.51
Client:
	Tag:         v1.6.7
	SHA:         46c8ac10
	Built:       
	Go version:  go1.21.8 X:loopvar
	OS/Arch:     darwin/arm64
Server:
	NODE:        10.10.10.51
	Tag:         v1.7.0-beta.1
	SHA:         77581447
	Built:       
	Go version:  go1.22.2
	OS/Arch:     linux/amd64
	Enabled:     RBAC
```

- Platform: OpenStack

**Comment by smira** [comment]
Interesting, OpenStack in your dump publishes the IPv6 default gateway as a route, vs. the IPv4 example we used, where it is published as a gateway (another explicit field).

This doesn't trigger the code I added use a different route priority, as this code never supposed to work for default gateways.

**Comment by MindTooth** [comment]
Current schema: https://opendev.org/openstack/nova/raw/branch/master/doc/api_schemas/network_data.json

```json
    "l3_ipv6_network": {
      "$id": "#/definitions/l3_ipv6_network",
      "type": "object",
      "title": "L3 IPv6 network configuration",
      "required": [
        "id",
        "link",
        "network_id",
        "type"
      ],
      "properties": {
        "id": {
          "$ref": "#/definitions/l3_id"
        },
        "link": {
          "$ref": "#/definitions/l3_link"
        },
        "network_id": {
          "$ref": "#/definitions/l3_network_id"
        },
        "type": {
          "$ref": "#/definitions/l3_ipv6_type"
        },
        "ip_address": {
          "$ref": "#/definitions/l3_ipv6_host"
        },
        "netmask": {
          "$ref": "#/definitions/l3_ipv6_netmask"
        },
        "routes": {
          "$id": "#/definitions/properties/l3_ipv6_network/routes",
          "type": "array",
          "title": "L3 IPv6 network routes",
          "items": {
            "$ref": "#/definitions/l3_ipv6_network_route"
          }
        }
      }
```

No mention of a key of `gateway`.  However, I was trying to use this schema through a validator against the current test data, but it's so old that I either can't find a validator that does this, nor that it's even working. 🤷🏻‍♂️

**Comment by MindTooth** [comment]
![thank you](https://media1.tenor.com/m/6bUnLYb54jgAAAAC/thank-you-thanks.gif)
