### ISSUE TITLE
Registry config for docker.io not applying

### ISSUE THREAD

**Issue by NickyHeuperman** [siderolabs/talos#8639]
I've been trying to get docker hub authentication working to fix the rate limit on docker.io.

I've patched my machines with the following config

`machine:
    config:
      docker.io:
        auth:
          username: {username here}
          password: {token here}`

According to docker hub the access token has never been used.

What should I do in order to make this work?

**Comment by smira** [comment]
Correct config: https://www.talos.dev/v1.7/reference/configuration/v1alpha1/config/#Config.machine.registries.config.-

The key under `machine.registries.confg` should be the hostname of the registry endpoint, which for `docker.io` is `registry-1.docker.io`.
