### ISSUE TITLE
💉  Talos/Omni Doctor

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#8682]
Proposal: have a somewhat simple rule system that evaluates current state against common pitfalls and provides solutions.

Two problems:

* enabling kubelet server certificate rotation and not approving CSRs (gate: check number of not approved certificates for the kubelet)
* overlapping Talos host address and K8s pod/service CIDRs

Report such issues e.g. to the resource (in Omni? Talos?) and show it using Talos dashboard/Omni dashboard

**Comment by runningman84** [comment]
One other pitfall is that you do not easily see that a given node is bootet from the install media instead of the internal install disk.

**Comment by smira** [comment]
> One other pitfall is that you do not easily see that a given node is bootet from the install media instead of the internal install disk.

This is fixed in 1.8 via https://www.talos.dev/v1.8/introduction/what-is-new/#taloshalt_if_installed-kernel-argument
