### ISSUE TITLE
Kubelet is not starting

### ISSUE THREAD

**Issue by Minivolk02** [siderolabs/talos#8689]
### Description
Kubelet is not starting after applying controlplane.config
### Logs
10.224.224.125: user: warning: [2024-05-02T06:38:37.183292616Z]: [talos] kubernetes endpoint watch error {"component": "controller-runtime", "controller": "k8s.EndpointController", "error": "failed to list *v1.Endpoints: Get \"https://10.224.224.125:6443/api/v1/namespaces/default/endpoints?fieldSelector=metadata.name%3Dkubernetes&limit=500&resourceVersion=0\": dial tcp 10.224.224.125:6443: connect: connection refused"}
10.224.224.125: user: warning: [2024-05-02T06:39:20.617136616Z]: [talos] kubernetes endpoint watch error {"component": "controller-runtime", "controller": "k8s.EndpointController", "error": "failed to list *v1.Endpoints: Get \"https://10.224.224.125:6443/api/v1/namespaces/default/endpoints?fieldSelector=metadata.name%3Dkubernetes&limit=500&resourceVersion=0\": dial tcp 10.224.224.125:6443: connect: connection refused"}
10.224.224.125: user: warning: [2024-05-02T06:39:25.582285616Z]: [talos] controller failed {"component": "controller-runtime", "controller": "k8s.NodeApplyController", "error": "1 error(s) occurred:\n\ttimeout"}
10.224.224.125: user: warning: [2024-05-02T06:40:05.102993616Z]: [talos] kubernetes endpoint watch error {"component": "controller-runtime", "controller": "k8s.EndpointController", "error": "failed to list *v1.Endpoints: Get \"https://10.224.224.125:6443/api/v1/namespaces/default/endpoints?fieldSelector=metadata.name%3Dkubernetes&limit=500&resourceVersion=0\": dial tcp 10.224.224.125:6443: connect: connection refused"}
10.224.224.125: user: warning: [2024-05-02T06:40:18.334781616Z]: [talos] controller failed {"component": "controller-runtime", "controller": "k8s.NodeApplyController", "error": "1 error(s) occurred:\n\ttimeout"}
10.224.224.125: user: warning: [2024-05-02T06:40:49.971045616Z]: [talos] kubernetes endpoint watch error {"component": "controller-runtime", "controller": "k8s.EndpointController", "error": "failed to list *v1.Endpoints: Get \"https://10.224.224.125:6443/api/v1/namespaces/default/endpoints?fieldSelector=metadata.name%3Dkubernetes&limit=500&resourceVersion=0\": dial tcp 10.224.224.125:6443: connect: connection refused"}
### Environment
Vagrant + libvirt
- Talos version: [`talosctl version --nodes <problematic nodes>`]
-- Client:
	Tag:         v1.7.0
	SHA:         70fb41ff
	Built:
	Go version:  go1.22.2
	OS/Arch:     linux/amd64
Server:
	NODE:        10.224.224.125
	Tag:         v1.7.0
	SHA:         70fb41ff
	Built:
	Go version:  go1.22.2
	OS/Arch:     linux/amd64
	Enabled:     RBAC
- Kubernetes version: [`kubectl version --short`]
1.30

- Platform:
Vagrant + Libvirt

**Comment by Minivolk02** [comment]
.StaticPodServerController", "id": "kube-controller-manager"}
[  192.126625] [talos] rendered new static pod {"component": "controller-runtime", "controller": "k8s.StaticPodServerController", "id": "kube-scheduler"}
[  202.139407] [talos] controller failed {"component": "controller-runtime", "controller": "k8s.ManifestApplyController", "error": "error creating mapping for object /v1/Secret/bootstrap-token-bbcfdg: Get \"https://127.0.0.1:7445/api?timeout=32s\": EOF - error from a previous attempt: read tcp 127.0.0.1:33292->127.0.0.1:7445: read: connection reset by peer"}
[  204.741754] [talos] controller failed {"component": "controller-runtime", "controller": "k8s.NodeApplyController", "error": "1 error(s) occurred:\n\ttimeout"}
[  206.616910] [talos] controller failed {"component": "controller-runtime", "controller": "k8s.KubeletStaticPodController", "error": "error refreshing pod status: error fetching pod status: an error on the server (\"Authorization error (user=apiserver-kubelet-client, verb=get, resource=nodes, subresource=proxy)\") has prevented the request from succeeding"}
[  209.176118] [talos] kubernetes endpoint watch error {"component": "controller-runtime", "controller": "k8s.EndpointController", "error": "failed to list *v1.Endpoints: Get \"https://10.224.224.134:6443/api/v1/namespaces/default/endpoints?fieldSelector=metadata.name%3Dkubernetes&limit=500&resourceVersion=0\": dial tcp 10.224.224.134:6443: connect: connection refused"}
[  212.812651] [talos] controller failed {"component": "controller-runtime", "controller": "k8s.ManifestApplyController", "error": "error creating mapping for object /v1/Secret/bootstrap-token-bbcfdg: Get \"https://127.0.0.1:7445/api?timeout=32s\": EOF"}

**Comment by smira** [comment]
There is nothing in the logs about `kubelet`, but rather about `kube-apiserver` not running.

This is most probably misconfiguration, and you can troubleshoot yourself via [docs](https://www.talos.dev/v1.7/introduction/troubleshooting/#kubernetes-control-plane).

I will close this issue, as there is no bug in Talos so far, but feel free to re-open if turns out another way.

**Comment by Minivolk02** [comment]
Sorry for reopen. You are right, i created air-gapped configuration, but api-server always dont wont to start, there is no containers api-server, i don't know why

**Comment by smira** [comment]
You have more logs to go through, but my guess your CRI can't pull the sandbox `pause` image.

https://www.talos.dev/v1.7/talos-guides/configuration/containerd/#pause-image

Either way, `talosctl logs cri` and `talosctl logs kubelet` and look through them.

**Comment by Minivolk02** [comment]
<img width="1453" alt="image" src="https://github.com/siderolabs/talos/assets/27731703/a0c110a2-c2c8-4d4d-b079-6987c4f9db1d">
Thank you so much, seems everything okey, but cluster is still not ready(

**Comment by Minivolk02** [comment]
<img width="1439" alt="image" src="https://github.com/siderolabs/talos/assets/27731703/61653e4d-de23-42bf-8aa7-a7d18952fcf0">
And cant get to api server

**Comment by Minivolk02** [comment]
[root@iris talos]# talosctl -n 10.224.239.100 logs -k kube-system/kube-apiserver-talos-87e-522:kube-apiserver:938e66bc3009
10.224.239.100: 2024-05-02T16:50:34.608169Z stderr F Error: invalid argument "" for "--advertise-address" flag: failed to parse IP: ""
I found this error in api server, i don't know how to solve it

**Comment by smira** [comment]
I do not know, Talos should never put an empty value there. You can check with `talosctl get staticpods -o yaml`. So if it's not empty there, then it's kubelet doing something. 

Just follow the troubleshooting guide I posted above, it's the best way.

**Comment by Minivolk02** [comment]
I follow , can i edit it manual?
<img width="1156" alt="image" src="https://github.com/siderolabs/talos/assets/27731703/7bf2037e-5752-4ba9-a087-f3b8d761d172">

**Comment by Minivolk02** [comment]
CrashLoopBackOff: \"back-off 10s restarting failed container=kube-apiserver pod=kube-apiserver-talos-87e-522_kube-system(f4696297b589a1a239765cd9887ea66e)\""}]}
10.224.239.100: {"ts":1714669273342.696,"caller":"kubelet/kubelet_node_status.go:711","msg":"Failed to set some node status fields","node":{"name":"talos-87e-522"},"err":"failed to validate nodeIP: node IP: \"10.224.224.138\" not found in the host's network interfaces"}
10.224.239.100: {"ts":1714669273345.797,"caller":"kubelet/kubelet_node_status.go:711","msg":"Failed to set some node status fields","node":{"name":"talos-87e-522"},"err":"failed to validate nodeIP: node IP: \"10.224.224.138\" not found in the host's network interfaces"}
10.224.239.100: {"ts":1714669273803.889,"caller":"kubelet/kubelet_node_status.go:711","msg":"Failed to set some node status fields","node":{"name":"talos-87e-522"},"err":"failed to validate nodeIP: node IP: \"10.224.224.138\" not found in the host's network interfaces"}
10.224.239.100: {"ts":1714669273804.461,"caller":"kubelet/kubelet_node_status.go:73","msg":"Attempting to register node","v":0,"node":{"name":"talos-87e-522"}}
10.224.239.100: {"ts":1714669273805.1465,"caller":"kubelet/kubelet_node_status.go:96","msg":"Unable to register node with API server","node":{"name":"talos-87e-522"},"err":"Post \"https://127.0.0.1:7445/api/v1/nodes\": EOF"}
I think kubelet is trying to get my old ip address, which i changed already, because i need static ip. Is it possible to resolve it?
