### ISSUE TITLE
Probelm with HP dl360 g7,g8,g9

### ISSUE THREAD

**Issue by cybercoder** [siderolabs/talos#8695]
## Bug Report
Talos metal amd64 iso, keyboard freezes after boot (No F2, F3), and the DHCP client doesn't work.

### Description
We have mounted the ```metal-amd-64``` iso file, both 1.6,1.7, and also 1.7.1 on 3 HP servers using iLO.
But we have no keyboard and also Nics won't get IP address.
### Environment
- Platform: HP proliant dl360

**Comment by smira** [comment]
Not exactly clear, but you can try removing `console=` args before the boot.

**Comment by cybercoder** [comment]
> Not exactly clear, but you can try removing `console=` args before the boot.

had no success. Also, I've configured:
```
console=ttyS0,115200n8 console=tty0
```
And doesn't work. 
Talos 1.5.3 will get IP via DHCP but Talos 1.7.0 not.

**Comment by cybercoder** [comment]
I have tried to upgrade from 1.5.3 to 1.7.5 too. ( 1.5.3 get IP address from DHCP but 1.6 and upper not )
After upgrade there's no IP address:

![Screen Shot 1403-04-14 at 17 50 13](https://github.com/siderolabs/talos/assets/437872/b2c8a84e-1f43-4328-80b4-963a3bf372d1)
It seems it doesn't detect the NIC.
