### ISSUE TITLE
kubelet can't change ip after reboot

### ISSUE THREAD

**Issue by Minivolk02** [siderolabs/talos#8714]
## Bug Report
Kubelet can't change ip after reboot after bootstrapping
### Description
1) I created a vm with dhcp address
2) I applied new configuration with new up address 
3) Kubelet send error based on previous ip
I read a kubelet config and its use 0.0.0.0 address, so that i think problem is that i can't change it. Even reboot kubelet and host is not working. Also i tried use nodeIP configuration changing througn talosctl edit mc
### Logs

`10.224.238.2: {"ts":1715089289928.7717,"caller":"kubelet/kubelet_node_status.go:701","msg":"Failed to set some node status fields","node":{"name":"duke-10-224-238-2"},"err":"failed to validate nodeIP: node IP: \"10.224.224.140\" not found in the host's network interfaces"}`

### Environment
Vagrant + libvirt
Kubelet config:
`address: 0.0.0.0
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 0s
    enabled: true
  x509:
    clientCAFile: /etc/kubernetes/pki/ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 0s
    cacheUnauthorizedTTL: 0s
cgroupRoot: /
clusterDNS:
- 10.96.0.10
clusterDomain: cluster.local
containerRuntimeEndpoint: unix:///run/containerd/containerd.sock
cpuManagerReconcilePeriod: 0s
evictionPressureTransitionPeriod: 0s
failSwapOn: false
featureGates:
  LocalStorageCapacityIsolationFSQuotaMonitoring: true
fileCheckFrequency: 0s
httpCheckFrequency: 0s
imageMaximumGCAge: 0s
imageMinimumGCAge: 0s
kind: KubeletConfiguration
kubeletCgroups: /podruntime/kubelet
logging:
  flushFrequency: 0
  format: json
  options:
    json:
      infoBufferSize: "0"
    text:
      infoBufferSize: "0"
  verbosity: 0
memorySwap: {}
nodeStatusReportFrequency: 0s
nodeStatusUpdateFrequency: 0s
oomScoreAdj: -450
port: 10250
protectKernelDefaults: true
resolvConf: /system/resolved/resolv.conf
rotateCertificates: true
runtimeRequestTimeout: 0s
serializeImagePulls: false
shutdownGracePeriod: 30s
shutdownGracePeriodCriticalPods: 10s
staticPodPath: /etc/kubernetes/manifests
staticPodURL: http://127.0.0.1:36407
streamingConnectionIdleTimeout: 5m0s
syncFrequency: 0s
systemCgroups: /system
systemReserved:
  cpu: 50m
  ephemeral-storage: 256Mi
  memory: 192Mi
  pid: "100"
tlsMinVersion: VersionTLS13
volumeStatsAggPeriod: 0s`

- Talos version: 
Client:
	Tag:         v1.7.0
	SHA:         70fb41ff
	Built:
	Go version:  go1.22.2
	OS/Arch:     linux/amd64
Server:
	NODE:        10.224.238.2
	Tag:         v1.7.0
	SHA:         70fb41ff
	Built:
	Go version:  go1.22.2
	OS/Arch:     linux/amd64
	Enabled:     RBAC
- Kubernetes version: Client Version: v1.30.0
- Platform:
libvirt 10.0.0

**Comment by smira** [comment]
Node IP is not specified in the kubelet config.

`talosctl get nodeip -o yaml` to see the IP picked by Talos.

If the kubelet `--node-ip` is overridden manually in the machine config, it's completely on you.

Make sure you're not hitting https://www.talos.dev/v1.7/introduction/troubleshooting/#conflict-on-kubernetes-and-host-subnets

**Comment by Minivolk02** [comment]
no, i am not hitting. My subnet is 10.224.224.0/20

**Comment by smira** [comment]
From your ticket it's unclear what you're doing and what goes exactly wrong.

It's possible to set the node IP.

**Comment by Minivolk02** [comment]
So how can i set node IP for kubelet? I mean about --node-ip setting

**Comment by smira** [comment]
Please see [documentation](https://www.talos.dev/v1.7/reference/configuration/v1alpha1/config/#Config.machine.kubelet), you're looking for `extraArgs`. 

But I think your issue is something else, as Talos should set the nodeIP automatically.

**Comment by Minivolk02** [comment]
Yes, you are right, extraArg helped me. This issue works when i change my ip address. After creating vm, dhcp server that i have not connection assign the ip address that i don't need, thats why i need to change manually it in machineconfig so that kubelet can't start
