### ISSUE TITLE
[Feature] Automatically add well-known labels on controlplane nodes (node.kubernetes.io/exclude-from-external-load-balancers)

### ISSUE THREAD

**Issue by donch** [siderolabs/talos#8749]
## Feature Request

It would be beneficial for Talos to automatically add the label 'node.kubernetes.io/exclude-from-external-load-balancers="")' to control plane nodes during the cluster creation process.

### Description

In certain environments, such as OpenStack, when creating a load balancer, all cluster nodes are added as backends. By default, it would be preferable for control plane nodes to have this label to be excluded from load balancers.

Some documentation : https://github.com/kubernetes/kubeadm/issues/2375
https://kubernetes.io/docs/reference/labels-annotations-taints/#node-kubernetes-io-exclude-from-external-load-balancers

**Comment by smira** [comment]
When translated to Talos, we can add an option for machine config 1.8+ to add this label to the default machine config `nodeLabels`, this will do the trick, and preserve backwards compatibility.

**Comment by donch** [comment]
Yes perfect 👍 , for now, i manually add the label to` .machine.nodeLabels`
