### ISSUE TITLE
Bare-metal nodes not rebooting properly in Talos 1.7.0+

### ISSUE THREAD

**Issue by jdmcmahan** [siderolabs/talos#8751]
## Bug Report

Bare-metal nodes don't seem to be rebooting properly in Talos 1.7.0+.

### Description

I have a 6-node cluster running on bare-metal nodes (Dell OptiPlex 7060 Micros) managed by Sidero Omni. Since upgrading to Talos 1.7.0, I have had an issue with nodes not coming back up after a reboot.

When running `talosctl reboot` or otherwise triggering a reboot, the node returns to the dashboard but does not regain network connectivity. I have also noticed that the node does not appear to "fully" reboot based on the display output. In other words, the POST, PXE, and `dmesg` screens are never displayed, only a brief black screen before returning to the dashboard. The only way to recover the node (since it is inaccessible to the network) is to forcibly shut it down via the power button. This means I am unable to perform upgrades or certain configuration changes without physically being present at the cluster.

After some troubleshooting, I found that the kernel parameters are different between 1.6.7 and 1.7.0 (according to `talosctl dmesg`):

1.6.7: `BOOT_IMAGE=/B/vmlinuz talos.platform=metal talos.config=none console=ttyS0 console=tty0 init_on_alloc=1 slab_nomerge pti=on consoleblank=0 nvme_core.io_timeout=4294967295 printk.devkmsg=on ima_template=ima-ng ima_appraise=fix ima_hash=sha512 reboot=k siderolink.api=https://my.siderolink.omni.siderolabs.io?jointoken=blah talos.events.sink=[blah::1]:8090 talos.logging.kernel=tcp://[blah::1]:8092`

1.7.0: `BOOT_IMAGE=/A/vmlinuz talos.platform=metal talos.config=none console=ttyS0 console=tty0 init_on_alloc=1 slab_nomerge pti=on consoleblank=0 nvme_core.io_timeout=4294967295 printk.devkmsg=on ima_template=ima-ng ima_appraise=fix ima_hash=sha512 siderolink.api=https://my.siderolink.omni.siderolabs.io?jointoken=blah talos.events.sink=[blah::1]:8090 talos.logging.kernel=tcp://[blah::1]:8092`

Note that the 1.7.0 parameters don't include the `reboot=k` parameter which seems to indicate a kernel configuration change between 1.6.x and 1.7.x.

Unfortunately, I have not been able to track down how this is set in the source code to find a relevant issue/PR. Is there a reason this parameter was removed? Any workarounds?

Thanks in advance!

### Logs

1.6.7: `BOOT_IMAGE=/B/vmlinuz talos.platform=metal talos.config=none console=ttyS0 console=tty0 init_on_alloc=1 slab_nomerge pti=on consoleblank=0 nvme_core.io_timeout=4294967295 printk.devkmsg=on ima_template=ima-ng ima_appraise=fix ima_hash=sha512 reboot=k siderolink.api=https://my.siderolink.omni.siderolabs.io?jointoken=blah talos.events.sink=[blah::1]:8090 talos.logging.kernel=tcp://[blah::1]:8092`

1.7.0: `BOOT_IMAGE=/A/vmlinuz talos.platform=metal talos.config=none console=ttyS0 console=tty0 init_on_alloc=1 slab_nomerge pti=on consoleblank=0 nvme_core.io_timeout=4294967295 printk.devkmsg=on ima_template=ima-ng ima_appraise=fix ima_hash=sha512 siderolink.api=https://my.siderolink.omni.siderolabs.io?jointoken=blah talos.events.sink=[blah::1]:8090 talos.logging.kernel=tcp://[blah::1]:8092`

### Environment

- Talos version: 1.7.0, 1.7.1
- Kubernetes version: 1.29.4, 1.29.5, 1.30.0, 1.30.1
- Platform: metal

**Comment by jdmcmahan** [comment]
`reboot=k` was just a guess based on the behavior and the differences I was seeing between versions.

I can easily reproduce the issue by changing only the `talos.version` in my Omni cluster template, so it shouldn't be an issue of overriding the machine configuration.

**Comment by smira** [comment]
Many things happen on upgrade, so if the reboot issue is missing `reboot=k`, you can add it to `machine.install.extraKernelArgs` and perform another upgrade to test if that fixes it for your hardware.

Also it might be that your hardware is incompatible with `kexec`, but kernel logs would show it better. 
If that's the case, you can simply add [kernel.kexec_load_disabled=0](https://sysctl-explorer.net/kernel/kexec_load_disabled/) as a config patch to the Talos machine (applies immediately), but I doubt it's an issue here, as 1.6 and 1.7 behave the same.

**Comment by jdmcmahan** [comment]
Unfortunately, patching the machine config with `reboot=k` under `machine.install.extraKernelArgs` (and performing an upgrade) didn't seem to help the issue. I did confirm the `reboot=k` kernel parameter appears to be set at boot now:

```
Kernel command line: talos.platform=metal talos.config=none console=ttyS0 console=tty0 init_on_alloc=1 slab_nomerge pti=on consoleblank=0 nvme_core.io_timeout=4294967295 printk.devkmsg=on ima_template=ima-ng ima_appraise=fix ima_hash=sha512 reboot=k siderolink.api=https://my.siderolink.omni.siderolabs.io?jointoken=blah talos.events.sink=[blah]:8090 talos.logging.kernel=tcp://[blah]:8092
```

and upon restarting the node:

```
[talos] stopped container kube-system/kube-flannel-txzw6:install-config
[talos] service[cri](Stopping): Sending SIGTERM to Process(["/bin/containerd" "--address" "/run/containerd/containerd.sock" "--config" "/etc/cri/containerd.toml"])
[talos] phase unmountUser (4/10): done, 202.366576ms
[talos] task unmountPodMounts (2/2): unmounting /var/run/netns/cni-619d1d12-9104-7d2d-c773-89c6efa3d5d4
[talos] task unmountPodMounts (2/2): done, 657.431106ms
[talos] task unmountOverlayFilesystems (1/2): done, 733.266456ms
[talos] phase umount (5/10): done, 818.226255ms
[talos] phase unmountBind (6/10): 1 tasks(s)
[talos] task unmountSystemDiskBindMounts (1/1): starting
[talos] task unmountSystemDiskBindMounts (1/1): unmounting /system/state
XFS (sda5): Unmounting Filesystem c0a2a68d-233c-43c3-8251-baa1f3af65f7
[talos] task unmountSystemDiskBindMounts (1/1): unmounting /var
XFS (sda6): Unmounting Filesystem 9cd44b72-f84c-44be-ad9e-a897e89f5e42
[talos] task unmountSystemDiskBindMounts (1/1): done, 676.23181ms
[talos] phase unmountBind (6/10): done, 762.242324ms
[talos] phase unmountSystem (7/10): 2 tasks(s)
[talos] task unmountStatePartition (2/2): starting
[talos] task unmountEphemeralPartition (1/2): starting
[talos] task unmountStatePartition (2/2): done, 159.847Âµs
[talos] task unmountEphemeralPartition (1/2): done, 140.132Âµs
[talos] phase unmountSystem (7/10): done, 289.367137ms
[talos] phase kexec (8/10): 1 tasks(s)
[talos] task kexecPrepare (1/1): starting
XFS (sda3): Mounting V5 Filesystem b9faf9d5-f9b6-4eb4-af2f-77a78bfd9e00
XFS (sda3): Ending clean mount
PEFILE: Unsigned PE binary
[talos] prepared kexec environment kernel="/boot/A/vmlinuz" initrd="/boot/A/initramfs.xz" cmdline="talos.platform=metal talos.config=none console=ttyS0 console=tty0 init_on_alloc=1 slab_nomerge pti=on consoleblank=0 nvme_core.io_timeout=4294967295 printk.devkmsg=on ima_template=ima-ng ima_appraise=fix ima_hash=sha512 reboot=k siderolink.api=https://my.siderolink.omni.siderolabs.io?jointoken=blah talos.events.sink=[blah]:8090 talos.logging.kernel=tcp://[blah]:8092"
XFS (sda3): Unmounting Filesystem b9faf9d5-f9b6-4eb4-af2f-77a78bfd9e00
[talos] task kexecPrepare (1/1): done, 2.268257757s
[talos] phase kexec (8/10): done, 2.339650589s
[talos] phase stopEverything (9/10): 1 tasks(s)
[talos] task stopAllServices (1/1): starting
[talos] service[dashboard](Stopping): Sending SIGTERM to Process(["/sbin/dashboard"])
[talos] service[apid](Stopping): Sending SIGTERM to task apid (PID 2387, container apid)
[talos] service[syslogd](Finished): Service finished successfully
[talos] service[dashboard](Finished): Service finished successfully
[talos] service[machined](Finished): Service finished successfully
[talos] service[apid](Stopping): Sending SIGKILL to task apid (PID 2387, container apid)
[talos] service[apid](Finished): Service finished successfully
[talos] service[containerd](Stopping): Sending SIGTERM to Process(["/bin/containerd" "--address" "/system/run/containerd/containerd.sock" "--state" "/system/run/containerd" "--root" "/system/var/lib/containerd"])
[talos] service[containerd](Finished): Service finished successfully
[talos] task stopAllServices (1/1): done, 11.010217543s
[talos] phase stopEverything (9/10): done, 11.085931286s
[talos] phase reboot (10/10): 1 tasks(s)
[talos] task reboot (1/1): starting
```

I'm actually not sure how to set `kernel.kexec_load_disabled` as a config patch since the [only documented child of `kernel` is `modules`](https://www.talos.dev/v1.7/reference/configuration/v1alpha1/config/#Config.machine.kernel). Should this be another kernel argument?

Also, should it be `kernel.kexec_load_disabled=1` instead since the page in your link defines `0` as the default?

I'm also happy to provide kernel logs if there's something in particular you're looking for.

**Comment by smira** [comment]
Well, I'm a bit lost now. 

1. Talos 1.6 never had `reboot=k`, but somehow it is in your boot cmdline.
2. Talos 1.6/1.7 have no changes in the way they perform the reboot.
3. If the machine doesn't reboot, it might be a lot of multiple reasons, which are hard to diagnose, and most probably need access to console to see what exactly is going on.
4. Disabling kexec is done with a config patch like:

```yaml
machine:
  sysctls:
    kernel.kexec_load_disabled: "1"
```  

After that patch is appiled, next reboot will alreay happen without kexec.

**Comment by jdmcmahan** [comment]
To be fair, I am also at a loss. I had already stumped a few people in the Slack channel before coming here.

Perhaps the kernel configuration was a red herring because the node still isn't rebooting with kexec disabled... which makes sense if nothing changed between 1.6.x and 1.7.x:

```
[talos] phase kexec (8/10): 1 tasks(s)
[talos] task kexecPrepare (1/1): starting
XFS (sda3): Mounting V5 Filesystem b9faf9d5-f9b6-4eb4-af2f-77a78bfd9e00
XFS (sda3): Ending clean mount
[talos] kexec support is disabled via sysctl
XFS (sda3): Unmounting Filesystem b9faf9d5-f9b6-4eb4-af2f-77a78bfd9e00
[talos] task kexecPrepare (1/1): done, 456.714934ms
[talos] phase kexec (8/10): done, 528.059816ms
[talos] phase stopEverything (9/10): 1 tasks(s)
[talos] task stopAllServices (1/1): starting
[talos] service[dashboard](Stopping): Sending SIGTERM to Process(["/sbin/dashboard"])
[talos] service[apid](Stopping): Sending SIGTERM to task apid (PID 2382, container apid)
[talos] service[syslogd](Finished): Service finished successfully
[talos] service[dashboard](Finished): Service finished successfully
[talos] service[machined](Finished): Service finished successfully
[talos] service[apid](Stopping): Sending SIGKILL to task apid (PID 2382, container apid)
[talos] service[apid](Finished): Service finished successfully
[talos] service[containerd](Stopping): Sending SIGTERM to Process(["/bin/containerd" "--address" "/system/run/containerd/containerd.sock" "--state" "/system/run/containerd" "--root" "/system/var/lib/containerd"])
[talos] service[containerd](Finished): Service finished successfully
[talos] task stopAllServices (1/1): done, 11.008350062s
[talos] phase stopEverything (9/10): done, 11.084047254s
[talos] phase reboot (10/10): 1 tasks(s)
[talos] task reboot (1/1): starting
```

**Comment by jdmcmahan** [comment]
FWIW the overall configuration of the cluster and machines is pretty straightforward https://github.com/jdmcmahan/home-ops/blob/main/infrastructure/sidero/omni/resources/cluster/vriska.yaml

**Comment by steverfrancis** [comment]
Could this be https://github.com/siderolabs/talos/issues/8743 ?

**Comment by jdmcmahan** [comment]
I'm not seeing the same output as mentioned in that issue but worth a shot!

**Comment by smira** [comment]
can you capture the serial console logs in full, starting before reboot and up to whatever?

or video console logs? you can also try to [disable Talos dashboard](https://www.talos.dev/v1.7/reference/kernel/#talosdashboarddisabled) to make sure only kernel logs are visible. 

we need to see what is going on, otherwise it's impossible to debug

**Comment by jdmcmahan** [comment]
Apologies for the potato video. I'm hoping to get a PiKVM sometime soon to help with this kind of thing.

This video shows the entire issue from start to finish:

1. Start with a healthy, running node.
2. Reboot the node. I'm using Omni's reboot button here but the behavior is the same for upgrades, `talosctl reboot`, etc.
3. The node appears to gracefully shut down its services and reboot.
4. Lengthy black screen.
5. Talos logs start to appear.
6. Endless `network unreachable` errors attempting to synchronize the time. With the dashboard enabled, the `CONNECTIVITY` shows as `FAILED` and the `IP` and `GATEWAY` are blank. The node never becomes `HEALTHY` from this point on (I've had to leave it for multiple days while traveling).
7. Perform a hard reset on the node by holding the power button.
8. The node POSTs and otherwise follows the typical series of outputs for a cold boot.
9. After some delay, the node becomes `HEALTHY`.

https://photos.app.goo.gl/DotwY2HuPCa4qKMH8

Some other random things I've tried:

- Manually configuring the network from the dashboard (`F3`) while the node is in its `network unreachable` state. This has limited success with the time synchronization errors but does not seem to fully recover the network.
- Disabling time synchronization via `machine.time.disabled: true`. Same result as above.
- Setting `efi=no_disable_early_pci_dma` and removing all `console` parameters per #8743. This did not seem to help, although I did verify my settings were being applied via grub.
- Upgrading to 1.7.2 per #8743 and #8711 - no luck.

One other thing I've noticed is that the `talos.dashboard.disabled` parameter has never gone away since setting it via Omni cluster template for the video. I have resynced the template without that parameter and undergone several Talos upgrades, but it is still showing up in grub and the `prepared kexec environment` logs. I'm not sure if this is even related but it does seem like something weird is going on with the kernel parameters.

Thanks for all the suggestions so far. This cluster might actually be cursed.

**Comment by smira** [comment]
> Apologies for the potato video. I'm hoping to get a PiKVM sometime soon to help with this kind of thing.

Great video. 

I can see that Talos is doing `kexec`-based reboot (this is the default behavior). 99% of the time it works just fine, but it skips BIOS POST phase, and some hardware might fail with `kexec`, it feels like that might be the case for your hardware.

Easy test: reboot the machine via Talos (Omni), and reboot via whatever other method (even just power off/on).  If this first way leads to broken networking, and the second one works, it's `kexec` issue.

If that's the case, and easy way to disable is to apply the following machine configuration patch:

```yaml
machine:
  sysctls:
    kernel.kexec_load_disabled: "1"
```

With this patch, next reboot will happen without `kexec` (full BIOS boot).

**Comment by jdmcmahan** [comment]
Thanks again for all the insight. That does seem consistent with the behavior we're seeing.

Sadly, I have already tested the `kernel.kexec_load_disabled` trick [here](https://github.com/siderolabs/talos/issues/8751#issuecomment-2117918278) with no luck. I also know there was some doubt around what could've changed with kexec between 1.6.7 and 1.7.x.

That said, I can try again with the 1.7.2 release once I'm back from my work travels.

**Comment by rothgar** [comment]
I had a similar problem with an HP Z2 Mini G4 system. Any time the system would update/install and use kexec it would lose network.

I found a setting in the BIOS under Advanced -> Network Settings -> "Extended DHCP Timeout" which appeared to be causing the problem for me. After disabling that setting I haven't had the problem. I'm not sure what the Dell settings might have, but you may want to look for something similar.

From what I found in the HP documentation is this setting allows the BIOS to try and get an IP address from pre-boot (PXE) environments. I don't have PXE set up and when the system would kexec the BIOS wouldn't let the OS get an IP address.

**Comment by jdmcmahan** [comment]
> With this patch, next reboot will happen without `kexec` (full BIOS boot).

I'm not sure what changed, but my second attempt seems to have finally stuck. The machine now fully POSTs before booting into Talos and the network is able to reconnect on a reboot. AFAICT the only difference between attempts was the Talos version (1.7.2 vs 1.7.1) so I guess we can chalk it up to an upstream kernel fix.

> I found a setting in the BIOS under Advanced -> Network Settings -> "Extended DHCP Timeout" which appeared to be causing the problem for me. After disabling that setting I haven't had the problem. I'm not sure what the Dell settings might have, but you may want to look for something similar.

This seems like a much more elegant solution, but unfortunately I wasn't able to find a Dell counterpart to that setting. I did try to turn off PXE from the BIOS without any luck. Regardless, that was a pretty clever find on your part!

Thanks all for the help on this one! Hopefully disabling kexec continues to work for me.
