### ISSUE TITLE
UUID  ffffffffff-ffffffff-ffffff-ffffffff

### ISSUE THREAD

**Issue by runningman84** [siderolabs/talos#8804]
## Bug Report
I have three almost identical msi cubi mini pcs. For some reason talos is not able to create a unique id for the third node. It is 
 ffffffffff-ffffffff-ffffff-ffffffff
Is this a known bug? For which purpose is the UUID used?

### Logs
Which log would you need?

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`] 1.7.2
- Kubernetes version: [`kubectl version --short`] 1.30.1
- Platform: msi cubi

**Comment by smira** [comment]
UUID is used to identify the machine in a unique way. I guess you're trying to use it with Omni?

This is certainly a hardware/firmware bug, but if you plane to use it with omni, we have https://github.com/siderolabs/omni/issues/38 to provide a workaround.

**Comment by runningman84** [comment]
Okay I am not using Omni yet. Even if it is some bios bug isn’t there some fallback like hashing the MAC addresses of all network interfaces?

**Comment by smira** [comment]
If not using Omni, you probably don't need to worry about it.

It's usually a firmware bug, there is no workaround. Sometimes vendors offer upgrades with fixes.

**Comment by kenlasko** [comment]
If your mini PC is running American Megatrends (AMI) BIOS, you might be able to run a bootable USB program to randomize the UUID. 

If you look at my repository for Omni, you'll see a folder that contains the bits.

https://github.com/kenlasko/omni-public/
