### ISSUE TITLE
Does not boot due to GRUB out of memory

### ISSUE THREAD

**Issue by skystar-p** [siderolabs/talos#8813]
## Bug Report

I installed Talos linux to a bare metal node(amd64), with some system extensions. Installation goes successfully, but it does not boot with following message right after boot entry selection:

```
error: out of memory

Press any key to continue...
```

System memory is 128GB so it not seem to be out of DRAM, but other kind of memory.

After few minutes, linux is booted, but kernel panics due to `root` kernel parameter is not exists. Maybe this is kind of GRUB bug (https://bugs.launchpad.net/oem-priority/+bug/1842320) but I cannot update grub because this is not a normal linux distribution.

Can I upgrade grub only, or are ther some workaround of this issue?

### Environment

- Talos version: v1.6.7
- Kubernetes version: v1.29.3
- Platform: metal (amd64)

**Comment by smira** [comment]
Please try with latest Talos release (1.7.2), it has newer GRUB version.

**Comment by skystar-p** [comment]
I've tried v1.7.4, and issue is gone. Upgraded grub may resovled this issue. Thanks!
