### ISSUE TITLE
1.7.3: Time sync errors out with invalid argument

### ISSUE THREAD

**Issue by samip5** [siderolabs/talos#8828]
### Description

It seems that after tying to upgrade to 1.7.3, it's no longer able to sync time due to "invalid argument" even with the default NTP server aka Cloudflare. Possibly related is that there is no RTC on-board.

### Logs

![IMG_20240530_054041](https://github.com/siderolabs/talos/assets/1703002/74e49bfd-5528-450f-b235-47dd7c53c8d8)

### Environment

- Talos version: 1.7.3
- Platform: Raspberry Pi 4 (metal)

**Comment by beevik** [comment]
This was an overflow bug introduced by v1.4.2 of the `beevik/ntp` package. The new release ([v1.4.3](https://github.com/beevik/ntp/tree/v1.4.3)) fixes this bug.
