### ISSUE TITLE
FR: Allow listening on node IPs for talos API even if siderolink is used

### ISSUE THREAD

**Issue by samip5** [siderolabs/talos#8837]
### Description

Currently this comes with an issue that if Talos is unable to connect to the endpoint for siderolink for any reason, eg butchered CNI install that made havoc via ebpf, there should always be a way to connect to gather logs.

Related to: https://github.com/siderolabs/omni/issues/307

**Comment by smira** [comment]
This issue is not valid, as Talos in non-maintenance mode listens on all IPs available, so I will close this one, and the Omni issue is the one to keep the discussion.
