### ISSUE TITLE
Talos VM breaks energy saving on Intel / Proxmox

### ISSUE THREAD

**Issue by Skaronator** [siderolabs/talos#8848]
### Description

I'm currently transforming my homelab to a low-power setup. I noticed that running Talos Control Plane within a VM skyrocket the power consumption of the whole server. I did some A/B testing using just an Ubuntu VM, and it doesn't increase in power consumption, as you can see here:

![image](https://github.com/siderolabs/talos/assets/2886913/baac3227-7376-4cde-87fa-821ad9beed42)

This is a freshly installed system. Using latest Proxmox, latest Talos running just a single VM.

Ubuntu and Talos VM are identically configured:

- 2 Cores
- 4096 MB RAM
- CPU "host"
- 32 GB Storage

CPU Usage is pretty similar. Ubuntu at 1% and Talos at 2-3%.

Server Idle: ~ 15W
Ubuntu 24.04 Server VM: **~19W**
Talos ISO Boot: **~50W**
Talos bootstrapped as Control Plane (out of 3): **~50W**

### Environment

- Talos version: v1.7.4
- Kubernetes version: v1.30.1
- Platform: x86

**Comment by Skaronator** [comment]
I did another test using Debian 12 which has an older kernel (6.1). I did install gnome by mistake, so CPU usage is a bit higher at 4% (and higher than Talos VM) but power consumption is similar to Ubuntu 24.04 at **~20W**.

**Comment by DmitriyMV** [comment]
@Skaronator is there any additional info issue or we can close this?

**Comment by Skaronator** [comment]
Hi @DmitriyMV,

thanks for the response. Here is some additional information that I can provide:

Here is the talos configuration. It currently has only 3 Control Planes and VIP enabled: https://github.com/Skaronator/homelab-talos

The bare-metal machine was freshly installed using [Proxmox VE 8.2 ISO Installer](https://www.proxmox.com/de/downloads/proxmox-virtual-environment/iso/proxmox-ve-8-2-iso-installer).

The VM was started using the [Talos v1.7.4/metal-amd64.iso](https://github.com/siderolabs/talos/releases/download/v1.7.4/metal-amd64.iso) image with the configuration I already provided above:

- 2 Cores
- 4096 MB RAM
- CPU "host"
- 32 GB Storage

After the first startup, I joined the VM to my existing (but also fresh, empty) Talos cluster.

```bash
talosctl apply-config --insecure -n 192.168.1.47 --file out/final-cp-3.yaml
```

Hardware:

- i5 14600
- 64GB DDR4-3200
- ASUS Prime H770-Plus D4
- Intel X710-DA2
- Crucial MX500 1TN
- Samsung 990 Pro 4TB

Logs are probably not that helpful because there are no errors. (Would be weird on a fresh vanilla setup)

![image](https://github.com/siderolabs/talos/assets/2886913/028e5a6c-c2cb-47de-aaff-3c1fc281d31b)

![image](https://github.com/siderolabs/talos/assets/2886913/e86e7615-a4bd-4ab2-a95e-0bc2504d2dfa)
(I did a couple of reboots, that why it spiked a few times)

**Comment by rothgar** [comment]
Can you try upgrading to an image that has the Intel firmware and ucode extensions from factory.talos.dev and let us know if the power consumption goes down

**Comment by Skaronator** [comment]
@rothgar thanks for suggesting the additional intel firmware extensions, totally forgot them.

Using these options:

```yaml
customization:
    systemExtensions:
        officialExtensions:
            - siderolabs/i915-ucode
            - siderolabs/intel-ice-firmware
            - siderolabs/intel-ucode
```

(as well as setting this option on the host `cpupower frequency-set --governor powersave`) fixes it!

**Comment by rothgar** [comment]
Glad it worked for you. Can you share what you're using to measure the power usage? I really like that dashboard and might look into something similar.

I'm also curious if Talos is less than the Ubuntu VM in your environment. I have been wanting to test this on bare metal to compare if the defaults on different OSs affect power consumption in any meaningful way.

**Comment by Skaronator** [comment]
I use [Shelly Plus Plug S](https://www.shelly.com/de/products/shop/shelly-plus-plug-s-1) to measure directly from the wall. The dashboard is [Home Assistant](https://www.home-assistant.io/). It's not as good as Prometheus with Grafana, but does plenty of other things well :)
