### ISSUE TITLE
Unable to upgrade to kubernetes v1.3 on talos 1.7.4 

### ISSUE THREAD

**Issue by danielheimburg** [siderolabs/talos#8849]
## Bug Report
Unable to upgrade to kubernetes v1.3 on talos 1.7.4 
### Description
I'm unable to upgrade to any k8s 1.3 version from 1.2 through the upgrade-k8s function. All I get is unsupported upgrade path? Is this not supported yet? The manual seems to indicate it is, https://www.talos.dev/v1.7/kubernetes-guides/upgrading-kubernetes/
### Logs
talosctl --nodes 10.13.10.21 upgrade-k8s --to 1.3.1 --dry-run
automatically detected the lowest Kubernetes version 1.29.5
unsupported upgrade path 1.29->1.3 (from "1.29.5" to "1.3.1")

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Client:
	Tag:         v1.7.4
	SHA:         cb3a8308
	Built:
	Go version:  go1.22.3
	OS/Arch:     darwin/arm64
Server:
	NODE:        10.13.21.24
	Tag:         v1.7.4
	SHA:         cb3a8308
	Built:
	Go version:  go1.22.3
	OS/Arch:     linux/amd64
	Enabled:     RBAC
	NODE:        10.13.21.21
	Tag:         v1.7.4
	SHA:         cb3a8308
	Built:
	Go version:  go1.22.3
	OS/Arch:     linux/amd64
	Enabled:     RBAC
	NODE:        10.13.21.22
	Tag:         v1.7.4
	SHA:         cb3a8308
	Built:
	Go version:  go1.22.3
	OS/Arch:     linux/amd64
	Enabled:     RBAC
- Kubernetes version: [`kubectl version --short`]
- Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.5
- Platform:
Talos 1.7.3 on Proxmox

**Comment by MindTooth** [comment]
Do you mean `talosctl --nodes 10.13.10.21 upgrade-k8s --to 1.30.1 --dry-run`? 

1.3 is 27 versions lower than 1.30.
