### ISSUE TITLE
Hetzner Install (controlplane.yaml) don't work

### ISSUE THREAD

**Issue by remotejob** [siderolabs/talos#8850]
## Bug Report
ref: https://www.talos.dev/v1.7/talos-guides/install/talosctl/

### Description

Hetzner ENV 
Install completely based on https://www.talos.dev/v1.7/talos-guides/install/talosctl/

` hcloud server create --name talos-control-plane-1 --image ${IMAGE_ID} --type cx21 --location hel1 --label 'type=controlplane' --user-data-from-file controlplane.yaml`

### Logs
hcloud: invalid input in field 'user_data' (invalid_input)

### Environment

- Talos version: v1.7.4
- Kubernetes version: v1.28.2
- Platform: x86

**Comment by smira** [comment]
Please submit a PR updating the documentation if it's outdated. 

Hetzner is a [community-supported platform](https://www.talos.dev/v1.7/introduction/support-matrix/#tier-3).

**Comment by mgcth** [comment]
This is related to the 32KB limit for the user field, see https://docs.hetzner.cloud/#servers-create-a-server. My `controlplane.yaml` file was 33 KB.

Removing some comments in the `controlplane.yaml` file solves it.

**Comment by remotejob** [comment]
Yes! Great! Thanks, it resolves issue!
