### ISSUE TITLE
Air-gapped installation without DNS

### ISSUE THREAD

**Issue by trevex** [siderolabs/talos#8859]
### Description

Currently domains of registries need to be resolvable for mirrors to work. For an air-gapped installation following https://www.talos.dev/v1.7/advanced/air-gapped/  the following records need to exist: `docker.io`, `ghcr.io`, `gcr.io` and `registry.k8s.io`.

When bootstrapping from zero it would be great if the failover to mirrors works without any DNS records as the referenced registry might be a registry that will exist within the bootstrapped Kubernetes cluster itself.
Currently when the domain is not resolvable the installation will fail and reboot the machine. This behavior surprised me and is at least not well documented.

**Comment by smira** [comment]
If you use registry mirrors, the domains don't need to be resolvable.

If that's not the case, please open a specific bug report.

**Comment by trevex** [comment]
Okay, let me reproduce this in a VM based setup as the air-gapped HW I tested on is not easily accessible.

**Comment by trevex** [comment]
I don't know how I encountered this behaviour. I am not able to reproduce it in a VM based setup.
This must have been an issue on my end.

For completeness the code used to test the air-gapped installations with libvirt is here: https://github.com/trevex/bootstrap-from-zero
