### ISSUE TITLE
Kubernetes 1.31 update

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#8911]
See https://github.com/kubernetes/kubernetes/releases/tag/v1.31.0-alpha.1

1. Update siderolabs/go-kubernetes for 1.31, add new deprecations (interesting case is CSI in-tree removal).
2. Update kubelet
3. Update Talos

**Comment by frezbo** [comment]
also make sure to handle the upgrade path for 1.31 -> 1.31, we usually forget that :sweat_smile:
