### ISSUE TITLE
Mount debugfs filesystem

### ISSUE THREAD

**Issue by alexandrem** [siderolabs/talos#8916]
## Feature Request

Mount debugfs at the standard `/sys/kernel/debug` mount point automatically.

### Description

Similar to https://github.com/siderolabs/pkgs/issues/963 and the associated change https://github.com/smira/talos/commit/10e555ae6ad9b0bc782b4fc28f9691e20baa51e4 that got introduced in v1.7.3, I think it would be useful to have debugfs automatically mounted.

We have some older application that depends on that for the tracing (it may be updated to tracefs soon, but no ETA).

This currently requires adding some privileged daemonset or initContainer to do the mounting automatically as a workaround.

I don't think there's any downside to enable this by default in Talos Linux.

**Comment by smira** [comment]
`debugfs` is not considered to be secure nowadays according to the best practices, and there are better solutions, so it won't be enabled in Talos Linux.
