### ISSUE TITLE
Failed to get disk map: open /sys/block/nvme1c1n1/dev

### ISSUE THREAD

**Issue by Rammurthy5** [siderolabs/talos#8924]
## Bug Report
Nodes move to NotReady state 

### Description
Nodes which were in Ready state moves to NotReady state 

### Logs
{"ts":1718772785058.5205,"caller":"machine/info.go:104","msg":"Failed to get disk map: open /sys/block/nvme1c1n1/dev: no such file or directory\n"}

### Environment

- Talos version: 1.7.2
- Kubernetes version: 1.28.3
- Platform: AWS EC2

**Comment by smira** [comment]
Is this a `kubelet` error? If it is, it's not Talos Linux exactly. (you might want to disable NVMe multipath in Linux kernel args to get rid of these devices).
