### ISSUE TITLE
Part of a hostname after period is omitted

### ISSUE THREAD

**Issue by abcdegorov** [siderolabs/talos#8934]
### Description
When setting up a machine with the `foo.bar` hostname (whether specified in `machine.network.hostname` or passed otherwise), Talos strips the part after the period and the machine is left with the `foo` hostname which can cause problems in some environments. Machines should be set up with their full names as specified.

### Environment

- Talos version: `1.7.4`
- Kubernetes version: `1.27.2`
- Platform: Hetzner virtual machine

**Comment by rothgar** [comment]
Characters after the . are part of the domain and not hostname. Valid hostname characters do not include `.` 

Where are you seeing this behavior? I'm assuming this is running Talos in AWS which requires the fully qualified  domain when the kubelet registers with the API.

If that is the case you should use the configuration
```
machine:
  kubelet:
    registerWithFQDN: true
```
Let us know if that fixes your problem

**Comment by abcdegorov** [comment]
Hi @rothgar, this is happening in a Hetzner Cloud virtual machine as I've specified in the original post. The config I'm applying already has the `registerWithFQDN: true` option, but it does not change a thing.

I may have found the cause of the issue though - I assume the `hcloud` version of the Talos image has some Hetzner-specific tricks up its' sleeve, such as querying their metadata [API](https://docs.hetzner.cloud/#server-metadata) endpoint. I've checked the `hostname` endpoint and it returns only the `foo` portion of the hostname, even if the machine itself has the `foo.bar` name in the Hetzner Cloud console.

**Comment by smira** [comment]
So if you specify the hostname manually with `machine.network.hostname`, it overrides the whatever platform says. 

And @rothgar advice on `registerWithFQDN` is exactly right if you want to use hostname + domain name as the Kubernetes Node name (you might need to do it before the node initial start up to make it correctly create the `Node` resource in the first place).
