### ISSUE TITLE
Bridge vlan_filtering support

### ISSUE THREAD

**Issue by e3b0c442** [siderolabs/talos#8941]
## Feature Request
Add ability to configure VLAN filtering on a host bridge interface.

### Description
I'm trying to use KubeVirt on my Talos cluster, in a setup that has certain workload types separated by VLAN. Prior to Talos, this would be accomplished by setting the `vlan_filtering` field on a host bridge, and then using the `vlan` field with the `bridge` CNI in a multus `NetworkAttachmentDefinition` to allow the bridge to handle the VLAN filtering. However, Talos does not currently allow me to affect this configuration.

There are two unergonomic workarounds to the situation (outside of using an external CNI plugin):
* create a privileged pod with host networking to create and configure the bridge on each node
* create and maintain VLAN interfaces off the bridge for each VLAN, then have multus create its own bridges off of these vlan interfaces

Ideally this would be a parameter in `MachineConfig.network`.

Thanks!

**Comment by stijoh** [comment]
Second this!!
