### ISSUE TITLE
join windows node

### ISSUE THREAD

**Issue by FalkWinkler** [siderolabs/talos#8943]
## Feature Request
Join a Windows Worker Node to Talos
### Description

We use Kubernetes with Talos as the OS. At the moment it does not run part of our software only with Windows and we therefore need to add a Windows node.

Is there already a way to do this or can you make it possible?

**Comment by stereobutter** [comment]
Is using a Windows VM inside KubeVirt on a regular Talos node an option?

**Comment by smira** [comment]
See https://github.com/siderolabs/talos/issues/3990. 

Talos doesn't run on Windows, but you can use `kubeadm` to join a worker to an existing Talos Linux cluster.
