### ISSUE TITLE
New Kernel Module: uinput

### ISSUE THREAD

**Issue by jacaudi** [siderolabs/talos#8949]
### Description
Please consider adding the uinput kernel module to the precompiled module list. 

### Background

I am attempting to run a headless steam container on my Talos cluster, and everything works minus controller/keyboard/mouse input over Steam Play.

**Comment by judahrand** [comment]
@smira are the two PRs referenced what you had in mind?

**Comment by judahrand** [comment]
Whoops, probably shouldn't have used the 'closed' keyword... Only half of this is merged so this isn't currently closed!

**Comment by frezbo** [comment]
> Whoops, probably shouldn't have used the 'closed' keyword... Only half of this is merged so this isn't currently closed!

no worries, will get the extensions one merged too

**Comment by judahrand** [comment]
@jacaudi I hope this solves it for you! I'm planning on trying something similar with Sunshine and Moonlight soon.
