### ISSUE TITLE
Control Plane nodes become unhealthy after 1.7.0+ upgrades

### ISSUE THREAD

**Issue by UnknownBlunders** [siderolabs/talos#8952]
## Bug Report
Every upgrade since (and including) 1.7.0 my control plane nodes become unhealthy shortly after the upgrade and require a reboot.
### Description

I upgrade my nodes using the `talosctl upgrade` command. After running that command on a control plane node, the node will reboot into the new version and report healthy. I will then move on to the next node. Shortly after the upgrades, each of the control plane nodes become unhealthy after previously being healthy. This issue also occurs if I run `talosctl reset` and `talosctl apply-config` instead of using the `talosctl upgrade` command.

If I hard restart the node (by either pulling power or holding the power button) the problem goes away and won't return until the next upgrade. 

I've seen the kubelet, apiserver, controller-manager, and scheduler each report either healthy or unhealthy when this problem occurs. When this problem occurs, at least one will be unhealthy. There doesn't seem to be a consistent problem with any of them. In the screenshot below, it just happens to be the kubelet that reports as unhealthy.

I've been running these control plane nodes since Talos 1.5.1 and did not experience this issue on upgrades until 1.7.0. However, I did start using the `intel-ucode` extention from the image factory starting with 1.7.0. Before 1.7.0 I was just using the base `ghcr.io/siderolabs/installer` image.

[Here is a link to my talhelper formatted talosconfig.](https://github.com/UnknownBlunders/K8s/blob/main/talos/talconfig.yaml)

Attempting to collecting a support bundle from the effected nodes results in this error message:
`rpc error: code = DeadlineExceeded desc = error connecting to CRI: context deadline exceeded`

### Logs
![Screenshot from 2024-07-01 08-36-13](https://github.com/siderolabs/talos/assets/20568701/e945e4be-5612-44f6-bca3-eebc7eb5115c)

### Environment
- Talos version: 1.7.5 
- Kubernetes version: 1.30.1
- Platform: Metal

All control plane nodes are Intel N100 based mini PCs with 16GB of RAM.

**Comment by smira** [comment]
On your screenshot you have 82.5% of RAM being used, and 1.3GiB is well below [minimum requirements](https://www.talos.dev/v1.7/introduction/system-requirements/) for Talos Linux (most of that is actually Kubernetes/containers, not Talos itself).

**Comment by UnknownBlunders** [comment]
Low ram would explain it! Thanks @smira. Any Idea why Talos would only detect 1.3GiB when node actually has 15GiB? Talos properly detects the full 15GiB after I hard reboot it.

Here's that same node after a hard reboot. Note that the problem goes away after I reboot the node.
![image](https://github.com/siderolabs/talos/assets/20568701/3d5e6b74-5b5a-4052-9046-867a2b865d03)

**Comment by UnknownBlunders** [comment]
Perhaps I should open a new issue for the RAM not being detected?

**Comment by UnknownBlunders** [comment]
I'll give that a shot. Thanks!
