### ISSUE TITLE
Metal: API (50000) unavailable after some time, before etcd bootstrap

### ISSUE THREAD

**Issue by thoro** [siderolabs/talos#8954]
### Description

I have discovered that the api of nodes will go offline after around 20-30 minutes, the servers are still running, but the dashboard console application is shutdown.

Edit: I monitored the port availability:

Tue Jul  2 08:53:54 CEST 2024: 10.12.2.1 port 50000 closed.
Tue Jul  2 08:53:55 CEST 2024: 10.12.2.1 port 50000 open.
Tue Jul  2 10:03:56 CEST 2024: 10.12.2.1 port 50000 open.
Tue Jul  2 10:03:58 CEST 2024: 10.12.2.1 port 50000 closed.

### Logs

[support.zip](https://github.com/user-attachments/files/16063152/support.zip)

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`] 1.7.5
- Kubernetes version: [`kubectl version --short`] - not applicable, but 1.30 --
- Platform: metal, Dell R7615, EFI BIOS

**Comment by smira** [comment]
Talos has a timeout for node to become running, so it tries to reboot itself on timeout in case the reboot might fix the things, this is what you encounter here, it's not a bug.

**Comment by thoro** [comment]
Hi @smira 

the issue is not that it's rebooting, but that it does not reboot i.e seemingly stuck in the shutdown procedure!

**Comment by smira** [comment]
If it's stuck on reboot, please open an issue with details (kernel logs before being stuck).

**Comment by rothgar** [comment]
The fact that the API server goes down and the machine doesn't reboot is the problem we identified. Does `talosctl support` not grab any logs from the last reboot? I assumed it would keep some amount of logs around.

It's impossible to collect logs from the time the API server goes down and the system fails to reboot.
