### ISSUE TITLE
Unable to configure gateway using kernel parameters on metal platform

### ISSUE THREAD

**Issue by omniproc** [siderolabs/talos#8959]
### Description
When using a [ISO image ("metal platform")](https://www.talos.dev/v1.7/talos-guides/install/bare-metal-platforms/iso/) that has a static IP configured using [kernel parameters](https://www.talos.dev/v1.7/reference/kernel/#ip) the static network configuration is set (IP, hostname, netmask, DNS, NTP) _except_ for the network gateway, which is never configured. This seems only to occur when booting the ISO in a VMware vSphere environment.

Using the [VMware (OVA)](https://www.talos.dev/v1.7/talos-guides/install/virtualized-platforms/vmware/) platform with the same kernel parameters works as expected (all the network configuration is set _including_ the gateway).

### Logs

![talos-metal-gateway](https://github.com/siderolabs/talos/assets/2482535/edf6b777-d1f3-4ac6-8b78-cda722d64b5c)

### Environment

- Talos version: 1.7.4 (also reproduced in 1.7.1)
- Kubernetes version: n/a
- Platform: metal (ISO)
- VMware vSphere/ESXi: 8

**Comment by omniproc** [comment]
I'll try the VMware ISO. Regarding your remarks:

IP would be a.b.c.180/24 and gateway would be a.b.c.1/24, so it is within the same subnet. I'll double check that of course but as I said the exact same kernel args string is used with the OVA and works without any issues.

**Comment by smira** [comment]
Talos reconciles things, so this error might appear if the route is added before the address, but if there's a persistent error, it will be reported multiple times.

**Comment by omniproc** [comment]
That's what we have been thinking too. But we only saw it one time in the log. It seemed as if the controller is never re-trying to configure it. But I'll double check that too.

**Comment by smira** [comment]
Talos does retry such errors, so if you have an issue, please submit full kernel logs so we can look into that. 

If networking is up, please use `talosctl support` to gather diagnostics.

**Comment by omniproc** [comment]
So, I tested the things I promised to test:

- VMware specific iso works without issues
- the RouteSpecController error reported above doesn't repeat. Even after leaving the VM running for 10 hours I've not seen it reported a second time. I guess that could be the root problem with the "metal iso" on VMware (we've been speculating about a possible race condition internally).

**Comment by smira** [comment]
The error reported is temporary, and Talos retries always, so it can be ignored. 

So if there's a problem (like gateway is _not_ actually set up), let's dive into that; if it's a single message, the gateway was actually set up correctly.

**Comment by omniproc** [comment]
> the gateway was actually set up correctly.

Well in the dashboard after boot the gateway is not configured and thus no system outside of the current subnet can be reached. I might be able to provide a support bundle.
