### ISSUE TITLE
Hypver-V run metal iso failed to bootstrap control plane

### ISSUE THREAD

**Issue by wujun4code** [siderolabs/talos#8961]
### Description
I followed all the steps from https://www.talos.dev/v1.7/talos-guides/install/virtualized-platforms/hyper-v/
```
New-TalosVM -VMNamePrefix talos-cp -CPUCount 2 -StartupMemory 4GB -SwitchName wired-external -TalosISOPath C:\Users\Jun\Downloads\metal-amd64.iso -NumberOfVMs 1 -VMDestinationBasePath 'D:\VHD\Talos'
$CONTROL_PLANE_IP='192.168.6.120'
talosctl gen config talos-cluster  https://$($CONTROL_PLANE_IP):6443 --output-dir .
talosctl apply-config --insecure --nodes $CONTROL_PLANE_IP --file .\controlplane.yaml
```

### Logs
![image](https://github.com/siderolabs/talos/assets/5119542/eb148dae-ada7-413c-8629-a87d32e040c9)

### Environment
- Hypver-V 
- Windows 11
- Talos version
 ```
 talosctl version
Client:
        Tag:         v1.7.5
        SHA:         47731624
        Built:
        Go version:  go1.22.4
        OS/Arch:     windows/amd64
Server:
 ```

**Comment by smira** [comment]
Please follow steps to the very end of the document: https://www.talos.dev/v1.7/talos-guides/install/virtualized-platforms/hyper-v/#bootstrap-cluster

**Comment by wujun4code** [comment]
@smira  Thanks.
I did all the steps, but got this ->
![image](https://github.com/siderolabs/talos/assets/5119542/259b7119-363b-498b-b202-56dc1d2bd849)

and control plane is stuck at this state -> 
![image](https://github.com/siderolabs/talos/assets/5119542/6ac2d6cb-4cb2-4888-b335-b5298a71ef8d)

and workers failed to bootstrap either

![image](https://github.com/siderolabs/talos/assets/5119542/6d552562-82c9-4d39-b788-e7c35d869b79)

**Comment by smira** [comment]
The Hyper-V documentation is missing some steps, specifically this: https://www.talos.dev/v1.7/introduction/getting-started/#default-talosconfig-configuration-file

(I would recommend to read the whole getting started guide).

**Comment by wujun4code** [comment]
@smira Thanks so much, I fixed it.

```
New-TalosVM -VMNamePrefix talos-cp -CPUCount 2 -StartupMemory 4GB -SwitchName wired-external -TalosISOPath C:\Users\Jun\Downloads\metal-amd64.iso -NumberOfVMs 1 -VMDestinationBasePath 'D:\VHD\Talos'

New-TalosVM -VMNamePrefix talos-worker -CPUCount 4 -StartupMemory 8GB -SwitchName wired-external -TalosISOPath C:\Users\Jun\Downloads\metal-amd64.iso -NumberOfVMs 2 -VMDestinationBasePath 'D:\VHD\Talos' -StorageVHDSize 50GB


$CONTROL_PLANE_IP='192.168.6.145'

talosctl gen config talos-cluster  https://$($CONTROL_PLANE_IP):6443 --output-dir .

talosctl apply-config --insecure --nodes $CONTROL_PLANE_IP --file .\controlplane.yaml

talosctl apply-config --insecure --nodes 192.168.6.142 --file .\worker.yaml
talosctl apply-config --insecure --nodes 192.168.6.143 --file .\worker.yaml

talosctl bootstrap --nodes $CONTROL_PLANE_IP --endpoints $CONTROL_PLANE_IP --talosconfig=./talosconfig

talosctl kubeconfig --nodes $CONTROL_PLANE_IP --endpoints $CONTROL_PLANE_IP --talosconfig=./talosconfig
```
