### ISSUE TITLE
Orange PI 5 (RK3588S) Talos Support

### ISSUE THREAD

**Issue by imne** [siderolabs/talos#8968]
## Feature Request
Support for orange pi 5 devices
### Description
Hi I just wanted to check if talos support for orange pi 5 is in the pipeline for this year went though this closed thread not sure if there's been any new developments since https://github.com/siderolabs/talos/issues/7382

**Comment by si0ls** [comment]
Hi @imne 👋 

I try to maintain a port for the Orange Pi 5 here, it you wanna take a look:
https://github.com/si0ls/talos-orangepi5

**Comment by rothgar** [comment]
Thanks for the link. I just added it to the awesome talos repo

https://github.com/siderolabs/awesome-talos/tree/main
