### ISSUE TITLE
Extensions BOM

### ISSUE THREAD

**Issue by rotilho** [siderolabs/talos#8970]
## Feature Request

Each version of Talos includes a Bill of Materials (BOM) listing all extensions.

### Description

When an extension's version tag is not specified, Talos will default to using the version defined in the BOM. This approach simplifies both upgrades and testing, as Talos can be tested using the BOM-defined extension versions.

This change will maintain backward compatibility, since every extension currently requires a specified version.

**Comment by smira** [comment]
This is exactly how it works today: https://github.com/siderolabs/extensions

Not sure what this issue is about?

**Comment by rotilho** [comment]
Hey @smira! Sorry for the delay, I Just tried to upgrade without the version and the upgrade failed as you can see below.

```
 user: warning: [2024-07-04T18:51:56.424614128Z]:  failed to pull image "ghcr.io/siderolabs/util-linux-tools:latest": failed to resolve reference "ghcr.io/siderolabs/util-linux-tools:latest": ghcr.io/siderolabs/util-linux-tools:latest: not found                                                                        ```
 
 My configuration:
 
 ```
 resource "talos_machine_configuration_apply" "home_a" {
 ...
  config_patches = [
    yamlencode({
      machine = {
        install = {
          disk = "/dev/nvme0n1"
          wipe = true
          extensions = [
            {
              image = "ghcr.io/siderolabs/util-linux-tools"
            },
            {
              image = "ghcr.io/siderolabs/iscsi-tools"
            },
            {
              image = "ghcr.io/siderolabs/amd-ucode"
            },
            {
              image = "ghcr.io/siderolabs/amdgpu-firmware"
            },
            {
              image = "ghcr.io/siderolabs/gasket-driver"
            }
          ]
        }
        ...
  ]
}
 ```

**Comment by rotilho** [comment]
Hey @smira! Sorry for the delay. I just tried to upgrade without specifying the version, and the upgrade failed as you can see below.

```
 user: warning: [2024-07-04T18:51:56.424614128Z]:  failed to pull image "ghcr.io/siderolabs/util-linux-tools:latest": failed to resolve reference "ghcr.io/siderolabs/util-linux-tools:latest": ghcr.io/siderolabs/util-linux-tools:latest: not found                                                                        
```
 
 My configuration:
 
 ```
 resource "talos_machine_configuration_apply" "home_a" {
 ...
  config_patches = [
    yamlencode({
      machine = {
        install = {
          disk = "/dev/nvme0n1"
          wipe = true
          extensions = [
            {
              image = "ghcr.io/siderolabs/util-linux-tools"
            },
            {
              image = "ghcr.io/siderolabs/iscsi-tools"
            },
            {
              image = "ghcr.io/siderolabs/amd-ucode"
            },
            {
              image = "ghcr.io/siderolabs/amdgpu-firmware"
            },
            {
              image = "ghcr.io/siderolabs/gasket-driver"
            }
          ]
        }
        ...
  ]
}
 ```
 
I'm raising this issue because I tried to upgrade Talos to 1.7.5, but I forgot to update `gasket-driver`, causing the upgrade to fail. It would be great to not care about the extension version just the Talos.

**Comment by smira** [comment]
Talos already pins versions of extensions as I described above.

You seem to be using outdated/not supported method to install system extensions.

[Boot Assets](https://www.talos.dev/v1.7/talos-guides/install/boot-assets/) documentation has some guides for different ways to generate your install/upgrade assets.

But tl;dr the easiest way is to use [Image Factory](https://factory.talos.dev/) which does most of the work for you, and you just pick the extensions you would like to use.

**Comment by rotilho** [comment]
I totally missed that. Thanks @smira, it works like a charm.
