### ISSUE TITLE
`talosctl -n <ip> reset` On RaspberryPi Wipes Firmware

### ISSUE THREAD

**Issue by chr0n1x** [siderolabs/talos#8993]
## Bug Report

RPi4 Model B that was already running talosOS as a k8s-worker node fails to reboot/startup after a `talosctl reset`

### Description

I have my baremetal cluster running on a few RPi4s, model B.

While experimenting with things, I decided to `reset` one of the nodes before applying a new machine configuration.
The command run was:

```sh
talosctl -n <node IP> reset
```

### Logs

The command `exit 0`s on my main machine. The talos rpi worker however just seemingly goes into the rpi `poweroff` state. After unplugging the power and plugging it back in with a display, The RPi4 ModelB boot screen is present (instead of the uboot one) and there's a `Firmware not found` message.

### Environment

- Talos version: `1.7.5`
- Kubernetes version: `1.30.1`
- Platform: Raspberry Pi 4 model B. Host running `talosctl` is wsl2 ubuntu on win11 (if that matters)

**Comment by frezbo** [comment]
Yes a normal reset would wipe the whole disk, if you just want to reset back to maintenance use `--system-labels-to-wipe=STATE --system-labels-to-wipe=EPHEMERAL`
