### ISSUE TITLE
TPM Encryption does not fail if secureboot is not enabled

### ISSUE THREAD

**Issue by danacr** [siderolabs/talos#8995]
### Description
If the host machine has secureboot disabled, but the TPM available, Talos proceeds to install. There is no way to restrict the encryption. An attacker could boot an alternate OS and retrieve the encryption keys.

It would be great to have an additional config parameter in the tpm encryption requiring secure boot to be enabled, else disk encryption fails.

**Comment by steverfrancis** [comment]
An alternate OS could not retrieve the encryption keys from the TPM (an attacker modifying the firmware, or bootloader, or decryption tool (or analogues in e.g. an embedded device without a full OS) - whether directly, or by booting from a different boot device / program - will mean the PCRs don't have the same value and render the decryption key unavailable) - but the point of this ticket is to provide a configurable mechanism to ensure that SecureBoot is enabled whenever TPM encryption is enabled.

**Comment by runningman84** [comment]
But there is some other issue if for some reason secure boot was not enabled but the disk still got encrypted… if you notice the error and activate secure boot you cannot read the data afterwards anymore.

**Comment by steverfrancis** [comment]
From slack, goal is  a Talos configuration option in the config file that checks that SecureBoot is enabled, and if it is not, the system will do ... something

- fail to apply the config (and stay in maintenance mode)
- revert to maintenance mode
- boot loop
- or something else that makes it  evident that the system is "not healthy"
