### ISSUE TITLE
Support user-defined CA certs for the disk encryption KMS endpoint

### ISSUE THREAD

**Issue by michaelbeaumont** [siderolabs/talos#8996]
## Feature Request

Support user-defined CA certs for the disk encryption KMS endpoint

### Description

[We connect to the KMS endpoint using the default `tls.Config{}`](https://github.com/siderolabs/talos/blob/076f3c4f20006f732fa07ada14f45458dc65a9e8/internal/pkg/encryption/keys/kms.go#L133) but it's maybe common that the KMS endpoint will have its own CA. Should [`.kms`](https://www.talos.dev/v1.7/reference/configuration/v1alpha1/config/#Config.machine.systemDiskEncryption.state.keys..kms) have `.tls` similar to the [registry config](https://www.talos.dev/v1.7/reference/configuration/v1alpha1/config/#Config.machine.registries.config.-.tls)?

**Comment by smira** [comment]
No, it should be done via #8867 same way as any other outbound TLS communication.

**Comment by michaelbeaumont** [comment]
Wasn't aware that was coming in the next release
