### ISSUE TITLE
FR: Allow `talosctl dmesg` to be called with `--insecure` arg

### ISSUE THREAD

**Issue by samip5** [siderolabs/talos#9013]
### Description

There are times when the node is not going to be able to be installed onto, and to better grasp the problem, kernel logs could be useful. However before said node is installed, it's currently not possible to use dmesg with `--insecure`.

**Comment by smira** [comment]
This is not available for security reasons at the moment, as maintenance mode runs without PKI.

The best way is to use serial console and grab kernel logs there.

**Comment by samip5** [comment]
>This is not available for security reasons at the moment, as maintenance mode runs without PKI.

That's understandable, but results in this problem.

> The best way is to use serial console and grab kernel logs there.

Unfortunately, the cases were this is usually needed lacks serial console. If we could use eg Omni for just kernel log sink, that could be useful for this, just as an idea.

**Comment by samip5** [comment]
> I couldn't figure out a way to get dmesg logs from `talosctl` with a node if it's not part of a cluster.

Yes, you cannot untill Talos has been installed properly as it lacks the --insecure flag. You can get disks with insecure but not kernel logs and before you can install, you sometimes need logs. :)

**Comment by smira** [comment]
If this is an Omni question, Omni provides logs in the UI/API on its own, and the question is not relevant.

If this is about Talos without Omni, `dmesg` is not provided in maintenance mode for security reasons.
