### ISSUE TITLE
nvidia kernel module not found on reboot upon fresh install

### ISSUE THREAD

**Issue by achristianson** [siderolabs/talos#9041]
On v1.7.5 running nvidia proprietary modules + container toolkit official plugins.

GPU worker nodes install and run fine, but there is a glitch on the first reboot upon install (e.g. node goes into "Installing" state then reboots). On that first boot after "Installing" phase is complete, I get errors about the nvidia kernel modules not being found. This is fixed by performing a hard reboot of the system.

Notably, this happens both with qemu/libvirt VMs as well as bare metal. I think it may have something to do with ACPI soft reboot vs hard reboot.

Edit:

A couple other things of note:

One could speculate this is due to some kind of hardware issue, but before running Talos we were running k3s on debian on bare metal with official nvidia drivers (latest ~555 from nvidia repos). In that setup, I was always able to perform a software-initiated reboot, e.g. running "reboot" as root, and the nvidia kernel modules always loaded fine on the next boot, so this points to something different about how Talos is booting.

I can't pull logs since the node is "Booting" and I only have access via IPMI. Here's a screenshot from the IPMI that shows one of the module missing errors:

![image](https://github.com/user-attachments/assets/e6d29b46-d20f-44a3-aeb5-d3f456f81750)

EDIT 2:

I caught in the console during install process "kexec core: launching new kernel"

I believe what may be happening is when the kernel is reset with kexec, the GPUs are not hardware reset, and the driver fails to load. It could also possibly be an issue with kexec and locating/loading the nvidia modules.

**Comment by smira** [comment]
It might be the case with `kexec`, but the module should load still, might report a different error though if NVIDIA GPU is not found.

But I guess your case might be something related to the boot media (e.g. ISO) having GPU extension, while using an installer without one. So you boot initially with GPU, then install without GPU, kexec reboots from disk correctly, but GPU driver is missing.

If you hard reboot, you boot from an ISO vs. the disk once again.

**Comment by achristianson** [comment]
This is a PXE boot fresh install using matchbox following the Talos docs. The provisioning process in this case does a full wipe of the system, then on first boot post-wipe, Talos installer does its thing, system kexec reboots, and that's when we see the modules missing.

I believe I had the same thing happening on our libvirt deployments as well.

The workaround in our provisioning process is to detect Talos is ready, perform a reboot, then everything works fine from there, but it's a bit of a hack.

**Comment by smira** [comment]
I don't have much to add here besides what I said above. 

You can try disabling `kexec` and see if that fixes the issue for you. 

```yaml
machine:
  sysctls:
    kernel.kexec_load_disabled: "1"
```

**Comment by achristianson** [comment]
@smira I tried what you said, and it did cause the reboot stage to do a full reboot of the machine.

What's interesting, is that it still had the module not found issue, but only on a machine that allows Talos to change the EFI boot order.

What appears to be happening is that if the netbooted machine is booted from the disk that Talos installs to, that's when the modules are not found. It needs to do the netboot with the GPU kernel and initramfs in order to have the modules available.

Is the Talos install process possibly not copying modules to the disk install that were there from the netboot? The first netboot, of course, does the install. I believe it's wrong for Talos to mess with the UEFI order on a netboot machine (there are some other issues that reference this, e.g. breaking the netboot process on Hetzner machines), but that's something for a different issue.

**Comment by smira** [comment]
Installation flow from ISO/PXE requires NVIDIA to be present in the `installer`, (it doesn't matter if it's present in the PXE boot media).

See [docs](https://www.talos.dev/v1.7/talos-guides/install/boot-assets/#example-bare-metal-with-image-factory).
