### ISSUE TITLE
Make flannel images to be configurable using config file

### ISSUE THREAD

**Issue by jijiechen** [siderolabs/talos#9042]
## Feature Request

Talos supported overriding images for multiple components but flannel images are not included. Flannel image tags are hard-coded in the source. So it's not possible to replace the image registry for them at this time.

The source code is at:
https://github.com/siderolabs/talos/blob/c2b19dcb978ab015bd9b3c5a4eb47a53ee25e297/pkg/images/list.go#L44

**Comment by smira** [comment]
You can disable Talos's Flannel manifest and use your own completely. We don't support configuring the built-in manifests much.

If you're looking to host the images yourself, it's way easier to use Talos [registry mirror](https://www.talos.dev/v1.7/talos-guides/configuration/pull-through-cache/) feature.
