### ISSUE TITLE
talosctl upgrade-k8s - Unexpected behavior 

### ISSUE THREAD

**Issue by ChickenIQ** [siderolabs/talos#9054]
### Description
"talosctl upgrade-k8s" upgrades the entire cluster when a single node is specified.
This is not the case when using "talosctl upgrade".

### Environment
- Talos version: v1.7.5
- Kubernetes version: 1.30.1
- Platform: metal

### Unrelated 
This is unrelated, but "kubectl version --short" is not a thing (This is in the issue template)

**Comment by frezbo** [comment]
This is the expected behavior, k8s upgrades are cluster wide
