### ISSUE TITLE
vmware.sh doesn't work with networks that contains spaces

### ISSUE THREAD

**Issue by joltcan** [siderolabs/talos#9063]
## Bug Report

Tried to deploy but failed with `govc: device '-' not found`

### Description

Our sysadmins has naming convention for interfaces like "vlanXXXX - foobar", and that messes up the script

- Platform: vmware

### Proposed solution

Add `"` around `-net` variable:

```
govc vm.network.change -vm ${CLUSTER_NAME}-worker-${i} -net "${GOVC_NETWORK}" ethernet-0
```

**Comment by smira** [comment]
Please submit a PR to fix this issue, thank you.
