### ISSUE TITLE
[RFC] talosctl output standards

### ISSUE THREAD

**Issue by Ulexus** [siderolabs/talos#907]
As we have discussed a few times, it would be really useful to have a few standard output formats for osctl in order to allow easy automation.  Specifically, we should add `-o json` and (maybe) `-o yaml`.  We could do this by creating an interface similar to:

```go
interface OutputFormatter{
  // JSON writes JSON-formatted output to the given writer
  JSON(io.Writer) error

  // YAML writes YAML-formatted output to the given writer
  YAML(io.Writer) error

  // Tabular writes the given fields in tabular format to the given writer
  Tabular(io.Writer, fields ...string) error

  // Human writes the output in human-readable format
  Human(io.Writer) error
}
```

We can then provide a StandardFormatter for convenience which implements reasonable defaults for JSON, YAML, and Tabular, and maybe takes a `text.Template` for the Human formatting.

**Comment by Ulexus** [comment]
Actually, that map is probably not the best choice for Tabular output, since field order would be lost.

**Comment by andrewrynhard** [comment]
Awesome. Adding this to the agenda for tomorrow's meeting. Probably good that we think about this while we are rewriting the API.

**Comment by smira** [comment]
I like the ida!

I feel for efficiency, it's better to do something like:

```go

JSON(w io.Writer) error
```
(so that we don't build output in memory)

And if method returns some `Output` object, and that object might implement one or more formatting interfaces which are called in the end to generate output. E.g. `top` has only human-readable, while `ps` might do all of them.

The most generic methods might use generic structures which already implement formatting given some abstract data structure which is serializable to JSON/YAML.

**Comment by Ulexus** [comment]
The original form of the interface did exactly that (took an io.Writer as an argument to each), but I wasn't sure I wanted to couple the actual writer to it.  I thought this was a cleaner abstraction.

Thinking about it, though, I think you're correct.  It's better to just provide the `io.Writer` rather than having to buffer the entire output for no good reason.

**Comment by Ulexus** [comment]
I think it would be fine to implement a null output for commands specifically and solely related to human interaction, but they should still match the interface, even if the output is empty or `{"error": "JSON output not supported"}`.

**Comment by andrewrynhard** [comment]
Is this something we want for 0.4?

**Comment by AlekSi** [comment]
While working on it, we should investigate https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson package:

> This package produces a different output than the standard "encoding/json" package, which does not operate correctly on protocol buffer messages.

One thing it supports (and encoding/json does not) is `oneof` fields.

**Comment by Ulexus** [comment]
The new resources system handles YAML and JSON output formats.  It's not yet the entirety of `talosctl` output, but we're getting there.
