### ISSUE TITLE
Update NVIDIA driver version, keep old version as alternative extension

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#9086]
Update 535.x to the latest available, and "label" as "nvidia-535-" and "nvidia-old-".

Add latest stable (560.x), and label it as "nvidia-555-" and "nvidia-" (only OSS drivers).

**Comment by frezbo** [comment]
We'll be following NVIDIA data center driver versioning as per https://docs.nvidia.com/datacenter/tesla/drivers/index.html#cuda-drivers following keeping LTS and production version
