### ISSUE TITLE
Put the schematic ID in a node annotation

### ISSUE THREAD

**Issue by tjwallace** [siderolabs/talos#9089]
## Feature Request
Put the schematic ID in a node annotation

### Description
It would be helpful for automations like [`system-upgrade-controller`](https://github.com/buroa/system-upgrade-controller/blob/master/examples/talos.yaml) to have the Talos schematic ID in a node annotations (ie `cluster.talos.dev/schematic-id`) so it can be used to pull the correct [installer image](https://github.com/buroa/system-upgrade-controller/blob/master/examples/talos.yaml#L48).

Currently my cluster needs two different schematic IDs so I cannot set a single value in my `system-upgrade-controller` plan.

Thanks!

**Comment by smira** [comment]
See https://github.com/siderolabs/talos/discussions/9070, if the extensions will be exposed via node labels, the schematic will be exposed as wll.

**Comment by tjwallace** [comment]
@smira one issue is the schematic id is too long for a node label

**Comment by smira** [comment]
yeah, true, I believe annotations have same limits (?). Certainly some extensions make more sense as labels (e.g. "I have nvidia"), while schematic is fine as an annotation (as it makes less sense to filter on it)

**Comment by tjwallace** [comment]
Annotations can be up to [256kb](https://github.com/kubernetes/kubernetes/blob/eb729d1db72fc27f495ddf397289678b180926f1/staging/src/k8s.io/apimachinery/pkg/api/validation/objectmeta.go#L36)

**Comment by smira** [comment]
thanks @tjwallace, so it sounds like we'd need to split them across labels/annotations based on extension version length (as schematic virtual extension has schematic ID as a version). 

That doesn't sound too bad for me.

**Comment by smira** [comment]
```shell
$ kubectl describe nodes talos-default-worker-1
Name:               talos-default-worker-1
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    extensions.talos.dev/spin=v0.13.1
				...
```
