### ISSUE TITLE
[Talos 1.7.*] potential issues with network adapter  I219LM ?

### ISSUE THREAD

**Issue by Nerkho** [siderolabs/talos#9100]
### Description

I'm running Talos in my homelab on [these little machine](https://support.hp.com/us-en/document/c05371240).

I encounter no issues with 1.6.* but with 1.7.* there is some network issue. I suspect it's related to the adapter (I219LM) but not 100% sure. 

Simply put, in DHCP mode, the node is unable to acquire an IP address. The following pops up in the log :

```
..."operator":"dhcp4", "error": "unable to receive an offer: got an error while the discovery request: no matching response packet received", "link":"eth0"...
```

On the other hand, configuring a static IP results in connection timeouts across the board. So that doesn't help either.

There were no other changes to the configuration than the upgrade.

The weird thing is that it seems to work at first, it only fails after manually rebooting the node once.

Essentially, it looks like this with a fresh installation :

1. Install Talos 1.7.5 ---> Everything runs fine
2. Reboot the node ---> Not able to acquire an IP address anymore.

Did I miss something?

### Environment

- Talos version: 1.7.5
- Kubernetes version: 1.29.5
- Platform: metal
- Extensions:
  * siderolabs/util-linux-tools
  * siderolabs/iscsi-tools

**Comment by smira** [comment]
Please see https://github.com/siderolabs/talos/issues/8751#issuecomment-2120141890

It might be `kexec` issue (?)

**Comment by Nerkho** [comment]
Thanks a lot. That seems like it is the case. At least my testings seems to point to that.

Unfortunately, I'm currently using PXE to provision the node. I might have to rethink that.

**Comment by smira** [comment]
You can apply the workaround above no matter how you boot/provision your nodes.

**Comment by Nerkho** [comment]
> You can apply the workaround above no matter how you boot/provision your nodes.

Hmm, I might need to test it again then. I was under the impression that I was stuck in a provisioning loop once I disabled `kexec`.  
Meanwhile, I switched to provisioning with OpenTofu, but I will try again.
