### ISSUE TITLE
Kubernetes endpoint watch error after talosctl apply-config

### ISSUE THREAD

**Issue by bpawel10** [siderolabs/talos#9112]
## Bug Report

When I run `talosctl apply-config --insecure -n 192.168.0.46 --file controlplane.yaml`, my control plane CPU usage goes to 100% in the next few seconds and the same `kubernetes endpoint watch error` error keeps showing up.

### Description

I'm trying to configure a Talos VM on [Unraid](https://unraid.net/). What I did:
- generated a talos 1.7.5 metal amd64 ISO with qemu-guest-agent using the factory
- launched a VM
- `talosctl gen config test1 https://192.168.0.46:6443/`
- changed install disk in `controlplane.yaml` to `vda`
- `talosctl apply-config --insecure -n 192.168.0.46 --file controlplane.yaml`

The last command ran without any error, but as already mentioned, during the next few seconds CPU went to 100%, there's the error suggesting that the API server stopped working and the server itself is no longer responsive (`dial tcp 192.168.0.46:50000: connect: connection refused` when trying to run any other `talosctl` command).

I tried it multiple times using multiple VM instances and it's always the same.

### Logs

<img width="1429" alt="Zrzut ekranu 2024-08-5 o 15 45 02" src="https://github.com/user-attachments/assets/73ea69ca-cf85-4e55-aceb-a185b61eadbe">

I don't think I can run any other debugging, for example `talosctl support` will return `Failed to create kubernetes client rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 192.168.0.46:50000: connect: connection refused"`

### Environment

- Talos version:
```
Client:
	Tag:         v1.7.5
	SHA:         47731624
	Built:       
	Go version:  go1.22.4
	OS/Arch:     darwin/amd64
Server:
error getting version: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 192.168.0.46:50000: connect: connection refused"
```
- Platform: [Unraid](https://unraid.net/)

**Comment by smira** [comment]
The problem is in your screenshot - you don't have [enough RAM](https://www.talos.dev/v1.7/introduction/system-requirements/).
