### ISSUE TITLE
Talos on Oracle Cloud failing to boot

### ISSUE THREAD

**Issue by BobyMCbobs** [siderolabs/talos#9161]
### Description

Using disk images from releases, factory and omni, see the attempt matrix:

- v1.7.6 oracle image from factory + UEFI + secureboot -> UEFI shell
- v1.7.6 oracle image from github release + UEFI -> UEFI shell
- v1.7.6 oracle image from github release + BIOS -> blank screen
- v1.7.6 oracle image from omni + BIOS + launch from console -> blank screen
- v1.7.6 oracle image from omni + UEFI + launch from console  -> UEFI shell
- v1.6.7 oracle image from github release + BIOS -> blank screen
- v1.6.7 oracle image from github release + UEFI  -> UEFI shell

Talos does not appear to boot.

Oracle Instances are observed through the console, a SSH connection through an SSH proxy.

See the machine and image configs
- https://github.com/sharingio/infra/pull/2/files#diff-951202e42fc249274e7f66d3f50e7c07df42d831a979734f1a1d50475bb41618
- https://github.com/sharingio/infra/pull/2/files#diff-ed56e14714fad4a0305b7ef27518b06bbed8efd66062aa0516727f71e5d64614

Please note that to attempt UEFI, after the image is provisioned through Terraform, the image capabilities must be modified to turn off BIOS and any non-PARAVIRTUALIZED modes.

Note that v1.7.6 is the latest as of to date and v1.6.7 was said to be working for Artem.

See thread: https://taloscommunity.slack.com/archives/CMARMBC4E/p1723151839062929

### Logs

n/a

### Environment

n/a

**Comment by rothgar** [comment]
We also tried iPXE booting from the factory (1.7.6 IIRC) but the Oracle iPXE interface is too old to support booting over https. I forget the exact error message but it said something like
> This problem doesn't exist in iPXE anymore and you need to upgrade

**Comment by sergelogvinov** [comment]
Hi @BobyMCbobs , [Bring Your Own Image (BYOI)](https://docs.oracle.com/en-us/iaas/Content/Compute/References/bringyourownimage.htm) is very tricky.

Check this method https://github.com/sergelogvinov/terraform-talos/blob/main/oracle/images/README.md

You need to add extra files like `image_metadata_amd64.json` to the image before upload.
