### ISSUE TITLE
Please add support for RealTek RTL8125-based NICs

### ISSUE THREAD

**Issue by deitmerit** [siderolabs/talos#9171]
## Feature Request

Please add support for RealTek RTL8125-based NICs

### Description

As I wrote in discussions [here](https://github.com/siderolabs/talos/discussions/9168), I am currently trying to get Talos to run on Hetzner dedicated servers (EX-44) with two NICs, one of which is, according to lspci, a "Realtek Semiconductor Co., Ltd. RTL8125 2.5GbE Controller (rev 05)". This NIC is not found by Talos (tested v1.7.6 and v1.8.0-alpha.1). I tried the standard configuration plus 
```
customization:
  systemExtensions:
    officialExtensions:
      - siderolabs/realtek-firmware
```
I found [this issue](https://github.com/milas/rock5-talos/issues/11) in a related project, where they discuss how they got an SBC with an RTL8125 to run Talos, but it is way over my head to understand if there is anything there I could do to modify Talos myself to support this. If this is possible (custom kernel?), I would be very happy to get some pointers. Thank you!

**Comment by smira** [comment]
Let's keep this as a discussion until it's proven to be a real issue.

**Comment by deitmerit** [comment]
Problem can be fixed by adding kernel parameter `acpi=off`
