### ISSUE TITLE
System extensions do not run on the first boot after apply-config on a node

### ISSUE THREAD

**Issue by nenkoru** [siderolabs/talos#9184]
### Description
The first boot of a machine with a customised ISO containing system extensions from `factory.talos.dev` after executing `talosctl apply-config -f controlplane.yaml ...` doesn't start the extensions.
The virtual machine has to be forced shut down and boot up again, and at this 'second boot' the system extensions are actually booting up.
Its worth noting that one first boot of the machine, before applying a controlplane config I see a qemu guest agent running in a proxmox's interface.
Logs are attached as files, support.zip for both the cases attached.
### Logs
First boot after `talosctl apply-config -f controlplane ...`
Second boot after forced shutdown of the VM and boot up again
As well as support.zip files for both the cases.
See attached files.
[support_first_boot.zip](https://github.com/user-attachments/files/16624331/support_first_boot.zip)
[dmesg_first_boot.log](https://github.com/user-attachments/files/16624334/dmesg_first_boot.log)

[support_second_boot.zip](https://github.com/user-attachments/files/16624332/support_second_boot.zip)
[dmesg_second_boot.log](https://github.com/user-attachments/files/16624333/dmesg_second_boot.log)

### Environment
- Talos version: 1.7.6
- Kubernetes version: 1.30.3
- Platform: Proxmox
- ISO link: https://factory.talos.dev/image/324e32f0ab4f6a436fcbc4d1ade044a8ac363712b243131a4e5b7579af64b21a/v1.7.6/nocloud-amd64.iso # it contains qemu-user-agent which I used to determine this behaviour by looking at the IPs of the VM displayed in proxmox's interface, also tailscale, hello-world-service and intel-ucode.

**Comment by smira** [comment]
Make sure a few things as [documented](https://www.talos.dev/v1.7/talos-guides/install/boot-assets/):

* if booting from ISO/PXE/..., Talos will install itself to the disk, and the `installer` being used should contain the extensions you need
* make sure your boot order is correct, that is you don't boot from an ISO after Talos was installed to the disk

[Image Factory](https://factory.talos.dev/?arch=amd64&cmdline-set=true&extensions=-&extensions=siderolabs%2Fqemu-guest-agent&platform=nocloud&target=cloud&version=1.7.6) provides the links for all respective boot assets I mentioned above.

**Comment by nenkoru** [comment]
> Make sure a few things as [documented](https://www.talos.dev/v1.7/talos-guides/install/boot-assets/):
> 
> * if booting from ISO/PXE/..., Talos will install itself to the disk, and the `installer` being used should contain the extensions you need
> * make sure your boot order is correct, that is you don't boot from an ISO after Talos was installed to the disk
> 
> [Image Factory](https://factory.talos.dev/?arch=amd64&cmdline-set=true&extensions=-&extensions=siderolabs%2Fqemu-guest-agent&platform=nocloud&target=cloud&version=1.7.6) provides the links for all respective boot assets I mentioned above.

<img width="657" alt="image" src="https://github.com/user-attachments/assets/56f6177c-558d-4409-9626-04ef8b7bd05c">

The boot order seems fine in proxmox. 
Worth noting that I don't see the actual reboot happening with the selection of the `A - Talos` to choose after applying the controlplane.yaml config. Is this expected?

**Comment by nenkoru** [comment]
I am applying the controlplane.yaml as stated in the docs:
`talosctl apply-config -f controlplane.yaml --insecure -n 192.168.10.10`

**Comment by smira** [comment]
Please read my first answer. On initial install Talos does `kexec` correctly from install disk, but I guess when you do your hard reboot, it boots from something else.

**Comment by nenkoru** [comment]
> Please read my first answer. On initial install Talos does `kexec` correctly from install disk, but I guess when you do your hard reboot, it boots from something else.

Alright, now it makes sense. 
The installer installs the OS onto the disk, so the installer has to contain those extensions. 
I just thought for a moment that all the system extensions are getting copied from the boot ISO to the install disk, but they do not. 
They are getting installed by the installer. And they are included in the ISO's initramfs(?).
Closing the issue.
