### ISSUE TITLE
NVIDIA Modules Not Loading

### ISSUE THREAD

**Issue by AngellusMortis** [siderolabs/talos#9187]
### Description

I am following the docs on how to install NVIDIA drivers, and I am not able to get NVIDIA kernel modules to load.

```bash
$ talosctl -n cluster-3 read /system/state/config.yaml | yq '.machine.kernel'
{
  "modules": [
    {
      "name": "nvidia"
    },
    {
      "name": "nvidia_uvm"
    },
    {
      "name": "nvidia_drm"
    },
    {
      "name": "nvidia_modeset"
    }
  ]
}

# no modules
$ talosctl read /proc/modules -n cluster-3
mlx4_ib 274432 - - Live 0xffffffffc0664000
mlx4_en 200704 - - Live 0xffffffffc063c000
iTCO_wdt 12288 - - Live 0xffffffffc0636000
iTCO_vendor_support 12288 - - Live 0xffffffffc04e5000
ahci 45056 - - Live 0xffffffffc060a000
watchdog 40960 - - Live 0xffffffffc0606000
i2c_i801 36864 - - Live 0xffffffffc05f5000
lpc_ich 24576 - - Live 0xffffffffc05e5000
mlx4_core 483328 - - Live 0xffffffffc051d000
igb 294912 - - Live 0xffffffffc04f6000
libahci 49152 - - Live 0xffffffffc04d5000
i2c_smbus 12288 - - Live 0xffffffffc04d1000
mfd_core 12288 - - Live 0xffffffffc04cf000
i2c_algo_bit 12288 - - Live 0xffffffffc04c7000
```

I added the modules both via patching after install and at setup/install time by reinstalling.

### Logs

Only real logs I am seeing that look related are these:

```
cluster-3: kern:    info: [2024-08-16T02:45:06.081838725Z]: pci 0000:03:00.1: quirk_nvidia_hda_pm+0x0/0x40 took 88577 usecs
cluster-3: user: warning: [2024-08-16T02:46:08.53094834Z]: [talos] controller failed {"component": "controller-runtime", "controller": "runtime.KernelModuleSpecController", "error": "error loading module \"nvidia\": module not found\nerror loading module \"nvidia_drm\": module not found\nerror loading module \"nvidia_modeset\": module not found\nerror loading module \"nvidia_uvm\": module not found"}
```

### Environment

- Talos version: v1.7.6
- Kubernetes version: v1.30.3
- Platform: Bare Metal, amd64, NVIDIA Quadro P1000

**Comment by smira** [comment]
Make sure you have NVIDIA extension installed with `talosctl get extensions`.

Check [Boot Assets](https://www.talos.dev/v1.7/talos-guides/install/boot-assets/) guide on how to get extensions installed.

Make sure you're booting off the hard disk where Talos is installed (i.e. the ISO is ejected).

**Comment by AngellusMortis** [comment]
I thought I had done that too, but it did not work. Apparently, I did it wrong the first time.

**Comment by AngellusMortis** [comment]
I can make another issue, but I would rather not if it is just a simple fix/mistake like above. I am not getting the GPU resource to show up on my nodes now. 

The drivers and everything are working and even running the command for `nvidia-smi` is working and showing my CPU.

```bash
$ kubectl run nvidia-test --restart=Never -ti --rm --image nvcr.io/nvidia/cuda:12.1.0-base-ubuntu22.04 nvidia-smi
Sat Aug 17 03:41:07 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Quadro P1000                   On  | 00000000:03:00.0 Off |                  N/A |
| 34%   32C    P8              N/A /  N/A |      1MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

However, no GPU resources are showing in the cluster. If I add it to the request resources, it says it is unschedulable. If I use [kubectl-view-allocations](https://github.com/davidB/kubectl-view-allocations) or a `-A` on a node, there is no `nvidia.com/gpu`. 

```bash
$ kubectl view-allocations -r gpu
 Resource  Requested  Limit  Allocatable  Free
```

**Comment by smira** [comment]
@frezbo what should be that be that one needs to install on top?

**Comment by frezbo** [comment]
does it show up in `kubectl describe node`? Just needs the k8s-device-plugin running, if it doesn't start you'd need to look into it's logs, seems your test command does not set the runtimeclassname

**Comment by AngellusMortis** [comment]
No, it does not show up. And like I said, the device plugin daemonset is not even setting any desired count. There is nothing to log with it since there are no pods for the daemonset.

```
Capacity:
  cpu:                32
  ephemeral-storage:  1951312988Ki
  hugepages-2Mi:      0
  memory:             264074052Ki
  pods:               110
```

I am migrating from a `kubeadm` cluster that using the same nodes (migrated half the nodes now). After comparing with it and doing testing, it looks like it is [v0.15.0](https://github.com/NVIDIA/k8s-device-plugin/releases/tag/v0.15.0) that breaks it. It looks like 0.15.0 also breaks on my old nodes as well (I was running 0.12.2). So, the Talos nodes definitely seem to be set up right and it looks like an issue in the device plugin.

**Comment by AngellusMortis** [comment]
It looks like it is this [issue right here](https://github.com/NVIDIA/k8s-device-plugin/issues/315). Adding the label `nvidia.com/gpu.present=true` to the nodes fixes it. I could not find anything in the device plugin docs to indicate that is required/expected behavior though.
