### ISSUE TITLE
Latest kubelet patch versions (1.30.4, 1.29.8) break NFS volume mounts

### ISSUE THREAD

**Issue by e3b0c442** [siderolabs/talos#9190]
### Description
Updating to the latest kubelet patch version breaks NFS volume mounts that were working without issue prior to the upgrade:

```bash
➜  ~ kdp -n plex plex-0
# ...
Events:
  Type     Reason       Age                  From     Message
  ----     ------       ----                 ----     -------
  Warning  FailedMount  79s (x684 over 22h)  kubelet  MountVolume.SetUp failed for volume "media" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs 192.168.1.65:/volume1/k8s/media /var/lib/kubelet/pods/e504f760-ab44-44eb-9e1e-ea5c18da6e22/volumes/kubernetes.io~nfs/media
Output: mount: /var/lib/kubelet/pods/e504f760-ab44-44eb-9e1e-ea5c18da6e22/volumes/kubernetes.io~nfs/media: bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.
       dmesg(1) may have more information after failed mount system call.
```

Rolling the kubelet back to the prior patch version resolves the issue. My cluster is running 1.29, so 1.29.8 is the breaking version and 1.29.7 works fine. In searching for whether others have had this issue, another user described the same behavior after updating from 1.30.3 to 1.30.4 and subsequently rolling back.

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
```
Client:
	Tag:         v1.7.6
	SHA:         ae67123a
	Built:       
	Go version:  go1.22.5
	OS/Arch:     darwin/arm64
Server:
	NODE:        192.168.227.6
	Tag:         v1.7.6
	SHA:         ae67123a
	Built:       
	Go version:  go1.22.5
	OS/Arch:     linux/amd64
	Enabled:     RBAC
```
- Kubernetes version: [`kubectl version --short`]
```
Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.8
```

- Platform: hybrid AMD64 and ARM64 (AMD64 control plane)

**Comment by zargony** [comment]
Same here with 3 arm64 nodes (rpi), Talos 1.7.6, k8s 1.30.4. Rolling back to k8s 1.30.3 also fixed the issue for me.

**Comment by smira** [comment]
We did some changes recently, but it should be same same thing for old Kubernetes version, I will check it out.

**Comment by smira** [comment]
Fixed versions will be re-pushed shortly, thanks for reporting it!

**Comment by smira** [comment]
All affected versions were re-uploaded with fixes.
