### ISSUE TITLE
Node Keeps Returning to Maintenance Mode on Boot

### ISSUE THREAD

**Issue by AngellusMortis** [siderolabs/talos#9206]
### Description

I have a Dell PowerEdge R730xd and every time I reboot it, the node returns to maintenance.

If this is just a bug in Talos that I can work around, that is fine. I am just concerned that if I put PVCs on the server they will be lost each time it goes into maintenance mode. Will maintenance mode affect anything on disk after I reapply configs?

### Logs

dmesg after it reboot into maintenance mode and I re-apply config:

https://gist.github.com/AngellusMortis/d8d87b81048e1b4ba7f401ab36d3f9c1

### Environment

- Talos version: 1.7.6
- Kubernetes version: 1.30.3
- Platform: bare metal / Dell PowerEdge R730xd

The Dell PowerEdge R730xd can have a max of 26 disks, 2x SATA SSDs (rear/OS disk), 4x U.2 NVMe disks and 20x SATA SSDs (front disks). The server currently has 12 disks. 2x 2TB SSDs and 10x 8TB SSDs. Only 1 of the 2TB SSDs have anything on them (Talos).

**Comment by smira** [comment]
This issue was reported for similar hardware, but be a race issue.

The fix in 1.8 (not released yet) is in https://github.com/siderolabs/talos/pull/9176

**Comment by AngellusMortis** [comment]
Sweet. Is there any ETA on 1.8 going stable? Or does it returning to maintenance mode actually really affect anything? i.e. does applying the config back on top of it result in any data lose? I can leave with needing to manually applying the config on reboot until 1.8 drops.

**Comment by smira** [comment]
This is not a good issue to have, and the reason is that even though Linux kernel reports all devices as discovered, the actual disks are coming after that, so Talos assumes not being installed and falls into maintenance mode.

**Comment by AngellusMortis** [comment]
So, I should wait until 1.8 to try to use the node? Is there any rough ETA on when 1.8 will come out? I have not really been able to find anything about the actually release cycle for Talos or planning or anything.

**Comment by smira** [comment]
Talos 1.8 will be released somewhere in September, and the next alpha should be soon-ish (next week).

**Comment by AngellusMortis** [comment]
Thanks. I can probably test it out on the next alpha and just try to avoid putting any real data on it until it hits stable. Can you run nodes with mismatched versions (i.e. this one running the 1.8.0 alpha and the others running 1.7.6)?

**Comment by smira** [comment]
> Thanks. I can probably test it out on the next alpha and just try to avoid putting any real data on it until it hits stable. Can you run nodes with mismatched versions (i.e. this one running the 1.8.0 alpha and the others running 1.7.6)?

yes, you can
