### ISSUE TITLE
Nvme Kernel Modules Missing

### ISSUE THREAD

**Issue by zzachattack2** [siderolabs/talos#9214]
The nvme host (RDMA only) and nvme target (all) modules are built with the kernel in pkgs, but are not included in the Talos base image.

CONFIG_NVME_RDMA=m
CONFIG_NVME_TARGET=m
CONFIG_NVME_TARGET_LOOP=m
CONFIG_NVME_TARGET_RDMA=m
CONFIG_NVME_TARGET_FC=m
CONFIG_NVME_TARGET_TCP=m

Discussed on slack.

**Comment by smira** [comment]
Ref: https://github.com/siderolabs/pkgs/pull/906

**Comment by zzachattack2** [comment]
Thank you! Checked the fix but it is missing the one nvme host driver that which was compiled as a module... the host RDMA one (nvme/host/nvme-rdma.ko).

**Comment by smira** [comment]
> Thank you! Checked the fix but it is missing the one nvme host driver that was compiled as a module... the host RDMA one (nvme/host/nvme-rdma.ko).

True, thank you, I don't know how I missed that.
