### ISSUE TITLE
Please dont remove .machine.install.extensions it has benefits over boot assets

### ISSUE THREAD

**Issue by Syntax3rror404** [siderolabs/talos#9224]
### Description
If you're on newer Talos versions like 1.7.6 you get this warning while installing:
`WARNING: .machine.install.extensions is deprecated, please see https://www.talos.dev/latest/talos-guides/install/boot-assets/`

So the way arround is to use the image factory, which delivers install images with the extensions preinstalled which is also a great option!! Please dont get me wrong!

The downside is:
1. If you want specific driver/firmware versions it gets diffcult. You cant select specific versions you want.
2. If you want to implement you're own extensions you now must create boot assets instead just adding you're extensions as container images and ref them in the machine config. 

It makes everything uncomfortable and more difficult and in some szenarios unusable. I want just to use talos and not creating my own image factory just to install drivers with a specific version. 

The way by just declare install extensions containers via .machine.install.extensions is awesome!

I hope talos remains this feature.

**Comment by smira** [comment]
This feature will be probably removed for the technical reason that Talos needs lots of tools and RAM to re-build the image on the host itself.

Also this is not compatible with SecureBoot at all (you can't sign on the host).

Also people hit a problem with not updating image refs when upgrading, so this feature is deprecated for good reasons.

You can use `imager` to prepare boot assets beforehand, and referencing them as you go.

**Comment by Syntax3rror404** [comment]
@smira why not just persist this installation method as alternative solution instead of removing it? In some szenarios this way could be better.

**Comment by smira** [comment]
We are not removing this feature for Talos 1.8, but we might remove it in the future. The reasons I explained above, and it will make installer eventually smaller, which is a direct benefit.
