### ISSUE TITLE
Add selector for machine.disks or allow list with --insecure

### ISSUE THREAD

**Issue by Syntax3rror404** [siderolabs/talos#9225]
## Feature Request
It is not possible to install talos with the data disk. ATM you need to install talos frist and then run the commands to get the id for the disk and then you can apply the config again. 

### Description
Please add a selector for machine.disks like for the machine.install.diskSelector or allow ls with --insecure or add the real uuid/disk-id to the disks command. 

If you have a second disk for the data,  the disk selector is not implemented so you need for example `/dev/disk/by-id`
To get the information it is needed to run `talosctl list /dev/disk/by-id ` which is not available for --insecure so you need to install talos first.

Please keep in mind the UUID from `talosctl disks` does not match the real disk UUID from `/dev/disk/by-uuid` so this is also not possible.

**Comment by smira** [comment]
User disks will go away in the way they are today and they will be replaced with more robust solution based on #8367.
