### ISSUE TITLE
Missing URL for secure boot sidero ca cert

### ISSUE THREAD

**Issue by Syntax3rror404** [siderolabs/talos#9231]
### Description
If you want to use secure boot and if the setup mode is not possible e.g because you boot from iPXE or Ventoy and not directly from the talos iso, you have a problem with the secure boot key. One option is to add the key from the efi directory but this is not the signing cert and is individual for each build. So if you perfom a upgrade you're system cannot boot anymore because the signature is not the same. We need the public key that can validate the trust from the sidero build.

It could be that we have here a lack in the documentation: https://www.talos.dev/v1.7/talos-guides/install/bare-metal-platforms/secureboot/ 

If I'm completly wrong here and there is no sidero ca and so only a signature key, this means if you're not have a IPMI you have a pretty bad day if you perform a talos upgrade. 

Where can I get the sideo public secure boot cert? 

### Logs
No logs

### Environment

- Talos version: 1.7.6
- Kubernetes version: 1.30.3
- Platform: x86_64

**Comment by Syntax3rror404** [comment]
Ohhhh found them in the auto directory. Hopefully they dont get change and break some upgrades. 

But tested with a 1.7.6 signed certificate a 1.6 installation without any problems.

**Comment by smira** [comment]
It's not quite clear what you're asking about.

If you ask about official Sidero Labs key, it is available and documented: https://github.com/siderolabs/image-factory#get-securebootsigning-certpem

If you roll your own certificates, just use yours.

**Comment by Syntax3rror404** [comment]
Oh thats was exactly was I'm looking for!

This detail is missing in the https://www.talos.dev/v1.7/talos-guides/install/bare-metal-platforms/secureboot/ Documentation
