### ISSUE TITLE
uio_pci_generic can be required for DPDK or SPDK

### ISSUE THREAD

**Issue by aarnaud** [siderolabs/talos#9236]
### Description

https://spdk.io/doc/system_configuration.html

```
"error loading module \"uio_pci_generic\": module not found"
```

This module is require to use nvme with SPDK. 

I'm guessing I had to enable this https://github.com/siderolabs/pkgs/blob/v1.7.0/kernel/build/config-amd64#L4969

**Comment by frezbo** [comment]
Fixed via https://github.com/siderolabs/pkgs/pull/1015
