### ISSUE TITLE
Short circuit already-applied upgrades

### ISSUE THREAD

**Issue by jfroy** [siderolabs/talos#9242]
### Description

To improve compatibility with Rancher's system-upgrade-controller, it would be nice if Talos somehow kept track of already-applied upgrade sequences and did no work when such a sequence is re-applied.

Perhaps machined could keep a sort of intents log or journal with requested upgrade sequences (a hash of the RPC mixed with a hash of the resolve installer image?) and a completed/done flag?

See https://github.com/rancher/system-upgrade-controller/pull/328

**Comment by smira** [comment]
This is already available in Talos API, and there's nothing that needs to be done.

Talos upgrades work in two dimensions:

* Talos version
* Image Factory schematic ID

Talos version is available via `talosctl version` API, schematic ID is available via `talosctl get extensions`. The controller should reconcile until both dimensions match the spec.

**Comment by jfroy** [comment]
> This is already available in Talos API, and there's nothing that needs to be done.
> 
> Talos upgrades work in two dimensions:
> 
> * Talos version
> * Image Factory schematic ID
> 
> Talos version is available via `talosctl version` API, schematic ID is available via `talosctl get extensions`. The controller should reconcile until both dimensions match the spec.

What you're saying is we should use the Talos API to query if an update is needed before invoking `talosctl upgrade`?

- What is the behavior of the API if an upgrade sequence has been started but has not completed yet? Is there a time window between `talosctl upgrade` exiting and the node getting cordoned off where a new upgrade pod could start.
- It's not clear how we should handle system extensions and the schematic ID. Yes we can query the API for extensions installed on the node, but the schematic ID that was used to produce the installer image that was used to install or upgrade the node is not stored. So given a request to "upgrade to `factory.talos.dev/installer/<new_schematic_id>:<version>`", assuming `version` matches the current node version, how are we to determine that `<new_schematic_id>` is in fact new?

**Comment by jfroy** [comment]
I was hoping maybe the `installer` binary would have commands to output this information and we could fetch the image ourselves and query it about its payload, but that does not seem to be the case.

**Comment by smira** [comment]
I don't have an exact idea on what you're building right now, but what I described is how [Omni](https://github.com/siderolabs/omni/) works. So the APIs provided are enough, the implementation to handle all cases is not trivial.

If you'd like to implement something on your own, I would like to know first why Omni doesn't work for you.

**Comment by frezbo** [comment]
> but the schematic ID that was used to produce the installer image that was used to install or upgrade the node is not stored.

this is stored as a meta extension if using image factory, you can get the details from the meta extension spec

**Comment by jfroy** [comment]
> I don't have an exact idea on what you're building right now, but what I described is how [Omni](https://github.com/siderolabs/omni/) works. So the APIs provided are enough, the implementation to handle all cases is not trivial.
> 
> If you'd like to implement something on your own, I would like to know first why Omni doesn't work for you.

I, and a few other people, were looking into improving Talos upgrade automation using https://github.com/rancher/system-upgrade-controller. I have a few on-prem and cloud clusters that are not managed by Omni. I haven't looked at on-prem Omni recently and I should, but without an easy way to migrate an existing cluster to an Omni deployment it will be some time before I can use it.

**Comment by jfroy** [comment]
> > but the schematic ID that was used to produce the installer image that was used to install or upgrade the node is not stored.
> 
> this is stored as a meta extension if using image factory, you can get the details from the meta extension spec

Good to know. I'll ask a few people that have clusters installed from an image factory image to share that with me, and I can look for it in source code. My own on-prem clusters using custom boot assets and don't have that meta-extension (I am looking into deploying a custom image factory, but that is complexity I don't strictly need, so it's not been a priority).

Besides that, it would still be a useful enhancement to have provenance/identity/capabilities information in an installer image, maybe provided by the installer binary as a new command, maybe as files/layers in the image.

**Comment by smira** [comment]
Installer itself doesn't know much about itself, but a successful install transitions a Talos machine on version/schematic ID dimensions. 

If you're using your custom boot assets system, you can invent your own way to pick those dimensions, but the official answer is above.

**Comment by jfroy** [comment]
> Installer itself doesn't know much about itself, but a successful install transitions a Talos machine on version/schematic ID dimensions.

Yeah I was imagining that `installer` could have a `version` command, and a "get extensions" or "build manifest" command for systems that would like to inspect an installer prior to its application/use/deployment.

I appreciate all the information and feedback.
