### ISSUE TITLE
Frequent "error querying ethtool ioctl link state" in talos logs

### ISSUE THREAD

**Issue by jfroy** [siderolabs/talos#9296]
### Description

In v1.8.0-beta.0, I am now seeing this somewhat regular talos log line:

`[talos] error querying ethtool ioctl link state {"component": "controller-runtime", "controller": "network.LinkStatusController", "link": "<LINK>", "error": "no such device"}`

This appears to be logged shortly following this kernel log line:

`eth0: renamed from tmp<random>`

which I believe comes from cilium's normal operations.

The output of `talosctl get linkstatus` looks OK, so this may be a race when an interface gets renamed that resolves itself.

### Environment

- Talos version:
  ```
  Client:
          Tag:         v1.7.6
          SHA:         ae67123a
          Built:       
          Go version:  go1.22.5
          OS/Arch:     linux/amd64
  Server:
          NODE:        192.168.1.13
          Tag:         v1.8.0-beta.0
          SHA:         b92c2e49
          Built:       
          Go version:  go1.22.7
          OS/Arch:     linux/amd64
          Enabled:     RBAC
   ```
- Kubernetes version:
  ```
  Client Version: v1.31.0
  Kustomize Version: v5.4.2
  Server Version: v1.31.0
  ```
- Platform: baremetal
- Kernel: custom 6.10.6 configuration

I've attached a support file.

**Comment by smira** [comment]
These are harmless, but we should silence them

**Comment by Syntax3rror404** [comment]
eth0: renamed from tmp<random>

Could be the CNI which is normal.
