### ISSUE TITLE
1.8 Variable to set the kubernetes version

### ISSUE THREAD

**Issue by Syntax3rror404** [siderolabs/talos#9299]
## Feature Request
Please add a variable to set the kubernetes version. 

### Description
The [talos support matrix](https://www.talos.dev/v1.8/introduction/support-matrix/) shows, that talos supports more then only the "default" kubernets version. Applications like Rancher are not allways on the latest version so for example it would be helpful to use 1.30.4 Kubernetes on Talos 1.8.0. 

The Documentation don't showing a simple solution for this.

**Comment by smira** [comment]
You can use any supported Kubernetes version according to the support matrix.

What kind of variable are you talking about?

`talosctl gen config` supports `--kubernets-version` flag, `talosctl upgrade-k8s` supports upgrading Kubernetes version. 

Kubernetes version is simply an image reference for Kubernetes components in the Talos machine config.

**Comment by Syntax3rror404** [comment]
> You can use any supported Kubernetes version according to the support matrix.
> 
> What kind of variable are you talking about?
> 
> `talosctl gen config` supports `--kubernets-version` flag, `talosctl upgrade-k8s` supports upgrading Kubernetes version.
> 
> Kubernetes version is simply an image reference for Kubernetes components in the Talos machine config.

Thanks, If its just the image ref then this is exactly what im looking for.
