### ISSUE TITLE
I can't upgrade my node, am I being blocked by Azure?

### ISSUE THREAD

**Issue by budimanjojo** [siderolabs/talos#9319]
### Description
I'm trying to update my node with:
```
talosctl upgrade -n 192.168.200.22 --image=factory.talos.dev/installer/df491c50a5acc05b977ef00c32050e1ceb0df746e40b33c643ac8a9bfb7c7263:v1.7.6`
```

### Logs

Here's the `talosctl -n 192.168.200.22 dmesg` shows me:
```
192.168.200.22: user: warning: [2024-09-13T09:50:36.749045957Z]: [talos] upgrade request received: preserve true, staged false, force false, reboot mode DEFAULT
192.168.200.22: user: warning: [2024-09-13T09:50:36.750216957Z]: [talos] validating "factory.talos.dev/installer/df491c50a5acc05b977ef00c32050e1ceb0df746e40b33c643ac8a9bfb7c7263:v1.7.6"
192.168.200.22: user: warning: [2024-09-13T09:50:45.948662957Z]: [talos] retrying error: failed to pull image "factory.talos.dev/installer/df491c50a5acc05b977ef00c32050e1ceb0df746e40b33c643ac8a9bfb7c7263:v1.7.6": failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://image-factory-cwfea0e4e7fee4ac.z01.azurefd.net/docker/registry/v2/blobs/sha256/dc/dc56ca3c4514ad7e1716ffb9b2b60bd904becba885f5aba361ca4e2daa14f56f/data?se=2024-09-13T10%3A10%3A46Z&sig=UkG4xQ9jfKjAlYwkeiKV2rDpXz0mbCahekGn6Z335mk%3D&sp=r&spr=https&sr=b&st=2024-09-13T09%3A50%3A36Z&sv=2020-02-10": read tcp 192.168.200.22:57954->13.107.246.59:443: read: connection reset by peer
```

This has been happening for days now and I thought the server was down but I got confirmed by others that they're not affected and can upgrade without problem.

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
```
Client:
        Tag:         v1.7.6
        SHA:         undefined
        Built:
        Go version:  go1.22.7
        OS/Arch:     linux/amd64
Server:
        NODE:        192.168.200.22
        Tag:         v1.7.1
        SHA:         e9cb904e
        Built:
        Go version:  go1.22.2
        OS/Arch:     linux/amd64
        Enabled:     RBAC
```
- Kubernetes version: [`kubectl version --short`]
```
Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0
```

- Platform: NixOS

**Comment by smira** [comment]
Yes, that might be it. You can set up a registry mirror for `factory.talos.dev` from a non-blocked location.

Where is your server located? Country? Is it Hetzner?

**Comment by budimanjojo** [comment]
How do I setup a registry mirror?

It's my home network in Indonesia. Is there any way I can make sure if my IP is really blocked?

**Comment by budimanjojo** [comment]
Maybe I can restart my home modem to get a new IP from my ISP and try again, but it's very weird that Azure blocking my home IP.

**Comment by smira** [comment]
We can't do much about it unfortunately, we don't do any blocking on our side, but Azure might do some geo-blocking or for other reasons.

**Comment by smira** [comment]
I think closing makes sense, as there's nothing we can do about it at the moment.

**Comment by budimanjojo** [comment]
@smira I'm still getting blocked even with brand new IPs but I found something. If I try to use `curl` command to GET the url manually, I get "connection reset" error like 7 out of 10 times I but I still have that 30% success rate of connecting so I'm a little bit confused if Azure is blocking me or something else is happening with Azure Front Door.

That 30% success rate is not the case with `talosctl upgrade` command though. I have zero chance of updating my node at all with `talosctl` (I have been occasionally trying again everyday without success), is there a way in the source code to make it try repeatedly instead of waiting for a couple of minutes before trying again (from what I see in the dmesg log it seems like this is currently what talosctl do?)?

**Comment by smira** [comment]
`talosctl upgrade` pulls an image, and it uses regular image pull logic and retries, it doesn't wait couple of minutes, but it might block on timeout or something like that.

**Comment by smira** [comment]
Your error by the way seems to be different, it doesn't look like you're geo-blocked, but rather some huge packet loss or something like that.

You can try doing `mtr` to the hostname.

**Comment by budimanjojo** [comment]
Here's the screenshot of it and it seems like you're right. Top is from my home network, bottom is from the working VPS.
![image](https://github.com/user-attachments/assets/8c9a1fea-1849-4e29-b7bb-7f19038ae31a)
Is there anything I can do about it? What does this mean?

**Comment by smira** [comment]
This is a question out of Talos context, you should talk to your ISP probably. I guess the packet loss is long before it hits the Microsoft network.

**Comment by budimanjojo** [comment]
Thanks!

Looking at the `mtr` output, seems like it never reach the destination IP `13.107.246.59`, the package stops at `104.44.212.206` and stay that way. I do IP lookup of `104.44.212.206` and it looks to be owned by Microsoft.
