### ISSUE TITLE
talosctl does not use system dns resolver

### ISSUE THREAD

**Issue by nebula-it** [siderolabs/talos#9324]
### Description
talosctl does not use dns resolver configured in system (both windows and linux) and seems like instead it just tries `127.0.0.53:53`. This results in no name resolution in both windows and WSL, and an error message is thrown.

### Logs
```
healthcheck error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp: lookup test-cluster-cp1 on 127.0.0.53:53: server misbehaving"
```

### Environment

- Talos version: [`v1.7.6`]
- Kubernetes version: [`v1.31.0`]
- Platform: Windows and Debian in WSL

**Comment by smira** [comment]
This error message is coming from Talos (I guess in a container in your case), not from `talosctl`. 

Talos in containers since 1.7 uses Docker's resolver.

**Comment by nebula-it** [comment]
This is from Talos VM's on vSphere.
I see, is Talos trying to resolve `test-cluster-cp1`? Because that entry would not exist, as node names are populated in DNS from DHCP but no such entry would be added for cluster name.

**Comment by nebula-it** [comment]
Figured it out, it happens when there are multiple endpoints defined in talosconfig (Doesn't matter those are IPs or hostnames)
