### ISSUE TITLE
Specify additional DNS search domains

### ISSUE THREAD

**Issue by michaelbeaumont** [siderolabs/talos#9342]
## Feature Request

It should be possible to add arbitrary search domains to the Talos + k8s DNS configurations. This is possible at the moment only by making the node name an FQDN built on the search domain.

**Comment by smira** [comment]
For the pods, this is configurable in Kubernetes: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config

For the host resolver, this is something that Talos should implement.
