### ISSUE TITLE
 i915  - Transparent Hugepage support is recommended for optimal performance on this platform!

### ISSUE THREAD

**Issue by VxDlH** [siderolabs/talos#9363]
## Feature Request

Can you add the following kernel-level option to Talos images?

CONFIG_TRANSPARENT_HUGEPAGE=y

### Description

Why this recommendation with the i915 driver ?

The message suggests enabling Transparent Hugepages to take full advantage of Intel GPU performance. This can improve graphics performance in certain cases, such as :

- Improved graphics rendering: the GPU can access memory more efficiently when large memory pages are used.
- Reduced memory fragmentation: The system is able to better organize and manage memory with less fragmentation, which improves overall performance, especially on large or memory-intensive workloads.
- Lower page management costs: Fewer pages to manage means less overhead from address translation and kernel interrupts.

**Comment by smira** [comment]
Yes, this setting should be good, and not only for i915.
