### ISSUE TITLE
Support for Kitty - talosctl dashboard

### ISSUE THREAD

**Issue by chrede88** [siderolabs/talos#9377]
## Feature Request
I'm using the Kitty terminal emulator on my Mac. If I execute `talosctl dashboard` I get the following output:
```zsh
> talosctl -n <IP> dashboard                             
terminal type unsupported
```

### Description

It would be great if `talosctl` would integrate support for Kitty (and maybe other new-ish terminal emulator).

**Comment by smira** [comment]
What is your `$TERM` value?

**Comment by chrede88** [comment]
`xterm-kitty`

**Comment by smira** [comment]
cool, we can handle that. In fact we intentionally minimized supported terminals, but that makes sense when a dashboard runs in Talos itself, but doesn't make that much sense for `talosctl`
