### ISSUE TITLE
Enable CONFIG_KSM in kernel

### ISSUE THREAD

**Issue by rothgar** [siderolabs/talos#9380]
## Feature Request
This will enable [samepage merging](https://www.kernel.org/doc/html/latest/admin-guide/mm/ksm.html) for virtual machines running on top of Talos.

### Description
This can help reduce memory usage for nodes running multiple of the same VM. It's supported in KubeVirt and can be enabled via their config https://kubevirt.io/user-guide/cluster_admin/ksm/

**Comment by smira** [comment]
This is already enabled in v1.8.0: see https://github.com/siderolabs/pkgs/pull/974, see the notes there.
