### ISSUE TITLE
systemd-boot menu doesn't show the Talos entry on a specific ARM machine

### ISSUE THREAD

**Issue by sfackler** [siderolabs/talos#9397]
### Description

I picked up an [Ampere Altra motherboard + CPU combo](https://www.newegg.com/asrock-rack-altrad8ud-1l2t-q64-22-ampere-altra-max-ampere-altra-processors/p/N82E16813140134?Item=N82E16813140134) and am trying to install Talos on it. When I boot off of the Secure Boot installer, the systemd-boot menu only has the "Reboot Into Firmware Interface" option - the "Talos (v1.8.0)" option is missing entirely.

I can manually run `EFI/Linux/Talos-v1.8.0` from the EFI shell and Talos comes up fine.

I tried using the same installer in VMWare Fusion on my M1 MacBook and the boot entry was there as expected, so it seems to somehow be an issue specific to the hardware or firmware? I'm running the newest firmware version, and the rest of the workflow (key registration, etc) seems to work fine.

### Logs

Screenshot of the boot menu with the option missing on the real hardware:

![Screenshot 2024-09-14 200917](https://github.com/user-attachments/assets/40e5091b-9773-4e17-80a6-6a89d3d7e9d7)

Screenshot of the option present in VMWare Fusion:

![Screenshot 2024-09-18 at 9 32 20 PM](https://github.com/user-attachments/assets/d5f20c74-d85b-434b-9464-1be94767c9a4)

I did some extra debugging in a Slack thread with @frezbo: https://taloscommunity.slack.com/archives/CMARMBC4E/p1726360120076059.

### Environment

- Talos version: 1.6.0
- Kubernetes version: N/A
- Platform: arm64

**Comment by smira** [comment]
I don't have any exact idea, but looks to be a problem with UEFI firmware or some sd-boot incompatibility. 

`sd-boot` should automatically discover UKIs and parse information from them, so I guess UEFI environment doesn't allow to do that, or reports something wrong.

https://man.archlinux.org/man/systemd-boot.7#KEY_BINDINGS

**Comment by sfackler** [comment]
I have no idea why, but things started working after powering things back on after a few weeks. Very mysterious but if it works, it works :D

**Comment by solidDoWant** [comment]
I just ran into this issue. For some reason, the tool I'm using to create boot disks (Rufus 4.3, 4.6), removes the '.efi' extension from the Talos EFI stub file specifically. Because of this, systemd-boot doesn't recognize the file as a boot option.

This also explains why this issue did not occur with vmware fusion - the VM used the image directly, rather than copying it.

**Comment by sfackler** [comment]
That's it! I didn't even think that things started working when I mounted the ISO via the box's BMC instead of the Rufus-plugging in the flashed USB drive.

**Comment by frezbo** [comment]
We've identified that we do not generate the SecureBoot iso correctly, will fix for Talos 1.9, see #9565

**Comment by frezbo** [comment]
@sfackler would you be able to test an iso?

**Comment by solidDoWant** [comment]
@frezbo sure no problem. Can you point me to a download link/provide download instructions?

**Comment by frezbo** [comment]
> @frezbo sure no problem. Can you point me to a download link/provide download instructions?

if you're on slack i can use that, also do you need an amd64 or an arm64 iso?

**Comment by solidDoWant** [comment]
I just setup an account (@sdw1). AMD64 please.

I can also build the ISO myself if you prefer, if it can be done relatively easily.

**Comment by frezbo** [comment]
> I just setup an account (@sdw1). AMD64 please.
> 
> I can also build the ISO myself if you prefer, if it can be done relatively easily.

sent you an iso in slack, if needing to build locally can use this PR: #9580
