### ISSUE TITLE
Missing v1.8.0 AWS AMIs

### ISSUE THREAD

**Issue by james-callahan** [siderolabs/talos#9398]
## Bug Report

The AMIs for v1.8.0 didn't seem to get uploaded/made public?

### Description

```
$ curl -Ls https://github.com/siderolabs/talos/releases/download/v1.8.0/cloud-images.json | jq '.[] | select(.cloud == "aws" and .region=="us-east-1" and .arch=="amd64")' 
{
  "cloud": "aws",
  "version": "v1.8.0",
  "region": "us-east-1",
  "arch": "amd64",
  "type": "hvm",
  "id": "ami-0100b2a1f40f3ecf2"
}
```

The 1.7.6 AMI did show up
```
$ curl -Ls https://github.com/siderolabs/talos/releases/download/v1.7.6/cloud-images.json | jq '.[] | select(.cloud == "aws" and .region=="us-east-1" and .arch=="amd64")' 
{
  "cloud": "aws",
  "version": "v1.7.6",
  "region": "us-east-1",
  "arch": "amd64",
  "type": "hvm",
  "id": "ami-0ac760e31c48d2ce7"
}
```
![Screenshot 2024-09-30 at 12-12-06 Images EC2 us-east-1](https://github.com/user-attachments/assets/352cd206-c5f7-4ac8-bb74-fbdc3c5db712)

### Logs

When trying to use the AMI as given in cloud-images.json I get:
```
│ Error: collecting instance settings: empty result
```

### Environment

- Talos version: v1.8.0
- Platform: AWS

**Comment by smira** [comment]
Thanks for reporting this, we run into some AWS limits, it should be good now.

**Comment by tgardiner** [comment]
@smira, mind checking `ca-central-1`? I can't find any 1.8.0 AMIs there.

**Comment by smira** [comment]
> @smira, mind checking `ca-central-1`? I can't find any 1.8.0 AMIs there.

there might be some regions with AMIs being unpublished (private), I can fix that manually, but for 1.8.1 they should be all good.

> `ca-centeral-1` should be good now

**Comment by 0xLE** [comment]
@smira Mind checking `eu-south-1`?

**Comment by smira** [comment]
> @smira Mind checking `eu-south-1`?

We don't have AMIs published to that region, but you can upload yourself downloading an AMI from the [Image Factory](https://factory.talos.dev/).
