### ISSUE TITLE
Siderolink not working with Dockerized talos due to a non-existing node UUID

### ISSUE THREAD

**Issue by Orzelius** [siderolabs/talos#9400]
In my attempts at getting my hands dirty developing Talos & Omni I tried to get the local development setup running on my Mac using the Docker provider, but I've run into issues trying to get talos and omni communicating.

Due to the node `UUID` (coming from [hardware.SystemInformation](https://github.com/siderolabs/talos/blob/392c4798f0bff7cb4518609deae7c90581f013f5/pkg/machinery/resources/hardware/system_information.go#L23)) being zero-valued, the siderolink logic does not work. The `META UUIDOverride` logic can't be used due to it [not being available in container mode](https://github.com/siderolabs/talos/blob/392c4798f0bff7cb4518609deae7c90581f013f5/internal/app/machined/pkg/runtime/mode.go#L88). Once I hardcoded an UUID the siderolink with my local omni instance was established successfully.

I see the following solutions:
1. Support `META` on Docker and pass an UUID override when creating the container
2. In case of docker platform, generate a UUID from the container name, id or some other unique property
3. Make qemu provider work on Mac

I think having a way to develop and run omni and talos on Mac would be nice given the popularity of the platform. 
I'm not educated enough to judge which solution is best but I'd love to contribute if somebody would be kind enough to describe the best approach for solving the problem at hand.

Slightly related issues: https://github.com/siderolabs/omni/issues/38, https://github.com/siderolabs/talos/issues/7694

**Comment by Unix4ever** [comment]
There are many issues with Dockerized Talos joining Omni, `UUID` absence is not the last one.
We had an internal discussion around that before. It doesn't make much sense to add Dockerized Talos support into Omni as it's way too different from the regular one which makes it irrelevant for testing purposes.

You can try using VirtualBox for testing, it should be pretty straightforward: download the ISO from Omni and mount it into the manually created VMs.

**Comment by smira** [comment]
On mac, you can use UTM (if I remember the name correctly), the biggest blocker is the networking setup between VMs with the bridge and stuff; in Linux, we just leverage CNI plugins for that (that for VMs, not inside Talos), on Mac - I have no idea.

If someone wants to contribute some `talosctl cluster create` provider for Mac, we are all for it.

**Comment by Orzelius** [comment]
Thank you for the insights! I'll close this as apparently development with dockerized talos doesn't seem to make too much sense anyway. I'll try my hands at getting qemu to work on Mac. Might take me a bit given my shallow network expertise 🤞

**Comment by steverfrancis** [comment]
UTM on a mac is super easy. (So easy even a CEO and do it!)
It's based off qemu.

**Comment by githubcdr** [comment]
I think I had this issue too with 2 Zimaboards (almost identical hardware), they both seem to get the same UUID and in my case that caused an automatic deploy of a masternode, replacing the older node

**Comment by Orzelius** [comment]
@githubcdr In this case you could try using `talosctl meta write 0xf <uuid>` to write to the meta `UUIDOverride` field. If you're using omni you can bump the issue that would solve this https://github.com/siderolabs/omni/issues/38

(`0xf` is the ID of the `UUIDOverride field`, which might change if the upgrade index is bumped) https://github.com/siderolabs/talos/blob/7acadc0c8fa969e4de7f0d4f68b0fd0cd833b489/pkg/machinery/meta/constants.go#L27
https://github.com/siderolabs/talos/blob/7acadc0c8fa969e4de7f0d4f68b0fd0cd833b489/pkg/machinery/meta/constants.go#L9
