### ISSUE TITLE
unifying protobuf/grpc codec implementation

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#9404]
* [x] Update services
  * [x] Discovery Service
  * [x] Talos
  * [x] Omni
* [x] grpc CodecV2
* [x] Support proto interfaces
  * [x] protobuf
  * [x] gogo
  * [x] vtprotobuf

**Comment by DmitriyMV** [comment]
We should [update](https://github.com/siderolabs/grpc-proxy/blob/ec3b59c869000243e9794d162354c83738475a32/proxy/codec.go) grpc-proxy too.

**Comment by DmitriyMV** [comment]
With talos PR [merged](https://github.com/siderolabs/talos/pull/9424), this is now closed.
