### ISSUE TITLE
Implement update-ca-certificates for Talos, so own CA + Omni works correctly.

### ISSUE THREAD

**Issue by Hacksawfred3232** [siderolabs/talos#9417]
## Feature Request
Actually implement a proper CA certificate injection system, instead of whatever these are:
https://www.talos.dev/v1.8/talos-guides/configuration/certificate-authorities/
https://www.talos.dev/v1.8/talos-guides/network/corporate-proxies/
### Description
So, I've been bashing my head against a wall, trying to figure out how to inject a CA certificate into Talos Linux so then it can connect back to Siderolabs Omni over Siderolink gRPC, which is behind a custom CA. I've been using a combination of the aforementioned ways of side-loading CA certificates. Which works okay, until the second I install plugins (I think the problem child is "nut", Network UPS tools client) after install, or just having them outright installed in the ISO or base image of Talos Linux and then provisioning the nodes. Upon reboot, the nodes lose connection to Omni, spewing out "Unknown certificate authority", as it appears that something calls "mk-ca-bundle.pl version 1.29" and wipes out the certificates added by me.

In other Linux distros, there is a mechanism called "update-ca-certificates". It loads both factory certificates bundles from Mozilla and user supplied CA certificates, allowing users to inject custom/corporate CA certificates. I'm guessing the two pages mentioned is supposed to be Talos' method of doing this, except _it doesn't work._ Especially if a plugin then over-writes the injected CA certificates. Oh, and the "certificate-authorities" document can't be used in a config patch inside Omni, nor inside a boot parameter (talos.config.inline) (talos.config.inline=<encoded/compressed config> does nothing to begin with anyway...), so that option isn't viable either. So perhaps instead of this bodged solution, maybe implement a proper "update-ca-certificates" mechanism, so plugins and the user can't step over each other and ultimately break everything? Especially considering Omni is sold as the "best commercial solution for running Kubernetes", and not having a proper CA injection mechanism really spits in the face of that marketing.

**Comment by smira** [comment]
I understand your frustration, but it's way better to pick a pointed discussion towards a specific problem which isn't in your issue.

The `talos.config.inline=` way works and it's tested automatically, so it's not a valid claim that it doesn't work.

Omni doesn't yet fully support Talos 1.8.0, but once again, as long as you submit a pointed ticket it would be way easier to have a discussion.

What kind of a plugin overwrites CA certificates?

> Note: using Let's Encrypt to provide proper trusted certificates is way easier.

**Comment by Hacksawfred3232** [comment]
> The `talos.config.inline=` way works and it's tested automatically, so it's not a valid claim that it doesn't work.

Okay, proof? Because I've tried it on my system, and it doesn't work. I've followed the documentation exactly, and adding a yaml file that contains some parameters from Omni plus the "certificate-authorities" document doesn't do anything.

> What kind of a plugin overwrites CA certificates?

Well, a bare-minimum setup I have that triggers the bug is "btrfs" and "nut". Btrfs is for file systems, so I think we can rule that one out. So it's gotta be "nut". Because when it's not there, everything is fine. But the second "nut" is installed, instant regret, and the infinite flow of "Unknown certificate authority" errors. I mean, it could be some other Talos component that's recreating the ca-certificates file, but for some reason it only triggers when a particular plugin is installed!?!?

> > Note: using Let's Encrypt to provide proper trusted certificates is way easier.
Doesn't matter. Even if I re-plan everything to try and somehow ham-fist LE certs into my scheme (everything is managed with Ansible), good luck trying to add deep inspection proxies CA certificates.

**Comment by smira** [comment]
> Okay, proof? Because I've tried it on my system, and it doesn't work. I've followed the documentation exactly, and adding a yaml file that contains some parameters from Omni plus the "certificate-authorities" document doesn't do anything.

https://github.com/siderolabs/talos/pull/9315

If you hit a problem, supply the steps to reproduce and create a specific issue with all relevant logs available at that state. 

> But the second "nut" is installed, instant regret, and the infinite flow of "Unknown certificate authority" errors.

I guess you might be missing the CA config in the Omni as a config patch, and it has nothing to do with any extensions, but once again without steps to reproduce it's all about nothing.

I'm going to close this issue, as it's not relevant, but please feel free to open a specific issue with relevant information.
