### ISSUE TITLE
upgrade-k8s hangs at "waiting for kubelet restart"

### ISSUE THREAD

**Issue by solarisfire** [siderolabs/talos#9441]
### Description

Today I've done two k8s upgrades:

1.30.4 -> 1.30.5
1.30.5 -> 1.31.1

The upgrade goes fine with no errors until I get to the point of updating the kubelet, which updates fine, but the upgrade is left hanging at: "waiting for kubelet restart".

Hitting ctrl+c and rerunning the upgrade command gets past this point, so it seems that the upgrade code is just hanging waiting for some event that never comes?

### Logs

<pre>
updating kube-proxy to version "1.31.1"
 > "10.0.1.101": starting update
 > "10.0.1.102": starting update
 > "10.0.1.103": starting update
updating kubelet to version "1.31.1"
 > "10.0.1.101": starting update
 > update kubelet: 1.30.5 -> 1.31.1
 > "10.0.1.101": machine configuration patched
 > "10.0.1.101": waiting for kubelet restart
</pre>

### Environment

- Talos version: Talos 1.8.0
- Kubernetes version: 1.30.4 & 1.30.5
- Platform: Hetzner Cloud (3 node cluster with floating IP)
Client:
        Tag:         v1.8.0
        SHA:         5cc935f7
        Built:       
        Go version:  go1.22.7
        OS/Arch:     linux/amd64

**Comment by solarisfire** [comment]
Console is reporting version 1.31.1, and healthy, but it remains hanging...

![image](https://github.com/user-attachments/assets/b95f0057-48b6-441c-a41e-b716391f2483)

**Comment by solarisfire** [comment]
After a quick look at the code behind this, it'll be tricky to work out without adding extra logging around the watchCh channel.

I'm wondering if the kublet restarts so fast that it's ready before the event watcher even has time to start up.

**Comment by smira** [comment]
Please submit `talosctl support` bundle when it hangs

**Comment by solarisfire** [comment]
I have it in a hanging state right now, I ran the support bundle in a separate terminal while it hung in the first.
 
[support.zip](https://github.com/user-attachments/files/17257529/support.zip)

**Comment by smira** [comment]
which node was it hanging on when the bundle was created?

**Comment by solarisfire** [comment]
control-plane-3, the one I ran the support bundle against.

**Comment by smira** [comment]
Thanks for the data, I will look into that, but still the bug is not quite clear.

**Comment by solarisfire** [comment]
As I said in my previous comment, I'm wondering if  the kublet restarts so fast that it's ready before the event watcher in the talosctl upgrade-k8s even has time to start up. In which case it would never see the state.Destroyed, state.Created, or state.Updated events it's waiting for.

That logic could probably be modified to check the kubelet after a time window, rather than just waiting forever for an event change:

Something like:

</pre>timeout := time.After(30 * time.Second)
for {
    select {
    case ev = <-watchCh:
        if ev.Type() == state.Destroyed {
            break
        }
    case <-timeout:
        options.Log("Timeout reached, checking kubelet status manually")
        kubeletSpec, err := safe.StateGet[*k8s.KubeletSpec](ctx, c.COSI, resource.NewMetadata(k8s.NamespaceName, k8s.KubeletSpecType, kubelet, resource.VersionUndefined))
        if err == nil && kubeletSpec.TypedSpec().Running && kubeletSpec.TypedSpec().Healthy {
            options.Log("Kubelet is running and healthy, continuing")
            return nil
        }
        return ctx.Err()
    case <-ctx.Done():
        return ctx.Err()
    }
}</pre>

**Comment by smira** [comment]
if you look into the code, you will see that watcher starts before the kubelet is upgraded

**Comment by solarisfire** [comment]
kubelet.go

Line 100 it initiates the kubelet upgrade:

<pre>
err = patchNodeConfig(ctx, cluster, node, options.EncoderOpt, upgradeKubeletPatcher(options, kubeletSpec))
</pre>

Line 116 it sets up a for loop where it waits for a state.Destroyed event:

<pre>
// first, wait for kubelet to go down
		for {
			select {
			case ev = <-watchCh:
			case <-ctx.Done():
				return ctx.Err()
			}

			if ev.Type() == state.Destroyed {
				break
			}
		}
</pre>

Output isn't verbose enough to know if this event is ever received.

It then establishes another watcher waiting for up and healthy events, and handles a few potential errors:

<pre>
// now wait for kubelet to go up & healthy
		for {
			select {
			case ev = <-watchCh:
			case <-ctx.Done():
				return ctx.Err()
			}

			if ev.Type() == state.Created || ev.Type() == state.Updated {
				var service *v1alpha1.Service

				service, err = ev.Resource()
				if err != nil {
					return fmt.Errorf("error inspecting service: %w", err)
				}

				if service.TypedSpec().Running && service.TypedSpec().Healthy {
					break
				}
			}
		}
</pre>

But there is no logic to handle a situation where no events are received at all? Which could be caused by a multitude of off-nominal scenarios?

**Comment by smira** [comment]
this is not the code which establishes the watcher, it is the code which receives watch events, the watcher is established way before that.

**Comment by smira** [comment]
From your initial post:

> with floating IP

Do you use floating IP as the `talosconfig` endpoint? 

If you do, that is unsupported, as it will break gRPC connections behind the scenes. Endpoints should be direct IPs of the controlplane machines.

**Comment by solarisfire** [comment]
Ah, yes I did...

I use the following terraform module to build the cluster: https://registry.terraform.io/modules/hcloud-talos/talos/hcloud/latest

This outputs a talosconfig that looks like:

<pre>
[solarisfire@astra talos]$ cat talosconfig 
context: solarisfire.com
contexts:
    solarisfire.com:
        endpoints:
            - **.***.***.**
        ca: LS0t**tLS0tCg==
        crt: LS0**UtLS0tLQo=
        key: LS0tL***VZLS0tLS0K
</pre>

And that endpoint is a floating ip that will always sit in front of a healthy control plane. I guess they shouldn't be creating a talosconfig like this then? What should it be pointing to? Or should it be a list of direct ips?

**Comment by smira** [comment]
Just the list of direct IPs/DNS names, never VIPs, Floating IPs or anything which can float between matchines.

https://www.talos.dev/v1.8/introduction/prodnotes/#endpoints

**Comment by solarisfire** [comment]
And your talosctl config isn't using the floating IP?

I've just modified mine to have the direct IP of the 3 control-plane nodes and talosctl is behaving much beter!

**Comment by solarisfire** [comment]
Yeah, give it a test:

I now have:

<pre>
contexts:
    solarisfire.com:
        endpoints:
            - *.*.*.*
            - *.*.*.*
            - *.*.*.*
</pre>

In my talosctl configuration, and each of those addresses is the external address of a control plane node. I just rebooted one of the control plane nodes using talosctl and the command updated through each step of the reboot correctly rather than just hanging :-)

**Comment by smira** [comment]
The technical detail is that any TCP long-running connection can't detect reliably and quickly that the IP moved to another machine, so it will just hang until one or another timeout.

Talos API client does automatic failover and load-balancing, so just specify direct endpoints, and it will always work as expected.

**Comment by nightguide** [comment]
@solarisfire Hi!

I fixed my talosconfig file (set Direct IP's) and now I no longer have problems with stucking when updating the version of Talos or Kubernetes on control plane nodes.

@smira @solarisfire Thanks!
