### ISSUE TITLE
Add newer well-known `app.kubernetes.io/` labels to control plane Pods

### ISSUE THREAD

**Issue by michaelbeaumont** [siderolabs/talos#9450]
## Feature Request

In addition to `tier` and `k8s-app` the control plane pods should probably use labels such as `app.kubernetes.io/part-of` and `app.kubernetes.io/name`. Those would be my suggestions for the analog labels at least. It might be worth checking what labels/values other distributions/tools set.

### Description

I suspect `tier` and `k8s-app` are older well-known labels but the `app.kubernetes.io` labels are by now pretty well established and understood by other tools, for example Loki.

Happy to make a PR one of these days, just adding these and leaving the others for now, if it would be approved.

**Comment by smira** [comment]
A PR would be appreciated, you need to add labels here: https://github.com/siderolabs/talos/blob/d4403c8d1cd3aa5e145152b16e44621fe2c8c71f/internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go#L464-L468

(and same for other pods)
