### ISSUE TITLE
Find a way to use `grpc-go >= 1.67.0` with `ALPN` disabled

### ISSUE THREAD

**Issue by DmitriyMV** [siderolabs/talos#9463]
Starting with [v1.67.0](https://github.com/grpc/grpc-go/releases/tag/v1.67.0) Go gRPC implementation no longer work with TLS connections that don't support ALPN. There is a special header `GRPC_ENFORCE_ALPN_ENABLED` which, when set to `false`, should disable this behavior. But setting it after the process started (even in `init` block) has no effect, because [relevant variable](https://github.com/grpc/grpc-go/blob/859602c14c6c8bcc4f3b7e6c129577229c9f9294/internal/envconfig/envconfig.go#L48) initialization happens before any init blocks.

**Comment by smira** [comment]
My first question - does Talos set up TLS wrong way so that it's not ALPN-enabled? We should fix it in the first place.

**Comment by howardjohn** [comment]
@smira just stumbled upon this while working on another project. I found if you use GetConfigForClient you may not get the ALPN set properly. See https://github.com/cert-manager/istio-csr/pull/422

**Comment by smira** [comment]
Thank you, that should be the case for us, as we do live cert reload.

**Comment by DmitriyMV** [comment]
So this is actually interesting: basically all relevant code in Talos uses [credentials.NewTLS](https://pkg.go.dev/google.golang.org/grpc@v1.67.1/credentials#NewTLS) which internally uses [AppendH2ToNextProtos](https://github.com/grpc/grpc-go/blob/v1.67.1/internal/credentials/util.go#L28) which ensures that we have "h2" in TLS config. Except in our crypto library we indeed use [GetConfigForClient](https://github.com/siderolabs/crypto/blob/v0.4.4/tls/tls.go#L115) which drops doesn't carry changes that gRPC did to `tls.Config` since they operate on copy.

What is good, is that even before gRPC 1.67.0 the client would send the proper "h2" tag during negotiation. It should have warned us about incorrect ALPN [settings](https://github.com/grpc/grpc-go/blob/v1.66.0/credentials/tls.go#L129) even on [v1.65.0](https://github.com/grpc/grpc-go/blob/v1.65.0/credentials/tls.go#L133) gRPC but I guess we are silencing that log somewhere. I also have **no idea how that works in the first place**, since Go TLS [negotiateALPN](https://cs.opensource.google/go/go/+/refs/tags/go1.23.2:src/crypto/tls/handshake_server.go;l=291) should revert to http/1.1 if there is no proper ALPN.

**Comment by smira** [comment]
Whatever way we end up with fixing it, we should have a way for 1.9 `talosctl` to talk to 1.8 Talos.
