### ISSUE TITLE
Talos upgrade encounters kmsg error

### ISSUE THREAD

**Issue by chrede88** [siderolabs/talos#9483]
## Bug Report

While upgrading to Talos `v1.8.1`, the upgrade failed (but somehow recovered) because it can't read from `/dev/kmsg`.

The installer was successful, but the "watcher" script (`talosctl upgrade`) on my machine was hanging even after everything was back up and in a good state.

### Logs

dmesg error output:
```
2 errors occurred:
 error reading from kmsg: read /dev/kmsg: file already closed
 rpc error: code = Unknown desc = close /dev/kmsg: file already closed
```

### Environment

- Talos version: v1.8.0
- Kubernetes version: v1.31.1
- Platform: Bare-metal

**Comment by smira** [comment]
This should be harmless, this is I guess an error on the client side (`talosctl`).
