### ISSUE TITLE
talosctl health gives "rpc error: code = PermissionDenied desc = no request forwarding"

### ISSUE THREAD

**Issue by MichaelTrip** [siderolabs/talos#9485]
## Bug Report

I transferred roles from certain worker nodes from control plane to worker. After that, talosctl health gives a error when requesting the health. `rpc error: code = PermissionDenied desc = no request forwarding`

### Description

I converted my cluster from 3 nodes with a combined role (control plane and worker) to worker only roles. I added a control plane and after that i did the following:

- A talosctl reset on the node
- A new apply with the same hostname with the worker.yaml

Everything works, but when i run `talosctl healtn -n <nodeip>` on a former control plane node i get the following message:

```
 talosctl health -n 10.99.101.1
discovered nodes: ["10.99.101.1" "10.99.101.2" "10.99.101.3" "10.99.101.9"]
waiting for etcd to be healthy: ...
```

and it just hangs. 

### Logs
``` 
talosctl health -n 10.99.101.1
discovered nodes: ["10.99.101.1" "10.99.101.2" "10.99.101.3" "10.99.101.9"]
waiting for etcd to be healthy: ...
```
### Environment

- Talos version: v1.7.6
- Kubernetes version: v1.30.3
- Platform: Proxmox / virtual machines

**Comment by smira** [comment]
You're using worker nodes as endpoints in `talosconfig`, this is not allowed.
