### ISSUE TITLE
Resource type "cpus" is ambiguous

### ISSUE THREAD

**Issue by sprat** [siderolabs/talos#9519]
## Bug Report

Since the introduction of the pcidevices resource, the following command fails:
```bash
$ talosctl --talosconfig=talosconfig get cpus
rpc error: code = InvalidArgument desc = resource type "cpus" is ambiguous: [cpustats.perf.talos.dev pcidevices.hardware.talos.dev processors.hardware.talos.dev]
```

The mistake seems to lie [here](https://github.com/siderolabs/talos/blob/5c5a248861c8e5848f9a23cd0cd7b3b749f21e4b/pkg/machinery/resources/hardware/pcidevice.go#L53)

### Description

See above

### Logs

N/A

### Environment

- Talos version: v1.8.1
- Kubernetes version: v1.31.1
- Platform: metal

**Comment by smira** [comment]
Yes, thank you, that is definitely a bug.
