### ISSUE TITLE
Config_patches are invalid due to unknown keys found during decoding

### ISSUE THREAD

**Issue by alexvanderberkel** [siderolabs/talos#9544]
### Description

I am trying to deploy a Talos cluster with version 1.8.1 and the latest terraform provider. I would like to make use of the new volume feature. This is the machine config that I am passing into terraform. 

This is worker.yaml.tftpl file: 

`machine:
  network:
    hostname: ${hostname}
  nodeLabels:
    topology.kubernetes.io/region: ${cluster_name}
    topology.kubernetes.io/zone: ${node_name}           
  provisioning:
    diskSelector:
        match: system_disk
    minSize: 2GiB
    grow: true
`

Error I am getting is: 

`│ Error: config_patches are invalid
│ 
│   with data.talos_machine_configuration.machine_configuration["talos-node-1"],
│   on talos.tf line 16, in data "talos_machine_configuration" "machine_configuration":
│   16: data "talos_machine_configuration" "machine_configuration" {
│ 
│ unknown keys found during decoding:
│ machine:
│     provisioning:
│         diskSelector:
│             match: system_disk
│         minSize: 2GiB
│         grow: true
│ 
╵`

I am uncertain if this is possible or if I am on the wrong track as I cannot find anything in the docs: https://www.talos.dev/v1.8/reference/configuration/v1alpha1/config/

### Environment

- Talos version: 1.8.1
- Kubernetes version: 1.31

**Comment by frezbo** [comment]
You're supposed to used the volumeconfig https://www.talos.dev/v1.8/reference/configuration/block/volumeconfig/

not sure where you found the `provisioning` key, it's not referenced anywhere

**Comment by smira** [comment]
That is certainly wrong config patch.

You can play with it offline via `talosctl gen config ... --config-patch @file.yaml` 

https://www.talos.dev/v1.8/reference/configuration/block/volumeconfig/

https://www.talos.dev/v1.8/talos-guides/configuration/disk-management/#machine-configuration
