### ISSUE TITLE
Installer only processing first mirror in image-mirrors list

### ISSUE THREAD

**Issue by PrivatePuffin** [siderolabs/talos#9554]
### Description

When image mirrors are being used for the image factory, the installer seems to only try the first one.
If that one is wholly unavailable it seems to get stuck.

### Expected behavior

It should try them in-order and fall back to the normal endpoint if all mirrors fail.
(this is standard docker/containerd/any-container-backend-really, behavior)

### Example Config:

```
      factory.talos.dev:
        endpoints:
          - http://127.0.0.1:30020
          - http://127.0.0.1:30021
```

### Logs

![2024-10-23_14_09_25-Spice_Javascript_client_-_Brave](https://github.com/user-attachments/assets/b48301e8-4aa2-4bad-b057-5c79a4d5c3df)

### Environment

- Talos version: v1.8.1
- Kubernetes version: v1.31
- Platform: Irrelevant

**Comment by smira** [comment]
The installer doesn't use mirrors, can you supply the logs?

**Comment by PrivatePuffin** [comment]
@smira Sorry, wrong logs.
And I meant the Apply/bootstrap done during install.

**Comment by smira** [comment]
Screenshot is not informative either - it just says the first one failed, and it keeps trying.

If you have a log which shows the problem, please re-open the issue.

**Comment by PrivatePuffin** [comment]
> Screenshot is not informative either - it just says the first one failed, and it keeps trying.
> 
> If you have a log which shows the problem, please re-open the issue.

Whut, this IS the problem?!
It looks like this resolving takes the Containerd mirrors, but only keeps trying the first one.
Which is not normal behavior.

it should fail over to the next, and the next and then use the main url as a fallback.

These ARE your logs, showing the problem:
It should've failed over to the next mirror etc, which it isn't doing.

**Comment by smira** [comment]
> Closing this so easily is also incredibly rude.

Leaving open issues which are not relevant confuses other users. We treat all bugs as first class citizens, but it should be a real bug.

> It looks like this resolving takes the Containerd mirrors, but only keeps trying the first one.

There's nothing in the log so far. It tried the first one, and probably hangs on the next one, but impossible to guess (I have no idea what you're doing with these localhost entries).

> it should fail over to the next, and the next and then use the main url as a fallback.

No, it shouldn't use main URL as a fallback, as documented.

**Comment by PrivatePuffin** [comment]
> No, it shouldn't use main URL as a fallback, as documented.

Actually, that explains the issue a lot.
But I dont see where you got that information?

Its does fall back to the normal non mirror. Thats so standard that k3s in their config design, had to make explicit exemptions to allow it to NOT fall back.

**Comment by smira** [comment]
I'm not sure about k3s and Spegel, these are not our projects. 

But I think I found the bug itself.

**Comment by smira** [comment]
Or probably not, anyways, it's easy to test instead of doing false assumptions.

**Comment by PrivatePuffin** [comment]
> I'm not sure about k3s and Spegel, these are not our projects.

Yeah understandable.
Ive went over containerd docs and other examples again, and *all examples* I can find state it should fail over.


> Or probably not, anyways, it's easy to test instead of doing false assumptions.

No worries happens all the time.

**Comment by smira** [comment]
No there's no bug, it works as expected:

```
 5237.764781] [talos] validating "127.0.0.1:5005/siderolabs/installer:v1.9.0-alpha.0-9-g38b1d348f4-dirty"
INFO[5237] trying next host                              error="failed to do request: Head \"http://172.20.0.1:5015/v2/siderolabs/installer/manifests/v1.9.0-alpha.0-9-g38b1d348f4-dirty?ns=127.0.0.1%3A5005\": dial tcp 172.20.0.1:5015: connect: connection refused" host="172.20.0.1:5015"
INFO[5237] trying next host                              error="failed to do request: Head \"http://172.20.0.1:5016/v2/siderolabs/installer/manifests/v1.9.0-alpha.0-9-g38b1d348f4-dirty?ns=127.0.0.1%3A5005\": dial tcp 172.20.0.1:5016: connect: connection refused" host="172.20.0.1:5016"
```

Two failovers and the third endpoint works, so your case is something else broken, and the issue is not valid.

As for the default fallback, it [might be true for containerd](https://github.com/containerd/containerd/blob/main/docs/hosts.md#server-field), but Talos doesn't do it, so the most explicit way is to set it up explicitly if needed.

**Comment by smira** [comment]
> Might I suggest explicitly noting this in the docs?

We'll think about it. I think containerd would fallback, while Talos would not. Need a bit more digging to understand fully.

**Comment by PrivatePuffin** [comment]
> > Might I suggest explicitly noting this in the docs?
> 
> We'll think about it. I think containerd would fallback, while Talos would not. Need a bit more digging to understand fully.

Appreciate the effort!
