### ISSUE TITLE
Graceful node shutdown

### ISSUE THREAD

**Issue by michaelbeaumont** [siderolabs/talos#9556]
## Feature Request

Talos should ideally support [graceful node shutdown](https://kubernetes.io/docs/concepts/cluster-administration/node-shutdown/#graceful-node-shutdown).

### Description

I'm assuming this isn't supported at the moment because it seems to require some amount of systemd:

> The Graceful node shutdown feature depends on systemd since it takes advantage of [systemd inhibitor locks](https://www.freedesktop.org/wiki/Software/systemd/inhibit/) to delay the node shutdown with a given duration.

Which looks like it requires D-Bus. Can a minimal amount of support for this be included without depending too deeply on systemd?

**Comment by frezbo** [comment]
This is already supported in Talos, we implement a fake d-bus and inform kubelet

**Comment by michaelbeaumont** [comment]
Ah great!
