### ISSUE TITLE
Configuration issue prohibiting cluster to be ready

### ISSUE THREAD

**Issue by alexvanderberkel** [siderolabs/talos#9563]
## Bug Report

Most likely an error on my side due to misconfigs. However, I hope to get some hint on what I am doing wrong. Thanks for all your efforts upfront.

### Description

The following error is thrown: 

user: warning: [2024-10-24T13:55:47.714125834Z]: [talos] controller failed {"component": "controller-runtime", "controller": "k8s.NodeApplyController", "error": "1 error(s) occurred:\n\terror getting node: nodes \"talos-node-0\" not found"}  

Dashboard looks the following:

![image](https://github.com/user-attachments/assets/a782a480-1f5e-47c2-aae6-1f3bdaea9770)

Config Patches for Control Plane are:

cluster_name= homelab
hostname: controlplane-0
node-name:  controlplane-0

`machine:
  network:
    hostname: ${hostname}
    extraHostEntries: 
      - ip: ${ip}
  install:
    disk: ${disk}
    wipe: false
  features:
    hostDNS:  
      enabled: false
      forwardKubeDNSToHost: false 
  nodeLabels:
    topology.kubernetes.io/region: ${cluster_name}
    topology.kubernetes.io/zone: ${node_name}     

cluster:
  allowSchedulingOnControlPlanes: true
  network:
    cni:
      name: none
  proxy:
    disabled: true
`

### Environment

- Talos version: 1.8.1
- Kubernetes version: 1.31.1
- Platform: ubuntu

**Comment by smira** [comment]
First of all, you can check with `kubectl get nodes` yourself.

The node readiness doesn't depend on this error though (or it shouldn't?).

The best way is to attach `talosctl support` bundle so that we could take a look.

**Comment by alexvanderberkel** [comment]
The nodes are not ready as the output of `kubectl get nodes` suggests:

NAME             STATUS     ROLES           AGE     VERSION
controlplane-0   NotReady   control-plane   5h56m   v1.31.1
controlplane-1   NotReady   control-plane   5h56m   v1.31.1
controlplane-2   NotReady   control-plane   5h56m   v1.31.1
worker-0         NotReady   <none>          5h56m   v1.31.1
worker-1         NotReady   <none>          5h56m   v1.31.1

This is for the controlplane-0 the output of talosctl support:
[support.zip](https://github.com/user-attachments/files/17512180/support.zip)

I am not sure why the node readiness is not getting up.

**Comment by smira** [comment]
your Cilium install doesn't work, probably because the documentation submitted is not correct: #9495 

as CNI is not up, nodes are not ready (you can see it yourself in the e.g. `kubectl describe node`).

If you're not comfortable yet with Kubernetes/CNI, I would recommend to stick with Talos default Flannel CNI.

If you would like to use Cilium, disable Flannel in Talos machine config, and follow Cilium documentation for installing it (e.g. using `cilium` CLI). This way you get better understanding of the process and quick feedback.

Once you feel comfortable managing CNIs, you can try to automate install using one or another method.

**Comment by alexvanderberkel** [comment]
Thanks @smira! I thought that the CNI was the problem as well yesterday night. Though I wasn't sure as I was using the inline manifest from the docu with method 5. I'll give it try with flannel and try to locate the issue in the cilium config.
