### ISSUE TITLE
Load config failed when boot from USB on baremetal

### ISSUE THREAD

**Issue by mmakarov-muse** [siderolabs/talos#9589]
## Bug Report
Talos does not read the configuration when installed and booted from a USB stick on bare-metal host. 

### Description
```
$ talosctl -n IP disks -i
DEV            MODEL                        SERIAL           TYPE      UUID   WWID                                   MODALIAS      NAME   SIZE     BUS_PATH                                                                                                     SUBSYSTEM          READ_ONLY   SYSTEM_DISK
/dev/sda       Transcend 64GB               -                HDD       -      -                                      scsi:t-0x00   -      62 GB    /pci0000:00/0000:00:02.1/0000:03:00.0/0000:04:0c.0/0000:0b:00.0/usb2/2-1/2-1:1.0/host0/target0:0:0/0:0:0:0   /sys/class/block               *
```

I deployed Talos to /dev/sda
```
root@rescue ~ # wget https://factory.talos.dev/image/6905bc709e5947573a4ec2d11723b58882936d3d0e15c708f7d78f0c689684a5/v1.8.1/metal-amd64.raw.zst

root@rescue ~ # zstdcat ./metal-amd64.raw.zst | dd of=/dev/sda bs=1M
0+19942 records in
0+19942 records out
1306525696 bytes (1.3 GB, 1.2 GiB) copied, 16.9795 s, 76.9 MB/s
```

After reboot the host, Talos booted without hostname
```
$ talosctl -n IP get hostname -i
NODE   NAMESPACE   TYPE   ID   VERSION   HOSTNAME   DOMAINNAME
```

After I applied worker config with hostname `hz50`
```
$ grep hostname ./worker.yaml 
    hostname: hz50

talosctl -n IP apply-config -f ./worker.yaml -i
```

Config applied and worker registered in kube cluster
```
$ talosctl -n IP get hostname
NODE            NAMESPACE   TYPE             ID         VERSION   HOSTNAME   DOMAINNAME
IP   network     HostnameStatus   hostname   1         hz50       

 kubectl get nodes
NAME    STATUS   ROLES           AGE    VERSION
hz50    Ready    <none>          2d3h   v1.31.1
```

Next step - fully reboot the host.
I applied "hardware reset" in Hetzner control panel.

After host reboot Talos booted in the default configuration (no config)
```
$ talosctl -n IP get hostname
rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate signed by unknown authority"

$ talosctl -n IP get hostname -i
NODE   NAMESPACE   TYPE   ID   VERSION   HOSTNAME   DOMAINNAME
```

I applied config again and try to cat config file from disk
```
$ talosctl -n IP cat /system/state/config.yaml | grep hostname
    hostname: hz50
```
Config stored on disk.

I guess, that problem in boot sequence.
dmesg log below:
```
$ talosctl -n 144.76.154.70 dmesg | grep -n 'loadConfig\|sda5'
1933:144.76.154.70: kern:    info: [2024-10-28T15:30:34.061539115Z]:  sda: sda1 sda2 sda3 sda4 sda5 sda6
1951:144.76.154.70: user: warning: [2024-10-28T15:30:34.074359115Z]: [talos] task loadConfig (1/1): starting
1958:144.76.154.70: kern:    info: [2024-10-28T15:30:34.184486115Z]:  sda: sda1 sda2 sda3 sda4 sda5 sda6
1960:144.76.154.70: kern:    info: [2024-10-28T15:30:34.291628115Z]:  sda: sda1 sda2 sda3 sda4 sda5 sda6
2001:144.76.154.70: user: warning: [2024-10-28T15:33:51.268123115Z]: [talos] task loadConfig (1/1): done, 3m17.191987044s
2020:144.76.154.70: kern:  notice: [2024-10-28T15:33:51.269342115Z]: XFS (sda5): Mounting V5 Filesystem 125e8f1f-a559-4719-a179-a2a28032064e
2023:144.76.154.70: kern:  notice: [2024-10-28T15:33:51.406989115Z]: XFS (sda5): Starting recovery (logdev: internal)
2024:144.76.154.70: kern:  notice: [2024-10-28T15:33:51.424529115Z]: XFS (sda5): Ending recovery (logdev: internal)
```

As can you see Talos tried to loadConfig before mounting state file system.

- Talos version: checked on 1.8.1, 1.8.2
- Platform: baremetal

**Comment by mmakarov-muse** [comment]
Since this is a remote bare-metal host, it's challenging to collect logs from the com console.
But, here's the dmesg output from the same boot, and here’s why.
In short, the steps were as follows:
1. Deployed Talos.
2. Applied the configuration.
3. Rebooted the host (here, the config didn’t load from sda5).
4. Re-applied the configuration (the host wasn’t rebooted).
5. Collected dmesg. This dmesg should be from step 3.

Hetzner support reports that the server has no serial port.  
What options are available to obtain console logs in maintenance mode from a remote bare-metal server without a serial port?  
The host has no IPMI; it’s a regular desktop server.

**Comment by smira** [comment]
> What options are available to obtain console logs in maintenance mode from a remote bare-metal server without a serial port?

Nothing easy, you could try SideroLink, but this is not easy to manage.

The fact that `STATE` is mounted after `loadConfig` is totally expected (on no machine config), as it gets created only after machine config is submitted.

One thing you could check with maintenance mode is `talosctl get dv` after reboot (when it "loses" machine config).

**Comment by vitaly-zverev** [comment]
> The fact that `STATE` is mounted after `loadConfig` is totally expected (on no machine config), as it gets created only after machine config is submitted.
> 
AFAIK, it's unexpected order of events in regular booting of configured machine. 
In contrast, we should see the stable opposite order, when STATE is mounted before loadConfig. 
For example, It was observed on raspberry pi, with single USB drive (Talos v1.8.0, v1.8.1):
```
user: warning: [2024-10-28T12:59:26.519286771Z]: [talos] phase mountSystem (10/12): 1 tasks(s)
 user: warning: [2024-10-28T12:59:26.525615771Z]: [talos] task mountStatePartition (1/1): starting
 kern:  notice: [2024-10-28T12:59:26.534926771Z]: XFS (sda5): Mounting V5 Filesystem 677e91f1-ef96-4218-b937-dc979cbe2ca4
 kern:    info: [2024-10-28T12:59:26.568455771Z]: XFS (sda5): Ending clean mount
 user: warning: [2024-10-28T12:59:26.574963771Z]: [talos] task mountStatePartition (1/1): done, 49.355963ms
 user: warning: [2024-10-28T12:59:26.582473771Z]: [talos] node identity established {"component": "controller-runtime", "controller": "cluster.NodeIdentityController", "node_id":
 "mnqlWq6hWdOdiuREfKh16a9C5aOCOkzMe2egSf6g3YxB"}
 user: warning: [2024-10-28T12:59:26.601124771Z]: [talos] phase mountSystem (10/12): done, 63.238963ms
 user: warning: [2024-10-28T12:59:26.607763771Z]: [talos] phase config (11/12): 1 tasks(s)
 user: warning: [2024-10-28T12:59:26.613357771Z]: [talos] task loadConfig (1/1): starting
 user: warning: [2024-10-28T12:59:26.631297771Z]: [talos] machine config loaded successfully {"component": "controller-runtime", "controller": "config.AcquireController", "sources": ["state"]}
 user: warning: [2024-10-28T12:59:26.657969771Z]: [talos] task loadConfig (1/1): done, 19.080185ms
 user: warning: [2024-10-28T12:59:26.664773771Z]: [talos] phase config (11/12): done, 57.000519ms
```

```
talosctl disks --nodes 192.168.0.188 | grep /dev/sda
192.168.0.188   /dev/sda     RTL9210B-CG   -        SSD       -      naa.3001237923792379   scsi:t-0x00   -      256 GB   /platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb4/4-2/4-2:1.0/host0/target0:0:0/0:0:0:0   /sys/class/block 

talosctl cat /proc/mounts  --nodes 192.168.0.188  | grep state
/dev/sda5 /system/state xfs rw,relatime,attr2,inode64,logbufs=8,logbsize=32k,noquota 0 0

talosctl ls -r /system/state  --nodes 192.168.0.188
NODE            NAME
192.168.0.188   .
192.168.0.188   config.yaml
192.168.0.188   node-identity.yaml
192.168.0.188   platform-network.yaml

```

**Comment by mmakarov-muse** [comment]
I made the two experiments.

First was with my laptop and USB stick. I reproduced the problem. But, my laptop have no serial port and I cant capture boot logs.

Second was with libvirt virtual machine and simulated USB stick.
In this case problem was not reproduced.

@smira I guess you was right about low speed of USB device.

But, in my opinion its not a correct.
Looks line loadConfig should wait, while main boot device would be full initialized and mounted.

**Comment by smira** [comment]
Yes, it might not be correct, but Talos can't wait indefinitely for the `STATE` to appear, so it waits for `udevd` to settle, and then finalizes the decision. As there are no logs, it's hard to say what exactly happened.

You can try https://www.talos.dev/v1.8/reference/kernel/#talosdevicesettle_time if that fixes the issue (it has to be added to the image on every boot).

**Comment by mmakarov-muse** [comment]
Param `talos.device.settle_time` is solved the problem.
Thank you.

**Comment by smira** [comment]
@mmakarov-muse if you have boot logs with settle time, I'd be curious to see from the moment `initramfs` starts to the moment `STATE` becomes `read`y, thank you!

**Comment by mmakarov-muse** [comment]
Unfortunately, I have no any device with serial port. But, I'll do it if this device would be in my hands.

**Comment by smira** [comment]
No, I mean just plain talosctl dmesg after a successful boot

**Comment by mmakarov-muse** [comment]
Oh, sorry. No problem.
[dmesg.log](https://github.com/user-attachments/files/17598674/dmesg.log)

**Comment by smira** [comment]
Thank you, interesting, the default USB timeout (1 second) wasn't enough.
