### ISSUE TITLE
copying image cache

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#9615]
On install, the image cache should be copied from the ephemeral installation media (e.g. ISO) to the disk.

Proposed flow:

* a user should define a user volume which will contain the image cache on disk, it will be prepared by Talos
* an explicit copy (merge) should happen from discovered image caches to the user volume (?)

**Comment by smira** [comment]
Talos discovers an ISO with a label `TALOS_*`, and mounts its contents to a temporary directory.

Talos tries to find a folder names `imagecache/` in the ISO, if found, it configures the runtime image cache to serve from the ISO.

Talos after installation performs copying of the ISO contents to the image cache volume explicitly configured by the user.

**Comment by frezbo** [comment]
> Talos after installation performs copying of the ISO contents to the image cache volume explicitly configured by the user.

seems I already added support for this in #9778, just need to hook up the cache path from installer.

**Comment by smira** [comment]
> > Talos after installation performs copying of the ISO contents to the image cache volume explicitly configured by the user.
> 
> seems I already added support for this in #9778, just need to hook up the cache path from installer.

This is not exactly flexible, but could be a solution - I added configuration for the `IMAGECACHE` to be anywhere, so we might have a bit better luck outside of this (not sure how, but I can look into that next week)
