### ISSUE TITLE
Add support autoload kernel modules defined in /etc/modules-load.d/*.conf

### ISSUE THREAD

**Issue by shaba** [siderolabs/talos#9621]
## Feature Request
Add support autoload kernel modules defined in /etc/modules-load.d/*.conf

### Description
For custom build or scenarios, need load kernel modules. Easy way add support read configs from /etc/modules-load.d/*.conf, as any other linux distributives.

**Comment by dsseng** [comment]
Talos does not use modules-load.d, instead please use [corresponding machine config](https://www.talos.dev/v1.8/reference/configuration/v1alpha1/config/#Config.machine.kernel).

What do you want to use this feature for? What are the specific reasons you cannot use the existing configuration?

**Comment by steverfrancis** [comment]
Talos does support dynamic loadable kernel modules, and all modules have to be signed correctly, for security reasons.
That won't change.
