### ISSUE TITLE
Permissions on /var/log + /var/log/containers doesn't allow non-root Daemonset to gather logs

### ISSUE THREAD

**Issue by zviratko** [siderolabs/talos#9630]
## Bug Report

Permissions (700) on /var/log and /var/log/containers don't allow non-root Daemonset to tail logs

I believe relaxing permissions to rwx--x--x is better than running logging containers as root...
... unless there's a completely different and better way to do this?

### Description

See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33083#issuecomment-2454525827

### Environment

- Talos version: 1.8.2
- Kubernetes version: 1.31.2
- Platform: amd64

**Comment by frezbo** [comment]
I believe adding this fixes it:

```yaml
    capabilities:
      add:
        - DAC_READ_SEARCH
```

**Comment by smira** [comment]
I think the whole concept of running a DaemonSet which mounts something from the host is a bad design decision (in Kubernetes/CRI), but there is no better way today.

So the API becomes the host filesystem, and permissions on the log files and directories become the API of the operating system towards log collection daemons.

I think given all of that, the only option is to make permissions match some sane defaults.

**Comment by frezbo** [comment]
> That didn't work for me (nor for the original issue creator)

ahh okay, at least it allowed to read files owned as `nobody`
