### ISSUE TITLE
boot asset iso is 1.9 alpha?

### ISSUE THREAD

**Issue by depeo** [siderolabs/talos#9632]
Hi,

I created an iso here:
https://factory.talos.dev/

I selected , 
bare metal, 
no secure boot, 
version 1.8.2,
Iscsi-tools,
Qemu-guest-agent,

I downloaded the generated 1.8.2 iso , but when booting the iso it says the version is 1.9 alpha.

I set installer image to:
factory.talos.dev/installer/a3183906a70997be43facc5771a93f15a8a0d36a759d5e7b508a5
3ec2c3da9ce:v1.8.2

Is this a bug or am I doing something wrong?

**Comment by smira** [comment]
Please provide a link to the ISO and we can check.

**Comment by depeo** [comment]
https://factory.talos.dev/image/a3183906a70997be43facc5771a93f15a8a0d36a759d5e7b508a53ec2c3da9ce/v1.8.2/metal-amd64.iso

It happens after install:
<img width="524" alt="Screenshot 2024-11-04 at 14 09 02" src="https://github.com/user-attachments/assets/28b9092b-4976-4305-b8db-259edaed8e04">

```
$ grep installer controlplane.yaml
        image: factory.talos.dev/installer/a3183906a70997be43facc5771a93f15a8a0d36a759d5e7b508a53ec2c3da9ce:v1.8.2 # Allows for supplying the image used to perform the installation.
```

**Comment by frezbo** [comment]
it seems your schematic id is wrong for the selected extensions? :thinking: 

![image](https://github.com/user-attachments/assets/b4849883-d09a-44a9-88e6-5aa2b94efe98)

**Comment by depeo** [comment]
Ah, I added this as well, might not be  needed but I wanted to know what the if names were.
```
  extraKernelArgs:
    - net.ifnames=0
    - biosdevame=0
```

**Comment by smira** [comment]
@depeo the screenshot you posted is not from the ISO, it's installed Talos booted up.

Make sure you've actually wiped your disks between experiments.

**Comment by smira** [comment]
I closed the issue, as the ISO is definitely Talos 1.8.2 and the issue is not valid. 

Whatever else that happens is different, and not related to the ISO version from the Image Factory.
