### ISSUE TITLE
enable dm_cache

### ISSUE THREAD

**Issue by chifu1234** [siderolabs/talos#9641]
## Feature Request
I would like to use dm-cache in order to increase read performance of my lvm. Currently dm_cache is not enabled in the build. Or would you prefer to create our own build for that use-case ? 
https://github.com/siderolabs/pkgs/blob/2e733cccfd225712eb7395cf04b6d8df0bf2b8d2/kernel/build/config-amd64#L2387

**Comment by smira** [comment]
Please send a PR to enable that option, and we can get it in.

**Comment by chifu1234** [comment]
https://github.com/siderolabs/pkgs/pull/1075
