### ISSUE TITLE
Not able to resize a disk

### ISSUE THREAD

**Issue by UnixxSH** [siderolabs/talos#9656]
## Bug Report
I'm trying to extend the partition on a disk, editing machine configuration with size didn't worked, and it seems I can't change the volumeconfiguration neither (this is a second disk /dev/sdb). I didn't find documentation to do that.

### Environment
Proxmox

- Talos version: 1.8.2

**Comment by smira** [comment]
This is not supported for user disks at the moment, sorry.

New user volumes _should_ support it, but it's not there yet.
