### ISSUE TITLE
Talos Linux Kernel update to 6.9.9+ for iGPU LLM usage

### ISSUE THREAD

**Issue by keatontaylor** [siderolabs/talos#9657]
## Feature Request
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=8d656c7a0fed8e1675a170d0d17039fe713beb59

Per the above commit, for Small APUs VRAM allocations can now go to GTT in kernel 6.9.9+. As many of us in the talos home lab community run hardware supporting iGPU APUs, upgrading the linux kernel in upcoming versions of talos will allow us to better take advantage of LLM workloads where models exceed the size of the allocatable VRAM in the BIOS.

### Description
See above

**Comment by frezbo** [comment]
Talos will ship the next LTS kernel (possibly 6.12) in the next release

**Comment by smira** [comment]
To make it more clear: our policy is to ship only Linux LTS kernels which allow updates for extended periods of time (4-8 months). You can build your own Talos version with the kernel you like, but official releases will only ship LTS kernels.
