### ISSUE TITLE
HTTP 500 when attempting download of image

### ISSUE THREAD

**Issue by Hexoplon** [siderolabs/talos#9694]
### Description

When attempting to download a metal image with multiple extensions of the new v1.9.0-alpha.2 release, I get a HTTP 500 internal server error response. However, it works for the plain image, as well as with a single extension.

See `856b061c615e1d15460c46bd87a3021d353c0a3f1fae5f2c68f22dd3d3084e14`, [metal-amd64.iso](https://factory.talos.dev/image/856b061c615e1d15460c46bd87a3021d353c0a3f1fae5f2c68f22dd3d3084e14/v1.9.0-alpha.2/metal-amd64.iso) as an example.

### Environment

- Talos version: v1.9.0-alpha.2

**Comment by smira** [comment]
```
{"level":"info","ts":1731321404.9692018,"caller":"http/http.go:164","msg":"request","frontend":"http","method":"GET","path":"/image/856b061c615e1d15460c46bd87a3021d353c0a3f1fae5f2c68f22dd3d3084e14/v1.9.0-alpha.2/metal-amd64.iso","error":"error generating asset: error validating extension \"glibc\": version constraint >= v1.9.0 can't be satisfied with Talos version 1.8.0-alpha.1"}
```

(This is the error, and it's wrong).

**Comment by Hexoplon** [comment]
The issue is resolved now! Thanks :D
