### ISSUE TITLE
Can't passthrough Intel iGPU to talos vm

### ISSUE THREAD

**Issue by DizzieNight** [siderolabs/talos#9714]
### Description
I am trying to passthrough my Intel iGPU to my talos worker for plex but I get this error when booting:
![image](https://github.com/user-attachments/assets/c4720c48-ea06-4e73-b406-1975367644a7)

The gpu works because it used to be on my old cluster on the same machine and also I have the i915-ucode extension loaded onto the worker so I'm a bit confused.
![image](https://github.com/user-attachments/assets/2a799fbd-898c-4b56-81ab-78456b9e642a)

### Environment

- Talos version: 1.8.2
- Kubernetes version: 1.31.2
- Platform: Proxmox

**Comment by smira** [comment]
This looks like a panic in the Linux kernel, so the only chance is to report it upstream (and search if it has already been reported). It might have already been fixed as well, in that case Talos v1.8.3 (coming out today) to see if that works.

**Comment by DizzieNight** [comment]
Okay cool, I'll wait for v1.8.3 and see if it resolves the issue

**Comment by DizzieNight** [comment]
Could not resolve the issue. I ended up getting physical machines to do the transcoding
