### ISSUE TITLE
etcd database corrupted 

### ISSUE THREAD

**Issue by DizzieNight** [siderolabs/talos#9734]
### Description
I am rebuilding my cluster and I had it working pretty well but I woke up this morning to find etcd has now corrupted. I have been getting some corruption recently and it could do with the pcie riser I have used on my proxmox server for extra nvme slots.

Just wondering if anyone knows how to fix the etcd database without a backup and without starting the cluster all over again?

### Logs
I am not home at the moment but can provide logs once I get home.

### Environment

- Talos version: v1.8.2
- Kubernetes version: v1.31.2
- Platform: Proxmox
- 3 Masters and 3 Workers

**Comment by DizzieNight** [comment]
Just wondering if it's possible to put the masters into maintenance and then reapply the control plane yaml file?

**Comment by smira** [comment]
We have pretty extensive [documentation](https://www.talos.dev/v1.8/advanced/disaster-recovery/) on this topic.

If you have any specific question which is not answered in the docs, please ask them here.

**Comment by DizzieNight** [comment]
No problem thank you. I ended up rebuilding my cluster and will do regular backups of etcd. Cheers
