### ISSUE TITLE
Log delivery stops after cluster reboot

### ISSUE THREAD

**Issue by attilaolah** [siderolabs/talos#9736]
## Bug Report

After rebooting the entire cluster (e.g. recovering from a power outage), logs are no longer pushed to the in-cluster Vector aggregator, even though configured.

### Description

I have configured kernel logs and service logs to be delivered to an in-cluster Vector log source. This works well when I configure Talos at a time the Vector instances are up and running. However, when recovering from a cluster-wide power loss, Talos comes up first, and then the in-cluster Vector aggregator. As such, when Talos starts, the endpoints where logs should be pushed are not available yet.

When I change the logging config (both kernel and service), e.g. by removing the log destinations and applying the config with `--try`, so after a minute the log destinations would be back, logging recovers for that node, and I even seem to get the kernel logs from boot time.

It would be nice if there was some retry mechanism built in, otherwise I need to perform manual action after a power loss; even if I were to deliver logs outside of the cluster, the endpoint would likely not be available as quickly as Talos starts up.

### Logs

No logs, that's the point :)

### Environment

- Talos version: v1.8.2
- Kubernetes version: v1.31.2
- Platform: metal arm64

**Comment by smira** [comment]
The retry mechanism is there, so whatever happens is something different, if you open a bug report, attach `talosctl support` bundle for the machine in a problem state.

**Comment by attilaolah** [comment]
After some more investigation, it turns out that I had a Cilium misconfiguration (conflicting IP pools) that caused ingress LBs not to get their IPs assigned sometimes, but only some of them (where my annotations were in the conflicting range). And my Vector uses an ingress LB, hence the problem.

Sorry for the noise, it took a while for me to track down the real issue here.
