### ISSUE TITLE
I would like to specify a primary interface for talos api to listen on

### ISSUE THREAD

**Issue by janvanlith** [siderolabs/talos#9752]
## Feature Request
I want to specify on which interface a node listens for talos api calls. (with kubelet I can use validSubnets)

### Description

I have a cluster with worker nodes that have extra interfaces that are connected to a data network and I have the management network where also the control plane nodes are in. (they do not have a extra interface)
When I now deploy the cluster and do a `talosctl health` the api call go wrong as it want to connect to the extra interface its ip address. But that is not routed from the management network and goes wrong.
Can you create a config value that set the primary interface to listen on for talos api or make a value that can set validSubnets for the api?

**Comment by smira** [comment]
Please see https://github.com/siderolabs/talos/discussions/9690
