### ISSUE TITLE
[Grafana / Prometheus] pod having cpu throttling but it never hit the limit on Grafana 

### ISSUE THREAD

**Issue by rubber-ant** [siderolabs/talos#9770]
## Bug Report
pod having cpu throttling but it never hit the limit on Grafana 

### Description

On _talosctl dashboard_ on the monitor tab I can see when the PID for this pod with 1 CPU takes CPU% = 100% , meaning the full CPU allocated but on grafana it show less 40% - 60% but it never reach 100% of CPU utilisation. 
 
I noticed a pod with CPU limits set to 1, where computations take 5 seconds. 
When I remove the CPU limit or increase it to 8, the computation time drops to 0.2–0.5 seconds.

On the` talosctl dashboard` (`monitor` tab), the pod's PID shows 100% CPU% usage, meaning it's fully utilising the allocated CPU and it's what I'm expecting to see on Grafana. 
However, Grafana shows only 40–60% CPU utilization, never reaching 100%.

On Grafana shows  usage of 0.4-0.6 CPU with limit to 1. 
 
<img width="1276" alt="image" src="https://github.com/user-attachments/assets/77bef424-e361-463c-86ca-2184c062d7e0">

I tried set Prometheus with:  
```
      - prometheus:
          prometheusSpec:
            scrapeInterval: 1s
            evaluationInterval: 1s
```

also in Grafana  on the chart CPU  set `Min interval` to 1s without any luck

### Environment

- Talos version: 
```
- talosctl version --nodes 192.168.121.13
Client:
	Tag:         v1.8.2
	SHA:         88f861a0
	Built:
	Go version:  go1.22.8
	OS/Arch:     linux/amd64
Server:
	NODE:        192.168.121.13
	Tag:         v1.8.2
	SHA:         88f861a0
	Built:
	Go version:  go1.22.8
	OS/Arch:     linux/amd64
	Enabled:     RBAC
```
- Kubernetes version: `Server Version: v1.29.10`
- Platform:   ` Ubuntu 22.04.5 - 5.15.0-124-generic`  using `vagrant  2.4.1`

**Comment by smira** [comment]
Is this issue for Talos Linux or Grafana?

**Comment by rubber-ant** [comment]
The computation is 3-4 seconds but Grafana/Prometheus for some reason is  not able to show same as `taloctl dashboard`

**Comment by smira** [comment]
So I don't quite see what would you like us to fix on Talos side? Do you think that dashboard shows CPU usage wrong?

**Comment by smira** [comment]
Also please keep in mind that CPU usage is split at least into user/sys time, `talosctl dashboard` shows aggregate of both.

**Comment by rubber-ant** [comment]
I initially thought this was a [bug kernel](https://engineering.indeedblog.com/blog/2019/12/unthrottled-fixing-cpu-limits-in-the-cloud/) on Talos, but I no longer believe this to be the case.

anyway , what kernel is using tag `v1.8.2` ?

**Comment by smira** [comment]
You can check yourself with `kubectl get nodes -o wide` ;) 

I don't think it's a bug anywhere, but your need to understand metrics and they way are reported and presented a bit more to get to the correct conclusion.
