### ISSUE TITLE
IP configuration via kernel cmdline is not working with bonding interface

### ISSUE THREAD

**Issue by kvaps** [siderolabs/talos#9806]
### Description

I tried to configure bonding using parameters from the doc https://www.talos.dev/v1.8/reference/kernel
```
bond=bond0:eno3,eno4:mode=802.3ad vlan=bond0.253:bond0 ip=192.168.253.2::192.168.253.1:255.255.255.0::bond0.100:::::
```

Bond interface has been created but IP-address is not applied to it.
I tested this configuration without vlan previusly and it is also not worked for me

### Environment

- Talos version: v1.8.2
- Platform: metal

**Comment by smira** [comment]
It looks to be `bond0.253` and `bond0.100`, so it shouldn't apply?

**Comment by kvaps** [comment]
My bad, sorry, I'll recheck and reopen issue if it is not working
