### ISSUE TITLE
OpenStack: Inconsistent Information between Documentation and Release

### ISSUE THREAD

**Issue by throbach** [siderolabs/talos#9901]
Description:

The [documentation](https://www.talos.dev/v1.8/talos-guides/install/cloud-platforms/openstack/) states that the image for OpenStack is available in the releases under the name "openstack-$ARCH.tar.gz". However, the image cannot be found under this name in the releases.

Error Details:

Documentation: https://www.talos.dev/v1.8/talos-guides/install/cloud-platforms/openstack/
Release: [Link to release](https://github.com/siderolabs/talos/releases/tag/v1.8.3)
Expected Image Name: openstack-arm64.tar.gz

**Comment by smira** [comment]
Please use [Image Factory](https://factory.talos.dev/).

**Comment by throbach** [comment]
Nice, thank you!
