### ISSUE TITLE
Segfault when installing talos v1.9.0-beta.0 on bare metal

### ISSUE THREAD

**Issue by stereobutter** [siderolabs/talos#9912]
### Description
When hitting `talosctl apply-config -f ... --insecure --nodes ...` against my bare metal machine in maintenance mode I almost immediately get a segfault. 

### Logs
<img width="2032" alt="talos19_segfault" src="https://github.com/user-attachments/assets/a9b5e9c1-e905-4ea5-82c9-a8863a241045">

### Environment

- Talos version: v1.9.0-beta.0 (from image factory)
- Platform: amd64, secureboot

**Comment by smira** [comment]
Thanks for reporting this, this is definitely a bug.
