### ISSUE TITLE
Can't boot to SecureBoot using generated iPXE script

### ISSUE THREAD

**Issue by maxpain** [siderolabs/talos#9947]
## Bug Report
Can't boot to SecureBoot using generated iPXE script

### Description
Hello. I'm trying to iPXE boot using this script:
```
#!ipxe

dhcp
kernel https://pxe.factory.talos.dev/image/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba/v1.8.3/metal-amd64-secureboot-uki.efi
boot
```

But Talos reboots endlessly.

I've generated this image on factory.talos.dev using the following configuration:
```yaml
customization: {}
```

### Logs
![image](https://github.com/user-attachments/assets/25e81088-30e1-4b1b-a48c-6351a345c7ef)

### Environment

- Talos version: v1.8.3
- Platform: Bare Metal, x86

**Comment by frezbo** [comment]
ahh you're missing `talos.platform=metal`

**Comment by frezbo** [comment]
okay, think it's a factory bug

**Comment by frezbo** [comment]
@maxpain from the logs seems you're booting a different image which has extensions? Or does this error occur after applying config, if so what's the installer image used?

**Comment by maxpain** [comment]
> @maxpain from the logs seems you're booting a different image which has extensions?

I tried images with and without extensions, no difference.

> Or does this error occur after applying config

No, it's rebooting right after booting using iPXE

**Comment by frezbo** [comment]
@maxpain I see the problem, since you're pxe booting UKI cmdline are ignored, it'll be only applicable when booting from sd-boot, so you'd need to set these https://www.talos.dev/v1.8/reference/kernel/#commandline-parameters

**Comment by smira** [comment]
> @maxpain I see the problem, since you're pxe booting UKI cmdline are ignored, it'll be only applicable when booting from sd-boot, so you'd need to set these [talos.dev/v1.8/reference/kernel#commandline-parameters](https://www.talos.dev/v1.8/reference/kernel/#commandline-parameters)

but I wonder if Image Factory script is correct then? what happens if it's SecureBoot enabled system?
